### PR TITLE
fix(sdk): Fix environment variable set in component yaml lost during compilation. Fixes #8884

### LINKED ISSUE #8884: [sdk] Environment variable set in container not reflected in IR
### Environment

*  KFP version:  N/A

*  KFP SDK version:  2.0.0-beta.12

*  All dependencies version:

### Steps to reproduce
Compile the [sample pipeline with environment variable](https://github.com/kubeflow/pipelines/blob/master/sdk/python/test_data/pipelines/pipeline_with_env.py), with line 48-49 `set_env_variable(name='ENV2', value='val2')` removed. 

### Expected result
Because `ENV2` is set at line 40 within the container, the IR should contain the value of `ENV2`.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
Fixes #8884

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
/lgtm

Thanks, @chensun!

Maybe add a release note for the rare case that a user notices a behavior change and want to trace it. Feel free to merge as-is if you prefer.

**Comment by chensun** [comment]
> /lgtm
> 
> Thanks, @chensun!
> 
> Maybe add a release note for the rare case that a user notices a behavior change and want to trace it. Feel free to merge as-is if you prefer.

Good call. I should have remembered doing that. Fixed.

**Review by connor-mccarthy — APPROVED** [review]
/lgtm
/approve

**Comment by chensun** [comment]
kubeflow-pipelines-sdk-execution-tests failure is unrelated to the change and tracked by https://github.com/kubeflow/pipelines/issues/8845 and https://github.com/kubeflow/pipelines/issues/8846 (pending release)

**Pull request merged**
