### PR TITLE
SDK/Compiler - Added the ability to apply a function to all ops in a pipeline

### PR DESCRIPTION
**Pull request by Ark-kun**
They can be used to apply some functions (e.g. to add secrets) to all pipeline ops.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1209)

### CODE REVIEW

**Comment by gaoning777** [comment]
Would you mind explaining why we need to add the transformers?

**Comment by Ark-kun** [comment]
> Would you mind explaining why we need to add the transformers?

"They can be used to apply some functions (e.g. to add secrets) to all pipeline ops."

So, it's basically `apply_to_all_ops`.

**Comment by gaoning777** [comment]
I think the exposed interface should be in the DSL instead of the compiler. In other words, this interface should be exposed in the DSL at best. WDYT?

**Comment by Ark-kun** [comment]
> I think the exposed interface should be in the DSL instead of the compiler. In other words, this interface should be exposed in the DSL at best. WDYT?

That's a bit problematic, because the ops are only created during the compilation.
I'll think a bit more about doing it the some other way, but this option seems to be a cheap way to tackle a practical issue.

Generally, my goal here is to move the non-portable and repeating things like attaching secrets out of the pipeline function so that it can be portable across clouds.

P.S. I'll remove the template modifiers as it's exposing Argo.

**Comment by Ark-kun** [comment]
I've removed the `template_transformers` so now only `op_transformers` remain.

**Comment by Ark-kun** [comment]
An example PR that would have been trivial with this: https://github.com/kubeflow/pipelines/pull/749

It could have just been a simple switch:

```
transformers = []
if environment == 'gcp':
  transformers.add(gcp.use_gcp_secret('user-gcp-sa'))
else:
  transformers.add(onprem.mount_pvc(pvc_name, 'local-storage', pvc_mount_path))
```

**Comment by Ark-kun** [comment]
@gaoning777 Can you please take a look again?

**Comment by Ark-kun** [comment]
Gentle ping
/cc @gaoning777

**Comment by jinchihe** [comment]
@Ark-kun This is great PR. Just want to confirm, not sure if we need to consider the case that user uses the `dsl-compile --py xxx.py --output xxx.yaml`, the `op_transformers` cannot be set, seems we need to expose one option for the `op_transformers` in `dsl-compile`?

And consult one quick question here, you used the `environment` to switch gcp and onprem, where get the `environment`? I think it's set from function header of pipeline python dsl file, right? Personally I think we should have a better way to let use define the variable to switch user cases. Thanks a lot!

**Comment by gaoning777** [comment]
> > I think the exposed interface should be in the DSL instead of the compiler. In other words, this interface should be exposed in the DSL at best. WDYT?
> 
> That's a bit problematic, because the ops are only created during the compilation.
How about passing the transformers to PipelineConf(https://github.com/kubeflow/pipelines/blob/2da723c2faf5228e646f12fb57e4d5f491e69c82/sdk/python/kfp/dsl/_pipeline.py#L54)?
> I'll think a bit more about doing it the some other way, but this option seems to be a cheap way to tackle a practical issue.
> 
> Generally, my goal here is to move the non-portable and repeating things like attaching secrets out of the pipeline function so that it can be portable across clouds.
> 
> P.S. I'll remove the template modifiers as it's exposing Argo.

**Comment by Ark-kun** [comment]
> How about passing the transformers to PipelineConf

Hmm. I guess it will solve some of the problems. Thanks for the suggestion.

**Comment by Ark-kun** [comment]
> we need to consider the case that user uses the `dsl-compile --py xxx.py --output xxx.yaml`, the `op_transformers` cannot be set, seems we need to expose one option for the `op_transformers` in `dsl-compile`?

You're right. This is an important use case. (I keep forgetting about it since I just start the pipeline files directly instead of using the compiler).



> And consult one quick question here, you used the `environment` to switch gcp and onprem, where get the `environment`?

I was thinking about a either having a constant variable in the pipeline program code or read the value from an environment variable.

**Comment by jinchihe** [comment]
@Ark-kun one more question, do you planed to handle the case that if we want to apply the function to all steps except first one? For example, the first step is to create the pvc but following steps need to apply the pvc (function). Thanks a lot!

**Comment by Ark-kun** [comment]
> do you planed to handle the case that if we want to apply the function to all steps except first one?

The function can inspect the op and decide whether to modify it or not. For example it can skip the nodes with particular name or all resource nodes.

**Comment by jinchihe** [comment]
> For more customized scenarios, why not write a python for loop to do it. For example,
> ops = []
> for op in ops:
> op.apply()
> Then, you can choose any op in the ops list.

Yes, in fact I've already done that in the PR #749 :-)

**Comment by Ark-kun** [comment]
> How about passing the transformers to PipelineConf(

Done.
/cc @gaoning777

**Comment by gaoning777** [comment]
Thanks for the change. 
/lgtm

**Pull request merged**
