### PR TITLE
feat(components): JSON - Added the "Build dict", "Build list" and "Combine lists" components

### PR DESCRIPTION
**Pull request by Ark-kun**

### CODE REVIEW

**Comment by chensun** [comment]
@Ark-kun the code itself looks good to me. But for my education, can you please explain what's the use cases for this? It feels a bit unpractical or limited that the components take a fixed number of inputs, and put them into a collection structure.

**Comment by Ark-kun** [comment]
> @Ark-kun the code itself looks good to me. But for my education, can you please explain what's the use cases for this?

These components are needed as a "glue" between some other components.
You can seem them in action in [multi_stage_optimization_atomic_pipeline](https://github.com/kubeflow/pipelines/blob/d639b80043998438e1ffc8525e708431c46d2b35/components/google-cloud/Optimizer/_samples/multi_stage_optimization_atomic_pipeline.py#L136).
For example, that pipeline needs to add new model measurements to the list of existing measurements.

>It feels a bit unpractical or limited that the components take a fixed number of inputs, and put them into a collection structure.

Yes, this is a limitation. I'm working on the design that would fix the associated issue. The design proposed to add built-in support for constructing JSON lists (and dictionaries) from arbitrary number of arguments.
Until this design is implemented, we have to deal with these limitations. Note that Argo, Tekton, TFX, etc all have this issue.

Meanwhile these components allow solving many practical use cases without every user reinventing the wheel.

**Comment by Bobgy** [comment]
Components is one way to reuse code, python functions is another.

I start to feel like writing one-off lightweight components in the pipeline for this type of glue task is a better fit.

There is definitely more flexibility using a real language. Also, it's still short enough for glue code.

What do you think?

**Comment by Ark-kun** [comment]
> Components is one way to reuse code, python functions is another.
> 
> I start to feel like writing one-off lightweight components in the pipeline for this type of glue task is a better fit.
> 
> There is definitely more flexibility using a real language. Also, it's still short enough for glue code.
> 
> What do you think?

One does not exclude another.
Having readily-made components is important for code-less pipeline building.
I'm working on the visual editor for pipelines and having enough component glue is important.

There are many small tasks that we'd consider trivial. For example, downloading or uploading the data. Yet our customers have told us they like those components. Having pre-built components for small everyday needs is important for the end-to-end usability.

With enough components we'll be enabling the experience where the pipeline builder no longer needs to create any new components most of the time.

**Pull request merged**
