### PR TITLE
Fix(samples): Upgrade tensorflow for sample lightweight_component

### PR DESCRIPTION
**Pull request by radcheb**
**Description of your changes:**
The CI check `kubeflow-pipeline-sample-test` fails because of lightweight_component sample. This PR aims to fix that.

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 
- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by NikeNano** [comment]
Do you know @radcheb why this error came up now and previously it was not a problem?

**Comment by radcheb** [comment]
Already solved by https://github.com/kubeflow/pipelines/pull/4585 so I will close this PR.


> Do you know @radcheb why this error came up now and previously it was not a problem?

@NikeNano I am not sure but it looks like tensorflow deleted some old versions of tensorflow, so the oldest one is `1.13.2`.

**Comment by radcheb** [comment]
Already solved by https://github.com/kubeflow/pipelines/pull/4585 so I will close this PR.

**Pull request closed without merging**
