### PR TITLE
chore(components/pytorch):kserve migration

### PR DESCRIPTION
**Pull request by jagadeeshi2i**
Signed-off-by: Jagadeesh J <jagadeeshj@ideas2it.com>

Migration change for KServe v2

1. Updating the pytorch examples to support kserve v2
2. [Unit test log](https://github.com/kubeflow/pipelines/files/8630567/tox.txt)

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by zijianjoy** [comment]
cc @chensun for fixing the python3.6 issue.

**Comment by chensun** [comment]
kubeflow-pipelines-component-yaml test will be fixed by https://github.com/kubeflow/pipelines/pull/7871 and https://github.com/kubeflow/pipelines/pull/7870

**Comment by chensun** [comment]
@shrinath-suresh the CI infra issue has been resolved. Feel free to merge whenever you're ready.

**Comment by shrinath-suresh** [comment]
@chensun The builds are failing again with the following error msg

```
Run details page URL:
https://4e18c21c9d33d20f-dot-datalab-vm-staging.googleusercontent.com/#/runs/details/2312ccf3-cacb-496b-80df-c4604b189fa9
Traceback (most recent call last):
  File "sample_test.py", line 164, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "sample_test.py", line 149, in main
    run_response = run_result.wait_for_run_completion(timeout_mins * _MINUTE)
  File "/home/prow/go/src/github.com/kubeflow/pipelines/sdk/python/kfp/deprecated/_client.py", line 1090, in wait_for_run_completion
    self.run_id, timeout)
  File "/home/prow/go/src/github.com/kubeflow/pipelines/sdk/python/kfp/deprecated/_client.py", line 1335, in wait_for_run_completion
    raise api_ex
  File "/home/prow/go/src/github.com/kubeflow/pipelines/sdk/python/kfp/deprecated/_client.py", line 1325, in wait_for_run_completion
    get_run_response = self._run_api.get_run(run_id=run_id)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/run_service_api.py", line 435, in get_run
    return self.get_run_with_http_info(run_id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/run_service_api.py", line 529, in get_run_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 369, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 185, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 393, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/rest.py", line 234, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Thu, 23 Jun 2022 04:25:18 GMT', 'Vary': 'Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Powered-By': 'Express', 'X-Xss-Protection': '0', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'S=cloud_datalab_tunnel=jGkucbYoeQnHPBJGYqo6Vb9azCIHm2FXig0mMvEpeHg; Path=/; Max-Age=3600'})
HTTP response body: {"error":"InternalServerError: Failed to get run: dial tcp 10.47.250.244:3306: connect: connection refused: dial tcp 10.47.250.244:3306: connect: connection refused","code":13,"message":"InternalServerError: Failed to get run: dial tcp 10.47.250.244:3306: connect: connection refused: dial tcp 10.47.250.244:3306: connect: connection refused","details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error","error_details":"InternalServerError: Failed to get run: dial tcp 10.47.250.244:3306: connect: connection refused: dial tcp 10.47.250.244:3306: connect: connection refused"}]}
```

**Comment by shrinath-suresh** [comment]
> @chensun The builds are failing again with the following error msg
> 
> ```
> Run details page URL:
> https://4e18c21c9d33d20f-dot-datalab-vm-staging.googleusercontent.com/#/runs/details/2312ccf3-cacb-496b-80df-c4604b189fa9
> Traceback (most recent call last):
>   File "sample_test.py", line 164, in <module>
>     fire.Fire(main)
>   File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
>     target=component.__name__)
>   File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "sample_test.py", line 149, in main
>     run_response = run_result.wait_for_run_completion(timeout_mins * _MINUTE)
>   File "/home/prow/go/src/github.com/kubeflow/pipelines/sdk/python/kfp/deprecated/_client.py", line 1090, in wait_for_run_completion
>     self.run_id, timeout)
>   File "/home/prow/go/src/github.com/kubeflow/pipelines/sdk/python/kfp/deprecated/_client.py", line 1335, in wait_for_run_completion
>     raise api_ex
>   File "/home/prow/go/src/github.com/kubeflow/pipelines/sdk/python/kfp/deprecated/_client.py", line 1325, in wait_for_run_completion
>     get_run_response = self._run_api.get_run(run_id=run_id)
>   File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/run_service_api.py", line 435, in get_run
>     return self.get_run_with_http_info(run_id, **kwargs)  # noqa: E501
>   File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/run_service_api.py", line 529, in get_run_with_http_info
>     collection_formats=collection_formats)
>   File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 369, in call_api
>     _preload_content, _request_timeout, _host)
>   File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
>     raise e
>   File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 185, in __call_api
>     _request_timeout=_request_timeout)
>   File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 393, in request
>     headers=headers)
>   File "/usr/local/lib/python3.7/site-packages/kfp_server_api/rest.py", line 234, in GET
>     query_params=query_params)
>   File "/usr/local/lib/python3.7/site-packages/kfp_server_api/rest.py", line 224, in request
>     raise ApiException(http_resp=r)
> kfp_server_api.exceptions.ApiException: (500)
> Reason: Internal Server Error
> HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Thu, 23 Jun 2022 04:25:18 GMT', 'Vary': 'Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Powered-By': 'Express', 'X-Xss-Protection': '0', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'S=cloud_datalab_tunnel=jGkucbYoeQnHPBJGYqo6Vb9azCIHm2FXig0mMvEpeHg; Path=/; Max-Age=3600'})
> HTTP response body: {"error":"InternalServerError: Failed to get run: dial tcp 10.47.250.244:3306: connect: connection refused: dial tcp 10.47.250.244:3306: connect: connection refused","code":13,"message":"InternalServerError: Failed to get run: dial tcp 10.47.250.244:3306: connect: connection refused: dial tcp 10.47.250.244:3306: connect: connection refused","details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error","error_details":"InternalServerError: Failed to get run: dial tcp 10.47.250.244:3306: connect: connection refused: dial tcp 10.47.250.244:3306: connect: connection refused"}]}
> ```

@chensun The same isssue is persisting. Can you please help?

**Pull request merged**
