### PR TITLE
fix(kubernetes_platform): Add optional field to SecretAsVolume and ConfigMapAsVolume. Fixes #10548

### LINKED ISSUE #10548: [sdk]  Missing optional parameter to  v2 `use_config_map_as_volume` and `use_secret_as_volume`
In kfp v1 the config map or secret can be marked as optional when used as a volume source, as shown in the example below.

This capability is missing in the recent added `use_config_map_as_volume` and `use_secret_as_volume` v2 sdk functions. (https://github.com/kubeflow/pipelines/pull/10400, https://github.com/kubeflow/pipelines/pull/10483)

```bash
vol = k8s_client.V1Volume(
        name='dummy',
        config_map=k8s_client.V1ConfigMapVolumeSource(name='name', optional=True),
    )
    component.add_pvolumes({mountPoint: vol})


vol = k8s_client.V1Volume(
        name='dummy',
        secret=k8s_client.V1SecretVolumeSource(secret_name='name', optional=False),
    )
    component.add_pvolumes({mountPoint: vol})

```

What is the use case or pain point?

Making the secret or config map an optional resource allows the KFP component to function without failing even if those resources are not present.

### PR DESCRIPTION
**Pull request by revit13**
Description of your changes:
Part of https://github.com/kubeflow/pipelines/pull/10400 and #10548

This PR adds missing optional field to SecretAsVolume and ConfigMapAsVolume to avoid a failure when the secret or config map used as volume source are missing.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by Tomcli — COMMENTED** [review]
/lgtm
/ok-to-test

**Comment by rimolive** [comment]
Last attempt

/test kfp-kubernetes-execution-tests

**Comment by Tomcli** [comment]
@rimolive You don't need to trigger the test if it's not required. That also could help lower the workload on the e2e pipelines.

**Review by chensun — APPROVED** [review]

**Pull request merged**
