### PR TITLE
feat(backend): Read launcher/driver images from ENV vars

### PR DESCRIPTION
**Pull request by kimwnasptd**
**Description of your changes:**
Fixes https://github.com/kubeflow/pipelines/issues/8741

We have users that run in an airgap environment and need to be able to configure all images in the Kubeflow components. Since currently those images are hardcoded this means their pipelines will crash 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@chensun @gkcalat I see the CI is failing in `kubeflow-pipelines-samples-v2`, but this PR seems to be unrelated with the error I'm seeing. Could you give me some hints?

```
Traceback (most recent call last):
  File "sample_test.py", line 21, in <module>
    import kfp.deprecated as kfp
  File "/usr/local/lib/python3.7/site-packages/kfp/deprecated/__init__.py", line 19, in <module>
    from . import dsl
  File "/usr/local/lib/python3.7/site-packages/kfp/deprecated/dsl/__init__.py", line 16, in <module>
    from ._pipeline import Pipeline, PipelineExecutionMode, pipeline, get_pipeline_conf, PipelineConf
  File "/usr/local/lib/python3.7/site-packages/kfp/deprecated/dsl/_pipeline.py", line 21, in <module>
    from kfp.deprecated.dsl import _component_bridge
  File "/usr/local/lib/python3.7/site-packages/kfp/deprecated/dsl/_component_bridge.py", line 29, in <module>
    from kfp.deprecated.dsl import component_spec as dsl_component_spec
  File "/usr/local/lib/python3.7/site-packages/kfp/deprecated/dsl/component_spec.py", line 21, in <module>
    from kfp.deprecated.dsl import type_utils
  File "/usr/local/lib/python3.7/site-packages/kfp/deprecated/dsl/type_utils.py", line 19, in <module>
    from kfp.components.types import type_utils
ModuleNotFoundError: No module named 'kfp.components.types'
make: *** [Makefile:18: sample-test] Error 1
```

**Comment by kimwnasptd** [comment]
Actually, I think this PR might not be needed. After a more careful look of the API Server code I see that this could be set already as an argument in the API Server

https://github.com/kubeflow/pipelines/blob/1386a826ba2bcdbc19eb2007ca43f6acd1031e4d/backend/src/v2/cmd/compiler/main.go#L36
https://github.com/kubeflow/pipelines/blob/1386a826ba2bcdbc19eb2007ca43f6acd1031e4d/backend/src/v2/compiler/argocompiler/argo.go#L127

Let me verify and I can drop this PR then

**Comment by kimwnasptd** [comment]
Actually, I see this place in which `nil` is hardcoded for `Options` struct. So this means that it won't get the value there, but am not sure of the code path entirely

https://github.com/kubeflow/pipelines/blob/1386a826ba2bcdbc19eb2007ca43f6acd1031e4d/backend/src/apiserver/template/v2_template.go#L75

**Comment by xixici** [comment]
Your work is commendable. However, I noticed a similar approach in another pull request, specifically in https://github.com/kubeflow/pipelines/pull/10269. Similarly, I'm puzzled by aspects of the feature, such as:



> I added the environment variables in the API server, but it doesn't seem to have any effect. Here are the commands I used:
> ```
> echo 'export V2_LAUNCHER_IMAGE=kfp-launcher:0.0.1-aarch64-beta' >> ~/.bashrc
> echo 'export V2_DRIVER_IMAGE=kfp-driver:0.0.1-aarch64-beta' >> ~/.bashrc
> 
> source ~/.bashrc
> ```
> I also added the environment variables in the ArgoExec image, but unfortunately, it doesn't work either.
> I'm confused about this feature. I am not a Golang engineer, so I might have made some mistakes in understanding or implementing the necessary configurations.

@kimwnasptd

**Comment by kimwnasptd** [comment]
hey @xixici, I hadn't seen the other PR you mentioned as it was newer than mine. The PR you mentioned should do the trick, as it makes those images configurable in the Argo compiler of the backend (by using env vars on the backend)

So no need for this PR
/close

**Comment by Pumbaa-peng** [comment]
> Your work is commendable. However, I noticed a similar approach in another pull request, specifically in #10269. Similarly, I'm puzzled by aspects of the feature, such as:
> 
> > I added the environment variables in the API server, but it doesn't seem to have any effect. Here are the commands I used:
> > ```
> > echo 'export V2_LAUNCHER_IMAGE=kfp-launcher:0.0.1-aarch64-beta' >> ~/.bashrc
> > echo 'export V2_DRIVER_IMAGE=kfp-driver:0.0.1-aarch64-beta' >> ~/.bashrc
> > 
> > source ~/.bashrc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also added the environment variables in the ArgoExec image, but unfortunately, it doesn't work either.
> > I'm confused about this feature. I am not a Golang engineer, so I might have made some mistakes in understanding or implementing the necessary configurations.
> 
> @kimwnasptd

Did you solve the problem?

**Comment by xixici** [comment]
> > Your work is commendable. However, I noticed a similar approach in another pull request, specifically in #10269. Similarly, I'm puzzled by aspects of the feature, such as:
> > > I added the environment variables in the API server, but it doesn't seem to have any effect. Here are the commands I used:
> > > ```
> > > echo 'export V2_LAUNCHER_IMAGE=kfp-launcher:0.0.1-aarch64-beta' >> ~/.bashrc
> > > echo 'export V2_DRIVER_IMAGE=kfp-driver:0.0.1-aarch64-beta' >> ~/.bashrc
> > > 
> > > source ~/.bashrc
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I also added the environment variables in the ArgoExec image, but unfortunately, it doesn't work either.
> > > I'm confused about this feature. I am not a Golang engineer, so I might have made some mistakes in understanding or implementing the necessary configurations.
> > 
> > 
> > @xixici
> 
> Did you solve the problem?

The way by changing environment variables is not successful for me. I have solved this by changing the code and compiling it myself.

**Pull request closed without merging**
