### PR TITLE
feat(backend): sorting on run metrics - step 1

### PR DESCRIPTION
**Pull request by jingzhang36**
**Description of your changes:**

We are trying to sort on the run metrics, and since sorted order that happens in the inner query is not preserved throughout the later join, we'll need to move the run metrics to the outer query.  This PR is moving the joining of run metrics table to the outer query, as the first step in adding the sorting features on run metrics.

The query before:
```
SELECT    subq.*, concat("[",group_concat(r.payload separator ","),"]") AS refs
FROM      (
                    SELECT    rd.*, concat("[",group_concat(m.payload separator ","),"]") AS metrics
                    FROM      (
                                       SELECT   uuid,
                                                experimentuuid,
                                                displayname,
                                                NAME,
                                                storagestate,
                                                namespace,
                                                serviceaccount,
                                                description,
                                                createdatinsec,
                                                scheduledatinsec,
                                                finishedatinsec,
                                                conditions,
                                                pipelineid,
                                                pipelinename,
                                                pipelinespecmanifest,
                                                workflowspecmanifest,
                                                parameters,
                                                pipelineruntimemanifest,
                                                workflowruntimemanifest
                                       FROM     run_details
                                       WHERE    uuid IN
                                                (
                                                       SELECT resourceuuid
                                                       FROM   resource_references AS rf
                                                       WHERE  (
                                                                     rf.resourcetype = ?
                                                              AND    rf.referenceuuid = ?
                                                              AND    rf.referencetype = ?))
                                       AND      storagestate <> ?
                                       ORDER BY createdatinsec DESC, uuid DESC limit 11) AS rd
                    LEFT JOIN run_metrics                           AS m
                    ON        rd.uuid=m.runuuid
                    GROUP BY  rd.uuid) AS subq
LEFT JOIN resource_references          AS r
ON        r.resourcetype='Run'
AND       subq.uuid=r.resourceuuid
GROUP BY  subq.uuid
ORDER BY  createdatinsec DESC, uuid DESC
```

The query after:
```
SELECT    subq.*,  concat("[",group_concat(rm.payload separator ","),"]") AS metrics 
FROM      ( 
                    SELECT    rd.*,  concat("[",group_concat(rr.payload separator ","),"]") AS refs 
                    FROM      ( 
                                         SELECT     uuid, 
                                                    experimentuuid, 
                                                    displayname, 
                                                    NAME, 
                                                    storagestate, 
                                                    namespace, 
                                                    serviceaccount, 
                                                    description, 
                                                    createdatinsec, 
                                                    scheduledatinsec, 
                                                    finishedatinsec, 
                                                    conditions, 
                                                    pipelineid, 
                                                    pipelinename, 
                                                    pipelinespecmanifest, 
                                                    workflowspecmanifest, 
                                                    parameters, 
                                                    pipelineruntimemanifest, 
                                                    workflowruntimemanifest 
                                         FROM       run_details 
                                         INNER JOIN resource_references 
                                         ON         run_details.uuid = resource_references.resourceuuid
                                         WHERE      ( 
                                                               resource_references.resourcetype = ?
                                                    AND        resource_references.referenceuuid = ?
                                                    AND        resource_references.referencetype = ?)
                                         AND        storagestate <> ? 
                                         ORDER BY   createdatinsec DESC,  uuid DESC limit 11) AS rd 
                    LEFT JOIN resource_references                       AS rr 
                    ON        rr.resourcetype='Run' 
                    AND       rd.uuid=rr.resourceuuid 
                    GROUP BY  rd.uuid) AS subq 
LEFT JOIN run_metrics                  AS rm 
ON        subq.uuid=rm.runuuid 
GROUP BY  subq.uuid 
ORDER BY  createdatinsec DESC,  uuid DESC
```

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Bobgy** [comment]
To be honest, I don't really understand complex SQL.
/lgtm

Q: is this code change unit testable?

**Comment by jingzhang36** [comment]
> To be honest, I don't really understand complex SQL.
> /lgtm
> 
> Q: is this code change unit testable?

A: this is covered by existing unit tests. E.g., by swapping the order of left joins, the resulting rows having the last two columns swapped. And if the code change in the scanning rows method is omitted from this PR, you'll see the unit tests broken. In other words, the existing units cover this sql query.

**Pull request merged**
