### PR TITLE
fix(backend): publish launcher execution even if it fails

### PR DESCRIPTION
**Pull request by Linchin**
**Description of your changes:**
@jlyaoyuli found that when a task fails, the launcher does not publish the execution, leading the status of the task to remain `running`.  This PR fixes that by moving the publish function into a defer function, so it is always carried out, even if the task fails.

Manually tested that failed status is reported.

Note:
Need to build and update launcher image once the PR is approved. 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — COMMENTED** [review]
/lgtm

Thank you @Linchin for the fix. Please go ahead and update the image.

**Comment by Linchin** [comment]
Merge due to only new change is updating launcher image.
/lgtm
/approve

**Review by chensun — APPROVED** [review]
/lgtm

Thanks!

**Pull request merged**
