### PR TITLE
SDK - Setup - Added cloudpickle to requirements

### PR DESCRIPTION
**Pull request by Ark-kun**
Cloudpickle is used by the `func_to_container_op(..., use_code_pickling=True)` and `create_component_from_airflow_operator`.
`setup.py` installs it, but requirements.txt did not have it.

Long-term fix: We need to make `setup.py` use `requirements.txt`. 

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2437)

### CODE REVIEW

**Comment by numerology** [comment]
Can you add to the description for where cloudpickle is used? Thanks.

**Comment by Ark-kun** [comment]
> Can you add to the description for where cloudpickle is used? Thanks.

Done.

**Comment by numerology** [comment]
/lgtm
Do we have any version constraint on cloudpickle?

**Comment by Ark-kun** [comment]
> Do we have any version constraint on cloudpickle?

I've added an explicit version in both places.

**Comment by numerology** [comment]
/lgtm
Thanks!

**Pull request merged**
