### PR TITLE
Add resnet-cmle sample back. Update all component images.

### PR DESCRIPTION
**Pull request by qimingj**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/632)

### CODE REVIEW

**Comment by gaoning777** [comment]
Add a sample test for the resnet?

**Comment by qimingj** [comment]
I do plan to but this one takes much longer time so we need to do some parameter tuning, and perhaps data sampling. Plan to do it in a separate change.

**Comment by qimingj** [comment]
Yes. The sample test will come soon. For some reasons your /lgtm was not picked up (maybe because the extra ".")?

**Pull request merged**
