### PR TITLE
add us to OWNERS for SHA

### PR DESCRIPTION
**Pull request by rmgogogo**
Add us to OWNERS for SHA

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2047)

### CODE REVIEW

**Comment by IronPan** [comment]
Could you add to just frontend for now?

**Comment by neuromage** [comment]
@rmgogogo Can this just be frontend for now?

**Comment by rmgogogo** [comment]
I removed Yuan and I but put Jing to owner list as prefer at least one people from SHA to co operate it.

**Comment by neuromage** [comment]
@rmgogogo You may not really need root OWNER here. Is there something outside frontend that you'll be working on, that you think will be impacted by the possible one day latency? If so, should we consider moving that to a separate directory? I think files like cloudbuild config are good candidates for this. WDYT?  I definitely don't want to slow SHA team down, but I'm not sure if this will make a material difference. It is also worth noting that you have write permission to this repository, so if an emergency fix is needed, you can use this mechanism (as a last resort of course, but it will work).

**Comment by rmgogogo** [comment]
Updated

**Comment by Bobgy** [comment]
@IronPan can you approve this one?

**Pull request merged**
