### PR TITLE
test(v2): fix kaniko component digest

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Debug logs are in https://github.com/kubeflow/pipelines/issues/5586

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
/assign @capri-xiyue @chensun 
this unblocks presubmit failures, so I'll merge first

**Comment by capri-xiyue** [comment]
The samples-v2-test failed with deadlock.
error msg is as follows:
`F0503 19:01:47.644931       1 main.go:56] Failed to execute component: rpc error: code = Aborted desc = mysql_query aborted: errno: 1213, error: Deadlock found when trying to get lock; try restarting transaction`

**Comment by Bobgy** [comment]
Final resolution recorded in https://github.com/kubeflow/pipelines/issues/5586#issuecomment-832439442

**Pull request merged**
