### PR TITLE
Build file added after running `bazel run //:gazelle`

### PR DESCRIPTION
**Pull request by chensun**
The file is added by running backend/api/generate_api.sh on master HEAD with no local change.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3199)

### CODE REVIEW

**Comment by numerology** [comment]
Can you elaborate on why this is needed? Thanks! @chensun

**Comment by chensun** [comment]
> Can you elaborate on why this is needed? Thanks! @chensun

Background was: I made changes to some API proto message, and ran the generate_api.sh script to update the generated code. This file was added during that process, and it appeared to be irrelevant to my API changes. Then I switched to a clean branch based off master and ran the script again, this build file is again generated. 
So I think every time someone ran the generate_api.sh script, they will experience the same util this file is checked in. Thus, I made this PR. 
Do you think this might be due to a glitch with the generate_api.sh script and I should discard this change?

**Comment by numerology** [comment]
> Do you think this might be due to a glitch with the generate_api.sh script and I should discard this change?

Probably that's because /backend used to be the only places we generate such APIs? IIUC the protos under SDK should not causing backend API changes. We might need to update `generate_api.sh` to white-list those.

Thanks for figuring this out :)

**Comment by chensun** [comment]
> > Do you think this might be due to a glitch with the generate_api.sh script and I should discard this change?
> 
> Probably that's because /backend used to be the only places we generate such APIs? IIUC the protos under SDK should not causing backend API changes. We might need to update `generate_api.sh` to white-list those.
> 
> Thanks for figuring this out :)

Make sense, I will close this PR for now. And we can sync later 

> > Do you think this might be due to a glitch with the generate_api.sh script and I should discard this change?
> 
> Probably that's because /backend used to be the only places we generate such APIs? IIUC the protos under SDK should not causing backend API changes. We might need to update `generate_api.sh` to white-list those.
> 
> Thanks for figuring this out :)

I took a quick look, because there is this proto file: `sdk/python/kfp/components/structures/components.proto`, the last line from `generate_api.sh`, i.e `bazel run //:gazelle` caused this `BUILD.bazel` to be generated. 

I can see that it might not make sense for `backend/api/generate_api.sh` to generate this file under sdk folder, but the addition of this file seems to me legit and worth checking in? WDTY?

**Comment by Ark-kun** [comment]
It's probably better to limit gazelle run to //backend

**Comment by numerology** [comment]
> I can see that it might not make sense for backend/api/generate_api.sh to generate this file under sdk folder, but the addition of this file seems to me legit and worth checking in? WDTY?

Is there any other piece of work depending on this file?

**Comment by chensun** [comment]
Looks like this change doesn't add much value. I'll close this PR then.

**Pull request closed without merging**
