### PR TITLE
fix(manifests): Remove redundant secret value in profile controller

### PR DESCRIPTION
**Pull request by zijianjoy**
**Description of your changes:**

Address comment in https://github.com/kubeflow/pipelines/pull/5864

cc @jacobmalmberg

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by jacobmalmberg** [comment]
not sure if my input is needed, but yeah this can be merged

**Comment by zijianjoy** [comment]
Thank you @Bobgy for the LGTM!

**Comment by zijianjoy** [comment]
/test kubeflow-pipeline-upgrade-test

Deployment timed out.

**Pull request merged**
