### PR TITLE
SDK - Added the argo-models to requirements.txt

### PR DESCRIPTION
**Pull request by Ark-kun**
requirements.txt needs to be consistent with setup.py.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1367)

### CODE REVIEW

**Comment by michelle192837** [comment]
Tide is failing to merge this; see #1371

**Comment by Ark-kun** [comment]
/hold cancel
/approve
@gaoning777 Can you please re-lgtm? (I've just re-pushed the same change to restart Travis. There were no changes)

**Pull request merged**
