### PR TITLE
tests: Fixed the kubeflow-pipelines-tfx-python36 test. Fixes #4390

### LINKED ISSUE #4390: The kubeflow-pipelines-tfx-python36 test is failing
```
+ python3 -m pip install . --upgrade
Processing /home/prow/go/src/github.com/kubeflow/pipelines/tfx
    ERROR: Command errored out with exit status 255:
     command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-vg98fja9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-vg98fja9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lbr5xhyc
         cwd: /tmp/pip-req-build-vg98fja9/
    Complete output (2 lines):
    Generating tfx/proto/example_gen_pb2.py...
    protoc is not installed nor found in ../src.  Please compile it or install the binary package.
```

### PR DESCRIPTION
**Pull request by Ark-kun**
Unpinned the TFX version.
This fixes the protoc issue.
The ml_metadata issue is already fixed in master.

Fixes https://github.com/kubeflow/pipelines/issues/4390

### CODE REVIEW

**Comment by numerology** [comment]
/lgtm

Thanks! However I think TFX is giving up the compatibility guarantee between TFX head and the latest released parent libs (MLMD/TFDV/TFT/TFMA...) so I think we might stop running the head test.

Do you mind adding a TODO here? I can address this shortly

**Comment by Ark-kun** [comment]
> TFX is giving up the compatibility guarantee between TFX head and the latest released parent libs (MLMD/TFDV/TFT/TFMA...) 

I wish TFX had a proper "known good" `requirements.txt`.

>so I think we might stop running the head test.

I can re-pin it to 0.23.rc0 instead. WDYT?

**Comment by Ark-kun** [comment]
/unhold
Re-pinned to v0.23.0-rc0

**Comment by numerology** [comment]
/lgtm

> I can re-pin it to 0.23.rc0 instead. WDYT?

Yes that SGTM at this moment

**Pull request merged**
