### PR TITLE
reduce taxi and xgboost test data to speed up sample test

### PR DESCRIPTION
**Pull request by gaoning777**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1917)

### CODE REVIEW

**Comment by gaoning777** [comment]
For sure. I was waiting for the tests to pass before cleaning those up, thus making sure the smaller size does not affect correctness.

**Comment by numerology** [comment]
Seems like we need a sample set big enough to include both pos and neg samples so that roc_curve can work. @gaoning777

**Comment by gaoning777** [comment]
> Seems like we need a sample set big enough to include both pos and neg samples so that roc_curve can work. @gaoning777

You are correct. Closing this.

**Comment by numerology** [comment]
How do you like the idea of hard coding one must-be-positive sample so that the roc_curve is defined?

**Pull request closed without merging**
