### PR TITLE
chore(components): clean up component directory

### PR DESCRIPTION
**Pull request by IronPan**
**Description of your changes:**
This PR cleans up the component directory and move the ones without maintain to the contrib folder.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
> @IronPan: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> kubeflow-pipelines-component-yaml	[8382aad](https://github.com/kubeflow/pipelines/commit/8382aadef83a10c555690cdff58ba270ed34d4a9)	[link](https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/7183/kubeflow-pipelines-component-yaml/1484441690633670656)	true	`/test kubeflow-pipelines-component-yaml`
> kubeflow-pipelines-samples-v2	[8382aad](https://github.com/kubeflow/pipelines/commit/8382aadef83a10c555690cdff58ba270ed34d4a9)	[link](https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/7183/kubeflow-pipelines-samples-v2/1484441690684002304)	true	`/test kubeflow-pipelines-samples-v2`

@IronPan @chongyouquan Were these failures investigated? If it's related to this change, do we plan to update the tests or disable them?

**Comment by chensun** [comment]
> **Description of your changes:** This PR cleans up the component directory and move the ones without maintain to the contrib folder.
> 
> **Checklist:**
> 
> * [x]  The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

@IronPan It looks like you intended to move them, but the change actually deleted them. Was this expected?

**Comment by zijianjoy** [comment]
This change has caused `components/build_image.sh` not found in the presubmit test: https://pantheon.corp.google.com/cloud-build/builds/6aab8551-74c1-4d21-b705-3ce2c7cd035b;step=21?project=ml-pipeline-test

**Pull request merged**
