### PR TITLE
Generate pipeline and job python client as part of SDK

### PR DESCRIPTION
**Pull request by IronPan**
So people can use python to CRUD pipeline or job, from for example notebook.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/628)

### CODE REVIEW

**Comment by IronPan** [comment]
fix https://github.com/kubeflow/pipelines/issues/617

**Comment by gaoning777** [comment]
How about adding another function: upload_pipeline in the SDK to fix #617?
Wrapping the swagger interface helps to reduce friction for python SDK usage.

**Comment by qimingj** [comment]
Ditto @gaoning777. This is fine as the first step and we'll need a wrapper. We also need to add the packages in setup.py (https://github.com/kubeflow/pipelines/blob/master/sdk/python/setup.py)

**Comment by qimingj** [comment]
We can probably do the wrapper and add those to setup.py in a separate change.

**Comment by IronPan** [comment]
thanks i always forgot setup.py. I'll add it separately

**Pull request merged**
