### PR TITLE
A more accurate grpc error code for duplicate pipeline/pipeline version/experiment names

### LINKED ISSUE #3353: Creating Pipeline with duplicate name fails in UI with 500
### What steps did you take:
Creating Pipeline with duplicate name fails in UI with 500

### What did you expect to happen:
Either allow create pipeline with same name or provide better msg.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

### LINKED ISSUE #3723: Return 409 instead of 500 when pipeline being uploaded already exists
### What steps did you take:
We are using kfp client to upload a pipeline. We are currently retrying 5xx errors to handle temporary server glitches; however, since upload pipeline returns 500 when the pipeline being uploaded already exists, we are also retrying those requests. A different status code would help us differentiate between different types of errors.

### What happened:
Return 500 error when pipeline being uploaded already exists.

```
HTTP response body: {"error_message":"Error creating pipeline: Create pipeline failed: Invalid input error: Failed to create a new pipeline. The name xxxx already exist. Please specify a new name.","error_details":"Error creating pipeline: Create pipeline failed: Invalid input error: Failed to create a new pipeline. The name xxxx already exist. Please specify a new name."}
```

### What did you expect to happen:
Return 409 error when pipeline being uploaded already exists. 

/kind bug
/area backend

### PR DESCRIPTION
**Pull request by jingzhang36**
Fixes #3353 
Fixes #3723

### CODE REVIEW

**Comment by Bobgy** [comment]
Thanks!
/lgtm

**Comment by Bobgy** [comment]
/hold
Travis test is still failing, this will break prow

**Comment by Bobgy** [comment]
@jingzhang36 FYI, I edited description, because it seems you put the wrong issue there.
(also used the Fixes syntax, so that issues will be automatically closed when this PR merged)

**Comment by jingzhang36** [comment]
> /hold
> Travis test is still failing, this will break prow

Travis test has been fixed by https://github.com/kubeflow/pipelines/pull/3833
And now the Travis test is passing. 
/hold cancel

**Pull request merged**
