### PR TITLE
Add external links that make some content easier to discover

### PR DESCRIPTION
**Pull request by Bobgy**
/assign @rmgogogo 
/assign @IronPan

Idea was proposed in https://github.com/kubeflow/pipelines/issues/1253
UPDATE, latest screenshots:
</img> </img>

The three links are:
* github repo: https://github.com/kubeflow/pipelines
* aihub samples: https://aihub.cloud.google.com/u/0/s?category=pipeline
* documentation: https://www.kubeflow.org/docs/pipelines/

Also added compile pipeline documentation link in pipeline upload dialog:
download (23)
The link is: https://www.kubeflow.org/docs/pipelines/sdk/build-component/#compile-the-pipeline

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2068)

### CODE REVIEW

**Comment by Bobgy** [comment]
Fixes https://github.com/kubeflow/pipelines/issues/1253

**Comment by Bobgy** [comment]
video: https://drive.google.com/file/d/1HU76mAjDFCCRCz_QLiCaWs0_f0YF8UM9/view
This is my initial attempt, I didn't go for the design that collapse all three external links to a single "..." item because it needs some complex animation set up to make that fluent.

Any feedback?

**Comment by rmgogogo** [comment]
hi Yuan, I just notice this PR. 
Is it still on radar to be continued? Seems put there for days.

I'm generally OK. We have another working item which link the KFP with explicit cluster in GCP. It may require more changes and we can handle it in another PR.

/lgtm

**Comment by Bobgy** [comment]
Yes, I plan to finish this. After other things I've put a higher priority.

**Comment by Bobgy** [comment]
FYI, I got the github icon from https://github.com/logos
It's recommended to be used when placed next to a link to github.

**Comment by rmgogogo** [comment]
/lgtm

Thanks.

**Pull request merged**
