### PR TITLE
Update OWNERS file

### PR DESCRIPTION
**Pull request by animeshsingh**
I will reviewing, merging and maintaining pipelines from IBM

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/698)

### CODE REVIEW

**Comment by gaoning777** [comment]
Do you mean the contrib/samples/openvino sample?

**Comment by animeshsingh** [comment]
Hi @gaoning777 -  It will be some sample pipelines we will be creating to be going to the main samples repository on an ongoing basis. Had a discussion with @jlewi on that yesterday

**Comment by vicaire** [comment]
Hi animeshsingh@, could you please reduce your ownership to the specific subdirectories that you need to modify?

**Comment by animeshsingh** [comment]
Thanks @vicaire - done.

**Comment by animeshsingh** [comment]
@vicaire please take a look

**Comment by vicaire** [comment]
Hi animeshsingh@,

At this time, "approver" permissions on the pipeline repo are only for core members of the pipeline team. 

We can grant "reviewer" permissions only on the specific code that you contribute to the repo.

**Comment by jlewi** [comment]
Hi @animeshsingh 

Here's some more information about OWNERs files and the review process
https://www.kubeflow.org/docs/about/contributing/#joining-the-community

This doc has some more general information about the distinctions between approvers and reviewers
https://goo.gl/kqHQLJ

In general we want to try to scope OWNERs files narrowly. This helps the review process because reviews can be auto-assigned to the person with the most context.

When possible and sensible if we can organize code that should be owned by an individual or group of individuals into its own directory this is best because then we can have an OWNERs file pertaining to that code.

So in this particular case I think it makes sense to create a directory for IBM related components and then we can add you and the other maintainers to the OWNERs file for that directory.

We could either create that directory in kubeflow/pipelines or kubeflow/examples.

If you're thinking of creating samples that are more than just pipeline components then it might make sense to put it in kubeflow/examples.

@rawkintrevo has been working on a guide for Kubeflow on BlueMix. 
https://github.com/intro-to-ml-with-kubeflow/ibm-install-guide

The current version is a bit outdated (its still using Kubeflow 0.2.5). kubeflow/examples would be a natural place to host that sample and begin soliciting additional contributions.

**Comment by animeshsingh** [comment]
Thanks @vicaire and @jlewi. As discussed, to begin with, the idea is to contribute Pipeline samples to pipeline repo, and we intend to do it on a regular basis. And hence at a minimum it will require access to pipelines samples and components repository. Now I will be more that happy to be an approver and reviewer for non IBM contributions as well to those two repos. If you think creating IBM specific subdirectories for both sample and components would be better approach, lets go with that to begin with.

**Comment by animeshsingh** [comment]
Thinking if we can do this - create a folder ibm-components under components, and ibm-samples under samples, and add a OWNER file with an approver and reviewers from IBM. If that works, I can rework this PR.

**Comment by vicaire** [comment]
Yes, you can get these permissions for the new directories that you listed, thanks!

**Comment by animeshsingh** [comment]
Thanks.  I will infact close this and start with a new one, to begin with placeholder directories for these components and samples

**Pull request closed without merging**
