### PR TITLE
fix(test): Pin pip version in presubmit-tests-tfx.sh Fixes #5049

### LINKED ISSUE #5049: Presubmit test kubeflow-pipelines-tfx-python36 failing
https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/5042/kubeflow-pipelines-tfx-python36/1354678589223604224

Times out while waiting for pip install to finish. 
```
...
INFO: pip is looking at multiple versions of requests-oauthlib to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of markdown to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of google-auth-oauthlib to determine which version is compatible with other requirements. This could take a while.
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)
{"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2021-01-28T08:32:17Z"}
{"component":"entrypoint","file":"prow/entrypoint/run.go:250","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace period","severity":"error","time":"2021-01-28T08:32:33Z"}
```

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
Fixes #5049

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by numerology** [comment]
/lgtm
/approve

Thanks!

**Comment by DavidSpek** [comment]
@chensun Any chance this is related to the errors seen in https://github.com/kubeflow/pipelines/pull/5057?

**Comment by chensun** [comment]
> @chensun Any chance this is related to the errors seen in #5057?

No. I replied in that PR.

So after I pinned pip to 20.2.3, it now reveals where the conflict is:
```
ERROR: Cannot install tfx-dev 0.27.0.dev0, apache-beam[gcp] 2.27.0 and tfx-dev because these package versions have conflicting dependencies.
The conflict is caused by:
    tfx-dev 0.27.0.dev0 depends on pyarrow<3 and >=1
    apache-beam[gcp] 2.27.0 depends on pyarrow<3.0.0 and >=0.15.1
    tensorflow-data-validation 0.26.0 depends on pyarrow<0.18 and >=0.17
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by DavidSpek** [comment]
Thanks for checking that quickly. Just as an FYI with regards to https://github.com/kubeflow/pipelines/pull/5056. The Renovate bot also pins dependencies. For example: https://github.com/DavidSpek/pipelines/pull/163.

**Comment by chensun** [comment]
> Thanks for checking that quickly. Just as an FYI with regards to #5056. The Renovate bot also pins dependencies. For example: [DavidSpek#163](https://github.com/DavidSpek/pipelines/pull/163).

Thanks for the info. I'll take a look.

Regarding the current dependency issue we here, this is due to a recent change on TFX side, so I opened https://github.com/tensorflow/tfx/issues/3157.

If you have PRs blocked by this test, we can likely ignore it. Please ping me if you need help merging such PRs.

**Comment by zijianjoy** [comment]
/lgtm
/approve

Thank you Chen!

**Pull request merged**
