### PR TITLE
SDK - Update argo-models version

### PR DESCRIPTION
**Pull request by nicolas-geniteau**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2103)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Which Argo version does `post1` correspond to?
We should probably use the release version.

**Comment by nicolas-geniteau** [comment]
`2.3.0.post1` correspond to `2.3.0` Argo.

The `post1` is the last release. The only difference with `2.3.0` is that it include LICENSE file in package.

**Comment by Ark-kun** [comment]
The SDK no longer uses the `argo-models` package.

**Pull request closed without merging**
