### PR TITLE
Revert sample test to mitigate test flakiness

### PR DESCRIPTION
**Pull request by IronPan**
https://github.com/kubeflow/pipelines/issues/272

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/277)

### CODE REVIEW

**Comment by yebrahim** [comment]
This doesn't look to me like a clean revert. Can you explain the change?

**Comment by IronPan** [comment]
I got "Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged." when i click revert button. 

this change instead commented out the tests.

**Comment by gaoning777** [comment]
Did the flakiness  result from the frontend integration tests or the basic e2e sample test?

**Comment by yebrahim** [comment]
The failures were in the frontend integration test as far as I've seen.

**Comment by gaoning777** [comment]
Shouldn't we keep the basic e2e sample tests then because it helps to test the consistency between dsl and pipeline system and make sure the basic sample tests are working e2e? @IronPan

**Comment by yebrahim** [comment]
Yes, we should do this revert properly, but it was good to unblock tests quickly too.

**Pull request merged**
