### PR TITLE
fix(components) fixes confusion matrix component. Fixes #5484

### LINKED ISSUE #5484: [bug] Confusion matrix component task fails
### What steps did you take

I created a task in a pipeline using the [confusion matrix](https://github.com/kubeflow/pipelines/tree/ab63956f3a61d4d11b27ac26f097e1784588fed9/components/local/confusion_matrix) component.

### What happened:
The task failed with the following message:
```
Traceback (most recent call last):
  File "/ml/confusion_matrix.py", line 29, in <module>
    import pandas as pd
ImportError: No module named pandas
```
I believe this is because the Python dependencies are [installed for Python 3](https://github.com/kubeflow/pipelines/blob/master/components/local/base/Dockerfile), whereas the command in the component definition is `python2 ...`. 

### What did you expect to happen:

For the task to complete successfully.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 
GCP AI Platform Pipelines
*  KFP version: 
1.4.1
*  KFP SDK version: 
1.4.0

### Anything else you would like to add:

If this issue is legitimate (and I haven't misinterpreted the error), I believe the [roc component](https://github.com/kubeflow/pipelines/tree/ab63956f3a61d4d11b27ac26f097e1784588fed9/components/local/roc) will suffer from the same issue.

### Labels

/area components

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by Mullefa**
**Description of your changes:**

Fixes #5484.

Note this PR as-is is not good to go. In particular the component definition will have to be updated to reference a new Docker image based on the updated Python code. I'm looking for advice on how to do this.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by NikeNano** [comment]
Thanks for the PR :) You will have to sign the CLA @Mullefa

**Comment by NikeNano** [comment]
Reminder that you have to sign the CLA @Mullefa

**Comment by rimolive** [comment]
Closing this PR. No activity for more than a year.

/close

**Pull request closed without merging**
