### PR TITLE
feat(components) Update KFServing component to use v0.5.1

### PR DESCRIPTION
**Pull request by pvaneck**
**Description of your changes:**

This PR updates the KFServing python package version used in this component. The image has already been pushed to quay.io.

### CODE REVIEW

**Comment by Ark-kun** [comment]
/lgtm

BTW, does KFServing work if model-uri is a container-local file path?

**Comment by pvaneck** [comment]
@Ark-kun Hmm, I do not believe so, but you can pass in a custom container spec that uses an image with the model baked in like [here](https://github.com/kubeflow/kfserving/blob/master/docs/samples/v1beta1/custom/torchserve/torchserve-custom.yaml) or use a PVC like [here](https://github.com/kubeflow/kfserving/blob/master/docs/samples/storage/pvc/mnist-pvc.yaml).

**Pull request merged**
