### PR TITLE
fix(sdk): fixes the default value for _is_refresh_token. Fixes #4189

### LINKED ISSUE #4189: [Testing] postsubmit test failing on release-1.0 branch
### What steps did you take:
Look at commit: https://github.com/kubeflow/pipelines/commit/bd7f3c9cd60144aef953db7aa2a4b17cec1cfa73

### What happened:
standalone component test failed:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-standalone-component-test/1281172742669864961

Error message in the client:
> sample-test-gf4sm-3534797757: 
sample-test-gf4sm-3534797757: Traceback (most recent call last):
sample-test-gf4sm-3534797757:   File "/python/src/github.com/kubeflow/pipelines/test/sample-test/sample_test_launcher.py", line 236, in <module>
sample-test-gf4sm-3534797757:     main()
sample-test-gf4sm-3534797757:   File "/python/src/github.com/kubeflow/pipelines/test/sample-test/sample_test_launcher.py", line 232, in main
sample-test-gf4sm-3534797757:     'component_test': ComponentTest
sample-test-gf4sm-3534797757:   File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 138, in Fire
sample-test-gf4sm-3534797757:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
sample-test-gf4sm-3534797757:   File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 468, in _Fire
sample-test-gf4sm-3534797757:     target=component.__name__)
sample-test-gf4sm-3534797757:   File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
sample-test-gf4sm-3534797757:     component = fn(*varargs, **kwargs)
sample-test-gf4sm-3534797757:   File "/python/src/github.com/kubeflow/pipelines/test/sample-test/sample_test_launcher.py", line 173, in run_test
sample-test-gf4sm-3534797757:     pysample_checker.check()
sample-test-gf4sm-3534797757:   File "/python/src/github.com/kubeflow/pipelines/test/sample-test/run_sample_test.py", line 140, in check
sample-test-gf4sm-3534797757:     response = self._client.wait_for_run_completion(self._run_id, self._test_timeout)
sample-test-gf4sm-3534797757:   File "/usr/local/lib/python3.7/dist-packages/kfp-1.0.0rc4-py3.7.egg/kfp/_client.py", line 680, in wait_for_run_completion
sample-test-gf4sm-3534797757:     self._refresh_api_client_token()
sample-test-gf4sm-3534797757:   File "/usr/local/lib/python3.7/dist-packages/kfp-1.0.0rc4-py3.7.egg/kfp/_client.py", line 242, in _refresh_api_client_token
sample-test-gf4sm-3534797757:     if getattr(self, '_is_refresh_token'):
sample-test-gf4sm-3534797757: AttributeError: 'Client' object has no attribute '_is_refresh_token'

The failing component's pod: https://storage.googleapis.com/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-standalone-component-test/1281172742669864961/artifacts/pods_info/xgboost-trainer-f9sct-3589735778.txt

>   - image: gcr.io/ml-pipeline-test/ml-pipeline-gcp:bd7f3c9cd60144aef953db7aa2a4b17cec1cfa73.0.0-rc.4
    imageID: ""
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    state:
      waiting:
        message: Back-off pulling image "gcr.io/ml-pipeline-test/ml-pipeline-gcp:bd7f3c9cd60144aef953db7aa2a4b17cec1cfa73.0.0-rc.4"
        reason: ImagePullBackOff

It seems the component image is broken.

### What did you expect to happen:
it should pass

### Environment:

KFP version: 1.0.0-rc.4

### Anything else you would like to add:
It seems there are two orthogonal problems here:
1. The client crashed after 1 hour, @numerology I think this should have been fixed by your change. Can you double check?
2. The image url is corrupted, it's a bug in my release script. I'll fix it tomorrow.

/kind bug
/area testing

### PR DESCRIPTION
**Pull request by numerology**
**Description of your changes:**

Fixes https://github.com/kubeflow/pipelines/issues/4189

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [x] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Bobgy** [comment]
/lgtm
/approve

Thanks for quick fix!

**Comment by Ark-kun** [comment]
Thank you for fixing this.

**Comment by numerology** [comment]
> Thank you for fixing this.

:shamecube  Sorry for making the careless culprit

**Comment by Bobgy** [comment]
@numerology thanks anyway! verified postsubmit tests time out properly. They don't fail with the client crash now: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-standalone-component-test/1281393699653160964.

**Pull request merged**
