### PR TITLE
Fix(frontend): content is not available

### PR DESCRIPTION
**Pull request by axel7083**
Fix: https://github.com/kubeflow/pipelines/issues/9611

## Description

The `metadata.Execution` object does not store, the task name, but the task display_name used. When calling [getTaskNameToExecution](https://github.com/kubeflow/pipelines/blob/ba322abb010d832539d57e90c34be0557f550252/frontend/src/lib/v2/DynamicFlow.ts#L373), you get a map of `display_name -> executions[]`. The frontend was using the task name as key, leading to undefined execution.

### CODE REVIEW

**Comment by jlyaoyuli** [comment]
Hi @axel7083 , can you run `npm run format` again for this PR? Thank you!

**Comment by axel7083** [comment]
> Hi @axel7083 , can you run `npm run format` again for this PR? Thank you!

Done

**Comment by sofsms** [comment]
Hi,

Any update on this?
I'm also facing the problem of Content is not available yet.

**Comment by zijianjoy** [comment]
/lgtm
/approve

Thank you @axel7083 for the fix!

**Pull request merged**
