### PR TITLE
chore: adding @hbelmiro to kubernetes_platform/OWNERS

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by hbelmiro** [comment]
@chensun `kfp-kubernetes-execution-tests` was removed from Prow. Can you please rebase so it doesn't block this PR?

**Comment by chensun** [comment]
> @chensun `kfp-kubernetes-execution-tests` was removed from Prow. Can you please rebase so it doesn't block this PR?

@hbelmiro It doesn't need rebase. The Prow config is separate from the KFP code base. As long as this PR get lgtm and approval label, it will be merged.

**Review by hbelmiro — APPROVED** [review]

**Pull request closed without merging**
