### PR TITLE
Enable forcing minio client to v2 signature

### PR DESCRIPTION
**Pull request by omesser**
- We use a minio substitute (v3io-webapi, in www.iguazio.com) which does not support newer signature formats yet, so this would enable compatibility with your upstream in that aspect (we have a few other stuff we need to hack around today, we will issue future PRs).
- Also fixed formatting in those 2 specific places :)

We would very much like to see such small config options in to enable us use pipelines from upstream

Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2866)

### CODE REVIEW

**Comment by rmgogogo** [comment]
sorry, it seems we didn't notice this PR.
/ok-to-test
/retest

@jingzhang36 for your review

**Comment by rmgogogo** [comment]
would you sync and merge? and then /retest

**Comment by omesser** [comment]
@rmgogogo sorry, forgot about that at the time.
Updated to master now, and hit some test failures which I'm not sure I understand.
Can you please take a look at the test failures (this is from backend-test):
```
fatal: unable to access 'https://github.com/modern-go/reflect2/': Failed to connect to github.com port 443: Connection refused
```
This seems related to the test infra

**Comment by omesser** [comment]
@IronPan maybe you can have a look-see please

**Pull request closed without merging**
