### PR TITLE
fix(sdk): Add OOB fix for v1.8 from #8262

### PR DESCRIPTION
**Pull request by gkcalat**
**Description of your changes:**

* Same logic being applied as in #8262 (check it out for more details)
* Tested on KF 1.6.0

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
/lgtm
/approve

Thanks for this! Looking forward to hearing feedback from users.

**Comment by zijianjoy** [comment]
/approve

Thank you Ablai!

**Review by chensun — COMMENTED** [review]
/lgtm
/approve

Thanks!

**Comment by pablofiumara-azumo** [comment]
@zijianjoy  @chensun @connor-mccarthy Are you going to release a new Kubeflow SDK version? If so, can you do it, please? Google set 10/3 as deadline. We, Google customers, need some time to try this before the deadline set by Google

**Comment by pablofiumara** [comment]
@zijianjoy @chensun @connor-mccarthy Are you going to release a new Kubeflow SDK version? If so, can you do it, please? Google set 10/3 as deadline. We, Google customers, need some time to try this before the deadline set by Google

**Comment by gkcalat** [comment]
@pablofiumara 

You can test the fix in 1.8 by following [these instructions](https://github.com/kubeflow/pipelines/issues/7474#issuecomment-1249482356), but add `git checkout sdk/release-1.8` to use v1.8 SDK.

**Comment by pablofiumara** [comment]
@gkcalat Thank you very much for your answer. I have already done that. I need to upgrade some projects in production. Are you all going to release a new KFP version?

**Comment by connor-mccarthy** [comment]
@pablofiumara, yes, we will release a new KFP 1.8 version soon. Likely this week. I will follow up here with a more precise release date (or link to a newly released version) by end of day tomorrow.

**Comment by pablofiumara** [comment]
@connor-mccarthy Have you had time to define when the next KFP release will be available?

**Comment by connor-mccarthy** [comment]
@pablofiumara, 1.8.14 was just released: https://pypi.org/project/kfp/1.8.14/.

**Pull request merged**
