### PR TITLE
feat(kubernetes_platform): Update kubernetes_platform go package to include pod labels and annotations

### PR DESCRIPTION
**Pull request by Tomcli**
**Description of your changes:**
Part of https://github.com/kubeflow/pipelines/issues/9714 and https://github.com/kubeflow/pipelines/issues/9768 and #10363 

Update kubernetes_platform go package to include pod labels and annotations. Once this is ready, I will also update the backend driver, compiler, and SDK with this new feature.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Tomcli** [comment]
Hi @connor-mccarthy, I'm not sure what caused the execution-tests to fail. The PR is intended to add the syntax and proto definition for pod labels and annotations. It won't impact the existing tests.

**Comment by connor-mccarthy** [comment]
@Tomcli, the `kfp-kubernetes-execution-tests` are independent of your code. Feel free to ignore. It is marked as optional and non-blocking.

**Comment by Tomcli** [comment]
Thanks @connor-mccarthy, feel free to let me know any syntax you want me to change in this PR. We want to start adding some common kubernetes pod configurations because we see a big demand on the community and our users.

**Comment by connor-mccarthy** [comment]
Thanks, @Tomcli.

If we are to proceed with these features, the backend changes should precede any SDK changes.

cc @chensun

**Comment by Tomcli** [comment]
Hi @connor-mccarthy, the backend changes actually depended on the go package changes in this PR. Because the go.mod is using an external version of the kubernetes_platform package, we will have to update the go.mod to use local module if we want to also include the backend changes in this PR.

https://github.com/kubeflow/pipelines/blob/55db6f5cef9dde7362872033590a3486c5a123f1/go.mod#L34

**Comment by connor-mccarthy** [comment]
@Tomcli, can we split out the `kfp-kubernetes` SDK changes from the go/proto/backend code? We should leave the `kfp-kubernetes` code in a releasable state whenever possible.

**Comment by Tomcli** [comment]
@connor-mccarthy I updated the PR to only include the proto file and go package changes. I will update the backend in my next PR and then update the SDK afterward.

**Comment by Tomcli** [comment]
@connor-mccarthy Is there anything you want me to change in this PR? I also have the backend changes ready if you want to see why we need to update the kubernetes_platform package.

**Comment by droctothorpe** [comment]
Happy to contribute to this initiative and the follow-up PRs since this feature and toleration support are a requirement for us to migrate to v2.

**Comment by Tomcli** [comment]
Thanks @droctothorpe, if you could help on implementing the toleration support that would be awesome. My plan is to add image pull secret and policy next. 

It seems like this is the flow to add these features:
1. Update the proto file and generate the new kubernetes_platform package (This PR)
2. Update the driver to patch the new pod spec. For pod metadata my changes are not in pod spec so I need to update the backend compiler instead.
3. Update the kfp-kubernetes Python SDK.

**Comment by droctothorpe** [comment]
Sounds good. Down to take a stab at the tolerations implementation. Will flow that you outlined. Makes a ton of sense to break it up into small, discrete PRs.

**Comment by connor-mccarthy** [comment]
/lgtm
/approve

FYI, we're in the process of migrating all of the Pipelines SDKs (`kfp`, `kfp-pipeline-spec`, and `kfp-kubernetes`) to protobuf 4. To do this, we plan to cut a release of `kfp-kubernetes` within the next week. Let's release your SDK changes after that. The proto changes here are okay to be included in this upcoming release.

**Comment by Tomcli** [comment]
> /lgtm /approve
> 
> FYI, we're in the process of migrating all of the Pipelines SDKs (`kfp`, `kfp-pipeline-spec`, and `kfp-kubernetes`) to protobuf 4. To do this, we plan to cut a release of `kfp-kubernetes` within the next week. Let's release your SDK changes after that. The proto changes here are okay to be included in this upcoming release.

That make sense to me. Thank you @connor-mccarthy for the context.

**Pull request merged**
