### PR TITLE
chore(sdk): enforce lower and upper bounds on all dependencies.

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
- Fill in missing lower bounds using versions from https://github.com/kubeflow/pipelines/pull/3303
- Fill in missing upper bounds using the next major versions (assuming they all use semantic versioning, no the next major version could have incompatible changes).

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Review by Bobgy — COMMENTED** [review]
Makes sense to me.

/LGTM
/Hold
In case you need more feedback, feel free to unhold by yourself.

**Comment by Ark-kun** [comment]
/lgtm
Can you please update `requirements.in` as well?

**Comment by chensun** [comment]
> /lgtm
> Can you please update `requirements.in` as well?

Done.

/unhold

**Comment by Bobgy** [comment]
/LGTM
Thank you!

**Pull request merged**
