### PR TITLE
feat(Backend + SDK): Update kfp backend and kubernetes sdk to support node affinity

### PR DESCRIPTION
**Pull request by cjidboon94**
**Description of your changes:**
This PR adds support for node affinity to the driver and kubernetes_platform SDK.

It is a follow up to #10671 and #10583, which updated the protobuf and Golang stub.

It follows the excellent example set by https://github.com/kubeflow/pipelines/pull/10427.

Huge thanks to @Tomcli for paving the way and sharing how to validate things end to end.
Part of https://github.com/kubeflow/pipelines/issues/9768 and https://github.com/kubeflow/pipelines/issues/9682

Pod (Anti)Affinity will be added in a separate PR

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by rimolive** [comment]
Hi @cjidboon94! With #10671 already merged, do you think we can unhold this PR?

**Comment by cjidboon94** [comment]
> Hi @cjidboon94! With #10671 already merged, do you think we can unhold this PR?

@rimolive  For sure!

**Comment by rimolive** [comment]
cc @chensun 

As the PR author said it's ready to review, can you remove the WIP tag?

**Comment by cjidboon94** [comment]
@rimolive Oh, it's not ready yet for review. Sorry, misunderstood what you meant by unhold. What I meant was that I'm going to finish this PR and then will switch it to "Ready for review"

**Comment by cjidboon94** [comment]
@droctothorpe Thanks for making some time! Maybe you can get ahead on the `podAffinity` and `podAntiAffinity` as this PR will only focus on `nodeAffinity`. While pod(anti)Affinity does fall under `Affinity`, I think they're separate enough that you could already work on it. I expect that we might need to merge some things or have a plan on which PR to merge first.

@rimolive 
I believe what's left is:
-[] backend tests
-[] python sdk implementation
-[] python sdk tests

I hope to finish up this week, had some life things going on that kept me off track but those are resolved now.

**Comment by cjidboon94** [comment]
Still requires some work, I think (several more python tests to show different cases), but open to feedback/reviews

**Comment by therc** [comment]
Any way we can help with this (and pod affinity)? The changes look OK from here.

**Pull request closed without merging**
