### PR TITLE
update the image in the samples to use the new component images

### PR DESCRIPTION
**Pull request by gaoning777**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1267)

### CODE REVIEW

**Comment by Ark-kun** [comment]
I think we can do it much easier, cleaner and less fragile:

```
dsl-compile --py taxi-cab-classification-pipeline.py --output taxi-cab-classification-pipeline.yaml

sed -i -e "s|gcr.io/ml-pipeline/ml-pipeline-dataflow-tfdv:\([a-zA-Z0-9_.-]\)\+|${DATAFLOW_TFDV_IMAGE}|g" taxi-cab-classification-pipeline.yaml
```

**Comment by gaoning777** [comment]
The approach you mentioned also requires changes to the run_tfx_test.py such that it accepts yaml files.
I think it does not make much difference whether updating the image tag in the source code or the compiled yaml.

**Comment by Ark-kun** [comment]
The code is extremely fragile. Even removing a single space will break it.

**Comment by gaoning777** [comment]
Make sense. 
Fixed.

**Comment by Ark-kun** [comment]
> Make sense.
> Fixed.

Thanks.

**Comment by Ark-kun** [comment]
Don't you also need to update the kubeflow-training-classification test?

**Comment by gaoning777** [comment]
I found out that the client handles all the different pipeline formats.

**Comment by Ark-kun** [comment]
> Don't you also need to update the kubeflow-training-classification test?

I meant this part for example:
https://github.com/kubeflow/pipelines/blob/84b071c4e985ff753d0fbad4c8ba6be0cdce38fb/test/sample-test/run_test.sh#L156

**Comment by gaoning777** [comment]
postsubmit test is not testing the tf-training sample. So, only the tfx and xgboost is updated.

**Comment by Ark-kun** [comment]
> postsubmit test is not testing the tf-training sample. So, only the tfx and xgboost is updated.

I see.

/lgtm

**Pull request merged**
