### PR TITLE
CRD for scheduling Argo workflows (Implementation)

### PR DESCRIPTION
**Pull request by vicaire**
We named this CRD a "schedule": It schedules workflows for now but we will add support for other K8 resources (e.g., jobs). It supports:

executing pipelines using a cron schedule
executing pipelines using a periodic interval
An optional start date and an end date.
Backfilling (by specifying a start date in the past).
A maximum number of concurrent workflows.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3)

### CODE REVIEW

**Comment by jlewi** [comment]
Can you update the PR description the list of not code generated files looks incorrect.

**Comment by jlewi** [comment]
Review status: 0 of 33 files reviewed at latest revision, all discussions resolved.

---

*[resources/schedule/controller.go, line 108 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHIPVM6A8GTn3AhZTM:-LDHIPVN49pzMukT534g:b-29ysvm) ([raw file](https://github.com/kubeflow/pipelines/blob/4eb4c624223a22a58e23e86c6b9baef8c73edd23/resources/schedule/controller.go#L108)):*
> ```Go
> 		UpdateFunc: func(old, new interface{}) {
> 			controller.enqueueSchedule(new)
> 		},
> ```

Why no DeleteFunc?

---

*[resources/schedule/controller.go, line 195 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHIfrfAMyDMzhUIBnr:-LDHIfrfAMyDMzhUIBns:b19u8ul) ([raw file](https://github.com/kubeflow/pipelines/blob/4eb4c624223a22a58e23e86c6b9baef8c73edd23/resources/schedule/controller.go#L195)):*
> ```Go
> // It then enqueues that Schedule resource to be processed. If the object does not
> // have an appropriate OwnerReference, it will simply be skipped.
> func (c *Controller) handleObject(obj interface{}) {
> ```

This is only handling Workflows right? So why not call it handleWorkflow?

---

*[resources/schedule/controller.go, line 216 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHJZfb2m3V94wag9j9:-LDHJZfb2m3V94wag9jA:bgf26ln) ([raw file](https://github.com/kubeflow/pipelines/blob/4eb4c624223a22a58e23e86c6b9baef8c73edd23/resources/schedule/controller.go#L216)):*
> ```Go
> 		// with it.
> 		if ownerRef.Kind != "Schedule" {
> 			glog.Infof("Processing object (%s): owner is not a Schedule.", object.GetName())
> ```

I recommend using logrus which allows you to output log entries as json records and attach  specific fields to the log entry.
This allows you to add fields for think like workflow schedule name. This makes it easy to filter logs to get all logs for a specific item which is tremendously useful for troubleshooting
see
https://github.com/kubeflow/tf-operator/blob/master/pkg/controller/controller.go#L221

---

*[resources/schedule/controller.go, line 381 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHLq8043MokMNCnQLa:-LDHLq8043MokMNCnQLb:bocf5wf) ([raw file](https://github.com/kubeflow/pipelines/blob/4eb4c624223a22a58e23e86c6b9baef8c73edd23/resources/schedule/controller.go#L381)):*
> ```Go
> 	}
> 
> 	workflow, nextScheduledEpoch, err := c.submitNextWorkflowIfNeeded(schedule, len(active), nowEpoch)
> ```

What happens if a workflow is deleted? 
e.g. suppose your supposed to trigger a workflow every minute
12:00 Trigger Workflow1
12:01 Trigger Workflow2
12:03 Trigger Workflow3

Now Workflow1 is deleted accidentally before it finished. Does Workflow1 get recreated?

---

*[resources/schedule/samples/concurrency.yaml, line 1 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHQ_Hm83ex5S7M_L4F:-LDHQ_Hm83ex5S7M_L4G:bbgoaeu) ([raw file](https://github.com/kubeflow/pipelines/blob/4eb4c624223a22a58e23e86c6b9baef8c73edd23/resources/schedule/samples/concurrency.yaml#L1)):*
> ```YAML
> apiVersion: kubeflow.org/v1alpha1
> ```

Can we move samples into a separate PR?

---

*[resources/schedule/util/parameter_formatter.go, line 33 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHQpAe1RRQTh04O1FB:-LDHQpAe1RRQTh04O1FC:b-n9e4yw) ([raw file](https://github.com/kubeflow/pipelines/blob/4eb4c624223a22a58e23e86c6b9baef8c73edd23/resources/schedule/util/parameter_formatter.go#L33)):*
> ```Go
> 	suffix                  = "]]"
> )
> ```

Per go style all exported types should be commented

---

*[resources/schedule/util/parameter_formatter.go, line 40 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHRu979VjQSo6kUrn8:-LDHRu98D-Vw3bWULo98:b-qw6jfu) ([raw file](https://github.com/kubeflow/pipelines/blob/4eb4c624223a22a58e23e86c6b9baef8c73edd23/resources/schedule/util/parameter_formatter.go#L40)):*
> ```
> func
> ```
The fact that we're creating yet another templating system seems unfortunate.

How does this compare to the templating that Argo uses?

I wonder if anyone has used lambdas or metacontroller to do server side template substitution.

---

*[resources/schedule/util/parameter_formatter.go, line 50 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHTdo1Dv8KfvZ1mx6a:-LDHTdo1Dv8KfvZ1mx6b:b-c084q3) ([raw file](https://github.com/kubeflow/pipelines/blob/4eb4c624223a22a58e23e86c6b9baef8c73edd23/resources/schedule/util/parameter_formatter.go#L50)):*
> ```Go
> 
> func (p *ParameterFormatter) Format(s string) string {
> 	re := regexp.MustCompile("\\[\\[(.*?)\\]\\]")
> ```

If you use a raw string literal back ticks instead of double quotes; can you avoid all the escaping?
https://golang.org/ref/spec#String_literals

---

*[resources/schedule/util/schedule_periodic_wrap.go, line 37 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHUu-aDuLkC8WQTiuu:-LDHUu-aDuLkC8WQTiuv:b-ob911c) ([raw file](https://github.com/kubeflow/pipelines/blob/4eb4c624223a22a58e23e86c6b9baef8c73edd23/resources/schedule/util/schedule_periodic_wrap.go#L37)):*
> ```Go
> }
> 
> func (s *PeriodicScheduleWrap) GetNextScheduledEpoch(lastJobEpoch *int64,
> ```

Isn't it brittle to only track lastJobEpoch and assume all prior jobs are ok? Per my other comment what if an earlier run is interrupted or deleted?

Why wouldn't you compare the state of expected jobs to actual jobs? The analogy would be a StatefulSet. If a StatefulSet has N replicas, you want to ensure all N pods exist. The only difference here is that N increases with time.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3)*

**Comment by jlewi** [comment]
Review status: 0 of 36 files reviewed at latest revision, 6 unresolved discussions.

---

*[resources/schedule/controller.go, line 381 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHLq8043MokMNCnQLa:-LDn-j7SAZ9gGuOToCqq:b-so4jzs) ([raw file](https://github.com/kubeflow/pipelines/blob/ebaffdf9f99ce49aa4205d55e473820ed3099c91/resources/schedule/controller.go#L381)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

What happens if a workflow is deleted? 
e.g. suppose your supposed to trigger a workflow every minute
12:00 Trigger Workflow1
12:01 Trigger Workflow2
12:03 Trigger Workflow3

Now Workflow1 is deleted accidentally before it finished. Does Workflow1 get recreated?
</blockquote></details>

There is an issue to address this
https://github.com/kubeflow/pipelines/issues/5

---

*[resources/schedule/util/schedule_periodic_wrap.go, line 37 at r1](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDHUu-aDuLkC8WQTiuu:-LDn1giK13xtecuuPt7D:b-27n41u) ([raw file](https://github.com/kubeflow/pipelines/blob/ebaffdf9f99ce49aa4205d55e473820ed3099c91/resources/schedule/util/schedule_periodic_wrap.go#L37)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Isn't it brittle to only track lastJobEpoch and assume all prior jobs are ok? Per my other comment what if an earlier run is interrupted or deleted?

Why wouldn't you compare the state of expected jobs to actual jobs? The analogy would be a StatefulSet. If a StatefulSet has N replicas, you want to ensure all N pods exist. The only difference here is that N increases with time.
</blockquote></details>

There is an open issue for this
https://github.com/kubeflow/pipelines/issues/5

---

*[resources/scheduledworkflow/util/label.go, line 26 at r2](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDn0OGV4QoB4nyahfrj:-LDn0OGV4QoB4nyahfrk:b-oz5veb) ([raw file](https://github.com/kubeflow/pipelines/blob/75f84b5c66dccc6c6aa60084326678beccafb2ca/resources/scheduledworkflow/util/label.go#L26)):*
> ```Go
> )
> 
> func GetRequirementForCompletedWorkflowOrFatal(completed bool) *labels.Requirement {
> ```

Exported functions should all have comments

---

*[resources/scheduledworkflow/util/swf_wrap.go, line 39 at r2](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDn1xJn3g29Wj-3QriA:-LDn1xJn3g29Wj-3QriB:bmut8vv) ([raw file](https://github.com/kubeflow/pipelines/blob/75f84b5c66dccc6c6aa60084326678beccafb2ca/resources/scheduledworkflow/util/swf_wrap.go#L39)):*
> ```Go
> )
> 
> // ScheduledWorkflowWrap is a wrapper to help manipulate ScheduledWorkflow objects.
> ```

Why do you need a wrapper?

Why can't you just define these functions directly on type *swfapi.ScheduledWorkflow e.g.

function (s *swfapi.ScheduledWorflow)_ ScheduleWorkflow () {
...
}

---

*[resources/scheduledworkflow/util/workflow_wrap.go, line 26 at r2](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDn2qyH4AKi-yCTd2RZ:-LDn2qyH4AKi-yCTd2R_:b-aq69ar) ([raw file](https://github.com/kubeflow/pipelines/blob/75f84b5c66dccc6c6aa60084326678beccafb2ca/resources/scheduledworkflow/util/workflow_wrap.go#L26)):*
> ```Go
> 
> // WorkflowWrap is a wrapper to help manipulate workflow objects.
> type WorkflowWrap struct {
> ```

Why do you need a wrapper? Why not just define these methods directly on type *workflowapi.Workflow?

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3)*

**Comment by vicaire** [comment]
Review status: 0 of 36 files reviewed at latest revision, 9 unresolved discussions.

---

*[resources/scheduledworkflow/util/workflow_wrap.go, line 26 at r2](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDn2qyH4AKi-yCTd2RZ:-LDo7MI9A9Yi-433MTaY:b-896fix) ([raw file](https://github.com/kubeflow/pipelines/blob/75f84b5c66dccc6c6aa60084326678beccafb2ca/resources/scheduledworkflow/util/workflow_wrap.go#L26)):*
<details><summary><i>Previously, vicaire (Pascal Vicaire) wrote…</i></summary><blockquote>

I would have to put these functions in pkg/apis to do that. But I don't want to put these functions there since the user of the API does not need them. 

I improved the implementation by using: 

type ScheduledWorkflow struct {
	*swfapi.ScheduledWorkflow
}

Which allows me to add funcs to a workflow using: 

func (s *ScheduledWorkflow) creationEpoch() int64 {
	return s.CreationTimestamp.Unix()
}



</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3)*

**Comment by jlewi** [comment]
Review status: 1 of 36 files reviewed at latest revision, all discussions resolved.

---

*[resources/scheduledworkflow/util/swf_wrap.go, line 39 at r2](https://reviewable.io/reviews/kubeflow/pipelines/3#-LDn1xJn3g29Wj-3QriA:-LDolv2_1aIydCmcEY57:b-ma6aux) ([raw file](https://github.com/kubeflow/pipelines/blob/75f84b5c66dccc6c6aa60084326678beccafb2ca/resources/scheduledworkflow/util/swf_wrap.go#L39)):*
<details><summary><i>Previously, vicaire (Pascal Vicaire) wrote…</i></summary><blockquote>

I would have to put these functions in pkg/apis to do that. But I don't want to put these functions there since the user of the API does not need them. 

I improved the implementation by using: 

type Workflow struct {
	*workflowapi.Workflow
}

Which allows me to add funcs to a workflow using: 

func (w *Workflow) OverrideName(name string) {
	w.GenerateName = ""
	w.Name = name
}


</blockquote></details>

Having two different types named ScheduledWorkflow and embedding one within the other seems like it could be confusing. 

Whatever you think best though works for me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3)*

**Pull request merged**
