### PR TITLE
Samples - Removed the immediate_value sample

### PR DESCRIPTION
**Pull request by Ark-kun**
Users can already pass constant values to components. There is no need to use PipelineParam for that.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1630)

### CODE REVIEW

**Comment by gaoning777** [comment]
please remove the sample from the e2e test  as well.

**Comment by Ark-kun** [comment]
> please remove the sample from the e2e test as well.

I think I did. Can you please point me to the place I missed?

**Comment by gaoning777** [comment]
Sorry, I missed the last two files.

**Pull request merged**
