### PR TITLE
revert the fix in proxy-agent to make sure hostname won't be changed

### PR DESCRIPTION
**Pull request by rmgogogo**
revert the fix in proxy-agent to make sure hostname won't be changed

It means the issue in https://github.com/kubeflow/pipelines/issues/3143 should be fixed in proxy-server side.

### CODE REVIEW

**Comment by rmgogogo** [comment]
background: Yash reports that he hits the issue that hostname got changed while he is still use old hostname.

**Comment by rmgogogo** [comment]
kindly ping.
Approve this one?

**Comment by rmgogogo** [comment]
@Bobgy

**Comment by Bobgy** [comment]
Sure
/lgtm
/approve

**Comment by Bobgy** [comment]
/hold
until travis tests have passed

**Comment by rmgogogo** [comment]
/approve

this PR revert the change which allows changing hostname. However it make user codes be painful.

Another fix in google3 will be provided (in proxy-server, not in Github).

**Pull request merged**
