### PR TITLE
Tests - Testing SDK with Python 3.8

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3124)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Tensorflow does not have wheels for Python3.8. TFX does not work.

**Comment by numerology** [comment]
> Tensorflow does not have wheels for Python3.8. TFX does not work.

Synced with TFX side, supporting 3.8 is on their roadmap. However currently it's blocked by lack of Py38 support for beam.

**Comment by Ark-kun** [comment]
> Tensorflow does not have wheels for Python3.8. TFX does not work.

Tensorflow now has packages for Python 3.8.

**Pull request closed without merging**
