### PR TITLE
chore(sdk): remove v1 dependencies from SDK v2

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Extracts deprecated requirements used in sample tests to prevent users from getting superfluous dependencies when they install KFP.

We should ultimately migrate the sample test suite to KFP v2, but this is a low-effort short-term alternative that benefits users immediately.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
`kubeflow-pipelines-sdk-execution-tests` failure is unrelated to these changes.

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks!

**Pull request merged**
