### PR TITLE
feat(api): add PipelineConfig to api to re-implement pipeline-level config

### PR DESCRIPTION
**Pull request by gregsheremeta**
**Description of your changes:**

KFP v1 supported setting pipeline-level configuration via a `PipelineConf` class. This class was deprecated and no replacement was added to KFP v2.

add new PipelineConfig message in the api to support setting pipeline-level configuration in KFP v2.

companion to #11112. #11333 has to be merged first.

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Review by hbelmiro — COMMENTED** [review]
/lgtm

> companion to https://github.com/kubeflow/pipelines/pull/11112

I suggest complementing this comment to tell that this PR has to be merged before https://github.com/kubeflow/pipelines/pull/11112.

**Comment by gregsheremeta** [comment]
> I suggest complementing this comment to tell that this PR has to be merged before https://github.com/kubeflow/pipelines/pull/11112.

done

**Comment by HumairAK** [comment]
fyi @chensun

**Comment by gregsheremeta** [comment]
> Note for anyone looking at this or relying on it: I'm not positive that it was ok to bump the version [here](https://github.com/kubeflow/pipelines/pull/11333/files#diff-42023372ccec7209826b2d45768cbac5c1181a3a79645c3e56b9527702b29572R3), but I'm looking into it. I see [other examples](https://github.com/kubeflow/pipelines/commit/f328f0b588c35cdf1e5b31638fbe3596b2f38413#diff-5724a6e29e4975c175523b69b5b9fed523b776efc3fd366d5d80c6c957408d03R17) where we've done a similar bump. I've added this as a topic for the [next SIG meeting](https://docs.google.com/document/d/1cHAdK1FoGEbuQ-Rl6adBDL5W2YpDiUbnMLIwmoXBoAU/edit?tab=t.0#heading=h.s8qy0rmylhrk).

Cancel the alarm. It's fine. My full write up on why:

November 5, 2024 - protoc versions - Google Docs
https://docs.google.com/document/d/19NF4NiZToLvP6Vp8fDleSsdkyK5fjv_jd8k1FCflyLQ/edit?tab=t.0

We can go over it at tomorrow's meeting.

**Pull request merged**
