### PR TITLE
chore: remove 'dummy_root' in test samples

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
Having the dummy_root in samples make them not work by default on KFP. 
We do have test coverage on pipeline_root setting in compiler UTs:
https://github.com/kubeflow/pipelines/blob/a646f3a0fd1e14de1913c66b4e972c8682ac8dde/sdk/python/kfp/compiler/compiler_test.py#L283-L290

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Linchin** [comment]
Hi @chensun, thank you for the quick fix! We may need to add a frontend change too, because it also passes `dummy_root` to the backend:
https://github.com/kubeflow/pipelines/blob/a646f3a0fd1e14de1913c66b4e972c8682ac8dde/frontend/src/pages/NewRunV2.test.tsx#L557

Another potential solution is to add `minio://` before `dummy_root`.

**Comment by chensun** [comment]
> Hi @chensun, thank you for the quick fix! We may need to add a frontend change too, because it also passes `dummy_root` to the backend:
> 
> https://github.com/kubeflow/pipelines/blob/a646f3a0fd1e14de1913c66b4e972c8682ac8dde/frontend/src/pages/NewRunV2.test.tsx#L557
> 
> Another potential solution is to add `minio://` before `dummy_root`.

That file is a unit test, it doesn't actually pass anything to the backend, otherwise it would have failed alreday.

**Comment by Linchin** [comment]
Thank you for explaining! Still, by removing `dummy_root` from test samples do we reduce test coverage on this? Maybe we can change it to `minio://dummy_root` so it's compliant with backend format requirement.

**Comment by Linchin** [comment]
Thank you @chensun!
/lgtm
/approve

**Pull request merged**
