### PR TITLE
Components - XGBoost - Added the recursive training pipeline

### PR DESCRIPTION
**Pull request by Ark-kun**
This pipeline demonstrates continuous training using a train-eval-check recursive loop.
The main pipeline trains the initial model and then gradually trains the model some more until the model evaluation metrics are good enough.

### CODE REVIEW

**Comment by Ark-kun** [comment]
@Bobgy Can you please take a look?
I've tested this sample pipeline in a notebook.

**Comment by Bobgy** [comment]
@Ark-kun Interesting example! Thanks!
/lgtm

**Comment by Ark-kun** [comment]
@jackwhelpton This pipeline might be interesting to you.

**Pull request merged**
