### PR TITLE
add metric image file for wiki

### PR DESCRIPTION
**Pull request by hongye-sun**
Added image for metrics wiki doc.

See https://github.com/kubeflow/pipelines/wiki/Log-metrics-from-your-component for the wiki.

Tracked by #296

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/316)

### CODE REVIEW

**Comment by hongye-sun** [comment]
Added more runs with metrics in the image.

**Comment by yebrahim** [comment]
/lgtm
Thanks @hongye-sun.

**Pull request merged**
