### PR TITLE
Add sample test for multiple output

### PR DESCRIPTION
**Pull request by gaoning777**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2328)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Thank you. Sorry for not doing this sooner. I was busy revamping other samples.

**Comment by Ark-kun** [comment]
I see the following error in the tests:
Is there any particular reason to require the GCS path to *end* with a letter or number?
```
run-sample-tests-loop(19:multiple_outputs):	     36     # The first and las characters must be alphanumeric.
run-sample-tests-loop(19:multiple_outputs):	     37     if not all([name[0].isalnum(), name[-1].isalnum()]):
run-sample-tests-loop(19:multiple_outputs):	---> 38         raise ValueError("Bucket names must start and end with a number or letter.")
run-sample-tests-loop(19:multiple_outputs):	     39     return name
run-sample-tests-loop(19:multiple_outputs):	     40 
run-sample-tests-loop(19:multiple_outputs):	ValueError: Bucket names must start and end with a number or letter.
```

**Comment by gaoning777** [comment]
Please review @Ark-kun

**Comment by gaoning777** [comment]
fixing https://github.com/kubeflow/pipelines/issues/1813

**Comment by Ark-kun** [comment]
/lgtm
P.S. The fix for multiline decorators is here: https://github.com/kubeflow/pipelines/pull/2345

**Comment by monicatao** [comment]
Hi How can I create multiple outputs with dsl.ContainerOp function without saving the results in file_outputs?

**Pull request merged**
