### PR TITLE
[UI] Upload pipeline version from local package

### PR DESCRIPTION
**Pull request by Bobgy**
UI of https://github.com/kubeflow/pipelines/issues/2977
demo: https://youtu.be/3dLjggHFqxg

TODO: add unit tests

/assign @jingzhang36 
/area frontend
/priority p0
/kind feature

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3059)

### CODE REVIEW

**Comment by rmgogogo** [comment]
/retest

the demo seems great. not sure whether can submit before Jing's cut.

**Comment by Bobgy** [comment]
/retest
Cloudbuild failures seem unrelated to this PR

**Pull request merged**
