### PR TITLE
[google-cloud-components] - change name to google-cloud-pipeline-components

### PR DESCRIPTION
**Pull request by SinaChavoshi**
change the name of the package from google-cloud-components to google-cloud-pipeline-components.

### CODE REVIEW

**Review by sasha-gitg — APPROVED** [review]
I think the Dockerfile also needs to be updated.

**Comment by SinaChavoshi** [comment]
> I think the Dockerfile also needs to be updated.

Good catch! updated accordingly.

**Comment by amygdala** [comment]
I think here in utils.py : https://github.com/SinaChavoshi/pipelines/blob/name_change/components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py#L563
you may need to change   '    - google_cloud_components.aiplatform.remote_runner', --> google_cloud_pipelines_components ?

**Comment by SinaChavoshi** [comment]
> I think here in utils.py : https://github.com/SinaChavoshi/pipelines/blob/name_change/components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py#L563
> you may need to change ' - google_cloud_components.aiplatform.remote_runner', --> google_cloud_pipelines_components ?

Great catch! thank you Amy.

**Review by sasha-gitg — APPROVED** [review]

**Pull request merged**
