### PR TITLE
docs(backend): Remove deprecated v2 compatibility mode docs

### PR DESCRIPTION
**Pull request by droctothorpe**
**Description of your changes:**
This PR just removes some deprecated documentation from the backend/src/v2 README file.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — APPROVED** [review]
/lgtm

**Review by hbelmiro — COMMENTED** [review]
@droctothorpe can you [sign off your commits?](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)

**Comment by droctothorpe** [comment]
> @droctothorpe can you [sign off your commits?](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)

Fixed. Sorry about that!

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Pull request merged**
