### PR TITLE
chore(sdk): Remove stack trace so it doesn't look like an error

### PR DESCRIPTION
**Pull request by randombishop**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by randombishop** [comment]
@googlebot I signed it!

**Comment by capri-xiyue** [comment]
/lgtm
@chensun  Can you help take a look at this pr?

**Comment by chensun** [comment]
@randombishop  Thanks for the PR. Can you please add an entry in the release note under "Current version > bug fixes and other changes"?
https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md

**Comment by randombishop** [comment]
@chensun Done, thanks for the review.

**Comment by chensun** [comment]
/lgtm
/approve

Thanks!

**Comment by chensun** [comment]
Fixes: https://github.com/kubeflow/pipelines/issues/6589

**Pull request merged**
