### PR TITLE
chore: Update image for metacontroller 

### PR DESCRIPTION
**Pull request by biswassri**
**Description of your changes:**

Based on [this](https://github.com/metacontroller/metacontroller/releases/tag/v4.11.21) release the docker image of the metacontroller is being deprecated and need to be updated.

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by hbelmiro** [comment]
@HumairAK it seems like the `/ok-to-test` still doesn't approve runs for first-time contributors.

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Comment by juliusvonkohout** [comment]
@HumairAK for approval

**Pull request merged**
