### PR TITLE
SDK/Compiler: Add add_pvolumes() method to ContainerOp

### PR DESCRIPTION
**Pull request by elikatsis**
Following [this discussion](https://github.com/kubeflow/pipelines/pull/749#issuecomment-493437097).

/cc @jinchihe

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1353)

### CODE REVIEW

**Comment by jinchihe** [comment]
Tested on-prem cluster with the `add_pvolumes()` method, that works fine for on-prem cases:
```
[root@jche1 ~]# argo list tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp
NAME                                                              STATUS      AGE   DURATION   PRIORITY
tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp   Succeeded   14m   7m         0
[root@jche1 ~]# argo get tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp

.....

STEP                                                                PODNAME                                                                     DURATION  MESSAGE
 ✔ tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp                                                                                        
 ├-✔ create-pvc                                                     tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp-4218758567  3s        
 ├-✔ checkout                                                       tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp-1053616485  2m        
 ├-✔ tfx-data-validation                                            tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp-3015059516  39s       
 ├-✔ transform-using-tf-on-dataflow                                 tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp-3048657474  51s       
 ├-✔ train-fc-dnn-using-tf                                          tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp-2639066820  2m        
 ├-✔ kubeflow-serve-tf-model                                        tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp-1317934331  40s       
 ├-✔ predict-using-tf-on-dataflow                                   tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp-1844614545  14s       
 ├-✔ tfx-analyze-model                                              tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp-133088148   27s       
 ├-✔ confusion-matrix                                               tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp-1162815283  5s        
 └-✔ roc-curve                                                      tfx-taxi-cab-classification-pipeline-example-for-on-prem-cdrccp-2939236461  5s        
```

**Comment by jinchihe** [comment]
Seems the method `add_pvolumes` has similar function with `onprem.mount_pvc`?

**Comment by elikatsis** [comment]
> Seems the method `add_pvolumes` has similar function with `onprem.mount_pvc`?

In the end yes, they both run `add_volume()` and `add_volume mount()`.
But `add_pvolumes()` also updates the `pvolumes` dict accordingly, making available the functionality of referencing a volume as `step.pvolumes["/common"]`.

**Comment by elikatsis** [comment]
Oh! It also handles the dependencies carried by `PipelineVolumes`, of course.

**Comment by jinchihe** [comment]
> Oh! It also handles the dependencies carried by `PipelineVolume`s, of course.

Oh, you are right. By the way, seems each following steps depend on the create_pvc component, that means there is a line to connnect from create_pvc to each following step, It looks a little messy, Is that possiable to cut down to just connect first related step? Just my personal thinking, not problems.

**Comment by elikatsis** [comment]
It does look weird, yes.
However, these dependencies exist because all of the steps use the `create_pvc`'s output parameter, and are automatically derived by the compiler's analysis.

I think it would be nice to not show redundant dependencies, but that would be misleading in a way. In such occasions the compiler finds out dependencies some of which are not very important to be shown, while others are. How would such distinction be made?

**Comment by elikatsis** [comment]
@Ark-kun friendly ping.

As you mention in the first part of your comment [here](https://github.com/kubeflow/pipelines/issues/1389#issuecomment-497099992), it seems reasonable to expose such functionality.

Could you take a look in this PR?
Thanks!

**Comment by Ark-kun** [comment]
>As you mention in the first part of your comment here, it seems reasonable to expose such functionality.

The functionality I've mentioned (`op.add_volume_mount`) already exists...

BTW, with this PR in place, do you still need the `pvolumes` parameter in the `ContainerOp` constructor?

/lgtm

@gaoning777 @hongye-sun  WDYT?

**Comment by elikatsis** [comment]
>The functionality I've mentioned (op.add_volume_mount) already exists...

I meant, according to the logic behind your comment, more of that functionalities should be available, and that is one of them.


>[...] do you still need the pvolumes parameter in the ContainerOp constructor?

Yes, I think both are good to have.

**Comment by elikatsis** [comment]
There seems to be some problems with the integration tests.
E.g., now the `build-frontend-integration-tests-image` test failed, but I think some other time it was the `run-frontend-integration-tests` that had failed.

Is it an infra issue?

**Pull request merged**
