### PR TITLE
Rewrite ResNet sample by GCP components

### PR DESCRIPTION
**Pull request by hongye-sun**
The PR includes:

* Rewrite samples/resnet-cmle by using GCP components from components/gcp folder.
* Moved components/resnet-cmle/resnet/resnet_model/trainer/preprocess.py to samples/resnet-cmle/preprocess/preprocess.py.
* Moved components/resnet-cmle/resnet/resnet_model/trainer to samples/resnet-cmle/trainer
* Remove wrapper classes under components/resnet-cmle/resnet
* Remove container files under components/resnet-cmle/containers

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1018)

### CODE REVIEW

**Comment by Ark-kun** [comment]
> The PR also removes old ResNet container code.

Do you think they might be still be useful for the CMLE container training?

**Comment by hongye-sun** [comment]
Alexey, I am not sure where it is going to be used, do you know any user is using that?

**Comment by Ark-kun** [comment]
> Alexey, I am not sure where it is going to be used, do you know any user is using that?

Probably no one is using them. I thought they might be useful to demonstrate using the same container to train on both CMLE and TFJob.

/lgtm

**Comment by Ark-kun** [comment]
Can you please add a bit more information here about what code is just moved, what code is remove and what code is added.

I see that some component code is just moved, but I'm not completely sure about some other code files.

Thanks.
/lgtm

**Comment by hongye-sun** [comment]
Done and need another LGTM. Thanks.

**Comment by Ark-kun** [comment]
CloudBuild is failing:

```
Starting Step #26 - "buildResnetCMLEDeployComponent"
Step #26 - "buildResnetCMLEDeployComponent": Already have image (with digest): gcr.io/cloud-builders/docker
Step #26 - "buildResnetCMLEDeployComponent": /bin/bash: line 0: cd: /workspace/components/resnet-cmle/containers/deploy: No such file or directory
```

When deleting files we should make sure they're not mentioned anywhere:
https://github.com/kubeflow/pipelines/search?q=%22components%2Fresnet-cmle%22&unscoped_q=%22components%2Fresnet-cmle%22

**Pull request merged**
