### PR TITLE
docs: Update AWS sample installation instructions

### PR DESCRIPTION
**Pull request by aleb**
Cosmetic + details how to get the RDS host

### CODE REVIEW

**Comment by Bobgy** [comment]
/assign @PatrickXYS 
Can you take a look or do you recommend someone else?

**Comment by Bobgy** [comment]
/lgtm
this looks good to me just for readability point of view

**Comment by aleb** [comment]
ping

**Comment by Bobgy** [comment]
@kubeflow/aws can someone do the approve?

**Comment by surajkota** [comment]
approved from AWS side but I am not part of OWNERS file

too many places with OWNERS file, its hard to keep track

**Comment by rimolive** [comment]
Closing this PR. No activity for more than a year.

/close

**Pull request closed without merging**
