### PR TITLE
Updated the "Basic - Exit handler" sample

### PR DESCRIPTION
**Pull request by Ark-kun**
Modernized the sample pipeline code.
/assign @gaoning777 @hongye-sun
/label area/components

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1109)

### CODE REVIEW

**Comment by gaoning777** [comment]
Thanks for updating these basic samples.
If I may, can I request you to combine the PRs that update the samples into one PR, please?
Thanks

**Comment by Ark-kun** [comment]
The sample tests have passed. https://prow.k8s.io/pr-history/?org=kubeflow&repo=pipelines&pr=1109

**Comment by Ark-kun** [comment]
> Thanks for updating these basic samples.
> If I may, can I request you to combine the PRs that update the samples into one PR, please?
> Thanks

I got feedback that I should make try and make my PRs smaller and more independent/granular.
This way it's easier to review each PR and also an issue in one PR is not blocking other PRs.

I accept your new feedback and will try updating the samples all at once in future.

For these samples it would be best not to spend additional time on recombining the PRs.

**Comment by gaoning777** [comment]
Discussed offline. 
For bigger changes that apply the same logic change to many files, it might be better to put in one single PR to reduce the CR time. 
For even small changes that apply multiple logic changes to a few files. it might be better to divide into multiple PRs.

The rule of thumb, IMHO, is to help with CR and bug detection.

**Pull request merged**
