### PR TITLE
doc(sdk/client): fix kfp-server-api py client's docstring format

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Fix https://github.com/kubeflow/pipelines/issues/3216

Cherry picked template docstring fix in https://github.com/OpenAPITools/openapi-generator/pull/6391 into KFP api client's template, so that generated doc can parse these formats semantically.
The diff https://github.com/kubeflow/pipelines/pull/4047/commits/c86c59a9a40e826be5c23378fcccbcc6989fa111 should be exactly the same as the PR in openapi generator repo.

/assign @Ark-kun 

**Checklist:**
- [x] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Ark-kun** [comment]
/lgtm
Thank you Yuan for backporting this fix.

**Comment by Bobgy** [comment]
Strange, looks like prow is not healthy

**Comment by Ark-kun** [comment]
Can you please update the package based on this change?

**Comment by Bobgy** [comment]
@Ark-kun will do in next rc

**Pull request merged**
