### PR TITLE
[AWS SageMaker] GroundTruth Pre/Post Lambda function region additions

### LINKED ISSUE #3916: [AWS SageMaker] Region availability of pre and post task lambdas for GroundTruth
Hi,

Is there a reason that only a subset of regions are used in `algorithm_arn_map` in https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/common/_utils.py to access the AWS Pre human and Post human lambda functions? In the SageMaker API docs there are more available: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_labeling_job.

I think it would be helpful to limit the use of these components as little as possible.

### PR DESCRIPTION
**Pull request by MattRose153**
Added more region lambda ARNs to the algorithm map as per the SageMaker documentation: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_labeling_job

Closes #3916

### CODE REVIEW

**Comment by surajkota** [comment]
Thank you for your contribution. Our on-call will take a look and respond.

account to region mapping update looks good to me

**Comment by surajkota** [comment]
Hi @MattRose153, thank you for your patience. Here are the next steps to merge this change

We would need to release a new docker image for this change and #3933(verified the change). The docker image version will also need to be bumped. So I request you to do the following so we can do a single release:
1. Please update this PR to include the changes in #3933 
2. Cherry-pick my commit where I have other release related changes to this PR - https://github.com/surajkota/pipelines/commit/0d0f593b7ee15bc26b970dc9fd7cc24deb50d304

Let me know if you need help with any of the above

**Comment by MattRose153** [comment]
Hey @surajkota, I think I've made changes as requested, let me know if anything else is required (and if you would like me to close #3933 since it's being incorporated into this PR).

**Comment by surajkota** [comment]
/approve
Thanks, feel free to close #3933

**Comment by surajkota** [comment]
@googlebot I consent

**Comment by surajkota** [comment]
@MattRose153 Just realized while working out the release process that a [new sagemaker component](https://github.com/kubeflow/pipelines/tree/master/components/aws/sagemaker/process) for processing was added in 0.4.0 release and the docker image tag update to 0.5.1 needs to go in [here](https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/process/component.yaml#L92) as well. Since `MattRose153:groundtruth_lambda_regions` branch is on top of 0.3.0 it does not have the new component. Here are the next steps:

1. Rebase with master
2. Update [this line](https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/process/component.yaml#L92) to `amazon/aws-sagemaker-kfp-components:0.5.1`

and update the PR. Let me know if you need any information

Thanks

**Comment by MattRose153** [comment]
@surajkota Unsure if I've done this correctly (were those extra commits from other authors supposed to come across as well?) so please let me know if theres anything that requires fixing/cleaning up

**Comment by surajkota** [comment]
Diff should consist of your commits and one commit from me, so needs to be fixed

Not sure how other changes are showing up

**Comment by MattRose153** [comment]
OK looks like it's fixed now @surajkota

**Pull request merged**
