### PR TITLE
Deduce proxy type from the presence of client_id

### LINKED ISSUE #2244: IAP host shouldn't be restricted to a cloud endpoint url
In https://github.com/kubeflow/pipelines/commit/8d5ec83f5e26312ee6cecabe647e79f3c7bf1e9b#diff-1f65a44a2187458da0f00e0ebbe730e5R142-R145, the logic for `self._is_iap_host` uses a regex to ensure that the host name is of the form `https://<deployment>.endpoints.<project>.cloud.goog/pipeline`. This breaks for us, because we use a different hostname, and thus when trying to connect via IAP an auth token is not generated.

We are able to workaround this by overriding the client and `def _is_iap_host(self, host, client_id)`, but just wanted to raise this issue here.

### PR DESCRIPTION
**Pull request by chensun**
* Use the presence of client_id to deduce whether it's Identity-Aware Proxy or Inverse Proxy.
* Remove the logic of detecting proxy type based on the endpoint URL.

 Fixes #2244 @daikeshi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3003)

### CODE REVIEW

**Comment by numerology** [comment]
/lgtm
Do you mind approving? @Ark-kun

**Comment by numerology** [comment]
run-sample-tests-loop(7:execution_order)[0m:	subprocess.CalledProcessError: Command '['gcloud', 'auth', 'print-access-token']' returned non-zero exit status 1

Does not seem to be a flakiness :(

**Comment by chensun** [comment]
> run-sample-tests-loop(7:execution_order)�[0m: subprocess.CalledProcessError: Command '['gcloud', 'auth', 'print-access-token']' returned non-zero exit status 1
> 
> Does not seem to be a flakiness :(

Found why it's failing. The format of this [endpoint string](https://github.com/kubeflow/pipelines/blob/13682eec3158099da1e6b82086a9d111f6bb2bd6/test/sample-test/run_sample_test.py#L61) previously wouldn't go into the `get_gcp_access_token` path.

I'm going to make `get_gcp_access_token` handle error gracefully.

**Comment by chensun** [comment]
@numerology can you please take a second look?

**Comment by numerology** [comment]
/lgtm
/approve

Thanks @chensun

**Pull request merged**
