### PR TITLE
Components - XGBoost

### PR DESCRIPTION
**Pull request by Ark-kun**
* Train
* Predict
* Sample pipeline

### CODE REVIEW

**Comment by Bobgy** [comment]
@Ark-kun Sorry my question may seem stupid. What's the difference between this and dataproc xgboost?

**Comment by Ark-kun** [comment]
> @Ark-kun Sorry my question may seem stupid. What's the difference between this and dataproc xgboost?

The main difference is that these components do not require Dataproc. You can run them in any local or on-prem Kubernetes cluster.

They also use the latest XGBoost version with best practices and are easier to maintain.

I'm building a sample pipeline demonstrating multi-framework model training (XGBoost, CatBoost, LightGBM, SciKitLearn).

**Comment by eterna2** [comment]
OT comments. 

I was trying to build some components myself. I noticed that `OutputPath` etc are type annotations instead of values?

Any particular reasons for that? Because an issue I encountered is that mypy will flag that as an error as `OutputPath(str)` is not a type (it is an instance).

Just wondering if it is better if we set that as default value instead?

```py
def op(some_path: OutputPath = OutputPath(str)):
  ...
```

**Comment by Bobgy** [comment]
Thanks!
/lgtm

**Comment by Ark-kun** [comment]
> I noticed that `OutputPath` etc are type annotations instead of values?
> Any particular reasons for that?

The "values" are reserved for default values in python function signatures.
I thing the `OutputPath` might be obscuring an actual issue. Let's see how it looks without that:

```python
def op(number: int = 42): ...
def op(number: 'Integer' = 42): ...
def op(number_path: InputPath('Integer') = None): ...
```

>mypy will flag that as an error as OutputPath(str) is not a type (it is an instance).

We could make `OutputPath` a metaclass (which it is in a sense, since it's essentially is a generic type `OutputPath[int]`).
But mypy will probably still complain about `text: 'CSV'`, right?
We could change the syntax to `text: TypeSpec('CSV')`, but this looks cumbersome.

What do you think?

**Comment by eterna2** [comment]
> > I noticed that `OutputPath` etc are type annotations instead of values?
> > Any particular reasons for that?
> 
> The "values" are reserved for default values in python function signatures.

I haven't looked at the current implementation in detail, but I thought this shouldn't affect anything? 

As in during execution in the pipeline, a value will always passed into the func? 

And in dev env, the lint and typecheck should all still work as long as we describe the interface properly? (e.g. `OutputPath` inherits from `str`, `OutputTextfile` has a `write` method, etc)?


> I thing the `OutputPath` might be obscuring an actual issue. Let's see how it looks without that:
> 
> ```python
> def op(number: int = 42): ...
> def op(number: 'Integer' = 42): ...
> def op(number_path: InputPath('Integer') = None): ...
> ```
> 
> > mypy will flag that as an error as OutputPath(str) is not a type (it is an instance).
> 
> We could make `OutputPath` a metaclass (which it is in a sense, since it's essentially is a generic type `OutputPath[int]`).
> But mypy will probably still complain about `text: 'CSV'`, right?
> We could change the syntax to `text: TypeSpec('CSV')`, but this looks cumbersome.
> 
> What do you think?

I did think of this also. But yeah, the tricky part is the metadata. 

I am thinking whether we can implement a type similar to `typing_extension.Literal`, where it can take any str.

https://github.com/python/typing/blob/08a537d484edddb563288982f8073d241fec5535/typing_extensions/src_py3/typing_extensions.py#L617

So we can just
```py
def op(csv_file: InputTextFile["csv"]):
  ...
```

what do u think?

**Comment by Ark-kun** [comment]
> I haven't looked at the current implementation in detail, but I thought this shouldn't affect anything?

If we replace `param1: 'Integer'` with `param1 = 'Integer'` then how does the component author express what's currently expressed using `param1: 'Integer' = 42`? The component author needs to be able to tell `create_component_from_func` about the default values and we do that using idiomatic python.

>As in during execution in the pipeline, a value will always passed into the func?

No. Parameters with default values become optional inputs and when nothing is passed to them, nothing gets passed in the command-line. It was pretty hard to implement that, but that was the only real way to make it possible to make the functions receive complicated values like `param1 = None` or `param1 = some_func_get_default('foo')`. It's important to be able to not pass anything for an optional input/parameter.

Does mypy fail for `def op(number: 'Integer' = 42):` ? I think I can fix `InputPath`, but I'm not sure about plain type names.

**Pull request merged**
