### PR TITLE
Remove UI metadata parameter from Bigquery Query component

### PR DESCRIPTION
**Pull request by kmrshntr**
I tried this sample.

https://github.com/kubeflow/pipelines/blob/master/components/gcp/bigquery/query/sample.ipynb

But `wait` container failed with the error log:

```
time="2020-01-27T09:31:01Z" level=error msg="`[sh -c docker cp -a 932c01e5f0fe1f09182a6cf05a09db31d76ff5086afb9cc4e34fe6b207818502:/outputs/MLPipeline_UI_metadata/data - | tar -ax -O]` stderr:\nError: No such container:path: 932c01e5f0fe1f09182a6cf05a09db31d76ff5086afb9cc4e34fe6b207818502:/outputs/MLPipeline_UI_metadata/data\ntar: This does not look like a tar archive\ntar: Exiting with failure status due to previous errors\n"
""
```

This component doesn't make any ui-metadata, right?
So I removed information related to UI metadata from component.yaml.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2917)

### CODE REVIEW

**Comment by Ark-kun** [comment]
@kmrshntr Are you sure? Usually, those GCP components output the job link there. It's hidden in the `components/gcp/container/component_sdk/...` library.

**Comment by Ark-kun** [comment]
Also, the Backend marks all UI Metadata outputs as optional, so they should not fail the run even if they're missing.

DO you have success running other components that do produce the UI metadata?

**Comment by kmrshntr** [comment]
@gaoning777 Thank you for feedback. I just realized that this component generates the UI metadata as you said. The artifacts tab shows query details link if it succeeded.

succeeded

But the component in master version fails and doesn't show any artifacts.

failed

**Comment by kmrshntr** [comment]
The logs of the component in my branch:

```
kubectl logs bigquery-query-pipeline-7zbb5-1367324499 -c wait
time="2020-01-27T11:11:20Z" level=info msg="Creating a docker executor"
time="2020-01-27T11:11:20Z" level=info msg="Executor (version: v2.3.0, build_date: 2019-05-20T22:10:54Z) initialized (pod: kubeflow/bigquery-query-pipeline-7zbb5-1367324499) with template:\n{\"name\":\"bigquery-query\",\"inputs\":{\"parameters\":[{\"name\":\"dataset-id\",\"value\":\"\"},{\"name\":\"dataset-location\",\"value\":\"US\"},{\"name\":\"job-config\",\"value\":\"\"},{\"name\":\"output-gcs-path\",\"value\":\"gs://buyma-analytics-kimura//bigquery/query/questions.csv\"},{\"name\":\"project-id\",\"value\":\"buyma-analytics\"},{\"name\":\"query\",\"value\":\"SELECT * FROM `bigquery-public-data.stackoverflow.posts_questions` LIMIT 10\"},{\"name\":\"table-id\",\"value\":\"\"}]},\"outputs\":{\"parameters\":[{\"name\":\"bigquery-query-output-gcs-path\",\"valueFrom\":{\"path\":\"/tmp/kfp/output/bigquery/query-output-path.txt\"}}],\"artifacts\":[{\"name\":\"mlpipeline-ui-metadata\",\"path\":\"/mlpipeline-ui-metadata.json\",\"s3\":{\"endpoint\":\"minio-service.kubeflow:9000\",\"bucket\":\"mlpipeline\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"accesskey\"},\"secretKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"secretkey\"},\"key\":\"runs/93d9e9da-30d9-4b7f-bd19-c4708915feae/bigquery-query-pipeline-7zbb5-1367324499/mlpipeline-ui-metadata.tgz\"},\"optional\":true},{\"name\":\"mlpipeline-metrics\",\"path\":\"/mlpipeline-metrics.json\",\"s3\":{\"endpoint\":\"minio-service.kubeflow:9000\",\"bucket\":\"mlpipeline\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"accesskey\"},\"secretKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"secretkey\"},\"key\":\"runs/93d9e9da-30d9-4b7f-bd19-c4708915feae/bigquery-query-pipeline-7zbb5-1367324499/mlpipeline-metrics.tgz\"},\"optional\":true}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"gcr.io/ml-pipeline/ml-pipeline-gcp:bae654dc5cf407359ac5f822d03833768739c4c1\",\"args\":[\"kfp_component.google.bigquery\",\"query\",\"--query\",\"SELECT * FROM `bigquery-public-data.stackoverflow.posts_questions` LIMIT 10\",\"--project_id\",\"buyma-analytics\",\"--dataset_id\",\"\",\"--table_id\",\"\",\"--dataset_location\",\"US\",\"--output_gcs_path\",\"gs://buyma-analytics-kimura//bigquery/query/questions.csv\",\"--job_config\",\"\"],\"env\":[{\"name\":\"KFP_POD_NAME\",\"value\":\"bigquery-query-pipeline-7zbb5-1367324499\"}],\"resources\":{}}}"
time="2020-01-27T11:11:20Z" level=info msg="Waiting on main container"
time="2020-01-27T11:11:21Z" level=info msg="main container started with container ID: c0425d4ecb396c9a0b8d8a2a966ee7e21d968a7949bdb341e8c4745e3b380954"
time="2020-01-27T11:11:21Z" level=info msg="Starting annotations monitor"
time="2020-01-27T11:11:21Z" level=info msg="Starting deadline monitor"
time="2020-01-27T11:11:21Z" level=info msg="docker wait c0425d4ecb396c9a0b8d8a2a966ee7e21d968a7949bdb341e8c4745e3b380954"
time="2020-01-27T11:11:35Z" level=info msg="Main container completed"
time="2020-01-27T11:11:35Z" level=info msg="No sidecars"
time="2020-01-27T11:11:35Z" level=info msg="Saving output parameters"
time="2020-01-27T11:11:35Z" level=info msg="Saving path output parameter: bigquery-query-output-gcs-path"
time="2020-01-27T11:11:35Z" level=info msg="Copying /tmp/kfp/output/bigquery/query-output-path.txt from base image layer"
time="2020-01-27T11:11:35Z" level=info msg="[sh -c docker cp -a c0425d4ecb396c9a0b8d8a2a966ee7e21d968a7949bdb341e8c4745e3b380954:/tmp/kfp/output/bigquery/query-output-path.txt - | tar -ax -O]"
time="2020-01-27T11:11:35Z" level=info msg="Annotations monitor stopped"
time="2020-01-27T11:11:36Z" level=info msg="Successfully saved output parameter: bigquery-query-output-gcs-path"
time="2020-01-27T11:11:36Z" level=info msg="Saving output artifacts"
time="2020-01-27T11:11:36Z" level=info msg="Staging artifact: mlpipeline-ui-metadata"
time="2020-01-27T11:11:36Z" level=info msg="Copying /mlpipeline-ui-metadata.json from container base image layer to /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz"
time="2020-01-27T11:11:36Z" level=info msg="Archiving c0425d4ecb396c9a0b8d8a2a966ee7e21d968a7949bdb341e8c4745e3b380954:/mlpipeline-ui-metadata.json to /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz"
time="2020-01-27T11:11:36Z" level=info msg="sh -c docker cp -a c0425d4ecb396c9a0b8d8a2a966ee7e21d968a7949bdb341e8c4745e3b380954:/mlpipeline-ui-metadata.json - | gzip > /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz"
time="2020-01-27T11:11:36Z" level=info msg="Archiving completed"
time="2020-01-27T11:11:36Z" level=info msg="S3 Save path: /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz, key: runs/93d9e9da-30d9-4b7f-bd19-c4708915feae/bigquery-query-pipeline-7zbb5-1367324499/mlpipeline-ui-metadata.tgz"
time="2020-01-27T11:11:36Z" level=info msg="Creating minio client minio-service.kubeflow:9000 using static credentials"
time="2020-01-27T11:11:36Z" level=info msg="Saving from /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz to s3 (endpoint: minio-service.kubeflow:9000, bucket: mlpipeline, key: runs/93d9e9da-30d9-4b7f-bd19-c4708915feae/bigquery-query-pipeline-7zbb5-1367324499/mlpipeline-ui-metadata.tgz)"
time="2020-01-27T11:11:36Z" level=info msg="Successfully saved file: /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz"
time="2020-01-27T11:11:36Z" level=info msg="Staging artifact: mlpipeline-metrics"
time="2020-01-27T11:11:36Z" level=info msg="Copying /mlpipeline-metrics.json from container base image layer to /argo/outputs/artifacts/mlpipeline-metrics.tgz"
time="2020-01-27T11:11:36Z" level=info msg="Archiving c0425d4ecb396c9a0b8d8a2a966ee7e21d968a7949bdb341e8c4745e3b380954:/mlpipeline-metrics.json to /argo/outputs/artifacts/mlpipeline-metrics.tgz"
time="2020-01-27T11:11:36Z" level=info msg="sh -c docker cp -a c0425d4ecb396c9a0b8d8a2a966ee7e21d968a7949bdb341e8c4745e3b380954:/mlpipeline-metrics.json - | gzip > /argo/outputs/artifacts/mlpipeline-metrics.tgz"
time="2020-01-27T11:11:36Z" level=warning msg="path /mlpipeline-metrics.json does not exist (or /mlpipeline-metrics.json is empty) in archive /argo/outputs/artifacts/mlpipeline-metrics.tgz"
time="2020-01-27T11:11:36Z" level=warning msg="Ignoring optional artifact 'mlpipeline-metrics' which does not exist in path '/mlpipeline-metrics.json': path /mlpipeline-metrics.json does not exist (or /mlpipeline-metrics.json is empty) in archive /argo/outputs/artifacts/mlpipeline-metrics.tgz"
time="2020-01-27T11:11:36Z" level=info msg="Annotating pod with output"
time="2020-01-27T11:11:36Z" level=info msg="Deadline monitor stopped"
time="2020-01-27T11:11:36Z" level=info msg="Alloc=4965 TotalAlloc=12790 Sys=70590 NumGC=5 Goroutines=10"
(base)
```

the logs of the component in `master` branch: 
```
$ kubectl logs bigquery-query-pipeline-58lsl-3475694387 -c wait
time="2020-01-27T09:30:45Z" level=info msg="Creating a docker executor"
time="2020-01-27T09:30:45Z" level=info msg="Executor (version: v2.3.0, build_date: 2019-05-20T22:10:54Z) initialized (pod: kubeflow/bigquery-query-pipeline-58lsl-3475694387) with template:\n{\"name\":\"bigquery-query\",\"inputs\":{\"parameters\":[{\"name\":\"dataset-id\",\"value\":\"\"},{\"name\":\"dataset-location\",\"value\":\"US\"},{\"name\":\"job-config\",\"value\":\"\"},{\"name\":\"output-gcs-path\",\"value\":\"gs://buyma-analytics-kimura//bigquery/query/questions.csv\"},{\"name\":\"project-id\",\"value\":\"buyma-analytics\"},{\"name\":\"query\",\"value\":\"SELECT * FROM `bigquery-public-data.stackoverflow.posts_questions` LIMIT 10\"},{\"name\":\"table-id\",\"value\":\"\"}]},\"outputs\":{\"parameters\":[{\"name\":\"bigquery-query-mlpipeline-ui-metadata\",\"valueFrom\":{\"path\":\"/outputs/MLPipeline_UI_metadata/data\"}},{\"name\":\"bigquery-query-output-gcs-path\",\"valueFrom\":{\"path\":\"/tmp/kfp/output/bigquery/query-output-path.txt\"}}],\"artifacts\":[{\"name\":\"mlpipeline-ui-metadata\",\"path\":\"/mlpipeline-ui-metadata.json\",\"s3\":{\"endpoint\":\"minio-service.kubeflow:9000\",\"bucket\":\"mlpipeline\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"accesskey\"},\"secretKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"secretkey\"},\"key\":\"runs/ab5cf2f8-2782-48d5-9fd3-124f076e9777/bigquery-query-pipeline-58lsl-3475694387/mlpipeline-ui-metadata.tgz\"},\"optional\":true},{\"name\":\"mlpipeline-metrics\",\"path\":\"/mlpipeline-metrics.json\",\"s3\":{\"endpoint\":\"minio-service.kubeflow:9000\",\"bucket\":\"mlpipeline\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"accesskey\"},\"secretKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"secretkey\"},\"key\":\"runs/ab5cf2f8-2782-48d5-9fd3-124f076e9777/bigquery-query-pipeline-58lsl-3475694387/mlpipeline-metrics.tgz\"},\"optional\":true}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"gcr.io/ml-pipeline/ml-pipeline-gcp:bae654dc5cf407359ac5f822d03833768739c4c1\",\"args\":[\"--ui_metadata_path\",\"/outputs/MLPipeline_UI_metadata/data\",\"kfp_component.google.bigquery\",\"query\",\"--query\",\"SELECT * FROM `bigquery-public-data.stackoverflow.posts_questions` LIMIT 10\",\"--project_id\",\"buyma-analytics\",\"--dataset_id\",\"\",\"--table_id\",\"\",\"--dataset_location\",\"US\",\"--output_gcs_path\",\"gs://buyma-analytics-kimura//bigquery/query/questions.csv\",\"--job_config\",\"\"],\"env\":[{\"name\":\"KFP_POD_NAME\",\"value\":\"bigquery-query-pipeline-58lsl-3475694387\"}],\"resources\":{}}}"
time="2020-01-27T09:30:45Z" level=info msg="Waiting on main container"
time="2020-01-27T09:30:46Z" level=info msg="main container started with container ID: 932c01e5f0fe1f09182a6cf05a09db31d76ff5086afb9cc4e34fe6b207818502"
time="2020-01-27T09:30:46Z" level=info msg="Starting annotations monitor"
time="2020-01-27T09:30:46Z" level=info msg="Starting deadline monitor"
time="2020-01-27T09:30:46Z" level=info msg="docker wait 932c01e5f0fe1f09182a6cf05a09db31d76ff5086afb9cc4e34fe6b207818502"
time="2020-01-27T09:31:00Z" level=info msg="Main container completed"
time="2020-01-27T09:31:00Z" level=info msg="No sidecars"
time="2020-01-27T09:31:00Z" level=info msg="Saving output parameters"
time="2020-01-27T09:31:00Z" level=info msg="Saving path output parameter: bigquery-query-mlpipeline-ui-metadata"
time="2020-01-27T09:31:00Z" level=info msg="Copying /outputs/MLPipeline_UI_metadata/data from base image layer"
time="2020-01-27T09:31:00Z" level=info msg="[sh -c docker cp -a 932c01e5f0fe1f09182a6cf05a09db31d76ff5086afb9cc4e34fe6b207818502:/outputs/MLPipeline_UI_metadata/data - | tar -ax -O]"
time="2020-01-27T09:31:00Z" level=info msg="Annotations monitor stopped"
time="2020-01-27T09:31:01Z" level=error msg="`[sh -c docker cp -a 932c01e5f0fe1f09182a6cf05a09db31d76ff5086afb9cc4e34fe6b207818502:/outputs/MLPipeline_UI_metadata/data - | tar -ax -O]` stderr:\nError: No such container:path: 932c01e5f0fe1f09182a6cf05a09db31d76ff5086afb9cc4e34fe6b207818502:/outputs/MLPipeline_UI_metadata/data\ntar: This does not look like a tar archive\ntar: Exiting with failure status due to previous errors\n"
time="2020-01-27T09:31:01Z" level=error msg="executor error: exit status 2\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).GetFileContents\n\t/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:42\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveParameters\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:412\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:48\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
time="2020-01-27T09:31:01Z" level=info msg="Alloc=3723 TotalAlloc=11165 Sys=70334 NumGC=4 Goroutines=8"
time="2020-01-27T09:31:01Z" level=fatal msg="exit status 2\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).GetFileContents\n\t/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:42\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveParameters\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:412\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:48\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
```

**Comment by Ark-kun** [comment]
There was a change couple of weeks ago that made the ui metadata output paths configurable from outside of the program.
Maybe the new `component.yaml` is using an image with old version of the GCP component sdk library?

**Pull request closed without merging**
