### PR TITLE
update version for 0.5.1

### PR DESCRIPTION
**Pull request by rmgogogo**
update version for 0.5.1

### CODE REVIEW

**Comment by rmgogogo** [comment]
visualization server's BUILD is flaky

**Comment by Ark-kun** [comment]
> /test kubeflow-pipeline-mkp-test

I've discovered a bug. Fixed by #3700 I've checked the e2e test cluster's logs and it seems to fix the cache-deployer issue.

**Comment by Ark-kun** [comment]
> /test kubeflow-pipeline-mkp-test

Are you sure it's OK to run two of these at the same time? They use the same cluster...

**Comment by Ark-kun** [comment]
The marketplace test should be passing now, but see https://github.com/kubeflow/pipelines/issues/3701

**Comment by rmgogogo** [comment]
> The marketplace test should be passing after #3702 is merged, but see #3701
> 
> Is that a problem with the test or is it going to be a problem for a real installation?

auto-test is OK as auto-test will delete the temp namespace. So all will be clean up.
In real installation, the progream-created cert/hook won't be GCed when delete/uninstall the application. Another possible issue is the cert expiration time.

I'm cutting 0.5.1 to test env first.

**Pull request merged**
