### PR TITLE
gpu example: wording cleanup

### PR DESCRIPTION
**Pull request by amygdala**

### CODE REVIEW

**Comment by amygdala** [comment]
Renmin, I made a few wording changes to the GPU example just to smooth it a bbit... feel free to reject any of it :)
cc @rmgogogo

**Comment by rmgogogo** [comment]
thanks.
/lgtm
/approve

**Comment by rmgogogo** [comment]
thanks.
/lgtm
/approve

**Comment by rmgogogo** [comment]
sorry mis-clicked "close & comment". reopened it.

**Pull request merged**
