### PR TITLE
[SDK/client] Fixes authentication refreshing mechanism

### LINKED ISSUE #3630: [SDK] kfp.Client().wait_for_run_completion() cannot handle long execution
### What steps did you take:
If one tries to kick off kick off a pipeline using `kfp.Client()` and wait for its completion, the waiting process will error out in ~1 hour with the following error msg.

```
AttributeError                            
Traceback (most recent call last)
<ipython-input-8-8ebf2be6196c> in <module>
      1 client = kfp.Client(host='2c688415e5fe965e-dot-us-central2.pipelines.googleusercontent.com')
----> 2 client.wait_for_run_completion(run_id=run_result.run_id, timeout=36000)

~/Library/Python/3.7/lib/python/site-packages/kfp/_client.py in wait_for_run_completion(self, run_id, timeout)
    597     while status is None or status.lower() not in ['succeeded', 'failed', 'skipped', 'error']:
    598       get_run_response = self._run_api.get_run(run_id=run_id)
--> 599       status = get_run_response.run.status
    600       elapsed_time = (datetime.now() - start_time).seconds
    601       logging.info('Waiting for the job to complete...')

AttributeError: 'NoneType' object has no attribute 'status'
```

Note that the 1 hour limitation seems very deterministic. My initial investigation pointed to the `gcloud auth print-access-token` we use [here](https://github.com/kubeflow/pipelines/blob/de0747ec8b9a4d4a412457004b3bbac2cea2e6a4/sdk/python/kfp/_auth.py#L40) Note that by default GCP access token has an expiration time of 1 hour, which will cause authorization issue during the long waiting.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Hosted CAIP pipeline in GKE MKP.

KFP version: 
0.5.0

KFP SDK version: 
0.5.0

Though I believe other version might have the same issue.

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/priority p1
/area sdk
/area backend

### PR DESCRIPTION
**Pull request by numerology**
Fixes #3630 

Synced with @chensun , we only need this refresh for inverse proxy style authentication because `gcloud auth print-access-token` has a 1 hour TTL while in `_get_auth_token()` we're using refresh token, which does not have such limit.

### CODE REVIEW

**Comment by Ark-kun** [comment]
Thank you for fixing the issue.
/lgtm
BTW, can this also fix https://github.com/kubeflow/pipelines/issues/2625 ?

**Comment by numerology** [comment]
> Thank you for fixing the issue.
> /lgtm
> BTW, can the same approach also be used to fix #2625 ?

Thanks! Actually I think #2625 is fixed by https://github.com/kubeflow/pipelines/pull/2626 IIUC, where refresh token is introduced.

I am under the impression that refresh token should not have 1 hour TTL. @chensun can correct me if I am wrong.

However if a user provide an existing token to the client I think they'll need to take care of the refreshing themselves.

**Comment by numerology** [comment]
Did some manual validation at https://2ce65529ad19b245-dot-us-central2.pipelines.googleusercontent.com/#/runs/details/56535ae7-561d-4fee-8149-4f3267340d57

Seems working

**Pull request merged**
