### PR TITLE
feat(sdk): add aws region field in use_aws_secret in kfp sdk

### PR DESCRIPTION
**Pull request by Jeffwan**
**Description of your changes:**
`use_aws_secret` didn't consider `AWS_REGION`, depends on the AWS SDK version and services to requests, some of the applications needs `AWS_REGION` to finish request. One example is Tensorflow. 

This PR adds an extra optional field `aws_region` in  `use_aws_secret` util for user who need it. 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [x] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Jeffwan** [comment]
```
+ python3 -m pip install . --upgrade
Processing /home/prow/go/src/github.com/kubeflow/pipelines/tfx
    ERROR: Command errored out with exit status 255:
     command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-vg98fja9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-vg98fja9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lbr5xhyc
         cwd: /tmp/pip-req-build-vg98fja9/
    Complete output (2 lines):
    Generating tfx/proto/example_gen_pb2.py...
    protoc is not installed nor found in ../src.  Please compile it or install the binary package.
```

It fails during installation. Seems some dependency issue. I doubt that's related

/test kubeflow-pipelines-tfx-python36

**Comment by Ark-kun** [comment]
> It fails during installation. Seems some dependency issue. I doubt that's related

Yes. This looks unrelated.

**Pull request merged**
