### PR TITLE
chore: change sample PVC access modes to ReadWriteOnce

### PR DESCRIPTION
**Pull request by Linchin**
**Description of your changes:**
Changes PVC access mode from `ReadWriteMany` to `ReadWriteOnce` in Kubernetes platform samples. Doing this due to Google Compute Engine does not support `ReadWriteMany`([ref](https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#access_modes)).

Added PR Label: [area/kubernetes_platform](https://github.com/kubeflow/pipelines/labels/area%2Fkubernetes_platform)

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by connor-mccarthy — APPROVED** [review]
/lgtm
/approve

**Comment by chensun** [comment]
@Linchin looks like there're still some test samples use `ReadWriteMany`, e.g.:
https://github.com/kubeflow/pipelines/blob/96742a648a270a776f6bc44bdb0801acbb9c5fc1/backend/src/apiserver/server/test/pipeline_with_volume.yaml#L166

Can you update all the related sample?

**Comment by Linchin** [comment]
@chensun Thank you for finding this. Updated.

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks!

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks!

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks!

**Pull request merged**
