### PR TITLE
Step 7 auto-generated change log for release 0.1.21

### PR DESCRIPTION
**Pull request by jingzhang36**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1527)

### CODE REVIEW

**Comment by IronPan** [comment]
could you just keep the note for this release and revert changes for the past ones.

**Comment by jingzhang36** [comment]
> could you just keep the note for this release and revert changes for the past ones.

You mean manually curate this PR? I thought this automatically generated changes are not meant to be curated manually. Is it because my local repo is somehow messed up so that some unrelated changes got in?

**Pull request merged**
