### PR TITLE
fix: increase TFX version from 0.20.2 to 0.22.0. Fixes #4084, fixes #4114

### LINKED ISSUE #4084: [Release] Upgrade tfx for 1.0 release
EDIT: upgrade tfx, tfdv and tfma

/cc @rmgogogo @jingzhang36 @numerology 
/assign @Bobgy

### LINKED ISSUE #4114: TFDV and TFMA visualizations crash in 1.0rc2
### What steps did you take:
Ran tfx taxi example
Look at statistics gen or other steps with TFDV/TFMA visualization.

### What happened:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-a59281919cdf> in <module>
     14 
     15 import base64
---> 16 import tensorflow_data_validation as tfdv
     17 from IPython.display import display
     18 from IPython.display import HTML

/usr/local/lib/python3.6/dist-packages/tensorflow_data_validation/__init__.py in <module>
     22 
     23 # Import stats API.
---> 24 from tensorflow_data_validation.api.stats_api import GenerateStatistics
     25 
     26 # Import validation API.

/usr/local/lib/python3.6/dist-packages/tensorflow_data_validation/api/stats_api.py in <module>
     46 
     47 import random
---> 48 import apache_beam as beam
     49 import pyarrow as pa
     50 from tensorflow_data_validation import constants

/usr/local/lib/python3.6/dist-packages/apache_beam/__init__.py in <module>
     94 
     95 from apache_beam import coders
---> 96 from apache_beam import io
     97 from apache_beam import typehints
     98 from apache_beam import version

/usr/local/lib/python3.6/dist-packages/apache_beam/io/__init__.py in <module>
     37 try:
     38   from apache_beam.io.gcp.bigquery import *
---> 39   from apache_beam.io.gcp.pubsub import *
     40   from apache_beam.io.gcp import gcsio
     41 except ImportError:

/usr/local/lib/python3.6/dist-packages/apache_beam/io/gcp/pubsub.py in <module>
     46 
     47 try:
---> 48   from google.cloud import pubsub
     49 except ImportError:
     50   pubsub = None

/usr/local/lib/python3.6/dist-packages/google/cloud/pubsub.py in <module>
     18 from __future__ import absolute_import
     19 
---> 20 from google.cloud.pubsub_v1 import PublisherClient
     21 from google.cloud.pubsub_v1 import SubscriberClient
     22 from google.cloud.pubsub_v1 import types

/usr/local/lib/python3.6/dist-packages/google/cloud/pubsub_v1/__init__.py in <module>
     16 
     17 from google.cloud.pubsub_v1 import types
---> 18 from google.cloud.pubsub_v1 import publisher
     19 from google.cloud.pubsub_v1 import subscriber
     20 

/usr/local/lib/python3.6/dist-packages/google/cloud/pubsub_v1/publisher/__init__.py in <module>
     15 from __future__ import absolute_import
     16 
---> 17 from google.cloud.pubsub_v1.publisher.client import Client
     18 
     19 

/usr/local/lib/python3.6/dist-packages/google/cloud/pubsub_v1/publisher/client.py in <module>
     27 from google.cloud.pubsub_v1 import _gapic
     28 from google.cloud.pubsub_v1 import types
---> 29 from google.cloud.pubsub_v1.gapic import publisher_client
     30 from google.cloud.pubsub_v1.gapic.transports import publisher_grpc_transport
     31 from google.cloud.pubsub_v1.publisher._batch import thread

/usr/local/lib/python3.6/dist-packages/google/cloud/pubsub_v1/gapic/publisher_client.py in <module>
     73 
     74 
---> 75 class PublisherClient(object):
     76     """
     77     The service that an application uses to manipulate topics, and to send

/usr/local/lib/python3.6/dist-packages/google/cloud/pubsub_v1/gapic/publisher_client.py in PublisherClient()
    243         message_storage_policy=None,
    244         kms_key_name=None,
--> 245         retry=google.api_core.gapic_v1.method.DEFAULT,
    246         timeout=google.api_core.gapic_v1.method.DEFAULT,
    247         metadata=None,

AttributeError: module 'google.api_core' has no attribute 'gapic_v1'
```

### What did you expect to happen:
visualization shows

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
standalone

KFP version: 
1.0.0-rc.2

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

### PR DESCRIPTION
**Pull request by jingzhang36**
**Description of your changes:**
Fixes https://github.com/kubeflow/pipelines/issues/4084, https://github.com/kubeflow/pipelines/issues/4114

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [x] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Bobgy** [comment]
Thanks!
/lgtm

**Comment by Ark-kun** [comment]
Thank you.
How did you manage to update `requirements.txt`? Previously, it did not work since `tfx==0.22.0` was self-inconsistent. (Maybe they've fixed that).
/lgtm

**Comment by jingzhang36** [comment]
> Thank you.
> How did you manage to update `requirements.txt`? Previously, it did not work since `tfx==0.22.0` was self-inconsistent. (Maybe they've fixed that).
> /lgtm

I didn't do anything special, so I guess they fix the inconsistency themselves? I just used ./update_requirements.sh <requirements.in >requirements.txt and ../../backend/update_requirements.sh google/cloud-sdk:279.0.0 <requirements.in >requirements.txt

**Comment by Ark-kun** [comment]
> I didn't do anything special, so I guess they fix the inconsistency themselves?

That's probably the case. Good to hear that.

**Pull request merged**
