### PR TITLE
Backend - Fixed handling of sample compilation failure

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/kubeflow/pipelines/issues/354

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/387)

### CODE REVIEW

**Comment by qimingj** [comment]
There is a build-image failure...

**Comment by Ark-kun** [comment]
@qimingj Looks like the dsl-compiler fails to load the file in some cases. Can you please investigate this?

```
build-api-server-image:	Step 21/32 : RUN  for pipeline in "$(find . -maxdepth 2 -name '*.py' -type f)"; do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done
build-api-server-image:	 ---> Running in 1af2bec754d0
build-api-server-image:	Traceback (most recent call last):
build-api-server-image:	  File "/usr/local/bin/dsl-compile", line 11, in <module>
build-api-server-image:	    sys.exit(main())
build-api-server-image:	  File "/usr/local/lib/python3.5/site-packages/kfp/compiler/main.py", line 100, in main
build-api-server-image:	    compile_pyfile(args.py, args.function, args.output)
build-api-server-image:	  File "/usr/local/lib/python3.5/site-packages/kfp/compiler/main.py", line 88, in compile_pyfile
build-api-server-image:	    __import__(os.path.splitext(filename)[0])
build-api-server-image:	ImportError: No module named 'xgboost-training-cm'
build-api-server-image:	The command '/bin/sh -c for pipeline in "$(find . -maxdepth 2 -name '*.py' -type f)"; do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done' returned a non-zero code: 1
```

**Comment by qimingj** [comment]
You don't need the quotes around find command.

RUN  for pipeline in "$(find . -maxdepth 2 -name '*.py' -type f)"; do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done

should be:

RUN  for pipeline in $(find . -maxdepth 2 -name '*.py' -type f); do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done

With the quotes the results are treated as a single string with multiple lines.

**Comment by Ark-kun** [comment]
@qimingj  Thanks for fixing the problem. I checked the code locally and it did not occur to me that it would work differently in Docker. I think we should modify the compiler so that it checks the existence of a file and give a meaningful error if the file does not exist.

> You don't need the quotes around find command.

I've checked that the quotes are needed when the files can have spaces. Otherwise `for` breaks them into parts. I wonder why this works differently when run by Docker.

**Comment by qimingj** [comment]
The other pair of quotes ("$pipeline") should take care of the space in file names?

I can reproduce the problem locally with your previous command.

**Comment by Ark-kun** [comment]
> The other pair of quotes ("$pipeline") should take care of the space in file names?

Those quotes cannot help when the file name is already split into parts by `for`:

```
$ ls -la
total 16
drwxr-xr-x  2 avolkov primarygroup 4096 Nov 26 18:20  .
drwxrwxrwt 16 root    root         4096 Nov 26 18:20  ..
-rw-r--r--  1 avolkov primarygroup    4 Nov 26 18:20 'aa bb'
-rw-r--r--  1 avolkov primarygroup    4 Nov 26 18:20 'cc dd'
```
```
$ for file in "$(find . -type f)"; do echo $file; done
./cc dd ./aa bb
```
```
$ for file in $(find . -type f); do echo $file; done
./cc
dd
./aa
bb
```

>I can reproduce the problem locally with your previous command.

Strange:

```
$ for pipeline in "$(find . -maxdepth 2 -name '*.py' -type f)"; do echo $pipeline; done
./ee ff.py

```

**Pull request merged**
