### PR TITLE
feat(backend): updates compiler to include kubernetes-specific specs in argo workflow

### PR DESCRIPTION
**Pull request by Linchin**
**Description of your changes:**
* Updated argo compiler to intake kubernetes-specific spec and incorporate it in the generated argo workflow
* Added compiler test

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by gkcalat — APPROVED** [review]
Thank you, @Linchin!

/lgtm
/approve

**Comment by chensun** [comment]
@Linchin, @gkcalat 

This PR likely introduced a highly flaky test.
https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/9076/kubeflow-pipeline-backend-test/1641760131995668480
https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/9075/kubeflow-pipeline-backend-test/1641754051475410944

@Linchin can you please take a look?

PS: Unlike e2e test, unit test should never be flaky, whenever we see `kubeflow-pipeline-backend-test` failure, we should investigate instead of retrying the test. 
https://oss.gprow.dev/pr-history/?org=kubeflow&repo=pipelines&pr=9059

**Comment by Linchin** [comment]
@chensun 
Thank you! It's been happening to me locally too. I will investigate this issue today.

**Pull request merged**
