### PR TITLE
Adds a Tensorboard component for local environments

### PR DESCRIPTION
**Pull request by swiftdiaries**
Right now, the Output Artifacts Viewer (Pipelines UI) only accepts GCS and Minio as the storage services [Source Code](https://github.com/kubeflow/pipelines/blob/master/frontend/src/lib/WorkflowParser.ts#L205).

However, Tensorboard cannot process links starting with `minio://` and as of now there's no way to read things off of the local filesystem through volumes and/or volume mounts.

This is a component that we have been using for our onprem demos, which we are working on open-sourcing.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/792)

### CODE REVIEW

**Comment by vicaire** [comment]
@neuromage added a CRD to start and manage instances of Tensorboard. The advantage of this CRD is that it manages the tensorboard instances and keeps track of them. 

https://github.com/kubeflow/pipelines/tree/master/backend/src/crd/samples/viewer

Could we add the functionality of this PR to this CRD? It should then be easy to create an instance of Tensorboard by using kubectl. Doing this will also put us on the right track to integrate this functionality with the UI. 

/cc @neuromage

**Comment by swiftdiaries** [comment]
@animeshsingh There's a set of pending PRs for adding S3 support.
https://github.com/kubeflow/pipelines/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+s3
This would enable any S3 compatible Object Stores including Minio.

**Comment by swiftdiaries** [comment]
@vicaire @neuromage Thank you for the reply. The ViewerCRD looks pretty neat. How does Pipelines run / orchestrate the ViewerCRD and how can it be attached to a training ContainerOp / TfJob op for example?

**Comment by vicaire** [comment]
/cc @neuromage 

@swiftdiaries, the CRD does not yet support mounting a volume. Would you be interested in adding support for this? 

The way it works today is like this: 
1) The pipeline runs. 
2) One of the steps outputs Tensorboard data in an object store (GCS, S3, etc.)
3) From the UI (clicking the pipeline step that generated the tensorboard data) or from kubectl, a Tensorboard instance is created (using the viewer CRD) that gets an argument specifying where to look for the data (object store only is supported today. Adding volume support would be great). 

WDYT?

**Comment by swiftdiaries** [comment]
@vicaire The Viewer CRD supports the addition of local volumes, I created a PR with a sample [here](https://github.com/kubeflow/pipelines/pull/822)
The frontend UI currently doesn't support reading off of local volumes, as a next step I'm looking to add that feature

**Comment by neuromage** [comment]
Yeah, the viewer CRD supports volumes. I tested this but should have documented and added a sample for how to do it. Thanks @swiftdiaries for looking into it and adding the sample. 

The next step is to replace the Tensorboard launcher in the UI to use the viewer CRD instead. If you'd like to look into that @swiftdiaries , that would be great.

/cc @yebrahim 
/cc @rileyjbauer

**Comment by swiftdiaries** [comment]
Thank you :) I’ll look into it and send a PR shortly

**Comment by vicaire** [comment]
SGTM. Thanks. Should we close this PR?

**Comment by swiftdiaries** [comment]
Closing because it's being handled via the Viewer CRD
PR for reference: #822 
Issue for reference: https://github.com/kubeflow/pipelines/issues/699

**Pull request closed without merging**
