### PR TITLE
Fix watson train component

### PR DESCRIPTION
**Pull request by mpoqq**
Add scheme to cos_endpoint for watson client and change deprecated author_email to author_name.
#1254 point 3.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1259)

### CODE REVIEW

**Comment by Tomcli** [comment]
I think overall it looks good to me, but it would be nice if we can make sure we get rid of the http:// scheme before passing to the Minio client. e.g.
```python
import re
url = re.compile(r"https?://")
cos_endpoint = url.sub('', cos_endpoint)
```

**Comment by animeshsingh** [comment]
Another option could be to just make the prefix a var, http or https (based on user`s setting). Otherwise /lgtm

**Comment by mpoqq** [comment]
I see your points, but if we configure the endpoint over two ways (creds.ini and parameter) it is maybe confuse. How about we say the endpoint must have a scheme and than do something like this:
```python
from urllib.parse import urlsplit
parts = urlsplit(endpoint_url)
endpoint_without_scheme = parts.hostname
endpoint_with_scheme = parts.geturl()
```
(it is equivalent what watson client api does [here](https://github.com/IBM/ibm-cos-sdk-python-core/blob/master/ibm_botocore/utils.py#L831))

**Comment by animeshsingh** [comment]
+1. Go ahead and test it once under different scenarios, and update the PR.

**Comment by animeshsingh** [comment]
Hi @mpoqq - I think there is a misunderstanding, and we can slack somewhere. I definitely dont want us to shift to ibm cos sdk - we want to stick with minio as the client.

**Comment by mpoqq** [comment]
Hi @animeshsingh, sorry for the misinterpretation. I send you a direct message in the kubeflow slack.

**Comment by mpoqq** [comment]
@animeshsingh friendly reminder =)

**Pull request merged**
