### PR TITLE
chore(sdk): accept newer `typing-extensions` versions

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Mirrors changes from #7632 in v1.x. Needed to unblock TFX (reference: 
https://github.com/kubeflow/pipelines/pull/7632#issuecomment-1135264526).

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more 
about the pull request title convention used in this 
repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
/lgtm
/approve

Thanks!

**Comment by guimou** [comment]
@connor-mccarthy Hi! Any target for this to be released (in 1.8.13 I guess)?

**Comment by guimou** [comment]
OK, thanks a lot!

**Pull request merged**
