### PR TITLE
Added checks for parallism values

### PR DESCRIPTION
**Pull request by NikeNano**
**Description of your changes:**

Based upon discussion in 4199, https://github.com/kubeflow/pipelines/pull/4199#discussion_r535751512
**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by NikeNano** [comment]
@chensun based upon the discussion [here](https://github.com/kubeflow/pipelines/pull/4199#discussion_r535751512).

**Comment by numerology** [comment]
/lgtm
/approve

Thanks!

**Comment by numerology** [comment]
@NikeNano The TFX failure was irrelevant, there is a pending fix at https://github.com/tensorflow/tfx/pull/3023

**Comment by NikeNano** [comment]
> @NikeNano The TFX failure was irrelevant, there is a pending fix at [tensorflow/tfx#3023](https://github.com/tensorflow/tfx/pull/3023)

Assumed it was a flaky test, great with the quick fix!

**Pull request merged**
