### PR TITLE
[Test] fix upgrade test

### PR DESCRIPTION
**Pull request by numerology**
After 0.4.0 release this TODO should be filled.

### CODE REVIEW

**Comment by rui5i** [comment]
/lgtm
Thanks, Jiaxiao.

**Comment by numerology** [comment]
@Bobgy 
Do you mind taking a look when possible? Not sure if we need to add a kubectl wait for the cache-deployer to make sure it's ready

**Comment by Bobgy** [comment]
@numerology @rui5i The error is complaining 0.4.0 tag's manifest's cache-deployer deployment is stuck at image pull backoff. I took a look at the manifest, it's using gcr.io/ml-pipeline/cache-deployer, while gcr.io/ml-pipeline/cache-deployer doesn't exist.

Looks like that's the root cause. Where did it go wrong in that image?

**Comment by numerology** [comment]
@Bobgy Thanks

I think as in it was named `cachedeployer`, which is a mismatch. Let me manually retag and fix .release.cloudbuild.yaml tmr.

[1] https://github.com/kubeflow/pipelines/blob/2d05e3d2e925d0e7195829e446117f18715ec68e/.release.cloudbuild.yaml#L345

**Comment by numerology** [comment]
Actually it's not pushed under gcr.io/ml-pipeline

**Comment by Bobgy** [comment]
@numerology All images have a name mismatch, e.g. gcr.io/ml-pipeline/visualization-server, but its marketplace image is called gcr.io/ml-pipeline/google/pipelines/visualizationserver

The root cause here, is that gcr.io/ml-pipeline/cache-deployer is not pushed as you figured out

**Comment by Bobgy** [comment]
cache-deployer should be added here: https://github.com/kubeflow/pipelines/blob/0.4.0/.release.cloudbuild.yaml#L587

**Comment by numerology** [comment]
/retest

Manually pushed. Giving a try

**Comment by Bobgy** [comment]
thanks

**Comment by rui5i** [comment]
Cache deployer should be built in this file: https://github.com/kubeflow/pipelines/blob/2d05e3d2e925d0e7195829e446117f18715ec68e/.cloudbuild.yaml#L106 and pushed in .release.cloudbuild.yaml. Seems like the image was built but not pushed before.

**Comment by Bobgy** [comment]
Note, with cloudbuild configuration, only images listed in the last `images` section will be pushed to remote. Other locally built images stay unpublished.

https://github.com/kubeflow/pipelines/blob/0.4.0/.release.cloudbuild.yaml#L576

**Comment by rui5i** [comment]
Thanks, Jiaxiao. I think cache-server also need to be pushed again.

**Comment by numerology** [comment]
> Thanks, Jiaxiao. I think cache-server also need to be pushed again.

Yes.

**Comment by Bobgy** [comment]
Thanks for the quick fix!

**Pull request merged**
