### PR TITLE
SDK - Compiler - Using properly serialized pipeline parameter defaults

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/kubeflow/pipelines/issues/2534
Fixes https://github.com/kubeflow/pipelines/issues/2825
Fixes https://github.com/kubeflow/pipelines/issues/2840
Fixes https://github.com/kubeflow/pipelines/issues/3806

### CODE REVIEW

**Comment by Ark-kun** [comment]
@numerology @Bobgy Can you please take a look.

**Comment by Bobgy** [comment]
FYI, @Ark-kun I'm cherry picking this to release-1.0 branch because it seems to fix a lot of issues

**Pull request merged**
