### PR TITLE
chore(backend): update python from 3.7 to 3.12

### PR DESCRIPTION
**Pull request by juliusvonkohout**
**Description of your changes:**

Follow up of https://github.com/kubeflow/pipelines/pull/10750
@rimolive @chensun @rickyxie0929 @connor-mccarthy 

@rickyxie0929 @rimolive this is a fast draft, i can add you to my pipelines for if you want to add changes here.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
We could also go to 3.11 first if that helps.

**Comment by juliusvonkohout** [comment]
CVE Scanning
Automatic CVE scanning with Trivy on the master branch is relevant for DevSecOps and enterprise security guidelines https://github.com/kubeflow/manifests/blob/master/.github/workflows/trivy.yaml
Here are some numbers from June 25 https://github.com/kubeflow/manifests/actions/runs/9658715319/job/26640495132

| Working Group           | Images | Critical CVE | High CVE | Medium CVE | Low CVE |
|-------------------------|--------|--------------|----------|------------|---------|
| AutoML                  | 13     | 15           | 231      | 547        | 756     |
| Pipelines               | 45     | 204          | 1909     | 7342       | 3236    |
| Workbenches(Notebooks)  | 12     | 26           | 222      | 315        | 230     |
| Kserve                  | 13     | 43           | 522      | 1986       | 1418    |
| Manifests               | 18     | 19           | 18       | 174        | 78      |
| Training                | 1      | 1            | 1        | 1          | 0       |
| Model Registry          | 3      | 18           | 71       | 104        | 147     |
| All Images              | 105    | 326          | 2974     | 10469      | 5865    |

**Comment by juliusvonkohout** [comment]
Do we have public access to the uploaded artifacts? if not please comment this section out in the workflow.

**Comment by rimolive** [comment]
@juliusvonkohout Can you please rebase?

**Comment by juliusvonkohout** [comment]
@rimolive rebase is done

**Comment by hbelmiro** [comment]
@juliusvonkohout what about the failing tests? They are not optional.

**Comment by juliusvonkohout** [comment]
@diegolovison  will probably continue this PR. I gave him access to the branch.

**Comment by juliusvonkohout** [comment]
Will be continued in https://github.com/kubeflow/pipelines/pull/11159/commits

**Pull request closed without merging**
