### PR TITLE
Upgrade @kubernetes/client-node

### PR DESCRIPTION
**Pull request by yebrahim**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/271)

### CODE REVIEW

**Comment by yebrahim** [comment]
This: https://www.npmjs.com/advisories/548.
And: https://github.com/kubernetes-client/javascript/commit/c55e8a359d9c1f11318d2d41e69425d4006aeb6d.

**Comment by Ark-kun** [comment]
The frontend tests seem to be super-flaky today ...

    -✖ run-frontend-integration-tests          integration-test-bwg62-578060046   3m        failed with exit code 1

**Comment by yebrahim** [comment]
Yes. My guess is it's https://github.com/kubeflow/pipelines/commit/790cb36f73fbe0aa321417cc3a387c4e8c6b0edc.
@gaoning777 can we revert this until we investigate?

**Pull request merged**
