### PR TITLE
Add notebook instructions on how to query ML Metadata for output artifacts

### PR DESCRIPTION
**Pull request by neuromage**
Add instructions on how to query ML Metadata for output artifacts from TFX components.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/932)

### CODE REVIEW

**Comment by neuromage** [comment]
@Ark-kun can you approve as well please? I don't have approval rights. Thanks!

**Comment by Ark-kun** [comment]
> @Ark-kun can you approve as well please? I don't have approval rights. Thanks!

Sure!
/approve

**Pull request merged**
