### PR TITLE
feat(samples): Added the caching sample. Fixes #4636

### LINKED ISSUE #4636: [Testing] Integration tests for KFP caching
To find cache deployer/cache server problems earlier (rather than before/after release):
I'd suggest writing an integration test that verifies caching behavior https://github.com/kubeflow/pipelines/tree/master/backend/test/integration

Then we can catch this type of problem next time in presubmit tests directly.
/cc @Ark-kun

_Originally posted by @Bobgy in https://github.com/kubeflow/pipelines/pull/4626#issuecomment-711480005_

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/kubeflow/pipelines/issues/4636

### CODE REVIEW

**Comment by Bobgy** [comment]
Thank you @Ark-kun! This fills the gap for caching auto testing.

**Comment by Bobgy** [comment]
/lgtm
Great work! Thank you so much @Ark-kun !
This could save so much effort as a presubmit test.

/hold
Just to make sure others have a chance to review, feel free to unhold when you see fit.

/assign @numerology @chensun

**Comment by numerology** [comment]
/lgtm

Super! Great job Alexey

**Comment by Ark-kun** [comment]
/hold cancel
This was really helpful. Writing this test helped me uncover an issue with caching and max_cache_staleness and a problem with the DSL compiler.

**Pull request merged**
