### PR TITLE
fix(docs): add note about protoc dependency and version

### PR DESCRIPTION
**Pull request by gregsheremeta**
**Description of your changes:**

Add a note about protoc being required, and a note about which versions are known to work.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by hbelmiro — COMMENTED** [review]
/lgtm
/ok-to-test

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by gregsheremeta** [comment]
@chensun can you merge this one too? ty!

**Review by chensun — APPROVED** [review]
/lgtm
/approve

**Comment by hbelmiro** [comment]
@gregsheremeta can you rebase?

**Pull request merged**
