### PR TITLE
fix(components): broken non ascii code after compilation

### PR DESCRIPTION
**Pull request by zsaladin**
In some cases non ascii code are broken after compilation.
To allow unicode option can fix it.

**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [x] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by zsaladin** [comment]
Hmm.. even if compiling pipeline to yaml is successful kubeflow fails with the error.

```json
{"error":"Failed to create a new run.: InternalServerError: Failed to store run ja-ko-9bg8f to table: Error 1366: Incorrect string value: '\\xEB\\xBD\\x80\\xEB\\xA1\\x9C...' for column 'WorkflowSpecManifest' at row 1","message":"Failed to create a new run.: InternalServerError: Failed to store run ja-ko-9bg8f to table: Error 1366: Incorrect string value: '\\xEB\\xBD\\x80\\xEB\\xA1\\x9C...' for column 'WorkflowSpecManifest' at row 1","code":13,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error","error_details":"Failed to create a new run.: InternalServerError: Failed to store run ja-ko-9bg8f to table: Error 1366: Incorrect string value: '\\xEB\\xBD\\x80\\xEB\\xA1\\x9C...' for column 'WorkflowSpecManifest' at row 1"}]}
```

argo runs it without errors.
i think kubeflow has to handle the error.

**Comment by zsaladin** [comment]
Hmm.. even if compiling pipeline to yaml is successful kubeflow fails with the error.

```json
{"error":"Failed to create a new run.: InternalServerError: Failed to store run test-9bg8f to table: Error 1366: Incorrect string value: '\\xEB\\xBD\\x80\\xEB\\xA1\\x9C...' for column 'WorkflowSpecManifest' at row 1","message":"Failed to create a new run.: InternalServerError: Failed to store run test-9bg8f to table: Error 1366: Incorrect string value: '\\xEB\\xBD\\x80\\xEB\\xA1\\x9C...' for column 'WorkflowSpecManifest' at row 1","code":13,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Internal Server Error","error_details":"Failed to create a new run.: InternalServerError: Failed to store run test-9bg8f to table: Error 1366: Incorrect string value: '\\xEB\\xBD\\x80\\xEB\\xA1\\x9C...' for column 'WorkflowSpecManifest' at row 1"}]}
```

argo runs it without errors.
i think kubeflow has to handle the error.

**Comment by Ark-kun** [comment]
> In some cases non ascii code are broken after compilation.

Interesting. Can you show an example, please?

I thought that when you save and then load a component, you get back the same strings. Does it fail for you?

**Comment by zsaladin** [comment]
Here are examples.

<details><summary>exaplme1</summary>
<p>

```py
@dsl.pipeline(
    name="pipeline"
)
def main():
    dsl.ContainerOp(
        name="hello",
        image="bash:lastest",
        command=["echo", "안녕"]
    )
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.0, pipelines.kubeflow.org/pipeline_compilation_time: '2021-03-12T00:32:29.793592',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.0}
spec:
  entrypoint: pipeline
  templates:
  - name: hello
    container:
      command: [echo, "\uC548\uB155"]  ######## Broken #########
      image: bash:lastest
  - name: pipeline
    dag:
      tasks:
      - {name: hello, template: hello}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner

```


</p>
</details>

<details><summary>exaplme2</summary>
<p>

```py
op = kfp.components.load_component_from_file('component.yaml')
@kfp.dsl.pipeline(
    name="hello"
)
def my_pipeline():
    op()
```

```yaml
# component.yaml
implementation:
  container:
    image: bash:latest
    command: [
      echo, 안녕
    ]

```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.0, pipelines.kubeflow.org/pipeline_compilation_time: '2021-03-12T00:39:12.501616',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "hello"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.0}
spec:
  entrypoint: hello
  templates:
  - name: component
    container:
      args: []
      command: [echo, "\uC548\uB155"]  ########### Broken ################
      image: bash:latest
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": ["echo", "\uc548\ub155"], "image": "bash:latest"}}}', pipelines.kubeflow.org/component_ref: '{"digest":
          "9da12977a70990cd36756a97f52bddf5a0022bd8ee88377a996229386539094f", "url":
          "component.yaml"}'}
  - name: hello
    dag:
      tasks:
      - {name: component, template: component}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
```

</p>
</details>

**Comment by Ark-kun** [comment]
Is the runtime behavior different?
I'm not sure it's broken is the execution result is the same.

**Comment by Ark-kun** [comment]
I'm a bit afraid that not every YAML parser will be able to support such strings, especially unquoted.
Also keep in mind that the list of command-line arguments is always an array of null-terminated C-strings. There is no Unicode support there.

Have you checked that the Workflow still works if you make the change?

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Pull request closed without merging**
