### PR TITLE
fix(frontend): TFX artifact visualization update. Fix tensorflow/tfx#3933

### PR DESCRIPTION
**Pull request by zijianjoy**
**Description of your changes:**
Fix https://github.com/tensorflow/tfx/issues/3933

tfxlabelpipelinestatgen

All blocking items are resolved:
1. ~~In statistics artifact, received error on UI: `ValueError: lhs_statistics proto contains multiple datasets. Only one dataset is currently supported.`~~
2. ~~In anomaliesArtifacts, need to use the right dependencies for `anomalies_pb2`: Currently I am using `from tensorflow_metadata.proto.v0 import anomalies_pb2`, but the recommendation is https://github.com/tensorflow/metadata/tree/master/google3/third_party/tensorflow_metadata/proto/v0, which appears to be not found when I apply this recommendation.~~
3. ~~In anomaliesArtifacts, `from tfx.utils import io_utils` doesn't work because tfx library is not found.~~
4. ~~In order to fix the above issue#3, I added tfx dependency to backend/src/apiserver/visualization. However, the TFX example `Taxi tip prediction model trainer` only works on KFP 1.4.1, but not on KFP 1.7.0-alpha.2. Failure message is `tensorflow.python.framework.errors_impl.InvalidArgumentError: 'object' must be a non-empty string. (File: gs://jamxl-kfp-dev/)` at the first step of pipeline. How should I apply the local built image of visualization server to my cluster?~~

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by jiyongjung0** [comment]
Thank you so much for the change!

For 1. The error message seems coming from [kubeflow pipelines](https://github.com/kubeflow/pipelines/blob/52b0792e9fdbfd819ce646cf516f777d9b4167be/backend/src/apiserver/visualization/types/tfdv.py#L55) Could you check what data was used in the test?

For 2. The recommended usage is available from `tensorflow-metadata` 1.0.0. So you can just use the old way or upgrade the package version.

For 3. (and 4): I think that we don't need the whole `tfx` library to read the file because it is a simple file read. We can do it using TF only, for example:
```
import tensorflow as tf
with tf.io.gfile.GFile('${artifact.getUri()}/Split-${name}', mode='rb') as f:
  anomalies_bytes = f.read()
```

**Comment by zijianjoy** [comment]
Thank you @jiyongjung0 for the help!

 
> For 1. The error message seems coming from [kubeflow pipelines](https://github.com/kubeflow/pipelines/blob/52b0792e9fdbfd819ce646cf516f777d9b4167be/backend/src/apiserver/visualization/types/tfdv.py#L55) Could you check what data was used in the test?

The pipeline I use is https://www.tensorflow.org/tfx/tutorials/tfx/template, more specifically: I ran the command in notebook to pull sample:
```
!tfx template copy \
  --pipeline-name={PIPELINE_NAME} \
  --destination-path={PROJECT_DIR} \
  --model=taxi
```
Then the csv data is in `data/` folder. To move forward with validation of this PR, what TFX pipeline do you suggest to use for various visualizations? (Statistics, SchemaGen, Anomalies, Evaluator)
 
> For 2. The recommended usage is available from `tensorflow-metadata` 1.0.0. So you can just use the old way or upgrade the package version.

Thank you for confirming! I will use the old way for now, until all Tensorflow libraries are available at 1.0.0.

> For 3. (and 4): I think that we don't need the whole `tfx` library to read the file because it is a simple file read. We can do it using TF only, for example:
> 
> ```
> import tensorflow as tf
> with tf.io.gfile.GFile('${artifact.getUri()}/Split-${name}', mode='rb') as f:
>   anomalies_bytes = f.read()
> ```

Thank you for confirming! Discussed offline, we are going to switch over to tensorflow/tfx:0.30.1 image for ability to use this library.

**Comment by zijianjoy** [comment]
@jiyongjung0 @Bobgy 

Thank you both for the help on upgrading TFX visualization! All blocking issues are resolved and PR is ready for review.

**Review by Bobgy — COMMENTED** [review]
Thank you for taking all the ownership for resolving this issue!
/lgtm
/approve
I think you might need to check the frontend tests

**Comment by zijianjoy** [comment]
> Thank you for taking all the ownership for resolving this issue!
> /lgtm
> /approve
> I think you might need to check the frontend tests

Thank you Yuan! Syncing the updated backend config file.

**Pull request merged**
