### PR TITLE
feat(sample): Use TFX 1.2.0 for Taxi tips prediction sample. Partial #6138

### PR DESCRIPTION
**Pull request by zijianjoy**
**Description of your changes:**

Partial #6138

TFX 1.2.0 adds worker pod ID to the custom_properities of execution, it allows UI to find the corresponding execution using argo workflow.

cc @jiyongjung0

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
Thank you for the fix!

I also forgot to update https://github.com/kubeflow/pipelines/blob/b7ff0ea917458bd2bb9af9408a7207afb3a2fa27/samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py#L167.

**Comment by zijianjoy** [comment]
> Thank you for the fix!
> 
> I also forgot to update
> 
> https://github.com/kubeflow/pipelines/blob/b7ff0ea917458bd2bb9af9408a7207afb3a2fa27/samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py#L167
> 
> .

Thank you for pointing it out! I included this change in my PR.

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you for the fix!

**Review by jiyongjung0 — APPROVED** [review]
LGTM! Thanks!

**Comment by Bobgy** [comment]
because the sample is only tested in postsubmit, we can merge now

**Pull request merged**
