### PR TITLE
feat(sdk.v2): Raise error on artifacts vs. parameters mismatch in v2.

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
- Raises error when pipeline arguments are categorized as artifacts - the most common cause is missing type annotation.
- Raises error on passing an artifact to a parameter or vice versa. 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
This PR supersedes https://github.com/kubeflow/pipelines/pull/5526. 
Instead of defaulting untyped pipeline inputs to be `String` typed, we throw an explicit error asking users to type annotate the pipeline inputs properly. 

The problem with https://github.com/kubeflow/pipelines/pull/5526 is that we create some inconsistency on how we decide artifacts vs. parameters: Pipeline inputs with no type defaults to `String` typed parameter, while component inputs with no type are still considered generic artifact, and this inconsistency could often lead to the mismatch of passing parameters to artifacts, which then requires users to properly type component inputs.
So overall I think https://github.com/kubeflow/pipelines/pull/5526 is a hacky solution that only solves a subset of a bigger problem. We would rather ask users to type annotate pipeline inputs, which is a relatively low user effort. 

/cc @Ark-kun

**Comment by Ark-kun** [comment]
This PR improves error messages for the users which is strictly an improvement.
Thank you, Chen.
/lgtm

However I think in the future we should do more and support more rich types for the pipeline parameters since we taught the users to, especially with the 1st-party types from the approved `kfp.dsl.types` module.
I think that #5478 can be considered a future improvement on top of this PR.

MLMD only supporting 2-3 primitive types should not preclude the users from having proper typing. `bool`, `DateTime`, `Url`, `GcsPath` etc are all valid types of pipeline parameters.

**Pull request merged**
