### PR TITLE
feat(backend): Add ExecutionSpec Interface

### PR DESCRIPTION
**Pull request by yhwang**
**Description of your changes:**
issue: #6888

Create an abstraction interface to encapsulate util.Workflow and decouple the dependency of Argo Workflow pkg.
ExecutionSpec wraps the Workflow and other runtime engines in the future. ExecutionStatus is used to access status information.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by yhwang** [comment]
This is the initial change and it only adds the interface and some basic functions. Try to make
minimal changes first. if this is the right direction, I will work on further changes.

**Review by Arhell — COMMENTED** [review]
/assign @chensun

**Comment by yhwang** [comment]
@chensun any comment to make this PR move forward?

**Comment by yhwang** [comment]
@chensun @zijianjoy, it's been a while. I have other potential PRs that depend on this one. We agree that the first PR shouldn't contain too many changes and we should do this in a series of PRs. Basically, changes in this PR are refactoring. I believe there is no functional change. Can you review the changes and provide feedback/comments if any? Any suggestions for the class/function name are welcome.

**Review by chensun — COMMENTED** [review]
@yhwang Sorry for the delay. 

/lgtm
/approve

Thanks!

**Comment by yhwang** [comment]
@chensun thanks for the review! I will continue the refactoring change. I will have other PRs soon.

**Pull request merged**
