### PR TITLE
[Sample] Add new TFX::OSS sample

### PR DESCRIPTION
**Pull request by numerology**
Add a sample showing how to run TFX pipeline on Kubeflow Runner.

TODO:
- [x] Add proper dependency so it can be built into preload samples
- [x] Add docs
- [x] Add sample test coverage

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2319)

### CODE REVIEW

**Comment by numerology** [comment]
Note that the compilation of new sample here requires a HEAD version of TFX (as of 10.07.2019) and a customized value in tfx.version pointing to TFX nightly build (because there is actually no image tagged as tfx:0.15.0.dev). I suggest that we move this sample to contrib sample dir to bypass integration test and make the compiled pipeline package part of our repo so that backend server can pre-load it, otherwise we might need rather complex dependency setup, which is also error-prone because it relies on a dev version of TFX.

I will add a doc so that a user knows how to compile such hacky sample successfully.

WDYT @neuromage @gaoning777

**Comment by neuromage** [comment]
> WDYT @neuromage @gaoning777

SGTM, thanks!

**Comment by gaoning777** [comment]
I think it is a little risky to load the sample in the API server without testing. The preloaded samples are supposed to be flagship samples that are guaranteed to work. Say, a new user tries out the KFP and runs the preloaded sample but failed. It could easily scare them away. Besides, we got lots of issues in the early stages when the preloaded samples break. @SinaChavoshi used to use the old TFX samples during customer workshops. 

My suggestion is a little change on top of your current work: write some custom sample test infra codes to cover the test for the compiled pipeline. WDYT? @numerology @neuromage

**Comment by numerology** [comment]
> I think it is a little risky to load the sample in the API server without testing. The preloaded samples are supposed to be flagship samples that are guaranteed to work. Say, a new user tries out the KFP and runs the preloaded sample but failed. It could easily scare them away. Besides, we got lots of issues in the early stages when the preloaded samples break. @SinaChavoshi used to use the old TFX samples for demos and IIRC, sample breaking during the demo is bad.
> 
> My suggestion is a little change on top of your current work: write some custom sample test infra codes to cover the test for the compiled pipeline. It shouldn't be too much custom codes but is rewarding. WDYT? @numerology @neuromage

One of the current problem is that we need a dev version and a nightly build of TFX to make this compile and run. If we put those dependencies in our sample test infra it might not be very stable. Talked to TFX side and I was told 0.15.0 release should be either this week or next week. I think it will be much easier and reliable to add a sample test coverage by then.

**Comment by gaoning777** [comment]
what I meant is not adding dependency on the dev version of the TFX, but adding custom sample test infra codes to run the chicago_taxi_pipeline_simple.tar.gz directly without compilation. To understanding, the chicago_taxi_pipeline_simple.tar.gz is working for the current KFP deployment.

**Comment by numerology** [comment]
> what I meant is not adding dependency on the dev version of the TFX, but adding custom sample test infra codes to run the chicago_taxi_pipeline_simple.tar.gz directly without compilation. We add the python codes and the compiled one as you have done here.

I see. That's doable. Let me ping you when it's done.

**Comment by numerology** [comment]
PTAL @neuromage  @gaoning777  Thanks!

**Comment by neuromage** [comment]
This is pretty awesome, thanks @numerology :-)
/lgtm
/approve

**Comment by gaoning777** [comment]
This is great.
Thanks

**Comment by animeshsingh** [comment]
@gaoning777 @numerology @neuromage we have a talk in KF summit and TF World on this topic - are there any additional materials (slides/design docs etc.)  you can point to vis a vis TFX which I can use?

**Comment by numerology** [comment]
> @gaoning777 @numerology @neuromage we have a talk in KF summit and TF World on this topic - are there any additional materials (slides/design docs etc.) you can point to vis a vis TFX which I can use?

The recommended entrypoint of a variety of docs besides the code repo is the [user guide](https://www.tensorflow.org/tfx/guide) where some basic concepts and orchestration mechanism of TFX are introduced. Also there is some recorded talks and tutorials [here](https://www.tensorflow.org/tfx/tutorials).

**Pull request merged**
