### PR TITLE
chore: sync pipeline_spec to current version. 

### PR DESCRIPTION
**Pull request by ji-yaqi**
Generated through running 
```
/pipelines/api$ make
```

This is to unblock schema_version development for SDK.

### CODE REVIEW

**Comment by ji-yaqi** [comment]
Hi @Bobgy, could you review this change? This helps unblock the PR for schema_version in SDK. Thanks!

**Comment by Bobgy** [comment]
There is not much to review in this PR, feel free to ask other approvers next time

**Pull request merged**
