### PR TITLE
[Doc] Update link of preload TFX sample

### PR DESCRIPTION
**Pull request by numerology**
so that the user can open the ipynb file in JaaS notebook. Inspired by [fastai](https://docs.fast.ai/applications.html)

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2839)

### CODE REVIEW

**Comment by numerology** [comment]
Will do.

> so that all links appear before the title.

Do you mean links appear before description? Thanks

**Comment by jessiezcc** [comment]
yes

**Comment by Ark-kun** [comment]
Thanks!
/lgtm

**Pull request merged**
