### PR TITLE
KFServing move to v1alpha2

### PR DESCRIPTION
**Pull request by animeshsingh**
Moving KFServing Pipeline to v1alpha2 and handling rename from kfservice to inference service

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2369)

### CODE REVIEW

**Comment by animeshsingh** [comment]
/assign @gaoning777 @Ark-kun 

cc @ellis-bigelow

**Comment by animeshsingh** [comment]
@gaoning777 @Ark-kun please accelerate this - part of v0.7 release

**Comment by gaoning777** [comment]
could you resolve the travis failure. 
Overall, LGTM

**Comment by animeshsingh** [comment]
@gaoning777 the tests passed

**Pull request merged**
