### PR TITLE
Upload pipeline/pipeline version with a description

### PR DESCRIPTION
**Pull request by jingzhang36**
Related https://github.com/kubeflow/pipelines/issues/3491

Verified with local built python package. 

Note: pipeline has description field in db, while pipeline version doesn't.

### CODE REVIEW

**Comment by Bobgy** [comment]
QQ: how did you generate these?
Did we forget to generate before last release?

**Comment by jingzhang36** [comment]
> QQ: how did you generate these?
> Did we forget to generate before last release?

Changing swagger json and rerun swagger autogen

Last time when I added description to backend UploadPipeline server, I only updated frontend calls but missed the client side interface, which also needs manual update to the swagger json. Otherwise, it is like the backend can take the parameter, but the parameter doesn't get exposed to the client interface.

**Comment by Bobgy** [comment]
> > QQ: how did you generate these?
> > Did we forget to generate before last release?
> 
> Changing swagger json and rerun swagger autogen
> 
> Last time when I added description to backend UploadPipeline server, I only updated frontend calls but missed the client side interface, which also needs manual update to the swagger json. Otherwise, it is like the backend can take the parameter, but the parameter doesn't get exposed to the client interface.

I see, so we need to manually maintain the swagger.json. Thanks for the fix!

**Pull request merged**
