### PR TITLE
[MKP] Remove the usage of user-gcp-sa for MKP deployment

### PR DESCRIPTION
**Pull request by numerology**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2424)

### CODE REVIEW

**Comment by IronPan** [comment]
If we don't change the backend to remove the user-gcp-sa from the samples, the sample pods might failed to start. @rmgogogo 
Also for cloudsql/gcs case, the proxy pods are mounting these secrets too. they might fail to start as well. @Bobgy

**Comment by numerology** [comment]
> If we don't change the backend to remove the user-gcp-sa from the samples, the sample pods might failed to start. @rmgogogo
> Also for cloudsql/gcs case, the proxy pods are mounting these secrets too. they might fail to start as well. @Bobgy

For the four simple pre-load samples: conditional/parallel/sequential/exit_handler, I guess they won't fail because the pipeline won't fail because user-gcp-sa is not used in the pipelines. Am I right?

For XGBoost and TFX sample they are failing either way: lack of user-gcp-sa or lack of proper permission.

**Comment by Bobgy** [comment]
What's the purpose of removing user-gcp-sa?
I don't know full context here.

**Comment by rmgogogo** [comment]
I didn't see the context of why do this change.
Please read my design doc sent last Friday. It requires 'smartly' set the ADC, not fully remove it.

**Comment by rmgogogo** [comment]
Got your meaning. Yes, KFP system doesn't need these two settings in latest design.
Please give 1-3 days to let all buy-in the design and then I will LGTM.

**Comment by rmgogogo** [comment]
"If we don't change the backend to remove the user-gcp-sa from the samples, the sample pods might failed to start."
It was mentioned in design doc. We need some additional changes. However Jiaxiao's this PR will finally be submitted, maybe not now.

**Comment by numerology** [comment]
> What's the purpose of removing user-gcp-sa?
> I don't know full context here.

#2394 introduces a new way to inject service account after deployment, which is simpler than the one based on `kubectl apply`. However the user needs to first delete the secret then create a new one, which is a bit of cumbersome. By not creating user-gcp-sa from the very beginning, the user only needs to run `kubectl create secret`. And actually, the deployment itself, together with the four simple pre-load sample actually does not require user-gcp-sa.

**Comment by rmgogogo** [comment]
Thanks Jiaxiao, since I just finish another g3 task, here have a breath to continue this.
Sorry for late reply.

I just refreshed the design doc and made a slide easy for review. We still need it in mode-1 for user workload (more for usage measurement, not for security). However we can remove ADC from system workload e.x. CloudSQLProxy etc.

**Comment by numerology** [comment]
/close
stale PR

**Pull request closed without merging**
