### PR TITLE
Backend - Removed Tensorflow from backend WORKSPACE

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/kubeflow/pipelines/issues/2468

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2856)

### CODE REVIEW

**Comment by rmgogogo** [comment]
Thanks Alexy, didn't aware you already have this PR.

**Comment by Ark-kun** [comment]
@IronPan @neuromage Can you please approve this old PR?

**Comment by rmgogogo** [comment]
Awesome change!!!
Jing and I will follow up https://github.com/kubeflow/pipelines/issues/3061 to do more clean up.

**Pull request merged**
