### PR TITLE
fix(metadata envoy): upgrade envoy and config from 1.12 to 1.27

### LINKED ISSUE #10578: [feature] upgrade metadata envoy
### What feature would you like to see?

upgrade envoy (and config version) to a supported version

### What is the use case or pain point?

envoy 1.12 is no longer supported or patched

### Is there a workaround currently?

I've created my own image for now using 1.27. I can make a PR but I don't know enough about kfp to know how to validate that I didn't break anything

---

Love this idea? Give it a 👍.

### PR DESCRIPTION
**Pull request by freefood89**
**Description of your changes:**
Upgrades envoy metadata proxy from 1.12 to 1.27 since 1.12 is no longer supported and is not receiving patches. I chose 1.27 because it's the version supported by the istio version I am using [istio docs](https://istio.io/latest/docs/releases/supported-releases/#supported-envoy-versions)

This is my first PR here! I might need some help validating that this doesn't break anything.

closes #10578 

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by freefood89** [comment]
As suggested by @rimolive I navigated to Executions, Artifacts, and then Lineage in Artifacts and I see no errors in the console or network tab of chrome dev tools. The run I used was "[Tutorial] DSL - Control structures"

The kubeflow I'm using is 1.8 deployed using [kubeflow/manifests](https://github.com/kubeflow/manifests)

**Comment by rimolive** [comment]
Thank you for your contribution @freefood89 !

/ok-to-test

**Comment by thesuperzapper** [comment]
This seems reasonable, and will help with the effort to make native ARM64 images:
 - https://github.com/kubeflow/pipelines/issues/10309

The old `envoyproxy/envoy:v1.12.2` tag does not have an ARM64 variant, but the new `envoyproxy/envoy:v1.27.3` one does.


/lgtm

**Review by chensun — APPROVED** [review]

**Pull request merged**
