### PR TITLE
fix(ui): fixes cron format go.doc link. Fixes #6068

### LINKED ISSUE #6068: [frontend] go.doc cron link not working properly
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

Following the Kubeflow v1.2 documentation for GCP: https://v1-2-branch.kubeflow.org/docs/distributions/gke/

*  KFP version: 1.0.4

### Steps to reproduce

- Access the `Experiments` page and click on the `+ Create run` button.
- Select `Run Type` -> `Recurring`.
- Set `Run Trigger` -> `Trigger type` to `Cron`.
- It will show a link to the cron expression format:
image
- Click the `here` link and it shows the following result:
image

### Expected result

I would expect to properly load [this doc page](https://pkg.go.dev/github.com/robfig/cron?utm_source=godoc#hdr-CRON_Expression_Format).

### Materials and Reference

I'm not a frontend developer so I'm not sure what is happening but I believe it is not redirecting/rendering the page properly, maybe because of the Shadow DOM!?

Also, a suggestion would be to include a `target="_blank"` to the `a` tag. 

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by kelvins**
**Description of your changes:**

- Add `target='_blank'` to the `a` tag.
- Also include `rel='noreferrer'` because of a secure risk: https://html.spec.whatwg.org/multipage/links.html#link-type-noopener
- Update snapshot with `npm test -u`.
- Fix issue https://github.com/kubeflow/pipelines/issues/6068.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by kelvins** [comment]
@googlebot I fixed it.

**Comment by zijianjoy** [comment]
@kelvins Thanks for the PR. I am wondering if this PR actually fixes the issue you are encountering. 

From the screenshot of the issue, looks like pkg.go.dev refused the connection. Maybe it is because a temporary service down? I tried to reproduce the issue but didn't encounter problem opening the link. (I used Chrome and Safari on MacOS)

Would you like to give it another try if the issue exists? If not, would you like to confirm this PR fixes your issue?

**Comment by kelvins** [comment]
Hello @zijianjoy, thanks for the review.

When I open the link in a new tab it is loading correctly, so I don't think it's a temporary service down. In fact, it looks like the page isn't being rendering inside the Kubeflow.

I also tested it by inspecting the page HTML and editing the `a` tag to include the `target="_blank"` and it solved the issue (since the page is opened in a new tab).

Furthermore, IMO it make sense to open this kind of link in a new tab since it is an "external" link, not related to the Kubeflow itself.

**Comment by Bobgy** [comment]
Jfyijust FYI, KFP UI has an ExternalLink component that embeds the same best practices.

Shall we use the existing component instead?

**Comment by kelvins** [comment]
Thanks for the review @Bobgy.

I changed it to use the ExternalLink component and removed an unnecessary whitespace before "format".

Can you guys please take a second look to make sure I used the component correctly?

**Comment by Bobgy** [comment]
/lgtm

Cc @zijianjoy

**Comment by zijianjoy** [comment]
/lgtm
/approve

Thank you both for the inputs, and thank you @kelvins for the change!

**Pull request merged**
