### PR TITLE
Update test directory OWNERS

### PR DESCRIPTION
**Pull request by yebrahim**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/240)

### CODE REVIEW

**Comment by vicaire** [comment]
There are ownership files in the subdirectories. Could you please justify the need for ownership at the top level? Thanks.

**Comment by yebrahim** [comment]
I think the entire team should have OWNERs over the root level files. .gitignore, .travis.yml, .dockerignore, README, and developer_guide are all files that every one of us has touched.

This specific instance I was fixing the README badges.

**Comment by vicaire** [comment]
Let's limit OWNERs at the top level of the test directory to a few folks. I think the current set is enough and will be able to approve PRs. The robot uses the OWNER file hierarchy to allocate reviewers. OWNERs at the top level get lgtm/approval permissions to all the subdirectories. Thanks.

**Pull request closed without merging**
