### PR TITLE
feat(sdk): add support for dynamic importer metadata in sdk v1

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Implements #7660 in v1

**Checklist:**
- [x] The title for your pull request (PR) should follow our title 
convention. 
[Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Ark-kun** [comment]
/lgtm

P.S. I wonder whether importer can just be a normal component.
```python
def import(uri: str, artifact_type: str, metadata: dict):
```

**Comment by chensun** [comment]
> /lgtm
> 
> P.S. I wonder whether importer can just be a normal component.
> 
> ```python
> def import(uri: str, artifact_type: str, metadata: dict):
> ```
> 
> P.P.S. One issue with importers is that the artifacts they create are a leaky abstraction. If you use importer on a HTTP URL or an AWS S3 URL, the pipeline will fail to work. Instead of such shallow importer I use explicit importers/downloaders: , `Download from Web`, `Download from GCS`, `Download from AWS S3`, `Download from IPFS` etc

I too prefer importer to be a normal component. But I guess it requires some metadata API not exposed to end users?

**Review by chensun — COMMENTED** [review]
/lgtm

**Pull request merged**
