### PR TITLE
fix(frontend): fixes flaky tests in CompareV2 resulting in false failures in PRs. Fixes #10811

### LINKED ISSUE #10811: [frontend] Flaky tests in CompareV2 resulting in false failures in PRs
Tests in CompareV2.test.tsx seem to be very Flaky, and keep resulting in random failures in PRs, I constantly have to re-run these tests to get it fully passing. Some examples of failure errors I've seen: 

<details>

<summary>failures.1</summary>

```txt
Summary of all failing tests

FAIL src/pages/CompareV2.test.tsx (91.424 s)

● CompareV2 › Parameters and Scalar metrics tab initially enabled with loading then error, and switch tabs

thrown: "Exceeded timeout of 5000 ms for a test.

Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

410 | });

411 |

> 412 | it('Parameters and Scalar metrics tab initially enabled with loading then error, and switch tabs', async () => {

| ^

413 | const getRunSpy = jest.spyOn(Apis.runServiceApiV2, 'getRun');

414 | runs = [newMockRun(MOCK_RUN_1_ID), newMockRun(MOCK_RUN_2_ID), newMockRun(MOCK_RUN_3_ID)];

415 | getRunSpy.mockImplementation((id: string) => runs.find(r => r.run_id === id));

at src/pages/CompareV2.test.tsx:412:3

at Object.<anonymous> (src/pages/CompareV2.test.tsx:34:1)

Test Suites: 1 failed, 113 passed, 114 total

Tests: 1 failed, 1611 passed, 1612 total

Snapshots: 427 passed, 427 total

Time: 238.994 s

````

</details>

<details>

<summary>failures.2</summary>

```txt
● CompareV2 › Parameters and Scalar metrics tab initially enabled with loading then error, and switch tabs

Unable to find an element with the text: An error is preventing the Scalar Metrics from being displayed.. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

<body>
....
OMITTED
....

426 | screen.getByText('There are no Parameters available on the selected runs.');

427 | screen.getByText('An error is preventing the Scalar Metrics from being displayed.');

428 |

at waitForWrapper (node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/wait-for.js:173:27)

at Object.<anonymous> (src/pages/CompareV2.test.tsx:425:18)

````

</details>

Examples:

* [Example 1 ](https://github.com/kubeflow/pipelines/pull/10794#issuecomment-2096930178)
* [Example 2](https://github.com/kubeflow/pipelines/pull/10787#issuecomment-2102865888)

---

Love this idea? Give it a 👍.

### PR DESCRIPTION
**Pull request by ElayAharoni**
fixes https://github.com/kubeflow/pipelines/issues/10884.

first trying to see all the flaky tests.

### CODE REVIEW

**Comment by hbelmiro** [comment]
@ElayAharoni please [link the PR to the issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by hbelmiro** [comment]
@HumairAK do you feel like we can close https://github.com/kubeflow/pipelines/issues/10884?

**Comment by ElayAharoni** [comment]
@HumairAK , @hbelmiro , what do you think? can we close the issue?

**Pull request closed without merging**
