### PR TITLE
feat(sdk): Uses 'https' as the default host protocol if users didn't specify any.

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
Part of https://github.com/kubeflow/pipelines/issues/5230.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [x] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by Bobgy** [comment]
This is a breaking change though...

Previously, it was possible to use `localhost:3000`.

So I'd suggest at least marking this as a feature.

**Comment by chensun** [comment]
> This is a breaking change though...
> 
> Previously, it was possible to use `localhost:3000`.
> 
> So I'd suggest at least marking this as a feature, so that it's not hidden from the changelog.

Makes sense. Updated the title.

**Comment by Bobgy** [comment]
/lgtm
/hold
To let you decide when to merge

**Comment by chensun** [comment]
> /lgtm
> /hold
> To let you decide when to merge

Thanks! 

/unhold

**Pull request merged**
