### PR TITLE
fix(components/pytorch): custom handler for cifar10, saves explain output as bytes image

### PR DESCRIPTION
**Pull request by shrinath-suresh**
Signed-off-by: Shrinath Suresh <shrinath@ideas2it.com>

This PR adds a custom handler for the cifar10 example, which saves explain output as a bytes image inside the get_insight function

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by shrinath-suresh** [comment]
image
image

**Review by chauhang — APPROVED** [review]

**Pull request merged**
