### PR TITLE
Remove pinning avro-python3, because it is already fixed

### PR DESCRIPTION
**Pull request by Bobgy**
/assign @numerology 
Reference, avro-python3 issue is already fixed in https://issues.apache.org/jira/browse/AVRO-2737

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3096)

### CODE REVIEW

**Comment by numerology** [comment]
/retest
/lgtm
/approve

Thanks! @Bobgy

**Comment by Bobgy** [comment]
@numerology thank you
@IronPan can I get approval for this?

**Pull request merged**
