### PR TITLE
fix(sdk): removed duplicate function. Fixes #6586

### LINKED ISSUE #6586: Potentially duplicated function list_pipeline_versions()?
Seems like there are two versions of this function within the same module:

https://github.com/kubeflow/pipelines/blob/7875b68654a69ca761cb0ba4a920a30925a0e94b/sdk/python/kfp/_client.py#L661

https://github.com/kubeflow/pipelines/blob/7875b68654a69ca761cb0ba4a920a30925a0e94b/sdk/python/kfp/_client.py#L1324

Should one of these be deprecated/removed/renamed?

### PR DESCRIPTION
**Pull request by KausthubK**
**Description of your changes:**
Removed duplicate fn as recommended by upstream issue [#6586](https://github.com/kubeflow/pipelines/issues/6586) 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
Hi @KausthubK, can you please add an entry in the release note under "Current version": https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md

**Comment by KausthubK** [comment]
> Hi @KausthubK, can you please add an entry in the release note under "Current version": https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md

Done.

**Comment by chensun** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
