### PR TITLE
chore(sdk1.8): cherry pick (#7453)

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Cherry picks #7453

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by ji-yaqi** [comment]
/lgtm

Thanks! 
/test kubeflow-pipelines-samples-v2

**Comment by ji-yaqi** [comment]
Sample test failed since there are no backend/src/v2 in this branch (but exist in main branch). Shall we maybe add back v2 folders here? 

cc @chensun

**Comment by chensun** [comment]
> Sample test failed since there are no backend/src/v2 in this branch (but exist in main branch). Shall we maybe add back v2 folders here?
> 
> cc @chensun

That would require cherry-picking https://github.com/kubeflow/pipelines/commit/1b107eb4bb2510ecb99fd5f4fb438cbf7c96a87a into this branch, likely quite some merge conflicts to resolve. So I would probably avoid that hassle and ignore the test failure here, since the "same" change has been tested on master branch, and we don't do such cherrypick quite often.

**Comment by chensun** [comment]
/approve
/lgtm

Thanks, Connor!

**Pull request merged**
