### PR TITLE
Add a simple TFX Taxi sample.

### PR DESCRIPTION
**Pull request by neuromage**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2312)

### CODE REVIEW

**Comment by animeshsingh** [comment]
@neuromage what is needed to run this? do we need to create GCP account? Or it can solely out of open source components?

**Comment by numerology** [comment]
> Seems the name is bit confusing here? It's called tfx-oss, and the components have dependency on GCP?

Hi @animeshsingh , @neuromage  and I discussed offline about how to make a parameterized TFX sample so that user can run it using their own GCS bucket easily. Please refer to #2319 . The only thing which is GCP specific here is the GCS storage used. 

I think this PR is more or less demonstrative purpose. @neuromage would like to give me a TFX pipeline that runs very fast so that I can work on it.

**Comment by neuromage** [comment]
@animeshsingh The components have no dependency on GCP. The output directory in the sample is a GCS bucket but could well be some other bucket which is supported by tf.io.gfile (since that's the IO library used by TFX components).

**Comment by gaoning777** [comment]
Currently the backend is compiling all the python files in the depth of two from the samples directory, which doesn't work for this sample. 
BTW, thanks for creating this simple tfx sample and it is not gcp specific.

**Comment by animeshsingh** [comment]
@gaoning777 did you find a woraround?

**Comment by numerology** [comment]
> @gaoning777 did you find a woraround?

#2319 is in. That one works fine, but still, compiling it requires some tweak, which was documented in the README.md

**Comment by numerology** [comment]
/close
for the current TFX sample works well. Thanks @neuromage

**Pull request closed without merging**
