### PR TITLE
[Frontend] Check format in travis CI

### PR DESCRIPTION
**Pull request by Bobgy**
Provides an error message like the following if test failed
```
Checking formatting...
src/Css.tsx
Code style issues found in the above file(s). Forgot to run Prettier?

=================
Please use `npm run format` to format your code.
Refer to https://github.com/kubeflow/pipelines/tree/master/frontend#code-style for our code style guidance.
```

/area front-end
/kind code-quality

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2463)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Is it possible to include some an IDE config, so that IDEs like VS Code automatically formatted the code?

**Comment by Bobgy** [comment]
@Ark-kun Already checked in, see https://github.com/kubeflow/pipelines/blob/master/frontend/README.md#code-style

**Pull request merged**
