### PR TITLE
feat(sdk/client): add cookie configuration to kfp client

### PR DESCRIPTION
**Pull request by prcastro**
We are using cookies for authentication, and the only requirement is being able to instantiate `ApiServer` with a cookie. To do that, we add a `cookie` optional argument to `Client` class and use that when instantiating the `api_server` object.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2679)

### CODE REVIEW

**Comment by prcastro** [comment]
@googlebot I signed it!

**Comment by steviecash** [comment]
I would like to give a gentle nudge on this merge request. I am using Kubeflow with DEX authentication and have to provide the session ID via cookies in order to manage pipelines outside of the Kubeflow cluster.

This simple fix would solve our problems completely.

**Comment by Bobgy** [comment]
/cc @Ark-kun @numerology @rmgogogo 
/cc @maganaluis
Any ideas? Can this potentially address https://github.com/kubeflow/kubeflow/issues/4912?

**Comment by Bobgy** [comment]
/cc @numerology @rmgogogo @Ark-kun 

Can this potentially solve https://github.com/kubeflow/kubeflow/issues/4912?
/cc @maganaluis

**Comment by maganaluis** [comment]
@Bobgy I confirmed this solves the issue with multi-user authentication, though I would label this a workaround, you need a separate package or process to obtain the cookie and renew it.

The code looks like this, and it can work in-cluster and locally. 

```python
import kfp
import kfp.components as comp
cookie = "_xsrf=2|1385654d|cf4d12a793965eae032a0d7fbaebbb63|1592765448; authservice_session=<secret>"
client = kfp.Client(host="example.com/pipeline", cookie=cookie)
client.create_experiment("test", namespace="projectxyz")
```

**Comment by Bobgy** [comment]
/ok-to-test
/assign @rmgogogo @numerology 
Do you want to review?

/lgtm
I'm okay with this change.

@maganaluis 
Can the extra process be generic for dex? We'd welcome such a contribution.

**Comment by Bobgy** [comment]
Edited title to match new title convention.

**Comment by Bobgy** [comment]
/lgtm
@numerology @Ark-kun Can you help me review this PR?

**Comment by Bobgy** [comment]
also
/assign @rmgogogo

**Comment by numerology** [comment]
/lgtm
/approve

Thanks!

**Comment by rmgogogo** [comment]
I'm wondering whether directly passing cookie value in SDK interface is a good way. However as long as it can solve your problem, SG.

quick check: how you get the cookie value? Is it manually via copy from browser?
@prcastro

**Comment by gabrielvcbessa** [comment]
@rmgogogo We use [browsercookie](https://pypi.org/project/browsercookie/)

**Pull request merged**
