### PR TITLE
Add Visualization Server to Cloud Build yaml Files

### PR DESCRIPTION
**Pull request by ajchili**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1738)

### CODE REVIEW

**Comment by IronPan** [comment]
the sample tests failure should be irrelavent.

**Comment by ajchili** [comment]
/hold
Need to test docker build command with pymongo dependency

**Comment by ajchili** [comment]
/hold cancel
Fixed docker build issue caused by pymongo dependency

**Pull request merged**
