### PR TITLE
update owners file

### PR DESCRIPTION
**Pull request by animeshsingh**
multiple sample being requested to review and approve. And have been reviewing them for more than a year now.

### CODE REVIEW

**Comment by Bobgy** [comment]
Can you point to which samples?
Does it make sense moving those samples to a lower level folder and grant OWNERS there?

**Comment by animeshsingh** [comment]
@Bobgy there is already a PR pending on KFServing and Seldon samples. Key is we can keep on going granular, or you need to be gatekeeper for every sample coming in?

**Comment by neuromage** [comment]
@animeshsingh I think we can have an OWNERS file for the contrib directory if needed instead. Will that help?

**Comment by animeshsingh** [comment]
@neuromage yes that will be great!

**Comment by neuromage** [comment]
Thanks @animeshsingh. I think the only  difference is that samples under core are tested as part of our Prow tests `kubeflow-pipeline-sample-test`. Do you want to go ahead an update this PR with an OWNERS file in contrib instead? Thanks!

**Comment by animeshsingh** [comment]
ok done @neuromage

**Comment by numerology** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
