### PR TITLE
Update default workflow ttl to 7 days after finish

### PR DESCRIPTION
**Pull request by hongye-sun**
This PR is to prevent accumulated workflows over time to slow down persistent agent and API services.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1723)

### CODE REVIEW

**Comment by Ark-kun** [comment]
What do you think about setting this property in backend? Do you think this property should be exposed to the pipeline authors?

**Comment by hongye-sun** [comment]
This setting has already been exposed to the pipeline author today. The PR is to add a default value to avoid the workflow to be accumulated infinitely.

**Comment by IronPan** [comment]
/hold
@hongye-sun with this change do you think we could close this PR https://github.com/kubeflow/pipelines/pull/1802/files

**Comment by hongye-sun** [comment]
No longer needed with PR https://github.com/kubeflow/pipelines/pull/1802

**Pull request closed without merging**
