### PR TITLE
chore(sdk): rename PipelineTask arguments parameter to args

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Renames `PipelineTask` `arguments` parameter to `args` to be consistent with #7391.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
/lgtm

Note that this class isn't user facing, thus changing the title to `chore`.

**Comment by ji-yaqi** [comment]
/lgtm
/approve
Thanks @connor-mccarthy!

**Pull request merged**
