### PR TITLE
fix(sdk)Remove unnecessary errors for dependencies on task groups

### PR DESCRIPTION
**Pull request by tristan-vt**
**Description of your changes:**
Some runtime errors were blocking end users to set dependencies on tasks within task groups. Removing these checks leads to the expected behaviour where a dependency on a task in a TaskGroup is replaced with a dependency on the TaskGroup on the same level as the current task.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by tristan-vt** [comment]
Sure!

Here is a small example based on the static loop sample:
```
from kfp import dsl, compiler
from typing import List


@dsl.component
def print_op(text: str) -> str:
    print(text)
    return text


@dsl.component
def concat_op(a: str, b: str) -> str:
    print(a + b)
    return a + b


_DEFAULT_LOOP_ARGUMENTS = [{'a': '1', 'b': '2'}, {'a': '10', 'b': '20'}]


@dsl.pipeline(name='pipeline-dependency-loop')
def my_pipeline(
    static_loop_arguments: List[dict] = _DEFAULT_LOOP_ARGUMENTS,
):
    print_task = print_op(text="Hello")

    with dsl.ParallelFor(static_loop_arguments) as item:
        concat_task = concat_op(a=item.a, b=item.b)
        concat_task.after(print_task)
        print_task_2 = print_op(text=concat_task.output)

    print_task_3 = print_op(text="DONE").after(print_task_2)


if __name__ == "__main__":
    compiler.Compiler().compile(
        pipeline_func=my_pipeline,
        package_path="pipeline.yaml",
    )

```

Before the fix, you would get an error saying:
```
ValueError: Cannot use .after() across inner pipelines or DSL control flow features. Tried to set concat-op after print-op, but these tasks do not belong to the same pipeline or are not enclosed in the same control flow content manager.
```

This means there is no way for me to put a dependency for a PipelineTask on a TaskGroup. Actually the above sample was working for older versions of kfp. By removing the errors that are being thrown, we get the expected behaviour, which is that the task print_task_3 will actually have a dependency on the entire ParallelFor. This is because of the [get_dependencies](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler/compiler.py#L568) function in the compiler which takes care of finding the first uncommon ancestor between each task and then switching over the dependency to the whole loop instead of just the task.

I do agree that this behaviour could be quite a bit more transparent though. Ideally we would probably just want users to be able to explicitely reference task groups in dependencies, but I think this requires a bit more rework and it would probably be a good idea to then also include a good way to access outputs of each task in a taskgroup. However, that is not in scope for this PR.

**Comment by connor-mccarthy** [comment]
@tristan-vt, thanks so much for catching this, explaining, and suggesting a fix. I agree -- we want to enable ordering of tasks and subdags (such as `dsl.ParallelFor`) within a pipeline.

> I do agree that this behaviour could be quite a bit more transparent though.

Definitely. While the compiler logic makes sense to me, the authoring style in the example makes the behavior somewhat ambiguous (after which for loop iteration should the downstream task execute? the first? the last?).

We will soon have support for using a pipeline in a pipeline (pipeline as a component/task). Wrapping a `dsl.ParallelFor` group in another pipeline function then placing a dependency on the upstream pipeline might enable a less ambiguous authoring syntax, at the cost of a slightly more constrained authoring style. What do you think?

While this probably needs some more discussion, I want to point out that the suggested fix in `pipeline_task.py` would introduce some extra ambiguity for `dsl.Condition` groups: what should the behavior be if there is an `.after` dependency on task in a condition group where the condition resolves to false?

/cc @chensun

**Review by connor-mccarthy — COMMENTED** [review]
@tristan-vt, thanks so much for catching this, explaining, and suggesting a fix. I agree -- we want to enable ordering of tasks and subdags (such as `dsl.ParallelFor`) within a pipeline.

> I do agree that this behaviour could be quite a bit more transparent though.

Definitely. While the compiler logic makes sense to me, the authoring style in the example makes the behavior somewhat ambiguous (after which for loop iteration should the downstream task execute? the first? the last?).

We will soon have support for using a pipeline in a pipeline (pipeline as a component/task). Wrapping a `dsl.ParallelFor` group in another pipeline function then placing a dependency on the upstream pipeline might enable a less ambiguous authoring syntax, at the cost of a slightly more constrained authoring style. What do you think?

While this probably needs some more discussion, I want to point out that the suggested fix in `pipeline_task.py` would introduce some extra ambiguity for `dsl.Condition` groups: what should the behavior be if there is an `.after` dependency on task in a condition group where the condition resolves to false?

/cc @chensun

**Comment by tristan-vt** [comment]
> placing a dependency on the upstream pipeline might enable a less ambiguous authoring syntax, at the cost of a slightly more constrained authoring style. What do you think?

Yes that would already be better indeed. Ideally I think a TaskGroup and a PipelineTask should both just share a super class that serves as an interface for a PipelineComponent (?) which can serve as a part of a pipeline and can be referenced in the after(). This also seems to be the way it is already represented in the YAML format.

> the suggested fix in pipeline_task.py would introduce some extra ambiguity for dsl.Condition groups: what should the behavior be if there is an .after dependency on task in a condition group where the condition resolves to false?

Gave this a quick test and did not get what I would have expected. Test pipeline:

```
@dsl.component
def print_op(text: str) -> str:
    print(text)
    return text


@dsl.component
def concat_op(a: str, b: str) -> str:
    print(a + b)
    return a + b


@dsl.component
def heads_op() -> str:
    return "heads"


_DEFAULT_LOOP_ARGUMENTS = [{'a': '1', 'b': '2'}, {'a': '10', 'b': '20'}]


@dsl.pipeline(name='pipeline-conditional-dependency')
def my_pipeline(
    static_loop_arguments: List[dict] = _DEFAULT_LOOP_ARGUMENTS,
):
    print_task = print_op(text="Hello")
    heads = heads_op()

    with dsl.Condition(heads.output == 'heads'): # Will evaluate to true, change to evaluate to false
        print_task_2 = print_op(text="In Condition").after(print_task)

    print_task_3 = print_op(text="DONE").after(print_task_2)
```

When the condition evaluates to True, then **print_task_3** is executed as expected. When it evaluates to False, **print_task_3** is skipped, which to me seems to not be what I would expect. **print_task_3** is no longer part of the conditional and therefore should be executed regardless of the result of the conditional and the tasks contained within. What do you think?

**Comment by connor-mccarthy** [comment]
@tristan-vt, that example demonstrates the ambiguity/problem very well.

If `print_task_3` can only run after `print_task2` and `print_task2` can only run if the condition evaluates to `True`, then there is less ambiguity of behavior if `print_task_3` is included in the same `dsl.Condition` scope. This is the permitted authoring style currently while the current example raises an exception.

The logic in this pipeline that is not currently supported is `print_task2`'s dependency on `print_task`, even though it's a reasonable thing to want to author. Currently, we've blocked all cross-DAG (a control flow context is considered a sub-DAG) dependencies, since some of them would not make sense from the perspective of typical programming control flow and we want to help users avoid anti-patterns. It is definitely possibly to add more granularity to this instead of blocking _all_ cross-DAG dependencies, but let's wait for the implementation of pipelines as a components (#8179), as I suspect this will resolve a substantial number of these problems.

**Pull request closed without merging**
