### PR TITLE
 Add component_sdk tests to travis tests

### PR DESCRIPTION
**Pull request by hongye-sun**
Same as https://github.com/kubeflow/pipelines/pull/752

I accidentally closed the original one.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/761)

### CODE REVIEW

**Comment by Ark-kun** [comment]
> I accidentally closed the original one.

Usually you can "/reopen" closed pull requests...

**Comment by hongye-sun** [comment]
Ah, didn't know that. Will try it next time. Thanks.

**Pull request merged**
