### PR TITLE
update sample tfx taxi to meet PR #823 changes

### PR DESCRIPTION
**Pull request by jinchihe**
In the PR #823 , we updated the deploy.sh to enhance hard code, the PR is to update sample TFX taxi to meet the #823 changes.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/843)

### CODE REVIEW

**Comment by gaoning777** [comment]
Thanks for separating these two PRs.
However, the image tag also needs to be updated. The pipeline team usually release all images at once and update all image tags for all samples to keep them consistent. 

Since I do not want to see the samples to fail at any point. Do you mind me sending a PR to include all the image tag update as well as your sample code change(deployer model-path param)?

**Comment by jinchihe** [comment]
> Thanks for separating these two PRs.
> However, the image tag also needs to be updated. The pipeline team usually release all images at once and update all image tags for all samples to keep them consistent.
> 
> Since I do not want to see the samples to fail at any point. Do you mind me sending a PR to include all the image tag update as well as your sample code change(deployer model-path param)?

Understood. I don't mind and that's my pleasure :-) Thank you! @gaoning777

**Comment by gaoning777** [comment]
Thanks, I have included the changes in this PR: https://github.com/kubeflow/pipelines/pull/849

**Comment by jinchihe** [comment]
> Thanks, I have included the changes in this PR: #849

@gaoning777 Thanks. I'm going to close the PR.

**Pull request closed without merging**
