### PR TITLE
SDK - Compiler - Removed the deprecated dsl-compile --package command

### PR DESCRIPTION
**Pull request by Ark-kun**

### CODE REVIEW

**Comment by Bobgy** [comment]
Shall we cherry pick this to 1.0 branch? It seems to be a breaking change, although we deprecated it a long time ago.

**Comment by Ark-kun** [comment]
> Shall we cherry pick this to 1.0 branch? It seems to be a breaking change, although we deprecated it a long time ago.

I think so. Thank you for reminding that the SDK canges need to be cherry-picked as well.

**Comment by Bobgy** [comment]
@Ark-kun Can you please resolve conflicts?
As we are targeting 1.0 release.

**Comment by Bobgy** [comment]
Thanks @Ark-kun !

/lgtm
/approve

**Pull request merged**
