### PR TITLE
feat(backend): enforce SA Token based auth b/w Persistence Agent and Pipeline API Server

### PR DESCRIPTION
**Pull request by difince**
Fixes: https://github.com/kubeflow/pipelines/issues/9937

Enforce Service Account(SA) Token-based auth between the Persistence Agent and the Pipeline API Server for all the requests.
SA Token auth has already been introduced and applied for  `ReportWorkflow` and `ReportScheduledWorkflow` by [this](https://github.com/kubeflow/pipelines/pull/9699) PR. 

Current PR enforces the SA token authentication for `readArtifacts` and `ReportMetrics` calls as well, which currently authenticates as a user. 
  
**Description of your changes:**

This PR :
- reverts changes done by [this](https://github.com/kubeflow/pipelines/pull/7819) PR
- Enforce the use the SA token authentiaction

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by difince** [comment]
Can someone help me with the failing test - `TestCreatePipelineV1_LargeFile`  ?

**Review by difince — COMMENTED** [review]
To simplify the review process, the changes in pipelines_client.go  `ReadArtifact` and `ReportRunMetrics` are the most meaningful ones. Here, the PA is forced to use SA Token, instead of authenticating as a user.

**Comment by chensun** [comment]
> Can someone help me with the failing test - `TestCreatePipelineV1_LargeFile` ?

Seems like it could be some transient issue?
```
```

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks!

**Pull request merged**
