### PR TITLE
revert kfp-cache from Hosted/MKP

### PR DESCRIPTION
**Pull request by rmgogogo**

### CODE REVIEW

**Comment by Bobgy** [comment]
/lgtm
/cc @rui5i 
Postsubmit tests are failing.
@rmgogogo Can you schedule a time to sync with @rui5i about suggestions for next step (I'm still not clear what was the root cause)?
@rui5i Before you can get this working with mkp, would it be fine if you start verifying the feature for kfp standalone.

**Comment by rui5i** [comment]
Ack. Will do that. Thanks!

**Comment by rmgogogo** [comment]
as synced with Rui, let's put it to Standalone CLI manifest to let it run well first. That path is much cheap to debug issues comparing with MKP/Hosted path.

I will submit this PR today to unlock others to make sure all PR got well tested for MKP.

**Pull request merged**
