### PR TITLE
fix(backend): Add default values to timestamps. Fixes #8845

### LINKED ISSUE #8845: [backend] InternalServerError: Failed to list tasks: sql: Scan error on column index 6, name "StartedTimestamp"
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
standalone

*  KFP version: 
2.0.0-beta.0

*  KFP SDK version: 
N/A

### Steps to reproduce

Run pipeline: https://github.com/kubeflow/pipelines/blob/master/samples/v2/pipeline_container_no_input.py

or find it run result from sdk-execution-test, e.g.: https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/8841/kubeflow-pipelines-sdk-execution-tests/1625208635669876736

Pipeline fails with pod error log:

```
I0213 19:00:39.519690      17 main.go:213] output ExecutorInput:{
  "inputs": {},
  "outputs": {
    "outputFile": "/tmp/kfp_outputs/output_metadata.json"
  }
}
F0213 19:00:39.519796      17 main.go:74] KFP driver: driver.Container(pipelineName=v2-container-component-no-input, runID=7cf802c0-d725-4eb2-b18d-ff22f8d4b112, task="hello-world-container", component="comp-hello-world-container", dagExecutionID=133285, componentSpec) failed: failure while getting executionCache: failed to list tasks: rpc error: code = Internal desc = List tasks failed: Failed to list tasks: InternalServerError: Failed to list tasks: sql: Scan error on column index 6, name "StartedTimestamp": converting NULL to int64 is unsupported: sql: Scan error on column index 6, name "StartedTimestamp": converting NULL to int64 is unsupported
```

### Expected result

No error, pipeline should succeed.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by gkcalat**
**Description of your changes:**

- Added default values (int64:0) to timestamps in the backend DB

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by gkcalat** [comment]
Fixes #8845

**Review by chensun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
