### PR TITLE
test: Migrate Frontend tests to a GHA Workflow 

### PR DESCRIPTION
**Pull request by DharmitD**
**Description of your changes:**
Resolves https://github.com/kubeflow/pipelines/issues/10879

Converts the Prow frontend test to a GH Action Workflow.

Here's a working GH Action run on my fork: https://github.com/DharmitD/data-science-pipelines-argo/actions/runs/9525123655/job/26258863870

PR to remove the frontend test from prow config: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2302

PR to remove frontend files not required anymore: https://github.com/kubeflow/pipelines/pull/10973

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Review by hbelmiro — APPROVED** [review]
/lgtm

**Comment by hbelmiro** [comment]
@jlyaoyuli @zijianjoy we still need approval from one of you guys.

cc @DharmitD

**Comment by DharmitD** [comment]
> @jlyaoyuli @zijianjoy we still need approval from one of you guys.
> 
> cc @DharmitD

@hbelmiro I added the removal of frontend files to a separate PR: https://github.com/kubeflow/pipelines/pull/1097
cc: @jlyaoyuli @zijianjoy

**Pull request merged**
