### PR TITLE
Add proxy agent as optional kustomize component

### PR DESCRIPTION
**Pull request by IronPan**
Proxy agent is added as an optional component for user to access KFP. 
For more details how to use proxy agent, see the updated readme.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1325)

### CODE REVIEW

**Comment by Ark-kun** [comment]
It looks like you're doing more than just adding the proxy kustomize component here. Some stray changes?

**Comment by ojarjur** [comment]
The proxy-agent bits look good to me, but I will echo Alexey's comment about the seemingly unrelated file deletions that should be a different PR

**Comment by IronPan** [comment]
done. sorry it was based on a wrong branch.

**Pull request merged**
