### PR TITLE
fix(backend): Revert API Generator update and regenerate backend API Proto and Swagger files

### LINKED ISSUE #10630: [backend] API updates for v2.1.0 release causing CI/Unit Test failures
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? N/A
*  KFP version: 2.1.0
*  KFP SDK version: 2.7.0

### Steps to reproduce
For one, `go test -v ./backend/...` produces many compile errors

### Expected result
Unit tests should not fail due to compilation errors

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by gmfrasca**
**Description of your changes:**
Reverts Backend API-Generator updates for v2.1.0 release, which was causing API mismatches and CI/unit test compilation errors 

Fixes #10630 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by Tomcli — COMMENTED** [review]
/ok-to-test
/cc @chensun

**Comment by chensun** [comment]
/hold

Sorry, I'm late to this conversation. First question I would ask: is 2.1.0 a bad release--has anyone tried and discovered any functionality break? I did a very preliminary test of deploying standalone KFP and triggerring a run, yet I didn't notice anything wrong. 

If 2.1.0 is indeed a bad release, there's probably a number of high priority action items to prevent the break spread to more users. 
If it's not, then I think we should forward fix the broken tests instead of rolling back the API generator update, because that's a change we would need anyway in the future. I don't think there's urgency in unblock presubmit to merge more PRs if they would sit in the repro not releasable.

**Comment by chensun** [comment]
@gmfrasca @Tomcli if you could take a look what's needed to fix the test, that would be great. Otherwise, I'll probably find some time in the upcoming weekend to take a look myself (sorry that I have a very busy schedule this week).

**Comment by rimolive** [comment]
@chensun The tests aren't breaking because of a funcional test, it's because the references has changed and the code is wrong. An example: https://github.com/kubeflow/pipelines/blob/master/backend/src/common/client/api_server/v2/experiment_client.go#L32

If you look at the reference, you will see that it's not the same:

https://github.com/kubeflow/pipelines/blob/master/backend/api/v2beta1/go_http_client/experiment_client/experiment_service/experiment_service_create_experiment_parameters.go#L64

**Comment by rimolive** [comment]
On another note: How to test if KFP 2.1.0 works? I'm asking that because the latest change in [SDK requirements.txt ](https://github.com/kubeflow/pipelines/blob/master/sdk/python/requirements.in#L19) does not allow to install with the latest kfp-server-api package. 

cc @connor-mccarthy

**Comment by Tomcli** [comment]
@chensun Functional wise 2.1.0 release works for me. However, many of my colleagues's PR is failing, and the root of the problem is the go tests are failing due to new API changes. I think we should either revert or update the API Server client to the new function name, otherwise the e2e test won't able to pass.

@gmfrasca Do you have time to look into how much work to rename all the API Server clients to the new function name? Sorry I got pulled into a different project so I'm busy for the next few weeks.

**Comment by gmfrasca** [comment]
@Tomcli I'll take a stab at it, from a quick glance there's a lot of places to refactor/update, but they're contained and organized relatively cleanly so hopefully it's not a terrible amount of work

**Comment by gmfrasca** [comment]
closing this as the issue has been properly addressed with #10640, which is now merged

**Pull request closed without merging**
