### PR TITLE
feat(frontend, sdk): towards namespaced pipelines. Part of #4197

### PR DESCRIPTION
**Pull request by grobbie**
Add some features to limit users' access to pipelines to pipelines in the user's own namespace and non-namespaced pipelines, in the web front end and in the Python SDK.
The necessary backend RBAC hooks are already available and implemented.

Note that I think relevant CRDs, roles and rolebindings will still be needed in order to properly close the circle on this.

### CODE REVIEW

**Comment by StefanoFioravanzo** [comment]
> Sure - as long as its implemented, that's what matters to me : ) I will make the PR a draft for now.

Thanks! We will be back with more within 2-3 weeks at most, we need to sort a few things out and then put together the PRs

**Comment by juliusvonkohout** [comment]
We also have an implementation ready https://github.com/kubeflow/pipelines/pull/7406

**Comment by juliusvonkohout** [comment]
> > Sure - as long as its implemented, that's what matters to me : ) I will make the PR a draft for now.
> 
> Thanks! We will be back with more within 2-3 weeks at most, we need to sort a few things out and then put together the PRs

At most 2-3 weeks ;-)  What is your status? I would really like to see this merged together with https://github.com/kubeflow/pipelines/pull/7725 to have a basic level of security.

**Comment by grobbie** [comment]
Sorry for the slow reply, was traveling to KubeCon 🙂

> At most 2-3 weeks ;-) What is your status? I would really like to see this merged together with #7725 to have a basic level of security.

Well afaic it's ready to go, I'll change the status.

**Comment by grobbie** [comment]
> > Sorry for the slow reply, was traveling to KubeCon slightly_smiling_face
> > > At most 2-3 weeks ;-) What is your status? I would really like to see this merged together with #7725 to have a basic level of security.
> > 
> > 
> > Well afaic it's ready to go, I'll change the status.
> 
> i am a bit confused. I was talking about @StefanoFioravanzo or does this here support both namespaced and shared pipelines?

Folks, this has been dragging on for quite some time. I'm keen to see it get at least some of this problematic stuff resolved one way or another. Can we at least try to make some progress on the front end?

**Comment by StefanoFioravanzo** [comment]
@grobbie Unfortunately we had to delay by a few weeks our contribution as we had to shift some priorities. We are still targeting to send some PRs (both backend and frontend) to support this fully as soon as possible. Possibly by the end of July. This is the design doc where we detailed the changes requires, including the frontend changes that we want to contribute with https://docs.google.com/document/d/1fM4y2L1IVqVj-iiNjYFRRktdCh7FQXgU2XpaYLaqt-A/edit?resourcekey=0-kd5loyP7w3PBD0ug6ECmLQ

**Comment by juliusvonkohout** [comment]
@grobbie please check https://github.com/kubeflow/pipelines/pull/8196

**Pull request closed without merging**
