### PR TITLE
CRD for scheduling Argo workflows (API spec)

### PR DESCRIPTION
**Pull request by vicaire**
We named this CRD a "schedule": It schedules workflows for now but we will add support for other K8 resources (e.g., jobs). It supports:

- executing pipelines using a cron schedule
- executing pipelines using a periodic interval
- An optional start date and an end date.
- Backfilling (by specifying a start date in the past).
- A maximum number of concurrent workflows.

Most of the files are automatically generated except for the files in: 

./hack/custom-boilerplate.go.txt
./hack/update-codegen.sh
./hack/verify-codegen.sh
./pkg/apis/schedule/register.go
./pkg/apis/schedule/v1alpha1/doc.go
./pkg/apis/schedule/v1alpha1/register.go
./pkg/apis/schedule/v1alpha1/types.go

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2)

### CODE REVIEW

**Comment by jlewi** [comment]
Review status: 0 of 33 files reviewed at latest revision, all discussions resolved.

---

*[pkg/apis/schedule/register.go, line 18 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFKIysD33uTC0zwUdB:-LDFKIysD33uTC0zwUdC:b-9bzmca) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/register.go#L18)):*
> ```Go
> 
> const (
> 	Kind      string = "Schedule"
> ```

"Schedule" seems like an incomplete name? Why not WorkflowSchedule since you use Workflow in other places (e.g. the Type).

---

*[pkg/apis/schedule/v1alpha1/types.go, line 27 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFGvn4493G-3uJfLvz:-LDFGvn4493G-3uJfLw-:biz5910) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L27)):*
> ```Go
> 
> // Schedule phases
> const (
> ```

I believe phases have been dropped in favor of conditions.
https://github.com/kubeflow/tf-operator/issues/223

---

*[pkg/apis/schedule/v1alpha1/types.go, line 62 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFHRRo2oLS9y7zQ4P4:-LDFHPgc7mcMt_GqBKJT:b-2ltzu5) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L62)):*
> ```
> type
> ```
What's meant by human readable? Does this mean its not used for anything?

---

*[pkg/apis/schedule/v1alpha1/types.go, line 65 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFHXdc-UHISBbwIEIF:-LDFHXdc-UHISBbwIEIG:bipy3ms) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L65)):*
> ```Go
> 
> 	// If the schedule is disabled, it does not create any new workflow.
> 	Enabled bool `json:"enabled,omitempty"`
> ```

Why would you enable/disable the schedule as opposed to just deleting it to disable it and creating it to enable it?

---

*[pkg/apis/schedule/v1alpha1/types.go, line 79 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFHkEh3C-z4RwIdWZW:-LDFHkEh3C-z4RwIdWZX:b-cx9rup) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L79)):*
> ```Go
> 	// MaxHistory cannot be larger than 100.
> 	// +optional
> 	MaxHistory *int64 `json:"maxHistory,omitempty"`
> ```

Why is there a limit on history? Whose keeping track of history?

---

*[pkg/apis/schedule/v1alpha1/types.go, line 97 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFI9in8NF0MCNHgwfY:-LDFI9in8NF0MCNHgwfZ:boeahtr) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L97)):*
> ```Go
> 	// [[ScheduledTime]] is substituted by the scheduled time of the workflow (default format)
> 	// [[CurrentTime]] is substituted by the current time (default format)
> 	// [[Index]] is substituted by the index of the workflow (e.g. 3 mins that it was the 3rd workflow created)
> ```

Why are you exposing Index? Why would operation/parameterization of a workflow depend on this?

---

*[pkg/apis/schedule/v1alpha1/types.go, line 124 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFJLR5DBJNnNlYezR7:-LDFJLR5DBJNnNlYezR8:b3agdx2) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L124)):*
> ```Go
> 
> 	// Create workflows periodically.
> 	PeriodicSchedule *PeriodicSchedule `json:"periodicSchedule,omitempty"`
> ```

Do you really need PeriodicSchedule? Is CronSchedule not sufficient?

---

*[pkg/apis/schedule/v1alpha1/types.go, line 134 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFIiXjAVME7yiMnKFR:-LDFIiXjAVME7yiMnKFS:b5oi4t7) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L134)):*
> ```
> not
> ```
no end time

---

*[pkg/apis/schedule/v1alpha1/types.go, line 207 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFJleT1WY8UX5aBArm:-LDFJleT1WY8UX5aBArn:bzbe37d) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L207)):*
> ```Go
> 
> 	// URL representing this object.
> 	SelfLink string `json:"selfLink,omitempty"`
> ```

What is this for?

---

*[pkg/apis/schedule/v1alpha1/types.go, line 213 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFJvz0A2cU-AYm5OXd:-LDFJvz0A2cU-AYm5OXe:bu7cb60) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L213)):*
> ```Go
> 
> 	// Phase is a high level summary of the status of the workflow.
> 	Phase v1alpha1.NodePhase `json:phase,omitempty`
> ```

Why do you have phase? Why not just conditions as noted above?

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2)*

**Comment by vicaire** [comment]
Review status: 0 of 45 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[pkg/apis/schedule/register.go, line 18 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFKIysD33uTC0zwUdB:-LDJnu-Q0QhRB8B8Niy1:b-a0zcih) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/register.go#L18)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

"Schedule" seems like an incomplete name? Why not WorkflowSchedule since you use Workflow in other places (e.g. the Type).
</blockquote></details>

Done. Renamed to ScheduledWorkflow as we discussed. 

---

*[pkg/apis/schedule/v1alpha1/types.go, line 27 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFGvn4493G-3uJfLvz:-LDJvdo7A4w79WbLU0yV:b-7urxzd) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L27)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

I believe phases have been dropped in favor of conditions.
https://github.com/kubeflow/tf-operator/issues/223
</blockquote></details>

Done. Switched to using conditions. 

---

*[pkg/apis/schedule/v1alpha1/types.go, line 62 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFHRRo2oLS9y7zQ4P4:-LDJvoWQBxcjBF1gi2O3:b-bk2uub) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L62)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

> ```
> type
> ```
What's meant by human readable? Does this mean its not used for anything?
</blockquote></details>

Removing it. I don't think it belongs in a CRD spec. 

---

*[pkg/apis/schedule/v1alpha1/types.go, line 65 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFHXdc-UHISBbwIEIF:-LDJwVA65_JKT_74Lpj3:b-95pabq) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L65)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Why would you enable/disable the schedule as opposed to just deleting it to disable it and creating it to enable it?
</blockquote></details>

This is needed for the following use case: 

- Say you create a ScheduledWorkflow to run from now to the end of time, every hour. 
- If you delete the workflow and re-create it, it will restart scheduling based on the time at which the ScheduledWorkflow was re-created. 
- If you disable the workflow and re-enable it, it will continue starting from the time at which it was disabled. 
Said another way, the enable/disable option backfills the missing hours. 

Here is another example: 
- Say you are backfilling. You need to run a workflow for every hour of the previous day (the Argo workflow is parameterized by the scheduled time). 
- If you delete/re-create, it will restart from scratch. 
- If you disable it will temporarily stop creating new workflows. When you re-enable, it will continue where it left off. 

This is similar to the backfill functionality of Airflow. 

---

*[pkg/apis/schedule/v1alpha1/types.go, line 79 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFHkEh3C-z4RwIdWZW:-LDJzAQI17Js8OhevoW0:b-8wfju7) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L79)):*
> Why is there a limit on history? Whose keeping track of history?
The ScheduledWorkflowStatus.WorkflowHistory structure is providing a list of recently executed workflow (both active and completed)

This is very convenient when using kubectl so that the user does not have to query the list of workflows separately with the correct labels. 

This is similar to the way the Argo resource returns the graph of PODs so that users can easily investigate the ones that failed. 

We need to limit the size of the history returned by the "kubectl get" call since ScheduledWorkflows may run forever

In the future, we may also decide to garbage collect the workflows that are completed, and only keep the X most recent ones in the K8 key value store. This is what the CronJob does: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/types.go#L276 

---

*[pkg/apis/schedule/v1alpha1/types.go, line 97 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFI9in8NF0MCNHgwfY:-LDK-U-80MqEJHeK4-Qd:b-yyam00) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L97)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Why are you exposing Index? Why would operation/parameterization of a workflow depend on this?
</blockquote></details>

This is one feature explicitly requested by users working on ML workflows. 

They want a value, substituted in the parameters of the workflow, that is unique, short, and indicating the order in which the workflows executed. 

A unique time can be very verbose: 20180504121645

A UUID is way too long. 

This index (suffixed to the workflow name in the Argo workflow spec), is ideal for these users. They use it to generate unique directories to store data in GCS for instance. 

---

*[pkg/apis/schedule/v1alpha1/types.go, line 124 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFJLR5DBJNnNlYezR7:-LDK0kOP6IfYFc7DznL5:brv21k8) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L124)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Do you really need PeriodicSchedule? Is CronSchedule not sufficient?
</blockquote></details>

We only provided Cron at first, but discovered an issue. 

Cron does not let you schedule a job, for instance, every 5 hours. 

It can handle every 6 hours: 0, 6, 12, 18, 0, 6, 12

But if you try for every 5 hours, you end up with: 0, 5, 10, 15, 20, <--- NOT 5 HOURS --> 0, 5, 10

This may be why Airflow supports both Cron and an interval as well: https://airflow.apache.org/scheduler.html#scheduling-triggers

---

*[pkg/apis/schedule/v1alpha1/types.go, line 134 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFIiXjAVME7yiMnKFR:-LDK2JKFDkIP4ufSWEu6:b-lx4fj3) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L134)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

> ```
> not
> ```
no end time
</blockquote></details>

Fixed. 

---

*[pkg/apis/schedule/v1alpha1/types.go, line 207 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFJleT1WY8UX5aBArm:-LDK2NZ7Di6liGdz30uT:b-enohkp) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L207)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

These are fields copied from the Argo status for convenience (and so that we can have a fancy looking CLI like Argo). 

The ScheduledWorkflowStatus provides a WorkflowHistory object. 

The WorkflowHistory object has a list of WorkflowStatuses for active Argo Workflows. 

The Workflow Status contains fields copied directly from the Argo status (except for the scheduledTime). 

---

*[pkg/apis/schedule/v1alpha1/types.go, line 213 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFJvz0A2cU-AYm5OXd:-LDKCpjq12GrFNkhVM75:bm12942) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L213)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Why do you have phase? Why not just conditions as noted above?
</blockquote></details>

The field is copied from Argo so we cannot change the type. It is very convenient for the user to have "kubectl  get ScheduledWorkflow" return a list of recently executed workflows and their status.  

I changed to a Condition above for our own CRD. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2)*

**Comment by jlewi** [comment]
Review status: 0 of 45 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/apis/schedule/v1alpha1/types.go, line 27 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFGvn4493G-3uJfLvz:-LDKqMcCCPPBRw7BhBoJ:b-896fix) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L27)):*
<details><summary><i>Previously, vicaire (Pascal Vicaire) wrote…</i></summary><blockquote>

Done. Switched to using conditions. 
</blockquote></details>

Done.

---

*[pkg/apis/schedule/v1alpha1/types.go, line 62 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFHRRo2oLS9y7zQ4P4:-LDKqOvl8F0Bnbxvkd28:b-896fix) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L62)):*
<details><summary><i>Previously, vicaire (Pascal Vicaire) wrote…</i></summary><blockquote>

Removing it. I don't think it belongs in a CRD spec. 
</blockquote></details>

Done.

---

*[pkg/apis/schedule/v1alpha1/types.go, line 65 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFHXdc-UHISBbwIEIF:-LDKqZ7SDPgiivfXK852:buzun20) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L65)):*
<details><summary><i>Previously, vicaire (Pascal Vicaire) wrote…</i></summary><blockquote>

This is needed for the following use case: 

- Say you create a ScheduledWorkflow to run from now to the end of time, every hour. 
- If you delete the workflow and re-create it, it will restart scheduling based on the time at which the ScheduledWorkflow was re-created. 
- If you disable the workflow and re-enable it, it will continue starting from the time at which it was disabled. 
Said another way, the enable/disable option backfills the missing hours. 

Here is another example: 
- Say you are backfilling. You need to run a workflow for every hour of the previous day (the Argo workflow is parameterized by the scheduled time). 
- If you delete/re-create, it will restart from scratch. 
- If you disable it will temporarily stop creating new workflows. When you re-enable, it will continue where it left off. 

This is similar to the backfill functionality of Airflow. 




</blockquote></details>

But I thought the whole point of the CRD and the database was that you are persisting actual job runs to a database.

So when you recreate it you should check the database for existing runs.

I think this goes to the point about the CRD being edge triggered vs. level triggered
https://hackernoon.com/level-triggering-and-reconciliation-in-kubernetes-1f17fe30333d

Suppose a ScheduledWorkflow has a schedule of
Daily at 7am
Starting on May1

If you're level triggered then on May 10 we know we want the following Workflows to exist
May 1 7am
May 2 7am
....
May 10 7am

It doesn't matter who/when/or how those runs were created. If any of them are missing we know that we should go and start them. 

Thus, it doesn't matter whether the schedule was deleted and then recreated.

I think your implementation is currently edge triggered. You are relying on observing transitions from one time to another.

I think this is going to be more brittle.

If you with a level design then I don't think you need the on/off bit.

---

*[pkg/apis/schedule/v1alpha1/types.go, line 97 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFI9in8NF0MCNHgwfY:-LDKt8IW1D4VpTkkx267:bzigmxe) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L97)):*
<details><summary><i>Previously, vicaire (Pascal Vicaire) wrote…</i></summary><blockquote>

This is one feature explicitly requested by users working on ML workflows. 

They want a value, substituted in the parameters of the workflow, that is unique, short, and indicating the order in which the workflows executed. 

A unique time can be very verbose: 20180504121645

A UUID is way too long. 

This index (suffixed to the workflow name in the Argo workflow spec), is ideal for these users. They use it to generate unique directories to store data in GCS for instance. 
</blockquote></details>

Why not use a random number? Or it least make it look random?

If you return a monotonically increasing number users will likely start to make inferences about what that index means and that will limit your implementation.

e.g. users will likely make assumptions like the numbers should be continuous and that they should match the trigger times of the runs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2)*

**Comment by vicaire** [comment]
Review status: 0 of 45 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/apis/schedule/v1alpha1/types.go, line 65 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFHXdc-UHISBbwIEIF:-LDN1VBF6exItScFSS9E:bjj3tt5) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L65)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

But I thought the whole point of the CRD and the database was that you are persisting actual job runs to a database.

So when you recreate it you should check the database for existing runs.

I think this goes to the point about the CRD being edge triggered vs. level triggered
https://hackernoon.com/level-triggering-and-reconciliation-in-kubernetes-1f17fe30333d

Suppose a ScheduledWorkflow has a schedule of
Daily at 7am
Starting on May1

If you're level triggered then on May 10 we know we want the following Workflows to exist
May 1 7am
May 2 7am
....
May 10 7am

It doesn't matter who/when/or how those runs were created. If any of them are missing we know that we should go and start them. 

Thus, it doesn't matter whether the schedule was deleted and then recreated.

I think your implementation is currently edge triggered. You are relying on observing transitions from one time to another.

I think this is going to be more brittle.

If you with a level design then I don't think you need the on/off bit.


</blockquote></details>

We want this implementation to be independent of the DB. 

Additionally, we need it to scale. The user could have a ScheduledWorkflow running for 3 years for every hour. As time progresses, verifying the complete list would become less and less efficient and slow down the controller (particularly if many instances of ScheduledWorkflow are running). 

Finally, the workflow resources may be garbage collected (they should be). If the ScheduledWorkflow runs for 3 years, I don't think the correct functioning of this CRD should require that all the workflow objects be preserved in the K8 key-value store. 

This is why we implemented this in a way similar to CronJob, keeping track only of scheduledTime of the latest workflow. 

We can implement something to address your use case later on, but that does not seem to fit this CRD very well. I would see it more as a CRD that executes workflows based on a list of possible values for the parameters of the workflow, where these values are times. The number of items in the list would have to be limited. 

---

*[pkg/apis/schedule/v1alpha1/types.go, line 97 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFI9in8NF0MCNHgwfY:-LDN5m5rCK0oQ5YikMmE:b-byxup8) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L97)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Why not use a random number? Or it least make it look random?

If you return a monotonically increasing number users will likely start to make inferences about what that index means and that will limit your implementation.

e.g. users will likely make assumptions like the numbers should be continuous and that they should match the trigger times of the runs.
</blockquote></details>

Returning a monotonically increasing number is here the requirement. 

Say the user creates a unique directory for each run of the workflow. They want the directories to be:

- my-directory-1
- my-directory-2
- my-directory-3
- etc.

We can easily add an substitution for a predictable random looking number (based on a hash). But we do need the monotically increasing, guaranteed to be unique index. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2)*

**Comment by jlewi** [comment]
Review status: 0 of 45 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/apis/schedule/v1alpha1/types.go, line 65 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFHXdc-UHISBbwIEIF:-LDOQR059w5UdN0AUemi:bs33jr5) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L65)):*
<details><summary><i>Previously, vicaire (Pascal Vicaire) wrote…</i></summary><blockquote>

We want this implementation to be independent of the DB. 

Additionally, we need it to scale. The user could have a ScheduledWorkflow running for 3 years for every hour. As time progresses, verifying the complete list would become less and less efficient and slow down the controller (particularly if many instances of ScheduledWorkflow are running). 

Finally, the workflow resources may be garbage collected (they should be). If the ScheduledWorkflow runs for 3 years, I don't think the correct functioning of this CRD should require that all the workflow objects be preserved in the K8 key-value store. 

This is why we implemented this in a way similar to CronJob, keeping track only of scheduledTime of the latest workflow. 

We can implement something to address your use case later on, but that does not seem to fit this CRD very well. I would see it more as a CRD that executes workflows based on a list of possible values for the parameters of the workflow, where these values are times. The number of items in the list would have to be limited. 




</blockquote></details>

As discussed offline the real issue here is making backfilling reliable. Right now we update last scheduled time as soon as a new workflow is started. But we shouldn't update it until that workflow completed (successfully or failed) so that controller can ensure work was actually completed.

As discussed offline please file an issue address this in a future PR.

---

*[pkg/apis/schedule/v1alpha1/types.go, line 97 at r1](https://reviewable.io/reviews/kubeflow/pipelines/2#-LDFI9in8NF0MCNHgwfY:-LDOQkYq7HoyPuHLnSbf:bb73djm) ([raw file](https://github.com/kubeflow/pipelines/blob/53374c46caaf3fea36653c65e5bf5670825f0ed5/pkg/apis/schedule/v1alpha1/types.go#L97)):*
<details><summary><i>Previously, vicaire (Pascal Vicaire) wrote…</i></summary><blockquote>

Returning a monotonically increasing number is here the requirement. 

Say the user creates a unique directory for each run of the workflow. They want the directories to be:

- my-directory-1
- my-directory-2
- my-directory-3
- etc.

We can easily add an substitution for a predictable random looking number (based on a hash). But we do need the monotically increasing, guaranteed to be unique index. 
</blockquote></details>

SGTM

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2)*

**Comment by jlewi** [comment]
/lgtm
/approve

Please file an issue to track making backfilling reliable.

**Comment by vicaire** [comment]
Issue filed to make backfills reliable: 

https://github.com/kubeflow/pipelines/issues/5

**Pull request merged**
