### PR TITLE
Cleanup code - Kaniko pod parameterization 

### PR DESCRIPTION
**Pull request by IronPan**
/assign @gaoning777 @Ark-kun

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1394)

### CODE REVIEW

**Comment by IronPan** [comment]
fix https://github.com/kubeflow/pipelines/issues/1316

**Comment by gaoning777** [comment]
This is not fixing the parameterized issue, though. 
https://github.com/kubeflow/pipelines/blob/02313e4e5ebf2d95a3b9726c687e5150ce4de382/sdk/python/kfp/compiler/_component_builder.py#L537

**Comment by IronPan** [comment]
The "default" ns should be ok. And the top level user facing function should optionally accept the namespace, since user not always have permission to default namespace in multi-tenant case.

**Pull request merged**
