### PR TITLE
feat(sdk): SDK - Components - Added annotations to TaskSpec

### PR DESCRIPTION
**Pull request by Ark-kun**
This allows the pipeline authors to add custom annotations to particular tasks.

Annotations
You can use annotations to attach arbitrary metadata to the task objects. Clients such as tools and libraries can retrieve this metadata.
For example, they can use the annotations to differentiate between the main model training task and  the auxiliary CV training tasks.
It's might also be a place to set other per-task information like the task display name for the UX.
We've had several users requesting the ability to tag tasks and the annotations provide a way to do so.

This feature is expected to mostly be used by external tools, so there are no needed changes in the backend or frontend.

### CODE REVIEW

**Comment by Bobgy** [comment]
/cc @rmgogogo for review

Can you explain why we are adding this?

**Comment by Ark-kun** [comment]
> Can you explain why we are adding this?

I've updated the description.

This allows the pipeline authors to add custom annotations to particular tasks.
For example, they can use the annotations to differentiate between the main model training task and  the auxiliary CV training tasks.
It's might also be a place to set other per-task information like the task display name for the UX.

**Comment by Ark-kun** [comment]
Travis got stuck, but the actual builds have succeeded https://travis-ci.com/github/kubeflow/pipelines/builds/174552916

**Comment by numerology** [comment]
For my understanding, does the CUJ of adding tags to tasks also require other change from UI/logging?

Reading the pod spec per se seems more like a workaround.

**Comment by Ark-kun** [comment]
>For my understanding, does the CUJ of adding tags to tasks also require other change from UI/logging?

I'm not sureUX support is needed dot this field to be useful. The main purpose is to be able to attach arbitrary information to the task object. This is similar to how it's possible to annotate component with source code URL or author, which is useful even if the UX does not explicitly surface this information. This is also similar to Kubernetes annotations: each object can be annotated, but Kubernetes itself does not read those annotations. Still there are many external tools that use them.
I want to add this field early, so components that use this field will be loadable in all 1.* SDK versions.

**Comment by Ark-kun** [comment]
I think Kubernetes provides a pretty good rationale for object annotations: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

**Pull request merged**
