### PR TITLE
feat(sdk): Allow ephemeral-storage to be defined as a Runtime resource

### PR DESCRIPTION
**Pull request by abaland**
For V1 compiler, it seems that which resources are allowed to be PipelineVariables is hard-coded in the compiler, and ephemeral-storage is not one of them, although Argo does seem to allow it. This is just to add ephemeral-storage to that list

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @chensun

**Comment by abaland** [comment]
Hey @chensun , sorry for the ping but are there any expected timelines for review? Not sure if this got lost in a mass of other stuff on your plate so I'd like to confirm. 
I realize this is a change on v1 compiler so probably lower priority but it's a really small change

**Review by chensun — COMMENTED** [review]
/lgtm

**Comment by abaland** [comment]
No problem at all. Edited the RELEASE.md file, sorry about that!

**Comment by abaland** [comment]
Saw last night that conflicts had happened so I updated the branch

@chensun Anything else I should do on my end?

**Comment by abaland** [comment]
@chensun Ping (sorry for the multiple pings, trying to make this MR not become lost)

**Comment by abaland** [comment]
@chensun  Just going to do one more ping before giving up and closing this MR

**Pull request closed without merging**
