### PR TITLE
chore(sdk): fix metrics schema title, and missing mapping

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
Fixing
- Some inconsistence in the schema title, some of them have the `kfp.` prefix, but not all.
- Missing mapping from string type name to the class and schema.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by dchickabasapa** [comment]
@neuromage  wanted to change the prefix from "kfp." to "system."  can this be done on this PR, if not don't worry about it, I can send a followup PR to update that.

**Comment by chensun** [comment]
> @neuromage wanted to change the prefix from "kfp." to "system." can this be done on this PR, if not don't worry about it, I can send a followup PR to update that.

Sure, I'll do that, need to fix some tests anyway.

**Comment by chensun** [comment]
> > @neuromage wanted to change the prefix from "kfp." to "system." can this be done on this PR, if not don't worry about it, I can send a followup PR to update that.
> 
> Sure, I'll do that, need to fix some tests anyway.

@dushyanthsc, Actually, I just chatted about this with Jialu, and he mentioned that changing to `system.` prefix would break now. I'll leave this to `kfp.` for now.

**Comment by dushyanthsc** [comment]
> > > @neuromage wanted to change the prefix from "kfp." to "system." can this be done on this PR, if not don't worry about it, I can send a followup PR to update that.
> > 
> > 
> > Sure, I'll do that, need to fix some tests anyway.
> 
> @dushyanthsc, Actually, I just chatted about this with Jialu, and he mentioned that changing to `system.` prefix would break now. I'll leave this to `kfp.` for now.

Sounds good.

**Pull request merged**
