### PR TITLE
version bump fix

### PR DESCRIPTION
**Pull request by rmgogogo**

### CODE REVIEW

**Comment by rmgogogo** [comment]
https://github.com/kubeflow/pipelines/pull/3467/files didn't cover this one.

This one is required by testing and later we will use script to update other files based on this file.

**Comment by sakaia** [comment]
It seems nothing changes for [CHANGELOG.md](https://github.com/kubeflow/pipelines/blob/master/CHANGELOG.md)
When logs are updated?

**Comment by numerology** [comment]
> It seems nothing changes for [CHANGELOG.md](https://github.com/kubeflow/pipelines/blob/master/CHANGELOG.md)
> When logs are updated?

It's in https://github.com/kubeflow/pipelines/pull/3468, blocked by one of the test. Investigating

**Pull request merged**
