### PR TITLE
chore: consistent yapf style config for the entire repo

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
I noticed that when I use vscode to edit files in samples/test, they use a style not consistent with `.style.yapf` -- actually they use the default yapf style.
After some investigation, I found that yapf only uses a style config, when it's in the same dir or in one of the parent dirs.

Therefore, I want to add the same .style.yapf for the entire repo. Some folders are not maintained by KFP maintainers, so we won't enforce the styling. They can override .style.yapf in sub-folders or choose a different formatting solution.

Moving the .style.yapf to root folder ensures that KFP maintained folders can easily have the same style, including
* samples/test
* samples/core
* samples/v2
* v2/test

Documentation for yapf is found when I run:
```
$ yapf -h
--style STYLE specify formatting style: either a style name (for
                        example "pep8" or "google"), or the name of a file
                        with style settings. The default is pep8 unless a
                        .style.yapf or setup.cfg or pyproject.toml file
                        located in the same directory as the source or one of
                        its parent directories (for stdin, the current
                        directory is used).
```

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
The style file was in the root directory previously, and we moved it to the  `sdk` folder so that it won't automatically apply on the `components` folders so that components contributors can choose their own style if they wish. 
What do you think about duplicate the style files in to the folders you mentioned above (i.e. `samples` and `v2`)?
Eventually it's choice of "enable for the entire repo and require explicit disable/override it in certain folders" vs. "not enabled for the entire repo and require explicit enable in certain folders".

**Comment by chensun** [comment]
> The style file was in the root directory previously, and we moved it to the `sdk` folder so that it won't automatically apply on the `components` folders so that components contributors can choose their own style if they wish. What do you think about duplicate the style files in to the folders you mentioned above (i.e. `samples` and `v2`)? Eventually it's choice of "enable for the entire repo and require explicit disable/override it in certain folders" vs. "not enabled for the entire repo and require explicit enable in certain folders".

I don't have a strong opinion here. So feel free to merge. 

/lgtm

**Comment by chensun** [comment]
> After some investigation, I found that yapf only uses a style config, when it's in the same dir or in one of the parent dirs.

At the end of the search path (lowest precedence), if can also read config from your home directory like ` ~/.config/yapf/style`

**Comment by Bobgy** [comment]
> The style file was in the root directory previously, and we moved it to the `sdk` folder so that it won't automatically apply on the `components` folders so that components contributors can choose their own style if they wish. What do you think about duplicate the style files in to the folders you mentioned above (i.e. `samples` and `v2`)? Eventually it's choice of "enable for the entire repo and require explicit disable/override it in certain folders" vs. "not enabled for the entire repo and require explicit enable in certain folders".

We do not enforce auto formatting for anyone, so I think it's fine to move it to root folder. Component contributors may use a different yapf config if they override, or use a totally different tool for formatting etc at their own choices.

Yes, I initially considered copying this config to each place that we maintain, but I soon realized it does not provide much value compared to simply putting it in root, based on above arguments.

I did not like letting every developer configure their own global configs, because people make mistakes. I did not know we could configure user configs, so I tried to format v2 samples and found that they were different from your last format. It took me a while to understand why. Therefore, to prevent mistakes like these, I think it's better the repo itself has yapf configs.

**Comment by Bobgy** [comment]
@chensun I would want to defer to your decision.

**Pull request merged**
