### PR TITLE
docs(sdk): add missing punctuation

### PR DESCRIPTION
**Pull request by droctothorpe**
**Description of your changes:**
This PR adds a missing period to the `list_runs` docstring. I sincerely apologize if this is excessively pedantic. Ran into it while doing some unrelated work in the same file that I'm hoping to PR soon. 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
@droctothorpe Thank you for your attention to details. But I'd probably suggest we take a different approach here for a couple of reasons:
1. I won't be surprised if our code base has many other styling issues. If we end up with too many PRs like this, it might cause a bit inconvenience when browsing commit history.
2. @ji-yaqi is working on a giant namespace refactor change (#7291) that move all v1 code including this file to a different location. This change would cause a merge conflict that Yaqi would need to resolve. I'd rather we save the trouble by postponing any trivial changes like this.

So given you said you have some ongoing work in the same file that you'd hope to PR soon. How about you combine this fix in that PR? 

/cc @ji-yaqi 
/cc @connor-mccarthy

**Comment by droctothorpe** [comment]
That makes perfect sense,  @chensun. No worries!

**Pull request closed without merging**
