### PR TITLE
[UI - multiuser] Fix pod log namespace source

### PR DESCRIPTION
**Pull request by Bobgy**
Fixes https://github.com/kubeflow/pipelines/issues/3290

After change in https://github.com/kubeflow/pipelines/pull/3403,
we can no longer get namespace from resource reference, instead read it from workflow metadata

Problem
now UI cannot read pod logs because it cannot get namespace when in multi user mode

/area frontend

### CODE REVIEW

**Comment by chetanoruganti** [comment]
Hi @Bobgy  Executed the pipeline sample in different user defined namespace . In the pipeline-ui pipeline steps logs are not getting fetched . 
pipeline ui version used 0.4.0
Looks like the above changes are not in the ml-pipeline/frontend:0.4.0  
if any frontend docker built with above changes can you please share .

**Comment by Bobgy** [comment]
@chetanoruganti if you have a problem, you may create a separate issue. This PR fixes problem for KFP multi user mode (not released yet). It doesn't break single user mode (current release).

**Comment by chetanoruganti** [comment]
@Bobgy  Thank you
I have given ml-pipeline apiserver serviceaccount(ml-pipeline) cluster level permissions . 
while creating the experiment  other namespace is passed .By doing so the workflow is created in the different namespace .

**Pull request merged**
