### PR TITLE
chore: Add instructions to develop the API server locally with kind

### PR DESCRIPTION
**Pull request by mprahl**
**Description of your changes:**

This provides instructions to provision a kind cluster with all components deployed except for the API server. The API server can then be run locally through VSCode for debugging and fast development.

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by mprahl** [comment]
It seems the test failures are unrelated to this change.

**Comment by mprahl** [comment]
@hbelmiro  could you please review the last commit? I saw you had been working with the `k8s_version` variable and two other workflows needed the variable set.

**Review by hbelmiro — COMMENTED** [review]
Good catch @mprahl.
/lgtm
/ok-to-test

cc @HumairAK

**Comment by mprahl** [comment]
@hbelmiro do you have access to cancel and retry the hanging "KFP e2e tests"?

**Comment by HumairAK** [comment]
awesome stuff @mprahl ! much needed!

/approve

**Pull request merged**
