### PR TITLE
[WIP] Initial attempt to migrate from react-scripts-ts to react-scripts

### PR DESCRIPTION
**Pull request by rileyjbauer**
WIP because it needs testing, manual and not

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1208)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Testing
/lgtm

**Comment by Bobgy** [comment]
@Ark-kun do you know what happened to this? what was the blocker? I think it's something we'd like to do sooner or later.

**Comment by Bobgy** [comment]
/close
Superseded by https://github.com/kubeflow/pipelines/pull/3156

**Pull request closed without merging**
