### PR TITLE
fix(sdk): Fixed missing export that's used in some code paths

### PR DESCRIPTION
**Pull request by Ark-kun**
The export is used in create_graph_component_from_pipeline_func

**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
Thanks, @Ark-kun. Where is `MetadataSpec` used by pipeline authors? I'm not familiar with this v1 object.

**Comment by Ark-kun** [comment]
> Thanks, @Ark-kun. Where is `MetadataSpec` used by pipeline authors? I'm not familiar with this v1 object.

`MetadataSpec` is a structure that is similar to Kubernetes' metadata structure - it contains component `labels` and `annotations` (not Python function parameter annotations).
It's directly used in `create_graph_component_from_pipeline_func` (when specifying annotations), so the import fails.

This is a simple case of forgetting to export a structure.

in `_python_op.py` we've used `from . import _structures as structures` import code, and the `structures.MetadataSpec` code worked. https://github.com/kubeflow/pipelines/blob/c11c2beef9984df6f4020a88e4b18e73b3a16b7d/sdk/python/kfp/components/_python_op.py#L937
in `_python_to_graph_component.py` we've used `from . import structures` import code, and the same `structures.MetadataSpec` code fails since `MetadataSpec` is not properly exported. https://github.com/kubeflow/pipelines/blob/c11c2beef9984df6f4020a88e4b18e73b3a16b7d/sdk/python/kfp/components/_python_to_graph_component.py#L79

**Comment by chensun** [comment]
@Ark-kun I think you want to merge into `sdk/release-1.8` instead. That's where we release sdk 1.8.* versions.

**Comment by Ark-kun** [comment]
> @Ark-kun I think you want to merge into `sdk/release-1.8` instead. That's where we release sdk 1.8.* versions.

Thank you. I did not know that. I've changed the base branch.

**Comment by Ark-kun** [comment]
@chensun The failures seem to be unrelated to the change.

**Pull request closed without merging**
