### PR TITLE
fix(sdk): add namespace check code.

### PR DESCRIPTION
**Pull request by kbc8894**
I had problem when I use python code generated by dsl-compile as module.

* add namespace check code. (`if __name__ == "__main__"`)
* add indent arg_parse_code, function call part.

Signed-off-by: ByungchanKim <kbc8894@gmail.com>

### CODE REVIEW

**Comment by kbc8894** [comment]
@googlebot I signed it!

**Comment by Ark-kun** [comment]
Hello.
Can you please show the issue you've encountered and how this PR is supposed to fix it?

>I had problem when I use python code generated by dsl-compile as module.

Can you please help me understand what you're doing?
`dsl-compile` just compiles a pipeline in a form that can be executed on KFP backend. I'm not sure we provide any support for using the resulting YAML as a module.

**Comment by kbc8894** [comment]
> Hello.
> Can you please show the issue you've encountered and how this PR is supposed to fix it?
> 
> > I had problem when I use python code generated by dsl-compile as module.
> 
> Can you please help me understand what you're doing?
> `dsl-compile` just compiles a pipeline in a form that can be executed on KFP backend. I'm not sure we provide any support for using the resulting YAML as a module.


I try to log save_model_op to mlflow tracking server with extra_code parameter.
because I want to use mlflowserver of seldon-core [link](https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html), and my model need to [python_function flavor](https://www.mlflow.org/docs/latest/models.html#python-function-python-function)

After that, when I deployed model using seldon-core mlflowserver
I met below error message 
```
usage: Save model op [-h] --model MODEL_PATH
Save model op: error: the following arguments are required: --model
```
because, when mlflowserver run and import model, It execute save_model_op.
I have work-around code. but, I think this pr is not impact pipeline functionality.
after merge this pr, pipeline code more clear I think.

In my pipeline code is below.
It is not working because It need to proper mlflow tracking server url and environment variable.
```python
import kfp
from kfp import dsl
from kfp.components import func_to_container_op, InputPath, OutputPath
from functools import partial


@partial(
    func_to_container_op,
    base_image="python:3.7-slim",
    packages_to_install=["pandas", "sklearn"],
)
def load_dataset_op(data_path: OutputPath()):
    from sklearn import datasets

    df = datasets.load_iris(as_frame=True)["frame"]
    df.to_csv(data_path, index=False)


@partial(
    func_to_container_op,
    base_image="python:3.7-slim",
    packages_to_install=["pandas", "sklearn", "dill"],
)
def train_svm_op(data_path: InputPath(), model_path: OutputPath("dill")):
    import pandas as pd
    from sklearn import svm
    import dill

    df = pd.read_csv(data_path)
    y = df["target"]
    X = df.drop(columns=["target"])
    with open(model_path, "wb") as f:
        dill.dump(svm.SVC().fit(X, y), f)


@partial(
    func_to_container_op,
    extra_code='import dill\n\ndef _load_pyfunc(path):\n    with open(path, "rb") as f:\n        return dill.load(f)',
    base_image="python:3.7-slim",
    packages_to_install=["mlflow", "sklearn", "boto3", "dill", "pandas"],
)
def save_model_op(
    model_path: InputPath("dill"),
):

    import mlflow
    from mlflow.utils.environment import _mlflow_conda_env
    import shutil
    import textwrap

    # It is workaround code.
    # with open("model.py", "w") as f:
    #    f.write(
    #        textwrap.dedent(
    #            """
    #        import dill
    #        def _load_pyfunc(path):
    #            with open(path, "rb") as f:
    #                return dill.load(f)
    #        """
    #        )
    #    )
    shutil.copy(__file__, "model.py")
    shutil.copy(model_path, "model.dill")
    mlflow.set_tracking_uri("http://someurl")
    _mlflow_conda_env("env.yml", additional_pip_deps=["sklearn"])
    mlflow.pyfunc.log_model(
        "my_model",
        loader_module="model",
        data_path="model.dill",
        code_path=["model.py"],
        conda_env="env.yml",
    )


@dsl.pipeline(
    name="iris svm classification pipeline",
    description="iris classification pipeline example.",
)
def iris_pipeline():
    load_dataset_task = load_dataset_op()
    train_svm_task = train_svm_op(load_dataset_task.outputs)
    save_model_task = save_model_op(train_svm_task.outputs["model"])


if __name__ == "__main__":
    kfp.compiler.Compiler().compile(iris_pipeline, __file__ + ".yaml")
```

**Pull request closed without merging**
