### PR TITLE
chore: adds more Azure Approvers and Reviewers

### PR DESCRIPTION
**Pull request by berndverst**
**Description of your changes:**
Chore: Adds additional (and more active) Azure reviewers and approvers for the Azure Pipelines Components.

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by dtzar — APPROVED** [review]

**Comment by berndverst** [comment]
@sudivate @dtzar I also need a LGTM to merge this.

**Pull request merged**
