### PR TITLE
fix(docs): Updated legal info due to migration from CLA to DCO

### PR DESCRIPTION
**Pull request by hbelmiro**
**Description of your changes:**

This PR depends on https://github.com/kubeflow/website/pull/3682.

This PR updates the legal info due to migration from CLA to DCO.
The new link points to the content added by [the PR that this PR depends on](https://github.com/kubeflow/website/pull/3682).

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by hbelmiro** [comment]
@terrytangyuan can you please take a look at this one too? Thank you in advance.

**Review by terrytangyuan — COMMENTED** [review]
This depends on https://github.com/kubeflow/website/pull/3682 so holding for now.

/hold

**Comment by hbelmiro** [comment]
@terrytangyuan I updated the link so now it directs to the community repo (the one that has the info on how to sign off commits).
Since https://github.com/kubeflow/website/pull/3682 was merged, I think we can unhold it.

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by hbelmiro** [comment]
@james-jwu can you PTAL?

**Pull request merged**
