### PR TITLE
chore: fix CI by adding a dependency of python/sdk for the e2e-test

### PR DESCRIPTION
**Pull request by rimolive**
**Description of your changes:**
This PR is also reverting the files deletion that are required to run CI tests.

**Checklist:**
- [X] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by diegolovison** [comment]
Suggestion to fix it properly.
* Update the commit message: fix CI by adding a dependency of python/sdk for the e2e-test
* Edit `.github/workflows/e2e-test.yml` and add `- 'sdk/python/**'` under `paths`
* Your PR will fail
* Add the files back
* Your PR will work

image

**Review by chensun — APPROVED** [review]

**Comment by gregsheremeta** [comment]
too late now, but in the future add a note to the commit along the lines of `partially reverts <git sha>` so we can more easily trace the lineage of the recreated files.

**Pull request merged**
