### PR TITLE
Reorganize ResourceOp samples

### PR DESCRIPTION
**Pull request by elikatsis**
Move the samples to different directories for the users to easier navigate to the desired usage demonstration.

Also add `README`s under `samples/volumes/` and `samples/snapshots/` with some documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1433)

### CODE REVIEW

**Comment by elikatsis** [comment]
Hey @gaoning777, any opinion on this PR?

**Comment by gaoning777** [comment]
Hey, Ilias, thanks for your contribution. I'm trying to collect some teamwide feedback in terms of the samples and sample test plans during the past two days. I will respond soon. Thanks

**Comment by elikatsis** [comment]
Hi there!

Any update on this?
It could supplement the work I'll be doing regarding the documentation of `ResourceOp`s and the rest of the entities (kubeflow/website#757, kubeflow/website#758).

Thanks!

**Pull request merged**
