### PR TITLE
presubmit for MKP/Hosted

### PR DESCRIPTION
**Pull request by rmgogogo**
presubmit for MKP/Hosted

It's not enabled in Prow yet. It can be run before submit a PR.

### CODE REVIEW

**Comment by rmgogogo** [comment]
@rui5i  I didn't add it to Prow yet but you can 
1. commit codes locally
2. run this script manually to trigger a test for Hosted/MKP.

Since verify via CLI/kubectl path is much cheaper than verify it in Hosted/MKP, would suggest you make it work in CLI/kubectl path first to save your bandwidth.

**Comment by rmgogogo** [comment]
@Bobgy @jingzhang36 Please help ask other PR owners to run the test in this PR if you think it may break MKP/Hosted. (I didn't review most PRs).

It can be run without a PR. After I change Prow config, "/test xxx" can help via robot. As synced, don't enable it for each PR for now. We may enable it for each PR later after we well refactory other tests to share the built result.

**Comment by rui5i** [comment]
Thanks, Renmin! I have a QQ: how do I know this test passes or faile? I saw some postsubmit test passes but still has error message. eg. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-mkp-e2e-test/1245964728736419840#1:build-log.txt%3A2723. Should I look at the cloudbuild status to identify success/fail?

**Comment by rmgogogo** [comment]
To Rui's question, if in post-submit, the Github kubeflow/pipeline/commits page can show it as success.
If manually launched via CLI, checking $? and if "0" means pass. 
After this PR, in pre-submit, the presubmit view in Github can tell whether pass.

**Comment by Bobgy** [comment]
@rmgogogo Can you run the presubmit test once here?

**Comment by Ark-kun** [comment]
Thanks for this test, @Renmin!
/lgtm

**Pull request merged**
