### PR TITLE
fix(docs): fix README pipeline example

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Fixes README pipeline in KFP v1.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title 
convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Ark-kun** [comment]
Do both versions work?

/lgtm

**Comment by connor-mccarthy** [comment]
Thanks, @Ark-kun! Yes, both work. The second is cleaner, more intuitive, and more consistent with v2 usage. Just pushed up one more commit to make even more consistent with v2 usage, if you don't mind re-LGTMing.

**Comment by Ark-kun** [comment]
>[use keyword arguments](https://github.com/kubeflow/pipelines/pull/8213/commits/4042ce310e614bdcae9d23429176c53f48f98810)

This is a good improvement.

/lgtm

**Comment by chensun** [comment]
Was about to comment that `create_component_from_func` doesn't work in v2, then realize this is in `sdk/release-1.8` branch.

/lgtm
/approve
/unhold

**Pull request merged**
