### PR TITLE
fix(components): remove needless arguments from AWS EMR scripts

### PR DESCRIPTION
**Pull request by slenky**
Remove needless arguments from submit_pyspark_job

**Description of your changes:**
Currently, submit_pyspark_job sends needless arguments to the EMR. 
We were trying to use this function but in `controller` EMR logs it produced output like that: 
```
2020-07-14T07:15:19.695Z INFO Ensure step 4 jar file command-runner.jar
2020-07-14T07:15:19.695Z INFO StepRunner: Created Runner for step 4
INFO startExec 'hadoop jar /var/lib/aws/emr/step-runner/hadoop-jars/command-runner.jar spark-submit --deploy-mode cluster command-runner.jar spark-submit s3://<redacted>/wordCount.py s3://<redacted>/word_excerpt.txt s3://<redacted>/output_wc.txt'
```
As you can see, there is multiple occurrence of 'command-runner.jar' and 'spark-submit'. 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by slenky** [comment]
@googlebot I fixed it.

**Comment by slenky** [comment]
@googlebot I fixed it.

**Comment by Jeffwan** [comment]
@slenky do you work with Radovan on this? Appreciate the feedbacks and contributions.

**Comment by slenky** [comment]
> @slenky do you work with Radovan on this? Appreciate the feedbacks and contributions.

Yes, we've also added a few minor things but unfortunately they're project-specific. Now it works well for us :) 
I'll extend it if we find out something useful for community.

**Comment by Jeffwan** [comment]
@slenky Thanks for the contribution. It's pretty helpful

**Pull request merged**
