### PR TITLE
docs: Backend release doc update

### PR DESCRIPTION
**Pull request by zijianjoy**
**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
Thank you for updating the docs!

Note, "fix" PR type is reserved for fixing user facing bugs and will be shown on changelog.
This PR is considered internal and should be of type "docs".

**Review by Bobgy — COMMENTED** [review]
/lgtm
/approve

**Comment by zijianjoy** [comment]
Thank you Yuan!

I was previously putting `doc:` to the title, which doesn't pass the title check. Now I know that it should be `docs: `

**Comment by Bobgy** [comment]
Exactly, FYI, you can find all categories in https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pr-type

**Pull request merged**
