### PR TITLE
Fixed CloudBuild failure

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/kubeflow/pipelines/issues/1123

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1124)

### CODE REVIEW

**Comment by hongye-sun** [comment]
/lgtm

Thanks for the fix.

**Comment by IronPan** [comment]
thanks!

**Comment by IronPan** [comment]
/test kubeflow-pipeline-e2e-test
--

**Pull request merged**
