### PR TITLE
chore(sdk-1.8): pydantic2 support

### PR DESCRIPTION
**Pull request by alexanderblnf**
**Description of your changes:**
Add support for `pydantic >=2.0,<3.0` by using the [compatibility layer](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features).

### CODE REVIEW

**Comment by rimolive** [comment]
@alexanderblnf Thanks for the contribution! Please sign-off your commits so we can proceed.

**Comment by rimolive** [comment]
Closing it. pydantic2 dependency was removed in kfpv2

/close

**Comment by alexanderblnf** [comment]
@rimolive Why was this closed?

KFP SDK v2 is unfortunately not backwards compatible with KFP 1.8, as it stands today. 
That was my first avenue that I tried, and there are API calls that are incompatible.

**Comment by rimolive** [comment]
SDK wasn't backward compatible as there are many core changes, and just like I said this dependency was removed in v2.x.

Just like I asked in https://github.com/kubeflow/pipelines/issues/10210#issuecomment-1978947173, let me know what are the blockers and we can work on getting them finished for Kubeflow 1.9.

**Pull request closed without merging**
