### PR TITLE
Update commit and release number for 0.1.28

### PR DESCRIPTION
**Pull request by rileyjbauer**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2001)

### CODE REVIEW

**Comment by Ark-kun** [comment]
This PR seems to miss updating component versions in samples. I can help resolving it.

**Comment by rileyjbauer** [comment]
> This PR seems to miss updating component versions in samples. I can help resolving it.

Thank you, but has the component version changed?

**Comment by Ark-kun** [comment]
> Thank you, but has the component version changed?

If the `component.yaml` files are changing, then the samples need to point to the new versions.

**Comment by Ark-kun** [comment]
Skipped

**Pull request closed without merging**
