### PR TITLE
Fix Dockerfile for viewer CRD image.

### PR DESCRIPTION
**Pull request by neuromage**
Let it build properly with Go modules, and also copy the source from
/vendor into the image for licensing requirements.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/760)

### CODE REVIEW

**Comment by gaoning777** [comment]
@neuromage Can you also watch the cloudbuild job after the PR merge and raise any issue if something bad happens? Thanks

**Comment by IronPan** [comment]
/lgtm
/approve

as @gaoning777 suggested please double check on CB to make sure it can build now

**Comment by neuromage** [comment]
Thanks @IronPan and @gaoning777  for local cloud build suggestion. I had started the process while pushing out this PR, and it just finished successfully.

**Pull request merged**
