### PR TITLE
add type checking sample to sample tests

### PR DESCRIPTION
**Pull request by gaoning777**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1129)

### CODE REVIEW

**Comment by gaoning777** [comment]
resolving https://github.com/kubeflow/pipelines/pull/1129

**Comment by Ark-kun** [comment]
AFAIK all current type checking code can be tested by unit-tests that do not require cluster.
If you want to test a sample notebook, it's easy to programmatically convert it to python and execute.

**Comment by gaoning777** [comment]
Correct. It does not require the cluster. By having the sample test results shown in the same place, it is easier to check the result.

**Comment by gaoning777** [comment]
And, the sample notebook is converted to python and get executed.

**Comment by Ark-kun** [comment]
Don't you get the Travis test results much sooner? They're also less flaky.

I just want us to test as much as possible using local unit tests so that the contributors can easily run them after local changes.

**Comment by gaoning777** [comment]
We can always add unit tests for the static type checking but it does not mean we can drop the sample tests here. The sample test here guarantees all samples work correctly.

**Comment by Ark-kun** [comment]
> it does not mean we can drop the sample tests here. The sample test here guarantees all samples work correctly.

Of course. I did not mean to drop them. We should test the samples. I'm just asking to run the test locally, not on cluster (using Travis, for example).

**Comment by Ark-kun** [comment]
OK, let's LGTM this one.
But please think about introducing Travis-based sample tests for samples that can be executed locally.

/lgtm

**Comment by gaoning777** [comment]
I do not see the benefits of introducing the Travis-based sample tests into the sample test infra now. 
1) Adding the travis based sample test infra takes some efforts while we only have this one sample that can be run locally.
2) If adding the travis based sample test infra reduces the testing time, running this test in the cluster does not cost more time.
3) If adding the travis based sample test infra is to make it easy to run the sample test, we can always add unit tests for the developers to quickly validate locally, which I think we do need to do.

**Comment by Ark-kun** [comment]
> 3\. If adding the travis based sample test infra is to make it easy to run the sample test, we can always add unit tests for the developers to quickly validate locally, which I think we do need to do.

That's what I meant.

**Comment by gaoning777** [comment]
Got it. Cannot agree more.

**Pull request merged**
