### PR TITLE
[Request for comments] Add config for yapf and pylintrc

### PR DESCRIPTION
**Pull request by numerology**
This is part of the efforts stated in #2442 

The plan is as follows:
1. Make it clear in [contributing guidance](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md) that we chose google python style and help contributors correctly configure their IDE to adopt it smoothly. @Bobgy can you help update the frontend part?

2. Make sure the configuration is acceptable to everyone.
3. Sent out linting PRs to fix current formatting issues.
4. Add pylint check to Travis CI.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2446)

### CODE REVIEW

**Comment by numerology** [comment]
@hongye-sun @SinaChavoshi @Ark-kun @gaoning777  Please take a look and LMK if you have any comments/suggested changes.

@Ark-kun : the problem re: long-named function you mentioned once to me should be solved by `split_before_first_argument = true`

**Comment by Ark-kun** [comment]
Thank you for doing this work!

>@Ark-kun : the problem re: long-named function you mentioned once to me should be solved by split_before_first_argument = true

Great!

>Please take a look and LMK if you have any comments/suggested changes.

One of my concerns is readability.
Python's standard library uses 4-space indents and I find it significantly more readable compared to python code formatted with 2-space indents. Indents are important in Python since there are no closing curly braces that help you see the depth. Thus, more prominent indentation makes the code more readable.

The official Python style guide is pretty clear here (explicit is better than implicit):
https://www.python.org/dev/peps/pep-0008/#indentation
>### Indentation
>Use 4 spaces per indentation level.

I'll try to find some time and see how the rest of the options look when applied to the KFP code.

**Comment by numerology** [comment]
> I find it significantly more readable compared to python code formatted with 2-space indents.

Either way looks good to me. However I imagine that once the unified DSL happens, at least the dsl part of the repo will be enforced 2-space indents, and if we do 4-space indents now, we'll have a lot of friction at that time. WDYT?

**Comment by Bobgy** [comment]
> Make it clear in contributing guidance that we chose google python style and help contributors correctly configure their IDE to adopt it smoothly. @Bobgy can you help update the frontend part?

@numerology Thanks! I will update about frontend part.

**Pull request merged**
