### PR TITLE
Drop support for python 3.6

### PR DESCRIPTION
**Pull request by pramodrj07**
**Description of your changes:**
Python 3.6 will be deprecated soon. Hence we need to drop the support for it and plan to use supported versions. 
Link to the issue -https://github.com/kubeflow/pipelines/issues/6687

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by ji-yaqi** [comment]
Hi @pramodrj07, thanks for your PR! 

Could you remove the test for python3.6 since you're dropping the support? Thanks.

**Review by ji-yaqi — COMMENTED** [review]
You might want to remove the 3.6 tests and also check for other locations to update this, thanks!

**Comment by ji-yaqi** [comment]
Closing this PR since it's idle and we have https://github.com/kubeflow/pipelines/pull/7303 ready. Thanks!

**Pull request closed without merging**
