### PR TITLE
feat(sdk): support for local execution of `dsl.importer`

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Support for local execution of `dsl.importer`:

```python
local.init(local.SubprocessRunner(), pipeline_root=ROOT_FOR_TESTING)

@dsl.component
def artifact_printer(a: Dataset):
    print(a)

@dsl.pipeline
def my_pipeline() -> Dataset:
    imp_op = dsl.importer(
        artifact_uri='/local/path/to/dataset',
        artifact_class=Dataset,
        metadata={
            'foo': 'bar',
        })
    artifact_printer(a=imp_op.outputs['artifact'])
    return imp_op.outputs['artifact']
```

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — COMMENTED** [review]
/lgtm

Not a blocker on this PR. But I feel like importer is a concept exists only for remote--it's an interface that retrieves artifact from MLMD store, yet there's no local MLMD store.

**Comment by connor-mccarthy** [comment]
@chensun, this is a good call out and I agree. I see the main benefit of a local `dsl.importer` is that this allows users to go from local --> cloud with more confidence that their components are stitched together correctly for pipelines that use an importer. But yes, ultimately this does not have the same effect on the Pipelines "system" that `dsl.importer` does remotely, since there is no "system" to speak of when executing pipelines locally.

**Comment by connor-mccarthy** [comment]
@chensun, this is a good call out and I agree. Ultimately this does not have the same effect on the Pipelines "system" that `dsl.importer` does when run remotely, since there is no "system" to speak of locally.

The benefit is that having a local `dsl.importer` allows more pipelines to seamlessly go from local --> cloud without any code modifications.

**Comment by connor-mccarthy** [comment]
Manually merging per prior LGTM. Only additional changes were to resolve merge conflicts via rebase.

cc @chensun

**Pull request merged**
