### PR TITLE
SDK - Tests - Improved the "ContainerOp.set_retry" test

### PR DESCRIPTION
**Pull request by Ark-kun**
Properly testing the feature isntead of just comparing with golden data.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1843)

### CODE REVIEW

**Comment by numerology** [comment]
Looks good. May I ask why this is actually better than comparing the compiled yaml with the golden file? Thanks!

**Comment by Ark-kun** [comment]
> Looks good. May I ask why this is actually better than comparing the compiled yaml with the golden file? Thanks!

The meta-issue tracking the effort is https://github.com/kubeflow/pipelines/issues/1763 . It provides the rationale behind making the test scope more focused.

The general idea is that tests should only fail when the feature behavior is broken, not when something unrelated to the test changes (e.g. workflow annotations or other metadata).

**Comment by Ark-kun** [comment]
This change ensures that the test fails if and only if `some_op().set_retry(number_of_retries)` does not result in `self.assertEqual(template['retryStrategy']['limit'], number_of_retries)`.

**Comment by Ark-kun** [comment]
@numerology Sorry, can you please re-LGTM?
/approve

**Comment by Ark-kun** [comment]
@numerology the PR needs /lgtm to be merged

**Comment by numerology** [comment]
> @numerology the PR needs /lgtm to be merged

Sorry I forgot.

**Pull request merged**
