### PR TITLE
better native-keras based sample

### PR DESCRIPTION
**Pull request by rmgogogo**
1. TensorBoard is added in TFX repo (google3)
2. Adjust sequence in this PR

### CODE REVIEW

**Comment by rmgogogo** [comment]
keras

**Comment by Bobgy** [comment]
You need to sync the frontend sample config: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/3900/kubeflow-pipeline-frontend-test/1268095894486519808#1:build-log.txt%3A250

**Comment by Bobgy** [comment]
Hmm, sorry there's one more place you need to fix: https://github.com/Bobgy/pipelines/blob/de8df8a644928bc2ba6b02508e1b6cacfa90593d/frontend/src/pages/GettingStarted.tsx

The config mapping for Getting started page

**Comment by rmgogogo** [comment]
> Hmm, sorry there's one more place you need to fix: https://github.com/Bobgy/pipelines/blob/de8df8a644928bc2ba6b02508e1b6cacfa90593d/frontend/src/pages/GettingStarted.tsx
> 
> The config mapping for Getting started page
> 
> EDIT: recommend making sure running `npm test` pass in `frontend` folder locally. That would be the fastest way to verify if the fix is correct.

all done.

**Comment by Bobgy** [comment]
thanks!
/approve

**Comment by Bobgy** [comment]
/approve
ohh I accidentally removed approve label

**Pull request merged**
