### PR TITLE
chore(backend): clean up backend code generation

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Changes:
* Prefer downloading required tools than building via bazel.
* Clean up proto unused imports (but I found error.proto imports are required).
* Remove licenses from generated code, because that's no longer required.
* Remove `BUILD.bazel` files that are no longer used.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by Bobgy** [comment]
Changes to remove importing error package is reverted, because after that, I get the following error during swagger generation:
```
/tmp/tmp.nP3pFaOTw6/swagger_linux_amd64 generate client -f /home/gongyuan_google_com/kfp/pipelines/backend/api/swagger/pipeline.swagger.json -A pipeline --principal models.Principal -c pipeline_client -m pipeline_model -t /home/gongyuan_google_com/kfp/pipelines/backend/api/go_http_client
2021/02/09 09:19:23 validating spec /home/gongyuan_google_com/kfp/pipelines/backend/api/swagger/pipeline.swagger.json
The swagger spec at "/home/gongyuan_google_com/kfp/pipelines/backend/api/swagger/pipeline.swagger.json" is invalid against swagger specification 2.0. see errors :
- invalid ref ".api.Status"
- ```

**Comment by Bobgy** [comment]
OK, if tests pass, I think this is ready to merge.

Then the follow up PRs to remove bazel should contain minimal changes: either https://github.com/kubeflow/pipelines/pull/4906 or https://github.com/kubeflow/pipelines/pull/5115

**Comment by Bobgy** [comment]
/assign @NikeNano 
Can you help me review and LGTM?

**Review by NikeNano — APPROVED** [review]
/LGTM

**Pull request merged**
