### PR TITLE
fix(samples): Update tensorboard_minio.py to load component from a permanent link

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
The references local file was deleted by https://github.com/kubeflow/pipelines/pull/7183
We should have used a permanent link anyway.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by zijianjoy** [comment]
/lgtm

Sounds good on using permanent link.

**Comment by Ark-kun** [comment]
Interesting. It looks like the change broke the tests, but was somehow still checked in.
I was under the impression that a PR can only be submitted when all tests pass.

Perhaps the branch protection is not fully configured.

**Pull request merged**
