### PR TITLE
better doc for MKP-KFP deployment

### PR DESCRIPTION
**Pull request by rmgogogo**
1. how to better handle inverse proxy permission setting
2. move CLI guide out of main readme and suggest user use UI

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2481)

### CODE REVIEW

**Comment by Bobgy** [comment]
/lgtm

Looks great to me! Needing one more click to cli documentation sounds like what user should know.

**Comment by IronPan** [comment]
@rmgogogo Accessing the UI won't need the project editor permission as it's not a good pratice for enterprise usecase
it at minimum requires service account user for the service account that creates the proxy. project editor should work but it will grant more access than needed

**Pull request merged**
