### PR TITLE
fix(sdk): Fix sdk requirements for kubernetes v19 dependency

### PR DESCRIPTION
**Pull request by abaland**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by abaland** [comment]
Addtional context in https://github.com/kubeflow/pipelines/pull/8526
I did not realize there were additional requirements to update in the setup.py until I tried to pip-compile kfp with kubernetes==19 today

**Comment by connor-mccarthy** [comment]
@abaland, indeed this is confusing -- I missed it too. I have put it on my backlog to make this more clear/simple.

Can you remove the previous `RELEASE.md` entry, as this change didn't actually take effect with that release? 

/ok-to-test

**Comment by abaland** [comment]
Sorry for the double PR by the way, and done!

**Comment by connor-mccarthy** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
