### PR TITLE
feat: Introduce cache_key for cache key customization

### PR DESCRIPTION
**Pull request by zzmao**
**Description of your changes:**
Introduce cache_key for cache key customization for issue #11328 
Doc: https://docs.google.com/document/d/1oNgYyFYondaVSFf9Pd3Q9uVzaqBr5wrOMHKgX9MMa78/edit?tab=t.0

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — APPROVED** [review]
/lgtm
/approve

**Comment by HumairAK** [comment]
This is spawning from https://docs.google.com/document/d/1oNgYyFYondaVSFf9Pd3Q9uVzaqBr5wrOMHKgX9MMa78/edit?tab=t.0 right? @zzmao can we get an associated github issue for this and mention both the doc and the issue in the PR body for tracking purposes? 

is there a backend follow up planned for this pr?

**Comment by zzmao** [comment]
Hi @HumairAK ,

Thanks for the review. Addressed your comment. 

Backend change is TBD. Open for community contribution.

**Comment by hbelmiro** [comment]
@zzmao can you please update the status of https://github.com/kubeflow/pipelines/issues/11328 explaining that it's partially implemented by this PR?

**Pull request merged**
