### PR TITLE
feat(backend): Support separate artifact repository for each namespace

### LINKED ISSUE #4649: [Multi User] Support separate artifact repository for each namespace
Part of https://github.com/kubeflow/pipelines/issues/1223

Support configuring separate artifact repository for each namespace, so that artifact repository can have namespace separation too.

This is currently not supported in KFP multi user support as explained in https://github.com/kubeflow/pipelines/issues/1223#issuecomment-656507073.

Use your thumbs up to show how important this issue is for you.

We'll most likely need upstream enhancement from argo in https://github.com/argoproj/argo/issues/3307.

### PR DESCRIPTION
**Pull request by juliusvonkohout**
**Description of your changes:**

This fixes #4649

The only limitation is that metrics are not rendered by the UI for whatever reason as shown in https://github.com/kubeflow/pipelines/issues/4649#issuecomment-1017674449. But MinIO provides them successfully according to the logs and you can download them from the web interface.

@Bobgy @zijianjoy I mainly used the black formatter. If you want a different python style lease tell me.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
i also need to update the local instead of the kubeflow namespace to generate the minio secret.

**Comment by juliusvonkohout** [comment]
@jacobmalmberg maybe it fails here https://github.com/kubeflow/pipelines/blob/276870585fa9e459bcbb2ee309feee85b98937d4/frontend/src/apis/run/api.ts#L935

**Comment by jacobmalmberg** [comment]
@juliusvonkohout Entirely possible! I probably won't have time to dig in deeper for the foreseeable future, though.

**Comment by juliusvonkohout** [comment]
@Bobgy gy @jacobmalmberg @ca-scribner 
There is a really strange design decision in kubeflow which will prevent this pull request from working properly. ml-pieline-ui uses (https://github.com/kubeflow/pipelines/issues/3554) the artifact proxy in the users namespace ml-pipeline-ui-artifact. ml-pipeline-ui-artifact uses the proper local minio instance. ml-pipeline(apiserver) does not use that proxy (https://github.com/kubeflow/pipelines/blob/6b7adfa78474929ecfc3f246c587c0c44f44e846/backend/src/apiserver/storage/minio_client.go#L38) and fails to fetch any artifacts because they are not in the global minio instance. This results in no mplpipeline-metrics artifact being found by the ml-pipeline-persistenceagent when it asks mp-pipeline(apiserver) for it. Therefore the persistenceagent doe snot report the metrics into the mysql database mlpipeline in the table run_metrics. And of course the API server becomes useless for artifacts in general. A proper design would be if the apiserver would use the artifact proxy and everyone else, especially ml-pipeline-ui would use the apiserver only instead of doing stuff manually.

This means one either hast to repair this structural deficit or use a global scalable minio instance with multiple buckets and different passwords per bucket. I will test whether the apiserver can get artifacts from different buckets per user.

**Comment by juliusvonkohout** [comment]
@Bobgy @ca-scribner @jacobmalmberg  this is my design proposal:

We keep the single Minio instance and use bucket name = profile name = namespace name because of the design limitations in https://github.com/kubeflow/pipelines/pull/7219#issuecomment-1023250351.

Detailed explanation:

https://github.com/kubeflow/pipelines/blob/6b7adfa78474929ecfc3f246c587c0c44f44e846/backend/src/common/util/workflow.go#L292 searches for the artifact key "mlpipeline-metrics" in the workflow manifest.
This value e.g. 'artifacts/bash-pipeline-cqkb6/2022/01/27/bash-pipeline-cqkb6-310116140/mlpipeline-ui-metadata.tgz' is returned here #https://github.com/kubeflow/pipelines/blob/6b7adfa78474929ecfc3f246c587c0c44f44e846/backend/src/apiserver/resource/resource_manager.go#L1106
So there is no bucket included, just the postfix https://github.com/kubeflow/pipelines/blob/6b7adfa78474929ecfc3f246c587c0c44f44e846/backend/src/apiserver/storage/object_store.go#L81
It is set by default to the environment variable OBJECTSTORECONFIG_BUCKETNAME ("mlpipeline")
https://github.com/kubeflow/pipelines/blob/6b7adfa78474929ecfc3f246c587c0c44f44e846/backend/src/apiserver/client_manager.go#L397 https://github.com/kubeflow/pipelines/blob/6b7adfa78474929ecfc3f246c587c0c44f44e846/backend/src/apiserver/client_manager.go#L405
So we have to change it somehow to use the name of the users profile/namespace (not the user which might contain forbidden letters like @) of the request as bucketname. This elegant solution does not need changes in the python SDK, we can keep the artifact keys without bucket names in the workflow manifest. 

```
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: julius-vonkohout # this will be the namespace and bucket name
  resourceVersion: '463979994'
  uid: 372f46ea-ea7f-43dc-8cf6-c562a461ea86
spec:
  owner:
    kind: User
    name: julius.vonkohout@....com
  resourceQuotaSpec: {}
```
This apiserver log shows that the username is there and so we can get the profile/namespace name. But of course not for reading artifacts... this is the most important API call that lacks the namespace specification...

```
I0127 15:27:00.857834       7 util.go:313] Getting user identity...
I0127 15:27:00.857858       7 util.go:323] User: julius.vonkohout@....com, ResourceAttributes: &ResourceAttributes{Namespace:julius-vonkohout,Verb:get,Group:pipelines.kubeflow.org,Version:v1beta1,Resource:experiments,Subresource:,Name:default,}
I0127 15:27:00.857876       7 util.go:324] Authorizing request...
I0127 15:27:00.861652       7 util.go:331] Authorized user 'julius.vonkohout@....com': &ResourceAttributes{Namespace:julius-vonkohout,Verb:get,Group:pipelines.kubeflow.org,Version:v1beta1,Resource:experiments,Subresource:,Name:default,}
I0127 15:27:00.864767       7 interceptor.go:37] /api.ExperimentService/GetExperiment handler finished
I0127 15:29:11.847320       7 interceptor.go:29] /api.RunService/ReadArtifact handler starting
I0127 15:29:11.856556       7 interceptor.go:37] /api.RunService/ReadArtifact handler finished
I0127 15:29:13.092830       7 interceptor.go:29] /api.RunService/ReadArtifact handler starting
I0127 15:29:13.100022       7 interceptor.go:37] /api.RunService/ReadArtifact handler finished
I0127 15:29:14.410155       7 interceptor.go:29] /api.RunService/ReadArtifact handler starting
I0127 15:29:14.419499       7 interceptor.go:37] /api.RunService/ReadArtifact handler finished
I0127 15:29:15.713893       7 interceptor.go:29] /api.RunService/ReadArtifact handler starting
I0127 15:29:15.721097       7 interceptor.go:37] /api.RunService/ReadArtifact handler finished
```

We really have to extend the API server artifacts API with the resource_reference_key.type=NAMESPACE and resource_reference_key.id=pavol-bauer. Somehow all other APIs do that properly, so it should be copy and paste. This is because we can share namespaces and e.g. Julius could ask for artifacts from namespace pavol-bauer (if it is shared) and julius-vonkohout. Trying to guess the right namespace/bucket then would be a nightmare. 

So we just use the namespace ResourceAttribute from the request as bucket name as the other APIs do. If there is no namespace in the request we just use the default bucket from the environment variable (mlpipeline) for backwards compatibility or "shared" pipeline results. This is handled the same way for namespaced pipeline definitions (YAML files) in the API server. We need to slightly modify the persistenceagent too then. It must send the namespace of the workflow in the request to the API server when it wants to check for "mlpipeline-metrics" artifacts to report them later on as run_metrics. At some point in the future also those run metrics should be namespaced the same way we handle namespaced pipeline definitions.

At this point we still have to create the buckets, passwords and bucket policies manually.

We can merge the kubeflow-pipelines-profile-controller code in this pull request into https://github.com/kubeflow/kubeflow/tree/master/components/profile-controller to get rid of metacontroller with cluster-admin rights and two separate controllers as wanted by @thesuperzapper in https://github.com/kubeflow/pipelines/pull/6629#issuecomment-930642835. Of course we will ditch the local PVC and MinIO instance for the global one in the kubeflow namespace, but we will keep the namespace specific passwords and change the bucket name. The ml-pipeline-ui will continue to work properly anyway because it uses the artifact proxy in the users namespace. Hopefully we can also get rid of that in the future...

We just need to include a routine that creates an S3 bucket, policy, quota and password on profile creation and removes it again on profile deletion. The password generation can be obtained from the kubeflow-pipelines-profile-controller code.

**Comment by ca-scribner** [comment]
I've only thought about the proposal for a few minutes, but I like it so far.  Would be good to have input from someone in the pipelines working group, but this sounds like a good idea to me.

**Comment by juliusvonkohout** [comment]
> I've only thought about the proposal for a few minutes, but I like it so far. Would be good to have input from someone in the pipelines working group, but this sounds like a good idea to me.

@kimwnasptd @thesuperzapper @davidspek
I have found another severe security issue in kubeflow... If alice shares the namespace with bob, bob can start a jupyterlab and extract the serviceaccounttoken. If alice unshares the namespace bob can just use the extracted token to still do what he wants in alices namespace. He can even do so from outside of the cluster. So we also have to delete all default-editor-tokens on a rolebinding change. They will be automatically recreated by the reconciler.

I will implement this too for this PR.

grafik

**Comment by juliusvonkohout** [comment]
this is now handled in #7406

**Pull request closed without merging**
