### PR TITLE
fix(sdk.v2): fixes broken output parameter type checking in `_handle_single_return_value`

### PR DESCRIPTION
**Pull request by judahrand**
**Description of your changes:**
This function would fail under two scenarios:
- typed `list` or `dict` output parameters (ie. `Dict[str, str]`) raised an incorrect `ValueError`
- using `list` or `dict` rather than `List` or `Dict` raised an incorrect `ValueError` ([PEP 585](https://www.python.org/dev/peps/pep-0585/#terminology))

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by judahrand** [comment]
This is one of two possible approaches. 
- This approach adds a dependency but checks the types inside a parameterized Generic (ie. `list[int]`). This has the advantage of failing before the JSON is serialized if unserializable objects are included in the `list` or `dict`.
- The alternative is to steal what `typeguard` does to just check the origin types. This would look like this:
```python
origin_type = getattr(annotation_type, '__origin__', None) or annotation_type
if type(return_value) != origin_type:
    raise ValueError(
        'Function `{}` returned value of type {}; want type {}'
        .format(self._func.__name__, type(return_value),
                origin_type))
```

This second option does not add a dependency but would also allow un-JSON-serializable types through regardless of the typehints. Given that I don't think we're currently checking whether the type hints point to something which is serializable perhaps the second approach is better?

Please let me know what you think.

**Comment by chensun** [comment]
> This is one of two possible approaches.
> 
> * This approach adds a dependency but checks the types inside a parameterized Generic (ie. `list[int]`). This has the advantage of failing before the JSON is serialized if unserializable objects are included in the `list` or `dict`.
> * The alternative is to steal what `typeguard` does to just check the origin types. This would look like this:
> 
> ```python
> origin_type = getattr(annotation_type, '__origin__', annotation_type)
> if type(return_value) != origin_type:
>     raise ValueError(
>         'Function `{}` returned value of type {}; want type {}'
>         .format(self._func.__name__, type(return_value),
>                 origin_type))
> ```
> 
> This second option does not add a dependency but would also allow un-JSON-serializable types through regardless of the typehints. Given that I don't think we're currently checking whether the type hints point to something which is serializable perhaps the second approach is better?
> 
> Please let me know what you think.

@judahrand Thanks for the fix and the detailed comparison between the two approaches. 
I tend to prefer the second option for no extra dependency. 
The executor code is evaluated only at runtime, so I don't think there's much difference between failing before JSON serialization and failing during the serialization.

**Comment by judahrand** [comment]
@chensun Sounds good, I've updated the PR to take that approach. 

I believe there are quite a lot of other type checking issues throughout the SDK. A lot of them seem to revolve are Python 3.6 support.

**Comment by chensun** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
