### PR TITLE
feat(sdk): migrate v1 auth to v2

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Migrates v1 auth to v2. Finishes PR started by #7497.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more 
about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by xin-hao-awx** [comment]
is this ready to be merged?

**Comment by chensun** [comment]
/lgtm
/approve

Thanks!

**Comment by connor-mccarthy** [comment]
Sample tests do not test this. Merging manually.

**Pull request merged**
