### PR TITLE
Release v0.22

### PR DESCRIPTION
**Pull request by kevinbache**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1525)

### CODE REVIEW

**Comment by Ark-kun** [comment]
The chosen commit has sample-test failing.

I've looked at the subsequent commits and the sample test is successful, so it's probably be OK to use that commit, but the situation deviates from the release doc.

**Comment by hongye-sun** [comment]
@Ark-kun, let's continue the process for now.

@kevinbache, are you still working on the release of v0.1.22? I am also working on the new release for this week? Do you think we can sync and only publish a single release this week?

**Pull request merged**
