### PR TITLE
[Proxy] Split domain name

### PR DESCRIPTION
**Pull request by numerology**
Get a dedicated subdomain name
Test endpoint is working at https://3b55c042b138bf86-dot-us-central2.pipelines.googleusercontent.com/#/pipelines

The new config is at https://storage.googleapis.com/ml-pipeline/proxy-agent-config.json

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2851)

### CODE REVIEW

**Comment by numerology** [comment]
/assign @IronPan 

Do you have any good advise in where to put the config file? I think the best practice is to factor out the 'greatest common divisor' but currently I made a separate copy.

**Comment by IronPan** [comment]
Is it possible in the original config file to have 
```
"agent-docker-containers": {
    "latest": {...}
    "pipelines": {...}
}
```

**Comment by numerology** [comment]
> Is it possible in the original config file to have
> 
> ```
> "agent-docker-containers": {
>     "latest": {...}
>     "pipelines": {...}
> }
> ```

Good call. We will need to request datalab team to do that

**Comment by rmgogogo** [comment]
Thanks Jiaxiao.

/lgtm

**Pull request merged**
