### PR TITLE
Notebooks - Stopped printing huge amount of info to notebook

### PR DESCRIPTION
**Pull request by Ark-kun**
Right now when you call `client.run_pipeline(...)` without assigning it to variable it prints a huge wall of JSON text to the notebook.
This PR keeps this information, but hides it behind the `RunPipelineResult` class.

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/108)

### CODE REVIEW

**Comment by gaoning777** [comment]
Why creating another response class when we have the swagger response?

**Comment by Ark-kun** [comment]
> Why creating another response class when we have the swagger response?

The response is huge (many pages of text) and might not look nice to the Notebook user.

**Comment by vicaire** [comment]
@Ark-kun, do you still need this one? Should we close?

**Comment by Ark-kun** [comment]
@gaoning777 @hongye-sun Do you think it's beneficial to do this?

We can merge it or close it.

**Pull request closed without merging**
