### PR TITLE
Add myself as a approver/reviewer

### PR DESCRIPTION
**Pull request by Ark-kun**
This will make it easier to work with `.travis.yml`, `.cloudbuild.yaml`, `CHANGELOG.md` etc.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1888)

### CODE REVIEW

**Comment by IronPan** [comment]
could you add a owner file for contrib/ instead?

**Comment by neuromage** [comment]
We should also consider putting the cloudbuild files under a /release directory with its own OWNERS file instead, so others, including SHA team can change quickly when needed.

**Comment by Ark-kun** [comment]
> could you add a owner file for contrib/ instead?

This request is more about changing the files in the root directory.

**Comment by Ark-kun** [comment]
Closing due to the postsubmit test issue.

**Pull request closed without merging**
