### PR TITLE
chore: Adding @gregsheremeta to SDK reviewers (kubernetes_platform)

### PR DESCRIPTION
**Pull request by gregsheremeta**
**Description of your changes:**
follows up on #11042
a lot of SDK work takes place in kubernetes_platform as well :)

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by gregsheremeta** [comment]
@chensun @terrytangyuan mind a quick ack here? Follows up on Chen's #11042

**Review by chensun — APPROVED** [review]
/lgtm

**Comment by chensun** [comment]
@gregsheremeta Can you sign the DCO?

**Pull request merged**
