### PR TITLE
[Backend][Multi-user] Reenable visualization server in multi-user mode

### PR DESCRIPTION
**Pull request by chensun**
Lift the multi-user check, so that visualization server at least works with shared permission.

/cc @IronPan @Bobgy

### CODE REVIEW

**Comment by Bobgy** [comment]
FYI, upgrade test is being fixed in https://github.com/kubeflow/pipelines/pull/3469

**Comment by chensun** [comment]
> FYI, upgrade test is being fixed in #3469

Ah, thanks for the heads up!

**Pull request merged**
