### PR TITLE
[SDK/compiler] Sanitize op name for PipelineParam

### LINKED ISSUE #2692: Can't loop over output from lightweight function
**What happened:**

When calling ParallelFor on the output of a lightweight python component, I get an error saying that the task is not defined.

```py
@dsl.pipeline(
    name="Parallel Pipeline",
)
def parallel_pipeline(
        project_id,
        region,
        pipeline_root,
        job_config=''
):
    get_areas_op = func_to_container_op(get_active_areas)
    test_op = func_to_container_op(test)

    areas_task = get_areas_op()

    with dsl.ParallelFor(areas_task.output) as item:
        test_op(item)
```

Pipeline returns the error

```
invalid spec: templates.parallel-pipeline.tasks.for-loop-for-loop-c9def31b-1.dependencies[1] dependency 'Get active areas' not defined
```

This occurs when triggering a run through `create_run_from_pipeline_func`. If the pipeline is compiled and uploaded using the browser, attempting to view the pipeline leads to a blank screen with the following errors in the console.

```
react-dom.production.min.js:179 TypeError: Cannot read property 'y' of undefined
    at Graph.tsx:161
    at Array.forEach (<anonymous>)
    at t.render (Graph.tsx:136)
    at so (react-dom.production.min.js:163)
    at ao (react-dom.production.min.js:162)
    at po (react-dom.production.min.js:169)
    at Ko (react-dom.production.min.js:204)
    at Xo (react-dom.production.min.js:205)
    at Da (react-dom.production.min.js:220)
    at Ma (react-dom.production.min.js:219)
bo @ react-dom.production.min.js:179
To.n.callback @ react-dom.production.min.js:190
ci @ react-dom.production.min.js:128
ui @ react-dom.production.min.js:128
Pa @ react-dom.production.min.js:229
Da @ react-dom.production.min.js:220
Ma @ react-dom.production.min.js:219
Sa @ react-dom.production.min.js:216
ea @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:134
x.setState @ react.production.min.js:13
t.setStateSafe @ Page.tsx:80
(anonymous) @ PipelineDetails.tsx:341
(anonymous) @ PipelineDetails.tsx:1
(anonymous) @ PipelineDetails.tsx:1
a @ PipelineDetails.tsx:1
Promise.then (async)
l @ PipelineDetails.tsx:1
a @ PipelineDetails.tsx:1
Promise.then (async)
l @ PipelineDetails.tsx:1
(anonymous) @ PipelineDetails.tsx:1
F @ PipelineDetails.tsx:1
t.load @ PipelineDetails.tsx:243
(anonymous) @ PipelineDetails.tsx:240
(anonymous) @ PipelineDetails.tsx:1
(anonymous) @ PipelineDetails.tsx:1
(anonymous) @ PipelineDetails.tsx:1
F @ PipelineDetails.tsx:1
t.componentDidMount @ PipelineDetails.tsx:239
Pa @ react-dom.production.min.js:229
Da @ react-dom.production.min.js:220
Ma @ react-dom.production.min.js:219
La @ react-dom.production.min.js:231
Tn @ react-dom.production.min.js:85
Graph.tsx:161 Uncaught (in promise) TypeError: Cannot read property 'y' of undefined
    at Graph.tsx:161
    at Array.forEach (<anonymous>)
    at t.render (Graph.tsx:136)
    at so (react-dom.production.min.js:163)
    at ao (react-dom.production.min.js:162)
    at po (react-dom.production.min.js:169)
    at Ko (react-dom.production.min.js:204)
    at Xo (react-dom.production.min.js:205)
    at Da (react-dom.production.min.js:220)
    at Ma (react-dom.production.min.js:219)
```

**What did you expect to happen:**

ParallelFor to run a task for each entry in the list returned by get_active_areas

**Anything else you would like to add:**

Pipeline compiled with 0.1.36, run on kubeflow 0.7.0

### PR DESCRIPTION
**Pull request by numerology**
Fix #2692

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2711)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Do you think that serializing the op name in [this part of the compiler](https://github.com/kubeflow/pipelines/blob/b8a2e6f4003ca8bee813873a0bd52782498ccd21/sdk/python/kfp/compiler/compiler.py#L481) will work as well?

**Comment by numerology** [comment]
> Do you think that sanitizing the op name in [this part of the compiler](https://github.com/kubeflow/pipelines/blob/b8a2e6f4003ca8bee813873a0bd52782498ccd21/sdk/python/kfp/compiler/compiler.py#L481) will work as well?

I think yes. Is there any case where we don't want PipelineParam.op_name to be sanitized? Thanks

**Comment by Ark-kun** [comment]
/lgtm
Can you please add a test that verifies this case? It can be done in another PR.

**Comment by numerology** [comment]
> I think that the name limitations are imposed by Argo, so the sanitization should be performed in the DSL-to-Argo compiler, not in DSL. (Imagine we had DSL-to-Airflow compiler that mandated using underscores instead of dashes.)
> /lgtm
> Can you please add a test that verifies this case? It can be done in another PR.

Actually I agree with you and would like to do those changes in this PR.
Anyway I'll need your approval :)

**Comment by Ark-kun** [comment]
> Anyway I'll need your approval :)

Sorry for the delay!

/lgtm
/approve

**Comment by numerology** [comment]
> Sorry for the delay!

No worry! Thanks!

**Pull request merged**
