### PR TITLE
chore: Release KFP SDK and v2 launcher 1.7.1

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by ji-yaqi** [comment]
Seems like we need to update `containerSpec.command` in compiler_cli_tests as well for `test_pipeline_with_custom_job_spec`. Maybe we can update golden to unblock and I will add the ignore version for that part later?

**Comment by chensun** [comment]
> Seems like we need to update `containerSpec.command` in compiler_cli_tests as well for `test_pipeline_with_custom_job_spec`. Maybe we can update golden to unblock and I will add the ignore version for that part later?

Thanks, Yaqi. I realized that `test_pipeline_with_custom_job_spec` contains `customJob` instead `container`, that's why it wasn't covered by the last fix. 
https://github.com/kubeflow/pipelines/blob/0615af5070e004a1f0f25131e416fc1e46f1b41a/sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json#L27-L41

Sent https://github.com/kubeflow/pipelines/pull/6371 for a simplified fix, and verified it covers both cases. PTAL.

**Pull request merged**
