### PR TITLE
test(sdk): Travis - Fixed pipeline validation

### PR DESCRIPTION
**Pull request by Ark-kun**
Updated the argo binary version

### CODE REVIEW

**Comment by Bobgy** [comment]
Thanks!
/lgtm
/approve

**Comment by Bobgy** [comment]
Shall we have a centralized place for such versions? e.g. a configfile that bash scripts read from?

**Comment by Bobgy** [comment]
@googlebot rescan

**Comment by Bobgy** [comment]
frontend integration test was flaky

**Comment by Ark-kun** [comment]
> Shall we have a centralized place for such versions? e.g. a configfile that bash scripts read from?

Generally all versions should be the same, but unfortunately Argo has made a change in 2.5.0 that caused the `argo` CLI to no longer work in containers. So v2.4.3 is the last version that we can use for validation. For all other cases we use 2.7.5 which can easily be upgraded by search/replace when needed.

**Pull request merged**
