### PR TITLE
Upgrade argo for GCP Markerplace

### PR DESCRIPTION
**Pull request by gkcalat**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by zijianjoy** [comment]
You need to run https://github.com/kubeflow/pipelines/blob/master/manifests/gcp_marketplace/test/snapshots.sh to apply the changes.

**Review by chensun — COMMENTED** [review]
/lgtm
/approve

**Comment by chensun** [comment]
/lgtm

Thanks, @gkcalat !

**Pull request merged**
