### PR TITLE
chore(backend): auto-generate the go_client, go_http_client, swagger in api server's docker file

### PR DESCRIPTION
**Pull request by jingzhang36**
**Description of your changes:**

Part of #3250 

As described at https://github.com/kubeflow/pipelines/pull/4373#issuecomment-673981681

Tested by using the image built by this new dockerfile on api server, and running a batch script against that api server.

/hold for a manual check of the diff between the auto-generated files in dockerfile and the previous auto-generated files by shell script.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Bobgy** [comment]
I don't agree with the reasoning to generate on build.
Let's talk directly.

**Comment by Bobgy** [comment]
I am thinking of a few drawbacks for generating code on build:
* when developing/running tests locally, IDE cannot compile the code/inspect generated code/tests cannot run
* there's no generated code diff when we change generation script

but I agree it's good to change `generate_api.sh` to use go library directly and get rid of bazel.

**Comment by jingzhang36** [comment]
> I am thinking of a few drawbacks for generating code on build:
> 
> * when developing/running tests locally, IDE cannot compile the code/inspect generated code/tests cannot run
> * there's no generated code diff when we change generation script
> 
> but I agree it's good to change `generate_api.sh` to use go library directly and get rid of bazel.

Sounds ok to me.

**Comment by NikeNano** [comment]
@jingzhang36 have you continued the work to update `generate_api.sh` file to replace bazel?

**Comment by Bobgy** [comment]
Hi @NikeNano , @jingzhang36 has moved forward.
You are welcome to take this : )

**Comment by Bobgy** [comment]
Let's close to make it clearer

**Pull request closed without merging**
