### PR TITLE
Dynamic addition of namespace and app name while creating kubeflow pipeline in gcp

### PR DESCRIPTION
**Pull request by pratibhadeepti**
@IronPan  To deploy a kubeflow pipeline application in different namespaces on different clusters with different app names,currently it's hardcoded, I have added the two parameters that can be exported from any shell script to automate the pipeline creation.
```
#! /bin/sh
export appName=$1
export namespace=$2
sed -i "s/{namespace}/$namespace/" pipelines/manifests/kustomize/cluster-scoped-resources/params.env
sed -i "s/{appName}/$appName/" pipelines/manifests/kustomize/base/params.env
```

### CODE REVIEW

**Comment by pratibhadeepti** [comment]
@googlebot I signed it!




Thanks & Regards
Pratibha Deepti | Devops Engineer
Contact No.: 9110842217 | 9968440375

**Comment by Bobgy** [comment]
@pratibhadeepti this is by design, the values are hard-coded, so they are usable default values.

For customizations, we support by using kustomize. https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/sample this is an example of overriding your values from outside.
Note that, params.env will be merged to produce the final configmap.

**Comment by Bobgy** [comment]
/close
Feel free to open PRs/create issues if you meet any problems using suggested approach.

**Comment by rmgogogo** [comment]
it's by design. To customize it, new overlay can do it.

Or tool like this: https://github.com/kubeflow/pipelines/pull/3629

**Comment by pratibhadeepti** [comment]
> @pratibhadeepti this is by design, the values are hard-coded, so they are usable default values.
> 
> For customizations, we support this use-case by using [kustomize](https://kustomize.io/) (it's builtin to kubectl too, the command kubectl apply -k is using kustomize to generate raw manifests. https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/sample this is an example of overriding your values from outside.
> Note that, params.env will be merged to produce the final configmap.

Thanks @Bobgy but I have used samples directory to customise it, what if I need to have a separate  app name in same project tow 2 or 3 developers there it creates a problem. I tried using /kustomize/samples but it fails to do so.

**Comment by Bobgy** [comment]
@pratibhadeepti No problem, you can copy the sample directory into a different name. Basically, the sample dir is a declarative representation of a KFP **instance**. When you have two instances to manage, you should copy it and have two instances.

Not sure if you know, the samples folder doesn't need to live in KFP repo either. You can put it in a separate repo, just make sure the ref correctly points to KFP manifest. https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/sample/kustomization.yaml#L5 (you can change the ref to point to different versions)

**Pull request closed without merging**
