### PR TITLE
feat: bring up a prometheus server and to verify it works, add some basic metrics for it to pull.

### PR DESCRIPTION
**Pull request by jingzhang36**
**Description of your changes:**

Bring up a prometheus server and to verify it works, add some basic metrics for it to pull

Part of https://github.com/kubeflow/pipelines/issues/3259

Screen Shot 2020-07-30 at 11 43 55 AM
Screen Shot 2020-07-30 at 12 11 36 PM

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Bobgy** [comment]
QQ: do users need us to include promeseus for them?
I think when looking at other OSS projects, they provide the metrics endpoint, but do not deploy prometheus. Many users may already have one if they are deploying to an existing cluster.

**Comment by rmgogogo** [comment]
LGTM the changes in KFP codes

As for the manifest, I strongly prefer we split it out to sample folder as add-on. two reasons

1. it's not core of KFP
2. user normally has these horizental instances centrally for not just KFP but also many others

**Comment by jingzhang36** [comment]
As for the prometheus deployment,  seems like most wanted approach is  (1) we don't have prometheus deployment in kfp default deployment, (2) we have it in the sample folder in case users want to start this deployment separately from the default kfp deployment. @rmgogogo @Bobgy WDYT?

Moreover, I am going to separate this PR into two different ones: one  for KPF code change. The other for deployment change.

**Comment by Bobgy** [comment]
> As for the prometheus deployment, seems like most wanted approach is (1) we don't have prometheus deployment in kfp default deployment, (2) we have it in the sample folder in case users want to start this deployment separately from the default kfp deployment. @rmgogogo @Bobgy WDYT?
> 
> Moreover, I am going to split this PR into two different ones: one for KPF code change. The other for deployment change.

Totally agree with all of these!

**Comment by jingzhang36** [comment]
> LGTM the changes in KFP codes
> 
> As for the manifest, I strongly prefer we split it out to sample folder as add-on. two reasons
> 
> 1. it's not core of KFP
> 2. user normally has these horizental instances centrally for not just KFP but also many others

Do we have a sample folder in manifests?

**Comment by Bobgy** [comment]
There is a folder manifest/kustomize/sample

**Comment by jingzhang36** [comment]
Move the prometheus deployment to manifests/sample https://github.com/kubeflow/pipelines/pull/4323/

**Pull request closed without merging**
