### PR TITLE
test: pin an older golang image in building presubmit test images. Fixes #9650

### LINKED ISSUE #9650: [6/16/23] e2e and upgrade presubmit tests failing consistently
e.g.: https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/9640/kubeflow-pipeline-e2e-test/1669824095170072576
```
Failed to build test images:
STEP                                              TEMPLATE          PODNAME                            DURATION  MESSAGE
 ✖ integration-test-bkwmd                         integration-test                                               child 'integration-test-bkwmd-1801226946' failed  
 └─┬─✖ build-api-integration-test-image           build-image                                                    No more retries left                              
   │ ├─✖ build-api-integration-test-image(0)      build-image       integration-test-bkwmd-2355310860  2m        Error (exit code 6)                               
   │ └─✖ build-api-integration-test-image(1)      build-image       integration-test-bkwmd-2824937097  1m        Error (exit code 6)                               
   ├─✔ build-basic-e2e-tests-image(0)             build-image       integration-test-bkwmd-616792187   4m                                                          
   ├─✔ build-frontend-integration-tests-image(0)  build-image       integration-test-bkwmd-406757411   3m                                                          
   └─✖ build-initialization-test-image            build-image                                                    No more retries left                              
     ├─✖ build-initialization-test-image(0)       build-image       integration-test-bkwmd-3701586361  2m        Error (exit code 6)                               
     └─✖ build-initialization-test-image(1)       build-image       integration-test-bkwmd-10760444    1m        Error (exit code 6)                               
```

and the error traced to curl command:
```
integration-test-bkwmd-10760444: curl: (6) getaddrinfo() thread failed to start
integration-test-bkwmd-2824937097: curl: (6) getaddrinfo() thread failed to start
integration-test-bkwmd-616792187: Unpacking libpython3.7-minimal:amd64 (3.7.3-2+deb10u4) over (3.7.3-2+deb10u3) ...
integration-test-bkwmd-2824937097: The command '/bin/sh -c curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz' returned a non-zero code: 6
integration-test-bkwmd-10760444: The command '/bin/sh -c curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz' returned a non-zero code: 6
```

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
Fixes #9650

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by zijianjoy** [comment]
Thank you Chen! I am curious if there is any issue tracked in the **golang** repo for this newly introduced problem.

**Comment by chensun** [comment]
> Thank you Chen! I am curious if there is any issue tracked in the **golang** repo for this newly introduced problem.

Opened https://github.com/docker-library/golang/issues/470

**Pull request merged**
