### PR TITLE
Add sample test without image build

### PR DESCRIPTION
**Pull request by gaoning777**
This sample test tests the samples against the pipeline without building new component images.

The previous sample tests will be tested as postsubmit later.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/578)

### CODE REVIEW

**Comment by Ark-kun** [comment]
The new test yaml still builds the images.

**Comment by Ark-kun** [comment]
Is it possible to trigger the old sample test that was building the component images?

**Comment by gaoning777** [comment]
I'm adding a postsubmit sample test that adopts the cloudbuild component images: https://github.com/kubeflow/pipelines/pull/613

**Pull request merged**
