### PR TITLE
Fix documentation for filter.proto

### PR DESCRIPTION
**Pull request by neuromage**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2447)

### CODE REVIEW

**Comment by Ark-kun** [comment]
This PR diff seems to be quite big.
Are you sure it only does what's in the PR title?

**Comment by neuromage** [comment]
> This PR diff seems to be quite big.
> Are you sure it only does what's in the PR title?

If you change anything in the proto, you have to regenerate the relevant files.

**Comment by neuromage** [comment]
/assign @IronPan 

Fixes #2412

**Comment by IronPan** [comment]
I think the exploded size of the PR due to previous changes not regenerating the files. 
/cc @jingzhang36

**Pull request merged**
