### PR TITLE
Remove backend unit tests from Travis config

### PR DESCRIPTION
**Pull request by jingzhang36**
Since we have backend unit tests in prow test (kubeflow-pipeline-backend-test)

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3264)

### CODE REVIEW

**Comment by Bobgy** [comment]
Thanks!
/lgtm
/approve

I will mark the new test as required

**Comment by Bobgy** [comment]
Marked `kubeflow-pipeline-backend-test` as required

**Comment by jingzhang36** [comment]
> Marked `kubeflow-pipeline-backend-test` as required

Thank you!

**Pull request merged**
