### PR TITLE
SDK - Annotate pods with component_ref

### PR DESCRIPTION
**Pull request by Ark-kun**
This preserves the information about the digest of the component and the location from which the component was loaded.

### CODE REVIEW

**Comment by Bobgy** [comment]
/lgtm
From my limited knowledge about these, you'd want someone else to review too.

**Comment by numerology** [comment]
/lgtm

Thanks @Ark-kun !

**Comment by Ark-kun** [comment]
> /lgtm
> From my limited knowledge about these, you'd want someone else to review too.

Thanks. I understand. I think this is fine, since I'm mostly just editing the code I've written. We both work on OSS KFP, so I'm also including you in the reviews.

**Pull request merged**
