### PR TITLE
SDK - Replaced .get_bucket() with .bucket() which requires less permissions

### PR DESCRIPTION
**Pull request by Ark-kun**
For instance, our runs do not usually have the required permission.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/209)

### CODE REVIEW

**Comment by Ark-kun** [comment]
> Why do you need to check the existence of bucket? You just want to check existence of the blob. Otherwise user still need bucket level permission.

Are you sure the permission requirements are the same? AFAIK, `get_bucket` requires `list items` permission, but `exists` just requests the `name` field of the bucket metadata.

@gaoning777 previously mentioned that the errors shown when you try to manipulate a blob in a non-existing bucket, are hard to understand, so I've added the check.

**Comment by gaoning777** [comment]
It seems that both calls triggers the same RestAPI 'Get'.https://github.com/googleapis/google-cloud-python/blob/675dbd88f4dceaab1146e1269d20066b68879944/storage/google/cloud/storage/bucket.py#L532

**Comment by gaoning777** [comment]
Could we close this PR since both these two calls trigger the same RestAPI call?

**Comment by vicaire** [comment]
@Ark-kun, do you still need this one? Should we close?

**Comment by gaoning777** [comment]
Can we close this? @Ark-kun

**Comment by gaoning777** [comment]
Please close the PR if it is not needed.

**Comment by Ark-kun** [comment]
No interest to merge this from the code owner.

**Pull request closed without merging**
