### PR TITLE
URLEncode instead of base64 encode the filter string

### PR DESCRIPTION
**Pull request by neuromage**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/620)

### CODE REVIEW

**Comment by yebrahim** [comment]
Why is this better?

**Comment by neuromage** [comment]
@yebrahim for some context, we discussed base64 vs urlencoding with @Ark-kun and @rileyjbauer yesterday and decided to switch here, mainly due to:
* @rileyjbauer points out it's slightly easier when debugging to parse the string
* @Ark-kun points out that it's probably what most http client libraries do when given a map of key value pairs and asked to construct a url query from them

**Comment by yebrahim** [comment]
I see, sgtm then.

**Comment by IronPan** [comment]
Thanks @neuromage 
@yebrahim url encoding is good for cases that human readable adds benefits which this case does.

**Pull request merged**
