### PR TITLE
test: Removed mkp tests

### PR DESCRIPTION
**Pull request by hbelmiro**
**Description of your changes:**

As discussed in https://docs.google.com/document/d/1cHAdK1FoGEbuQ-Rl6adBDL5W2YpDiUbnMLIwmoXBoAU/edit?disco=AAABPj_J-a4, removed:
- kubeflow-pipeline-mkp-test
- kubeflow-pipeline-mkp-snapshot-test
- kubeflow-pipeline-postsubmit-mkp-e2e-test

PR to remove the tests from GoogleCloudPlatform/oss-test-infra:

- https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2301

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

/assign @chensun

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by hbelmiro** [comment]
cc @chensun @zijianjoy @james-jwu

**Review by DharmitD — APPROVED** [review]
/Approve

cc: @chensun

**Comment by hbelmiro** [comment]
@gkcalat @zijianjoy we need the approval from one of you guys.

**Comment by hbelmiro** [comment]
@james-jwu can you help me to get this approved?

**Review by chensun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
