### PR TITLE
chore(sdk): fix sdk/python/tests/run_tests.sh to run all the tests in the folder.

### PR DESCRIPTION
**Pull request by judahrand**
**Description of your changes:**
Not all tests are being run by the `run_tests.sh` script

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by judahrand** [comment]
Sorry @NikeNano found a few more!

**Comment by chensun** [comment]
To be clear, the folder `sdk/python/tests` doesn't contain all the sdk tests. We are moving towards a pattern where unit tests files are alongside their source files in the main `sdk/python/kfp` folder.
I'm not sure how useful is this `run_tests.sh` script. In my workflow, I tend to run the command `python -m unittest discover -v -p "*test*.py"` from where I touched the code. And the GitHub presubmit tests run all the sdk tests: https://github.com/kubeflow/pipelines/blob/dec03067ca1f89f1ca23c7397830d60201448fa6/test/presubmit-tests-sdk.sh#L36

**Pull request merged**
