### PR TITLE
apiserver: Handle BucketExists() error

### PR DESCRIPTION
**Pull request by discordianfish**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3132)

### CODE REVIEW

**Comment by discordianfish** [comment]
Looks like a dependency isn't pinned and the tests fail because of: https://github.com/tensorflow/data-validation/issues/110
```
  File "/usr/local/lib/python3.5/site-packages/tensorflow_data_validation/coders/csv_decoder.py", line 26, in <module>
    from tfx_bsl.tfxio import record_based_tfxio
ImportError: cannot import name 'record_based_tfxio'
The command '/bin/sh -c set -e; find core tutorials -maxdepth 2 -name '*.py' -type f | while read pipeline; do python3 "$pipeline"; done' returned a non-zero code: 1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```

Let see if the upstream fix is pulled in as well.
/retest

**Comment by discordianfish** [comment]
@neuromage Can we merge this? Anything missing?

**Comment by neuromage** [comment]
Thanks for your PR. This looks good to me.

/lgtm
/approve

/retest

**Comment by discordianfish** [comment]
Hrm why did the bot remove the lgtm label? There were no changes, I've just rebased hoping to fix the tests.

**Comment by discordianfish** [comment]
@neuromage @Ark-kun Okay, rebase fixed the tests

**Comment by discordianfish** [comment]
@neuromage @Ark-kun Please, can we get this merged before it's breaking again?

**Pull request merged**
