### PR TITLE
chore(release): after release, also bump master to 1.4.1

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Note, this is not a release commit. The release commit is in `release-1.4` branch.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by Bobgy** [comment]
@chensun It seems that the KFP SDK test snapshots fail when sdk version changes. Any chance to make the test snapshots to be version agnostic?

**Comment by Bobgy** [comment]
I reverted bumping SDK version

**Comment by Bobgy** [comment]
@chensun there's still a strange snapshot mismatch for kfp v2 compiler test, any clues?

**Comment by numerology** [comment]
I think this is b/c SDK version is hard-coded in https://github.com/kubeflow/pipelines/blob/45c5c18716b57fbf9d491d88ab2fe7e345dc7edb/sdk/python/kfp/v2/google/testdata/expected_custom_job_pipeline.json#L39 as kfp 1.4.0, while it should be 1.4.1 now I guess.

A better fix should be either 1) mocking `kfp.__version__` or 2) erasing the version part in the compiled json before comparing against the golden spec.

**Comment by chensun** [comment]
> I think this is b/c SDK version is hard-coded in
> 
> https://github.com/kubeflow/pipelines/blob/45c5c18716b57fbf9d491d88ab2fe7e345dc7edb/sdk/python/kfp/v2/google/testdata/expected_custom_job_pipeline.json#L39
> 
> as kfp 1.4.0, while it should be 1.4.1 now I guess.
> A better fix should be either 1) mocking `kfp.__version__` or 2) erasing the version part in the compiled json before comparing against the golden spec.

Right on. Thank you @numerology. I'll make a fix shortly.

**Comment by chensun** [comment]
#5220, once merged, will unblock the presubmit tests.

**Pull request merged**
