### PR TITLE
fix policy binding command, clarify 'base64' usage

### PR DESCRIPTION
**Pull request by amygdala**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2478)

### CODE REVIEW

**Comment by numerology** [comment]
/retest

Sorry @amygdala you're right... I am planning to fix this by change our prow config but have not got a chance to do that yet.

**Comment by rmgogogo** [comment]
Thanks Amy!!!

**Comment by rmgogogo** [comment]
FYI Jessie, it would solve the issue you mentioned in my morning. (I will verify).
In the meeting, Jiaxiao mentioned need to wait for few minutes. Not sure whether didn't replace the "my-account".

Thanks Amy again.

**Comment by rmgogogo** [comment]
I think this PR can be closed (not submit) as we updated the document in Alpha release.

**Comment by amygdala** [comment]
SG, I'll close then.

**Pull request closed without merging**
