### PR TITLE
Update Basic Pipeline

### PR DESCRIPTION
**Pull request by swiftdiaries**
PipelineParam has been simplified. This change reflects that.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/781)

### CODE REVIEW

**Comment by gaoning777** [comment]
Why is this PR closed? any reasons?

**Comment by swiftdiaries** [comment]
I had to clean up some code. So I closed it and opened a new one.
Could you please review that?
Thanks

**Comment by gaoning777** [comment]
Do you mind pasting the link here such that the team can click the reference from this thread, too.
Thanks

**Comment by swiftdiaries** [comment]
https://github.com/kubeflow/pipelines/pull/782

Linking updated PR for reference.

**Pull request closed without merging**
