### PR TITLE
feat(frontend): Show full node names. Fixes #3989

### LINKED ISSUE #3989: Component names are truncated in the UX
Maybe we can [wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) the component names (2-3 lines) so that it's possible to distinguish components in the UX:

image

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/kubeflow/pipelines/issues/3989
image

### CODE REVIEW

**Comment by Bobgy** [comment]
What happens when names are too long?

**Comment by Bobgy** [comment]
/lgtm
/Hold
Can you verify that?
And you can unhold

**Comment by Ark-kun** [comment]
> What happens when names are too long?

The names do not overflow.

**Comment by Bobgy** [comment]
/unhold
Awesome, let's get this in.

**Pull request merged**
