### PR TITLE
 tech writer edits

### PR DESCRIPTION
**Pull request by jay-saldanha**
@hongye-sun I have updated the readme, there is one comment which needs input from you , please let me know the answer for that

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2282)

### CODE REVIEW

**Comment by hongye-sun** [comment]
@jay-saldanha I couldn't find the comment in the PR. Could you point to it?

**Comment by jay-saldanha** [comment]
> @jay-saldanha I couldn't find the comment in the PR. Could you point to it?

Check line 12

**Comment by jay-saldanha** [comment]
> Hi @jay-saldanha. Thanks for your PR.
> 
> I'm waiting for a [kubeflow](https://github.com/orgs/kubeflow/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/kubeflow/kubeflow/blob/master/CONTRIBUTING.md) to skip this step.
> 
> Once the patch is verified, the new status will be reflected by the `ok-to-test` label.
> 
> I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=kubeflow%2Fpipelines).

@hongye-sun yes sure, we will wait for the response.

**Pull request merged**
