### PR TITLE
update copyright

### PR DESCRIPTION
**Pull request by IronPan**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/880)

### CODE REVIEW

**Comment by yebrahim** [comment]
Oh, sorry if I wasn't clear on my earlier comment (assuming this is to tackle that). Only new files should have the 2019 copyright headers, older ones shouldn't change.

**Comment by gaoning777** [comment]
Should newly created files use 2019 copyright?

**Comment by vicaire** [comment]
Yes. Thanks!

**Pull request closed without merging**
