### PR TITLE
backend/metadata_writer: Pin python dependencies

### PR DESCRIPTION
**Pull request by discordianfish**

### CODE REVIEW

**Comment by Jeffwan** [comment]
What's the pain point? Do we have an issue?

**Comment by discordianfish** [comment]
@Jeffwan Tests in https://github.com/kubeflow/pipelines/pull/3379 fail because not all dependencies were pinned. This here is similar to https://github.com/kubeflow/pipelines/pull/3161
I hope I could speed up #3379 getting merged

**Comment by Jeffwan** [comment]
@discordianfish Makes sense to me.
Do you want to add command to pin dependencies in README.md as well?

**Comment by rmgogogo** [comment]
@dushyanthsc, would you help take a review?

**Comment by discordianfish** [comment]
@Jeffwan Not sure what you mean? I've already added a note to the README how to update the dependencies. Should I mention that you're suppose to edit the requirements.in? I though that should be a give. I've just copied the note from my other PR. I'd prefer to merge this as it and maybe add an contribution doc about general usage of pip-tools?

**Comment by Jeffwan** [comment]
@dushyanthsc  kindly ping

**Pull request merged**
