### PR TITLE
Use latest Tensorflow image for Tensorboard.

### LINKED ISSUE #2131: Tensorboard failed to visualize embedding
**What happened:**
The tensorboard UI failed to render embedding. It will get frozen with "computing PCA" and then the page becomes unresponsive.
failed

**What did you expect to happen:**
Here's a normal tensorboard output.
expected

**What steps did you take:**
I tried to upgrade the tensorboard version in the pod but no luck.

### PR DESCRIPTION
**Pull request by neuromage**
Fixes #2131

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2140)

### CODE REVIEW

**Comment by Ark-kun** [comment]
@neuromage 

```
   	github.com/kubeflow/pipelines/backend/src/crd/controller/viewer	[no test files]
--- FAIL: TestReconcile_EachViewerCreatesADeployment (0.04s)
    reconciler_test.go:188: Created viewer CRD &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:viewer-123 GenerateName: Namespace:kubeflow SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Type:tensorboard TensorboardSpec:{LogDir:gs://tensorboard/logdir} PodTemplateSpec:{ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{Volumes:[] InitContainers:[] Containers:[] RestartPolicy: TerminationGracePeriodSeconds:<nil> ActiveDeadlineSeconds:<nil> DNSPolicy: NodeSelector:map[] ServiceAccountName: DeprecatedServiceAccount: AutomountServiceAccountToken:<nil> NodeName: HostNetwork:false HostPID:false HostIPC:false ShareProcessNamespace:<nil> SecurityContext:nil ImagePullSecrets:[] Hostname: Subdomain: Affinity:nil SchedulerName: Tolerations:[] HostAliases:[] PriorityClassName: Priority:<nil> DNSConfig:nil ReadinessGates:[]}}}}
        Want deployment: [&Deployment{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:viewer-123-deployment,GenerateName:,Namespace:kubeflow,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[{kubeflow.org/v1beta1 Viewer viewer-123  0xc0004e5d80 0xc0004e5d81}],Finalizers:[],ClusterName:,Initializers:nil,},Spec:DeploymentSpec{Replicas:nil,Selector:&k8s_io_apimachinery_pkg_apis_meta_v1.LabelSelector{MatchLabels:map[string]string{app: viewer,deployment: viewer-123-deployment,viewer: viewer-123,},MatchExpressions:[],},Template:k8s_io_api_core_v1.PodTemplateSpec{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app: viewer,deployment: viewer-123-deployment,viewer: viewer-123,},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:PodSpec{Volumes:[],Containers:[{viewer-123-pod tensorflow/tensorflow [] [tensorboard --logdir=gs://tensorboard/logdir --path_prefix=/tensorboard/viewer-123/]  [{ 0 6006  }] [] [] {map[] map[]} [] [] nil nil nil    nil false false false}],RestartPolicy:,TerminationGracePeriodSeconds:nil,ActiveDeadlineSeconds:nil,DNSPolicy:,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:nil,ImagePullSecrets:[],Hostname:,Subdomain:,Affinity:nil,SchedulerName:,InitContainers:[],AutomountServiceAccountToken:nil,Tolerations:[],HostAliases:[],PriorityClassName:,Priority:nil,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[],},},Strategy:DeploymentStrategy{Type:,RollingUpdate:nil,},MinReadySeconds:0,RevisionHistoryLimit:nil,Paused:false,ProgressDeadlineSeconds:nil,},Status:DeploymentStatus{ObservedGeneration:0,Replicas:0,UpdatedReplicas:0,AvailableReplicas:0,UnavailableReplicas:0,Conditions:[],ReadyReplicas:0,CollisionCount:nil,},}]
        Got deployment: [&Deployment{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:viewer-123-deployment,GenerateName:,Namespace:kubeflow,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[{kubeflow.org/v1beta1 Viewer viewer-123  0xc000037a38 0xc000037a39}],Finalizers:[],ClusterName:,Initializers:nil,},Spec:DeploymentSpec{Replicas:nil,Selector:&k8s_io_apimachinery_pkg_apis_meta_v1.LabelSelector{MatchLabels:map[string]string{app: viewer,deployment: viewer-123-deployment,viewer: viewer-123,},MatchExpressions:[],},Template:k8s_io_api_core_v1.PodTemplateSpec{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app: viewer,deployment: viewer-123-deployment,viewer: viewer-123,},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:PodSpec{Volumes:[],Containers:[{viewer-123-pod tensorflow/tensorflow:1.11.0 [] [tensorboard --logdir=gs://tensorboard/logdir --path_prefix=/tensorboard/viewer-123/]  [{ 0 6006  }] [] [] {map[] map[]} [] [] nil nil nil    nil false false false}],RestartPolicy:,TerminationGracePeriodSeconds:nil,ActiveDeadlineSeconds:nil,DNSPolicy:,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:nil,ImagePullSecrets:[],Hostname:,Subdomain:,Affinity:nil,SchedulerName:,InitContainers:[],AutomountServiceAccountToken:nil,Tolerations:[],HostAliases:[],PriorityClassName:,Priority:nil,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[],},},Strategy:DeploymentStrategy{Type:,RollingUpdate:nil,},MinReadySeconds:0,RevisionHistoryLimit:nil,Paused:false,ProgressDeadlineSeconds:nil,},Status:DeploymentStatus{ObservedGeneration:0,Replicas:0,UpdatedReplicas:0,AvailableReplicas:0,UnavailableReplicas:0,Conditions:[],ReadyReplicas:0,CollisionCount:nil,},}]
        Diff:   []*v1.Deployment{
          	&{
          		TypeMeta:   v1.TypeMeta{},
          		ObjectMeta: v1.ObjectMeta{Name: "viewer-123-deployment", Namespace: "kubeflow", OwnerReferences: []v1.OwnerReference{{APIVersion: "kubeflow.org/v1beta1", Kind: "Viewer", Name: "viewer-123", Controller: &true, BlockOwnerDeletion: &true}}},
          		Spec: v1.DeploymentSpec{
          			Replicas: nil,
          			Selector: &v1.LabelSelector{MatchLabels: map[string]string{"app": "viewer", "deployment": "viewer-123-deployment", "viewer": "viewer-123"}},
          			Template: v1.PodTemplateSpec{
          				ObjectMeta: v1.ObjectMeta{Labels: map[string]string{"app": "viewer", "deployment": "viewer-123-deployment", "viewer": "viewer-123"}},
          				Spec: v1.PodSpec{
          					Volumes:        nil,
          					InitContainers: nil,
          					Containers: []v1.Container{
          						{
          							Name:    "viewer-123-pod",
        - 							Image:   "tensorflow/tensorflow:1.11.0",
        + 							Image:   "tensorflow/tensorflow",
          							Command: nil,
          							Args:    []string{"tensorboard", "--logdir=gs://tensorboard/logdir", "--path_prefix=/tensorboard/viewer-123/"},
          							... // 17 identical fields
          						},
          					},
          					RestartPolicy:                 "",
          					TerminationGracePeriodSeconds: nil,
          					... // 23 identical fields
          				},
          			},
          			Strategy:        v1.DeploymentStrategy{},
          			MinReadySeconds: 0,
          			... // 3 identical fields
          		},
          		Status: v1.DeploymentStatus{},
          	},
          }
--- FAIL: TestReconcile_ViewerUsesSpecifiedVolumeMountsForDeployment (0.00s)
```

**Comment by neuromage** [comment]
Thanks @Ark-kun !

**Comment by Ark-kun** [comment]
/lgtm
Are you sure the latest tf image won't break the installation one day?

**Comment by neuromage** [comment]
> Are you sure the latest tf image won't break the installation one day?

We can never be sure. If it does, we'll pin the version again. Ideally, we should let the user customize version if possible. I'll file another issue for that.

**Pull request merged**
