### PR TITLE
WIP namespace isolation for artifacts and pipeline definitions

### PR DESCRIPTION
**Pull request by juliusvonkohout**
**Description of your changes:**
Fixes https://github.com/kubeflow/pipelines/issues/4649 by using one bucket per user/namespace
Fixes https://github.com/kubeflow/pipelines/issues/5084 as seen on the screenshot. The kfp python SDK should also get an update
Fixes https://github.com/kubeflow/pipelines/issues/4197

The detailed proposal is in the first failed approach https://github.com/kubeflow/pipelines/pull/7219#issuecomment-1024086393 and in this proposal
[KFP Namespace isolation for pipeline definition and execution.docx](https://github.com/kubeflow/pipelines/files/8464432/KFP.Namespace.isolation.for.pipeline.definition.and.execution.docx)

@ca-scribner @jacobmalmberg please test. You have to do the user and  bucket management yourself. I have a working version with user, policy and bucket management but this is the first step.

@gabornyerges will make it mergeable

image

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
\ok-to-test

**Comment by ca-scribner** [comment]
I'm part-way through looking at this.  I like the idea but haven't got it all working right yet to make sure everything makes sense.  One thing I noticed was using the service account as the personalized minio password in the sync.py - are you separately creating minio accounts using those service accounts?

**Comment by juliusvonkohout** [comment]
> I'm part-way through looking at this. I like the idea but haven't got it all working right yet to make sure everything makes sense. One thing I noticed was using the service account as the personalized minio password in the sync.py - are you separately creating minio accounts using those service accounts?

Actually @gabornyerges will remove the sync.py prototype leftovers. How you create the namespace specific passwords will be up to you in the end. There are a lot of ways to choose them and create the buckets and policies etc. . The default admin one will be enough for verifying the functionality.

**Comment by juliusvonkohout** [comment]
Since @gabornyerges has signed the cla

/retest

**Comment by gabornyerges** [comment]
Since @gabornyerges has signed the cla

/retest

**Comment by juliusvonkohout** [comment]
@Bobgy @zijianjoy @StefanoFioravanzo @chensun i would really like to know from you whether this has a chance to be merged. It really separates the users and would make v1 pipelines enterprise ready from a security perspective.

**Comment by juliusvonkohout** [comment]
@gabornyerges https://github.com/kubeflow/pipelines/pull/7447 is a pull request that also implements the frontend part and passes the unittests. We could also wait for https://github.com/kubeflow/pipelines/issues/4197#issuecomment-1075284702 and merge this here without the frontend changes.

**Comment by gabornyerges** [comment]
> @gabornyerges #7447 is a pull request that also implements the frontend part and passes the unittests. We could also wait for [#4197 (comment)](https://github.com/kubeflow/pipelines/issues/4197#issuecomment-1075284702) and merge this here without the frontend changes.

i will look into both PRs.

**Comment by grobbie** [comment]
FWIW I'd like to see the bucket-per-user namespace parts merged regardless of which frontend implementation PR gets selected, and it looks like you've done a huge amount of work here. For me the Arikkto approach to the frontend is okay, although maybe overkill since the feedback we've had from users is overwhelmingly that they want pipelines isolated per user namespace. Anyway I've made my PR a draft for now.

Looking at the failed e2e test - looks like you didn't run `npm run lint` on the frontend?

```
 TS2339: Property 'namespace' does not exist on type 'typeof QUERY_PARAMS'.
Step #2 - "frontend":     129 |     const urlParser = new URLParser(props);
Step #2 - "frontend":     130 |     const pipelineId = urlParser.get(QUERY_PARAMS.pipelineId);
Step #2 - "frontend":   > 131 |     const namespace = urlParser.get(QUERY_PARAMS.namespace) || undefined;
```

**Comment by juliusvonkohout** [comment]
@arllanos @maganaluis this might be relevant for you too, since you started working on it last spring

**Comment by juliusvonkohout** [comment]
Due to newly discovered funtionality in argo and we will not use multiple buckets but just multiple folders and the following iam policy

## One bucket multiple folder namespace isolation

1. change the workflow-controller configmap `keyFormat: "artifacts/{{workflow.namespace}}/{{workflow.name}}/{{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{pod.name}}"`
We do not need the per namespace artifactrepositories configmaps anymore

2. We still need to create a minio user in sync.py and and save the individual credentials to the per namespace secret. But we now need only one policy although this policy must still be attached to every user. So sjust some small changes in sync.py. We do not need to create additional buckets anymore
```
"Resource": [
    "arn:aws:s3:::%s"  % shared_bucket_name,
    "arn:aws:s3:::%s/pipelines/shared/*"  % shared_bucket_name, # shared pipelines
    "arn:aws:s3:::%s/pipelines/${aws:username}/*"  % shared_bucket_name, # private pipelines
    "arn:aws:s3:::%s/artifacts/${aws:username}/*"  % shared_bucket_name, # private artifacts
    "arn:aws:s3:::%s/private/${aws:username}/*"  % shared_bucket_name, # private storage
    "arn:aws:s3:::%s/shared/*"  % shared_bucket_name # shared storage for collaboration
```
3. I reverted to upstream by using NAMESPACE_ISOLATION=false and it worked quite well. So we can revert to the upstream images for apiserver, persistenceagent etc. Only ml-pipeline-ui must be kept.

4. We just have to change the path for shared pipelines to /pipelines/shared/ and for private pipelines to /pipelines/${aws:username}/ in the apiserver. This should be trivial. It also works without those changes, but then you could steal other users pipeline definitions. Please use environment variables to make both paths configurable, so we can upstream it easier.

5. The pipeline-ui does not need to be changed since it uses the apiserver properly according to gabors changes in frontend/src/pages/PipelineList.tsx

6. Independent of folders vs buckets we need to add two small things from my comments in https://docs.google.com/document/d/19OfU-hIsY4xBKA6b_F3dYIbSgrLMrVshucUSsyqotQ4/edit#heading=h.qi0ol2nggxlt for a bit extra security in the readartifact https://github.com/kubeflow/pipelines/blob/1180e10632f1cad13d0616ac19597c76d283ee1e/backend/src/apiserver/server/run_server.go#L303 and reportmetrics https://github.com/kubeflow/pipelines/blob/1180e10632f1cad13d0616ac19597c76d283ee1e/backend/src/apiserver/server/run_server.go#L278 call.
Please took a look of https://github.com/kubeflow/pipelines/blob/1265113dffcde7bcdb68cc9c7c655797e7b026d5/backend/src/apiserver/server/run_server.go#L359-L393 and https://github.com/kubeflow/pipelines/blob/1265113dffcde7bcdb68cc9c7c655797e7b026d5/backend/src/apiserver/server/util.go#L348 .
We could also wait for the Vmware developers to do it for us.

**Comment by juliusvonkohout** [comment]
closed in favor of https://github.com/kubeflow/pipelines/pull/7725

**Pull request closed without merging**
