### PR TITLE
[WIP] Include timing info in presubmit test log

### PR DESCRIPTION
**Pull request by Bobgy**
/assign @numerology

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1882)

### CODE REVIEW

**Comment by Bobgy** [comment]
I need to figure out why time format isn't my expected configuration

**Comment by Ark-kun** [comment]
This PR might be related: https://github.com/kubeflow/pipelines/pull/579

Generally, the big parts are 
* Kubeflow (not pipelines) deployment
* Image building (script prints the timing)
* Tests themselves (Argo prints the timing)
* Kubeflow deployment deletion

**Comment by Bobgy** [comment]
@Ark-kun thanks for the info.

My ideas for how to improve:
Kubeflow (not pipelines) deployment - should be faster in kfp lite deployment
Image building (script prints the timing) - maybe try cloud build might be faster
Tests themselves (Argo prints the timing) - this is actually fast enough
Kubeflow deployment deletion - when using kfp lite deployment, we only need to delete the cluster, and it could be async. no time will be spent here

Looks like we can solve a lot soon.

BTW, did you intentionally left the PR not merged? I think it's worth actually being committed. People may from time to time want to look at that

**Comment by Bobgy** [comment]
/hold
this is only for collecting data
I will include timing info directly in https://github.com/kubeflow/pipelines/pull/1808

**Pull request closed without merging**
