### PR TITLE
Add HyperParameters back to SageMaker training job

### PR DESCRIPTION
**Pull request by Jeffwan**
To address #1370

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1377)

### CODE REVIEW

**Comment by Jeffwan** [comment]
@Ark-kun Looks like it pass test. Please have another look.

**Comment by Ark-kun** [comment]
/approve

In future you should probably either parametrize or deprecate those parameters.

**Comment by Jeffwan** [comment]
Agree. There's lots of first party algorithms and their hyper parameter is different, agree that I need to customize this part in next change.

**Pull request merged**
