### PR TITLE
Changelog 0.1.25

### PR DESCRIPTION
**Pull request by jingzhang36**
This change log is generated when 0.1.25 tag is bound to commit a16f3806374034b8f9898fe33c60eba46c5ae282

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1695)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Can you please only add the part for 1.25 without removing the history?

**Comment by jingzhang36** [comment]
> Can you please only add the part for 1.25 without removing the history?

Not quite sure why the removal of old entries happened. The PR is auto-generated by changelog tool.... Any idea why?

**Comment by jingzhang36** [comment]
Done with fix. Only 0.1.25 new entries are added. Previous changes are not touched.
/assign @IronPan 
/assign @Ark-kun

**Pull request merged**
