### PR TITLE
 SDK - Cleanup - Serialized PipelineParamTuple does not need value or type

### PR DESCRIPTION
**Pull request by Ark-kun**
Default values are only relevant when PipelineParam is used in the pipeline function signature and even in this case compiler captures them explicitly from the PipelineParam objects in the signature.
There seem to be no other uses for them.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1469)

### CODE REVIEW

**Comment by gaoning777** [comment]
Please fix the test failures.

**Comment by Ark-kun** [comment]
> Please fix the test failures.

The tests no longer fail.
/cc @gaoning777

**Comment by Ark-kun** [comment]
Gentle ping. @gaoning777

**Comment by gaoning777** [comment]
Why is the type information also removed from the pipelinepram? How does the compiler check the parameter consistency checks?

**Comment by Ark-kun** [comment]
> Why is the type information also removed from the pipelinepram?

The type information is NOT removed from PipelineParam. It's only removed from the `PipelineParamTuple` class.

> How does the compiler check the parameter consistency checks?

The type consistency check continues working (all the tests pass), because they correctly rely on `PipelineParam.param_type`.

This PR is only changed the string representation of `PipelineParam`s, so it does not affect type checking.

**Pull request merged**
