### PR TITLE
fix(sdk): add special handling for PipelineTaskFinalStatus to get_parameter_type

### LINKED ISSUE #8586: [sdk] Can't compile component that uses PipelineTaskFinalStatus: Enum value for ParameterTypeEnum must be an int, but got <class 'NoneType'> None.
### Environment

*  KFP version: 2.0.0b8

*  KFP SDK version: 2.0.0b8

*  All dependencies version: 2.0.0b8

### Steps to reproduce

When compiling a component that uses `PipelineTaskFinalStatus`, only the given parameter type is special cased during type checking, leading to an exception:

```python
from kfp.dsl import component, PipelineTaskFinalStatus
from kfp.compiler import Compiler

@component
def test(status: PipelineTaskFinalStatus):
    pass

Compiler().compile(test, package_path='test.yaml')  # TypeError: Enum value for ParameterTypeEnum must be an int, but got <class 'NoneType'> None.
```

### Expected result

It should be possible to compile components that use `PipelineTaskFinalStatus` to yaml.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by suned**
**Description of your changes:**

fixes #8586 by introducing special handling for `PipelineTaskFinalStatus` everywhere

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
Thanks, @suned! I think there's a legitimate use-case for this. It's somewhat of a `feat(sdk)` rather than a `fix(sdk)`, since we've never permitted compiling standalone exit tasks AFAIK (it's possible I'm missing something -- if so, please let me know).

A couple testing requests to get this merged:
- Can you add a test for the case of a compiled component shown in the issue?
- Can you add a test for the case of a compiled pipeline?
- For each, can you test that re-loading the compiled component/pipeline (`kfp.components.load_component_from_file`) and composing in another pipeline works as expected?

A good place for these tests is probably `compiler_test.py`.

**Comment by suned** [comment]
@connor-mccarthy Sounds good, I'll add the test cases :fire:

> I think there's a legitimate use-case for this. It's somewhat of a `feat(sdk)` rather than a `fix(sdk)`, since we've never permitted compiling standalone exit tasks AFAIK (it's possible I'm missing something -- if so, please let me know)

I see. In our current setup (`kfp==1.8.17`) we've been relying on `kfp.v2.dsl.component` using the `output_component_file` parameter to generate component yaml, which works fine with `PipelineTaskFinalStatus` and so we've come to rely on compiling components that use it 😅 

I realize that `output_component_file` is deprecated in `kfp==2.0.0b8`, but since our setup is very much based on sharing components via yaml files, upgrading to `2.0.0` this issue has become something of a blocker for us.

**Comment by connor-mccarthy** [comment]
@suned, I see. If this is supported in v1, then it is indeed a regression in v2! Thanks for catching this and explaining.

If you're able to add tests per the [comment](https://github.com/kubeflow/pipelines/pull/8587#issuecomment-1355154699) above, I'm happy to review and merge your change quickly.

**Comment by connor-mccarthy** [comment]
@suned, on second thought, I have another PR (better support for optional inputs) where these tests would fit in well, since `PipelineTaskFinalStatus` falls into the category of optional inputs.

Let's merge this PR and I'll add tests and more changes on top.

**Comment by connor-mccarthy** [comment]
/lgtm
/approve

Thank you, @suned

**Review by connor-mccarthy — APPROVED** [review]

**Pull request merged**
