### PR TITLE
chore(components): Updated the container image in the GCP components

### PR DESCRIPTION
**Pull request by Ark-kun**

### CODE REVIEW

**Comment by Bobgy** [comment]
Note the cloudbuild task on your release branch failed

**Comment by Ark-kun** [comment]
> Note the cloudbuild task on your release branch failed

I see that. It's failing installing Tensorflow when building the visualization server:
```
Collecting tensorflow==2.2.0
  Downloading https://files.pythonhosted.org/packages/3d/be/679ce5254a8c8d07470efb4a4c00345fae91f766e64f1c2aece8796d7218/tensorflow-2.2.0-cp36-cp36m-manylinux2010_x86_64.whl (516.2MB)
Killed
The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 137
```

Looks like that failure is now "stuck".

**Comment by Ark-kun** [comment]
Force-submitting since it's not possible to retry the postsubmit tests that were unexpectedly added here. The postsubmit test failures do not seem to be related to this change.

**Comment by Bobgy** [comment]
Agree

**Pull request merged**
