### PR TITLE
Lint check_notebook_results.py

### PR DESCRIPTION
**Pull request by numerology**
Previously check_notebook_results.py was not following correct coding style. This is only a linting PR. Nothing actually changed.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1997)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Are you sure that 2-space indents are more readable than 4-space?

**Comment by numerology** [comment]
> Are you sure that 2-space indents are more readable than 4-space?

Good question. PEP8 says 4 and google style guide says 2. I think a team-wide consensus is needed, though.

**Pull request closed without merging**
