### PR TITLE
[WIP] add coveralls for python sdk

### PR DESCRIPTION
**Pull request by numerology**
Linked issue #1850

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1854)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Possible duplicate of https://github.com/kubeflow/pipelines/pull/898

**Comment by numerology** [comment]
> Possible duplicate of #898

Thanks @Ark-kun for pointing that out.

**Comment by numerology** [comment]
Duplicate. Close.

**Pull request closed without merging**
