### PR TITLE
chore(sdk): expose compiler

### PR DESCRIPTION
**Pull request by munagekar**
**Description of your changes:**
- Exposes compiler, this enables autocompletion and removes IDE warnings

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by Ark-kun** [comment]
> * Exposes compiler, this enables autocompletion and removes IDE warnings

Out of interest, what warnings are produced by the current SDK?
I'd expect this to either work or fail, but not work with warnings.

**Comment by munagekar** [comment]
I tested this with Pycharm. Without this PR, it produces the following warning and autocompletion doesn't work.

```
Cannot find reference 'compiler' in '__init__.py' 
```
Screen Shot 2020-11-22 at 23 34 25

**Comment by munagekar** [comment]
@Ark-kun Do you feel this is okay to merge ?

**Comment by munagekar** [comment]
@Bobgy @chensun Can you take a look ?

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Pull request closed without merging**
