### PR TITLE
[Frontend] UI shows specified task display name in PipelineDetail page

### PR DESCRIPTION
**Pull request by Bobgy**
The display name shall be retrievable from metadata.annotations.pipelines.kubeflow.org/task_display_name from each components in workflow yaml spec.

For review, use [this link](https://github.com/kubeflow/pipelines/pull/2459/commits/4a69583bd3ca1fa770de1ad802d4bf6700ad200a) to avoid seeing unrelated format changes.

**Before the fix:**
download (17)
**After the fix:**
download (16)

/area front-end
/kind feature
/cc @numerology

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2459)

### CODE REVIEW

**Comment by Bobgy** [comment]
/approve

@numerology please LGTM if this looks good

**Comment by Bobgy** [comment]
Decided to merge first because I will reformat all frontend code.

**Comment by numerology** [comment]
/lgtm
Thanks @Bobgy !

**Pull request merged**
