### PR TITLE
chore(sdk): update contributing guidelines/tests

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Adds presubmit checks, contributing guidelines, and a pre-commit file. Also removes an outdated code 
formatting script.

Testing notes (first format code, then make sure each tests passes):
1. `pip install pre-commit`
2. `pre-commit install`
3. `pre-commit run --files sdk/python/kfp/**/*.py`
For each file in `['test/presubmit-docformatter-sdk.sh', 'test/presubmit-yapf-sdk.sh', 'test/presubmit-isort-sdk.sh']`:
4. `source <file>`
5. `echo $?` should `== 0`

Next steps:
1) Add prow tests corresponding to the presubmit checks, but allow failures until code base is 
adherent to these guidelines.
2) Apply changes to codebase.
3) Disallow test failures from prow.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull 
request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks!

**Comment by connor-mccarthy** [comment]
/override kubeflow-pipelines-samples-v2

Changes are unrelated to samples

**Pull request merged**
