### PR TITLE
Changed the file as per the new edits

### PR DESCRIPTION
**Pull request by jay-saldanha**
Final edits completed on Apr8 2019, this file is updated as per these edits

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1105)

### CODE REVIEW

**Comment by jay-saldanha** [comment]
@hongye-sun please review and update the Readme

**Comment by jay-saldanha** [comment]
yes


*Jayana Saldanha | *Technical Writer (Akorbi) | Cloud AI Platform Docs

**Comment by vicaire** [comment]
Closing as instructed.

**Comment by vicaire** [comment]
Closing as instructed.

**Pull request closed without merging**
