### PR TITLE
feat(backend): Add pipeline version description to backend. Part of #6256

### PR DESCRIPTION
**Pull request by casassg**
**Description of your changes:**
As described in #6256 we want to append some extra string information when uploading a new version of a pipeline. 

This is a first commit which adds the fields on the backend. Will move to frontend after this (as they probs require more changes and updates).

Included changes: 
- Added field to `backend/api/pipeline.proto`
- Frontend `npm run apis` with [jar](https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.7/swagger-codegen-cli-2.4.7.jar)
- go client refresh - `make`
- Python client refresh - `./build_kfp_server_api_python_package.sh`
- Manual changes in ` backend/src/apiserver/storage/pipeline_store.go`, `backend/src/apiserver/resource/resource_manager.go` and `backend/src/apiserver/model/pipeline_version.go` to load data from DB. 
- Tests to validate changes in the above manual changes ^

Ran:
- go unit tests
- npm run format

### CODE REVIEW

**Comment by Bobgy** [comment]
Thank you for the PR! I'll try to take a look tmr

**Comment by casassg** [comment]
CLA bot is deeply confused.

Moved fixes for current CI red into #6286 to keep PR separate. We may want to merge that one first.

**Comment by casassg** [comment]
@googlebot I consent.

**Comment by casassg** [comment]
@Bobgy curious if we can include this into the ongoing 1.7 release (if we think this is stable enough)

**Comment by Bobgy** [comment]
Sorry it took a while, I'm kind of busy with the release recently.

**Comment by casassg** [comment]
No worries, totally understand.  😄 

Separate - Lmk if I can help w that in any way as well (looking for ways to become more involved here as well)

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you for implementing this nice feature! Love it

The change is relatively straightforward and passing all the tests, so I think we can include it in 1.7.0 without much risk.

It'll be even better showing the version description in KFP UI & supporting changing description when uploading a version from KFP UI, but that can be a separate PR and that can be implemented by a different contributor too.

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you for implementing this nice feature! Love it

The change is relatively straightforward and passing all the tests, so I think we can include it in 1.7.0 without much risk.

It'll be even better showing the version description in KFP UI & supporting changing description when uploading a version from KFP UI, but that can be a separate PR and that can be implemented by a different contributor too.

**Pull request merged**
