### PR TITLE
chore: Batch update pipeline spec go generated code

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
@chensun, I think we can unhold after updating to include changes in https://github.com/kubeflow/pipelines/pull/9085

**Comment by chensun** [comment]
> @chensun, I think we can unhold after updating to include changes in #9085

meant to quote and reply but somehow edited in place...

Anyway, regenerated.

**Pull request merged**
