### PR TITLE
Changing the default volume size to 30

### PR DESCRIPTION
**Pull request by gautamkmr**
Changing the default value for volume size from 1 to 30 GB.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
Links to official docs or other places where they recommend 30?

/ready-to-test

**Comment by gautamkmr** [comment]
> Links to official docs or other places where they recommend 30?

I don't think sagemaker [official guide](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DebugRuleConfiguration.html#sagemaker-Type-DebugRuleConfiguration-VolumeSizeInGB) says anything on default value. That number is being used in component .yaml file

**Pull request merged**
