### PR TITLE
Move backend unit tests to Travis

### PR DESCRIPTION
**Pull request by yebrahim**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/589)

### CODE REVIEW

**Comment by yebrahim** [comment]
@IronPan what else do we need to change here to stop unit tests suite from starting?

**Comment by IronPan** [comment]
Can you remove the test entry in here
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/kubeflow-presubmits.yaml

**Pull request merged**
