### PR TITLE
Update component yaml reference to eb830cd73ca148e5a1a6485a9374c2dc068314bc

### PR DESCRIPTION
**Pull request by hongye-sun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1282)

### CODE REVIEW

**Comment by hongye-sun** [comment]
/hold

Wait for sample test to finish.

**Comment by hongye-sun** [comment]
/hold cancel
/approve

All tests passed.

**Comment by Ark-kun** [comment]
BTW, This whole process is getting automated in https://github.com/kubeflow/pipelines/pull/1283

**Pull request merged**
