### PR TITLE
chore(frontend): fix s3 artifact structure for Argo 3.1+. Fix #5930

### LINKED ISSUE #5930: [frontend] artifact preview & visualization breaks with argo v3.1+
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

kfp standalone
*  KFP version: 1.7.0-alpha.1

### Steps to reproduce

image

### Expected result

artifacts should show preview, visualizations should show up

### Materials and Reference

Root cause: argo removed some information in workflow status.
Previously, artifacts contain an object of information, but now artifacts only contain their keys.
See workflows.argoproj.io/outputs annotation
> workflows.argoproj.io/outputs: >-
      {"artifacts":[{"name":"main-logs","s3":{"key":"artifacts/file-passing-pipelines-xz8xs/2021/06/28/file-passing-pipelines-xz8xs-3422213888/main.log"}}]}

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by zijianjoy**
**Description of your changes:**
Fix #5930

Note: I found that there are some workflow steps which were not successful in writing main.log file (such file was shown as 0 byte file on minio). Others are working fine:

fixargo

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by zijianjoy** [comment]
Test failures are resolved.

**Comment by Bobgy** [comment]
Note, I'm changing title to chore, because this is never a user visible bug, we introduced the new problem and fixes it between releases.

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you for fixing this release blocker!

**Pull request merged**
