### PR TITLE
DEPRECATE(sdk): DSL - Deprecated output_artifact_paths parameter in ContainerOp constructor

### PR DESCRIPTION
**Pull request by Ark-kun**
The users should switch to file_outputs instead.
Previously `file_outputs` only supported small data outputs, but now it supports big files.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2334)

### CODE REVIEW

**Comment by Bobgy** [comment]
@Ark-kun does this need to get merged?

**Comment by Bobgy** [comment]
What do you think about the new title?
@Ark-kun 

I can add some configuration to make these PRs show up in a separate section in changelog.

**Comment by Bobgy** [comment]
/lgtm
/hold

leave to you to decide title

**Comment by neuromage** [comment]
@Ark-kun how does file outputs support big data passing? What happens if a downstream component refers to the output using inputValue? 

/cc @paveldournov 
/cc @hongye-sun 
/cc @james-jwu

**Pull request merged**
