### PR TITLE
Removing the unnecessary trunk when generating the DB name 

### PR DESCRIPTION
**Pull request by IronPan**
The marketplace app name can never exceed 32 char. Remove the trunk to improve code readability. 

/assign @rmgogogo

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2151)

### CODE REVIEW

**Comment by rmgogogo** [comment]
"The marketplace app name can never exceed 32 char. Remove the trunk... "
Didn't understand why you mention app name limitation but here is DB name. Anyway, LGTM

**Comment by rmgogogo** [comment]
Got it, saw you also remove trunk for release name.

**Comment by IronPan** [comment]
test failures not related to the change

**Pull request merged**
