### PR TITLE
chore: add missing places we need to upgrade mysql to 5.7

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Follow up fix of https://github.com/kubeflow/pipelines/pull/5278.
It broke gcp marketplace postsubmit test.
It's likely the lost+found argument that's the root cause, but I think it's nice keeping both manifests in sync anyway.
EDIT: that was wrong, root cause in https://github.com/kubeflow/pipelines/pull/5301#issuecomment-799358066

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by Bobgy** [comment]
Hmmm, this might not fix it.

The error message was unexpected:
https://oss-prow.knative.dev/view/gs/oss-prow/logs/kubeflow-pipeline-postsubmit-mkp-e2e-test/1371095476882903040#1:build-log.txt%3A8109

> Failed to pull image "gcr.io/ml-pipeline-test/hosted/3cdb1d9954c9edf058c556b401ef7b3b76577708/mysql:1.4.1": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/ml-pipeline-test/hosted/3cdb1d9954c9edf058c556b401ef7b3b76577708/mysql:1.4.1 not found: manifest unknown: Failed to fetch "1.4.1" from request "/v2/ml-pipeline-test/hosted/3cdb1d9954c9edf058c556b401ef7b3b76577708/mysql/manifests/1.4.1".

**Comment by zijianjoy** [comment]
/lgtm /approve

Thank you Yuan for the fix! Good finding on the hidden failure from `tag_for_hosted.sh`.

**Pull request merged**
