### PR TITLE
fix(docs): IR -> Pipeline Spec

### PR DESCRIPTION
**Pull request by gregsheremeta**
**Description of your changes:**
fix(docs): IR -> Pipeline Spec

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by hbelmiro — COMMENTED** [review]
/lgtm

@gregsheremeta fyi `kubeflow-pipelines-sdk-execution-tests` failure is fixed by https://github.com/kubeflow/pipelines/pull/10975, which is blocked by https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2313, which is pending review from one of the [approvers](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/6b8bc0d60cf4f07de78c450a4d2842289f4f7b7e/prow/prowjobs/kubeflow/OWNERS#L1): @chensun @gkcalat @james-jwu @zijianjoy.

cc @DharmitD

**Review by chensun — APPROVED** [review]
/lgtm

**Comment by hbelmiro** [comment]
> /lgtm
> 
> @gregsheremeta fyi `kubeflow-pipelines-sdk-execution-tests` failure is fixed by #10975, which is blocked by [GoogleCloudPlatform/oss-test-infra#2313](https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2313), which is pending review from one of the [approvers](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/6b8bc0d60cf4f07de78c450a4d2842289f4f7b7e/prow/prowjobs/kubeflow/OWNERS#L1): @chensun @gkcalat @james-jwu @zijianjoy.
> 
> cc @DharmitD

@gregsheremeta the blocking PRs were merged. If you rebase it, it should be ready to merge.

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Pull request merged**
