### PR TITLE
Bump TFX to 0.21.2

### PR DESCRIPTION
**Pull request by numerology**
This is a rather complex version bumping, including following work items:

- [x] Bump TFX dependency in backend/test-infra
- [x] Bump TFMA to 0.21.5 in frontend server
- [x] Modernize prebuilt TFX sample by deprecating ModelValidator
- [x] Verify caching works
- [x] Verify TFMA/TFDV and TB viz with and without caching (on a dev frontend)

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3255)

### CODE REVIEW

**Comment by numerology** [comment]
/assign @Bobgy 

Yuan do you mind taking a look to see whether TFMA part is good? Thanks!

**Comment by Bobgy** [comment]
@numerology look at https://github.com/kubeflow/pipelines/issues/3223#issuecomment-597473783

Fixes https://github.com/kubeflow/pipelines/issues/3223

**Comment by numerology** [comment]
> @numerology look at [#3223 (comment)](https://github.com/kubeflow/pipelines/issues/3223#issuecomment-597473783)
> 
> Fixes #3223

Thanks! It's working now

**Pull request merged**
