### PR TITLE
feat(sdk): Accepts higher PyYAML versions

### LINKED ISSUE #8666: [sdk] Accept higher PyYAML versions
### Feature Area

/area sdk

### What feature would you like to see?

The SDK currently requires `PyYAML>=5.3,<6`. I would like the SDK to accept higher versions - `>=6` specifically.

### What is the use case or pain point?

Would like to use kfp SDK from Google Cloud Composer. However, the latest Google Cloud Composer comes with `PyYAML==6.0` as per [Cloud Composer version list](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions)

### Is there a workaround currently?

There are some workarounds but I think it's no problem for the SDK to accept newer PyYAML versions. I double-checked the [change list of PyYAML 6.0](https://github.com/yaml/pyyaml/blob/6.0/CHANGES#L7-L18). I believe those changes have no impact to kfp SDK.

---

Love this idea? Give it a 👍.

### PR DESCRIPTION
**Pull request by mai-nakagawa**
**Description of your changes:**

Fixes #8666.

Looking at the [change list of PyYAML 6.0](https://github.com/yaml/pyyaml/blob/6.0/CHANGES#L7-L18), I believe those changes have no impact to kfp SDK.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
Thanks for this, @mai-nakagawa.

/ok-to-test

**Review by connor-mccarthy — CHANGES_REQUESTED** [review]
Can you please run `pip-compile` against this file per instructions [here](https://github.com/kubeflow/pipelines/blob/3fa2ac5f4e04111bf5758fd5c01a2f0d7ac4b866/sdk/python/requirements.txt#L5)?

Can you also please update the release notes [here](https://github.com/kubeflow/pipelines/blob/3fa2ac5f4e04111bf5758fd5c01a2f0d7ac4b866/sdk/RELEASE.md?plain=1#L24)?

**Comment by connor-mccarthy** [comment]
@mai-nakagawa, you can ignore `kubeflow-pipelines-sdk-execution-tests` test failures

**Comment by mai-nakagawa** [comment]
> Can you please run `pip-compile` against this file per instructions [here](https://github.com/kubeflow/pipelines/blob/3fa2ac5f4e04111bf5758fd5c01a2f0d7ac4b866/sdk/python/requirements.txt#L5)?

@connor-mccarthy Thanks for reviewing. I ran the command successfully without any updates in `requirements.txt` file, getting the following output:
```
➜  python git:(patch-1) pip-compile --no-emit-index-url requirements.in
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
#
# This file is autogenerated by pip-compile with Python 3.7
# by the following command:
#
#    pip-compile --no-emit-index-url requirements.in
#
absl-py==1.2.0
    # via -r requirements.in
attrs==22.1.0
    # via jsonschema
cachetools==5.2.0
    # via google-auth
certifi==2022.6.15
    # via
    #   kfp-server-api
    #   kubernetes
    #   requests
charset-normalizer==2.1.1
    # via requests
click==8.1.3
    # via
    #   -r requirements.in
    #   typer
cloudpickle==2.1.0
    # via -r requirements.in
deprecated==1.2.13
    # via -r requirements.in
docstring-parser==0.14.1
    # via -r requirements.in
fire==0.4.0
    # via -r requirements.in
google-api-core==2.8.2
    # via
    #   -r requirements.in
    #   google-cloud-core
    #   google-cloud-storage
google-auth==2.11.0
    # via
    #   -r requirements.in
    #   google-api-core
    #   google-cloud-core
    #   google-cloud-storage
    #   kubernetes
google-cloud-core==2.3.2
    # via google-cloud-storage
google-cloud-storage==2.5.0
    # via -r requirements.in
google-crc32c==1.5.0
    # via google-resumable-media
google-resumable-media==2.3.3
    # via google-cloud-storage
googleapis-common-protos==1.56.4
    # via google-api-core
idna==3.3
    # via requests
importlib-metadata==4.12.0
    # via
    #   click
    #   jsonschema
jsonschema==3.2.0
    # via -r requirements.in
kfp-pipeline-spec==0.1.17
    # via -r requirements.in
kfp-server-api==2.0.0a4
    # via -r requirements.in
kubernetes==23.6.0
    # via -r requirements.in
oauthlib==3.2.0
    # via requests-oauthlib
protobuf==3.20.1
    # via
    #   -r requirements.in
    #   google-api-core
    #   googleapis-common-protos
    #   kfp-pipeline-spec
pyasn1==0.4.8
    # via
    #   pyasn1-modules
    #   rsa
pyasn1-modules==0.2.8
    # via google-auth
pyrsistent==0.18.1
    # via jsonschema
python-dateutil==2.8.2
    # via
    #   kfp-server-api
    #   kubernetes
pyyaml==5.4.1
    # via
    #   -r requirements.in
    #   kubernetes
requests==2.28.1
    # via
    #   google-api-core
    #   google-cloud-storage
    #   kubernetes
    #   requests-oauthlib
    #   requests-toolbelt
requests-oauthlib==1.3.1
    # via kubernetes
requests-toolbelt==0.9.1
    # via -r requirements.in
rsa==4.9
    # via google-auth
six==1.16.0
    # via
    #   fire
    #   google-auth
    #   jsonschema
    #   kfp-server-api
    #   kubernetes
    #   python-dateutil
strip-hints==0.1.10
    # via -r requirements.in
tabulate==0.8.10
    # via -r requirements.in
termcolor==1.1.0
    # via fire
typer==0.6.1
    # via -r requirements.in
typing-extensions==4.3.0 ; python_version < "3.9"
    # via
    #   -r requirements.in
    #   importlib-metadata
uritemplate==3.0.1
    # via -r requirements.in
urllib3==1.26.12
    # via
    #   kfp-server-api
    #   kubernetes
    #   requests
websocket-client==1.4.0
    # via kubernetes
wheel==0.37.1
    # via strip-hints
wrapt==1.14.1
    # via deprecated
zipp==3.8.1
    # via importlib-metadata

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

**Comment by mai-nakagawa** [comment]
> Can you also please update the release notes [here](https://github.com/kubeflow/pipelines/blob/3fa2ac5f4e04111bf5758fd5c01a2f0d7ac4b866/sdk/RELEASE.md?plain=1#L24)?

@connor-mccarthy Should I update [in L24](https://github.com/kubeflow/pipelines/blob/3fa2ac5f4e04111bf5758fd5c01a2f0d7ac4b866/sdk/RELEASE.md?plain=1#L24) as you specify or [in L10](https://github.com/kubeflow/pipelines/blob/3fa2ac5f4e04111bf5758fd5c01a2f0d7ac4b866/sdk/RELEASE.md?plain=1#L10)? I'm asking it because kfp `v2.0.0b10` was already released in last December as per [the release history](https://pypi.org/project/kfp/#history).

**Comment by connor-mccarthy** [comment]
@mai-nakagawa 

> Should I update in L24 as you specify or in L10?

L10 is correct. Good catch!

> without any updates in requirements.txt file

Looks like the pip-compile output is unchanged. That's no problem. Thanks for letting me know.

**Comment by mai-nakagawa** [comment]
> > Should I update in L24 as you specify or in L10?
> 
> L10 is correct. Good catch!

@connor-mccarthy Updated by https://github.com/kubeflow/pipelines/pull/8665/commits/75e9eb217db4ef16f4e3866ffdf1fb3bf2302d0c. PTAL 🙏

**Comment by mai-nakagawa** [comment]
I just clicked `re-request review from @connor-mccarthy`, which automatically removed @zijianjoy unexpectedly 😢

**Comment by connor-mccarthy** [comment]
/lgtm
/approve

Thanks, @mai-nakagawa!
Manually merging, as `kubeflow-pipelines-sdk-execution-tests` failures are unrelated to these changes.

**Pull request merged**
