### PR TITLE
chore(mlmd): fix MLMD update scripts

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
/cc @zijianjoy 
I'm getting this low risk change merged quickly.

**Comment by zijianjoy** [comment]
Thank you for updating MLMD update script!

**Pull request merged**
