### PR TITLE
chore(sdk): update requirements.in to be in sync with setup.py

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
https://github.com/kubeflow/pipelines/blob/master/sdk/python/setup.py
https://github.com/kubeflow/pipelines/blob/master/sdk/python/requirements.in

the two should be in sync

Part of https://github.com/kubeflow/pipelines/issues/5137

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by chensun** [comment]
> https://github.com/kubeflow/pipelines/blob/master/sdk/python/setup.py
> https://github.com/kubeflow/pipelines/blob/master/sdk/python/requirements.in

> the two should be in sync

My take on this is instead of keeping the two in sync, we may want to reduce them to one. 

If we were to let Renovate bot to update `sdk/python/requirements.txt` (https://github.com/kubeflow/pipelines/pull/5056), we may consider remove `sdk/python/requirements.in`.

Alternatively, as @Ark-kun said [here](https://github.com/kubeflow/pipelines/issues/5137#issuecomment-785430958)-- let `setup.py` reference `requirements.in` (I have one concern that if we keep `requirements.in`, while let Renovate bot to update `requirements.txt`, the two are not really related, but people may think they do).

**Comment by Bobgy** [comment]
Yes, I think taking Renovate bot into consideration can be more complex. I'm not exactly sure how it updates versions, when we update versions, packages must be scoped to a certain python version. I'll leave the decision to you.

**Comment by chensun** [comment]
I want to echo again what I said [here](https://github.com/kubeflow/pipelines/issues/5137#issuecomment-785467128). I think `pip install -r sdk/python/requirements.txt` doesn't represent the most common user journey -- think about our notebook samples, it only has `pip install kfp` or `pip install kfp==<pinned version>`, but I've rarely seen `pip install -r sdk/python/requirements.txt`. 

So I would suggest we move away from installing requirements.txt in tests. So the tests creates an environment as close to a fresh installation of `pip install kfp`. If there's a newly emerged dependency issue, we would probably be able to see it in tests.

P.S.: Taking tfx for example, their [`requirements.txt`](https://github.com/tensorflow/tfx/blob/463586187bf0cdc1e7290f27bf5096d2f13f1593/requirements.txt) contains nothing but [`-e .`](https://pip.pypa.io/en/stable/reference/pip_install/?highlight=requirements.txt#cmdoption-e) (read from setup.py)

**Comment by chensun** [comment]
All that said, I think we can merge this PR first and figure out how to handle the duplication later.

/lgtm

/hold (remove when you're ready for merge, just keep it open for your attention on the above comments)

Thanks for making this effort, Yuan.

**Comment by Bobgy** [comment]
/unhold

I agree with Chen, testing as what users would get is an important test. We used to do that, the result was that from time to time presubmit broke without any clues and we needed to dig through the details to find out why.

**Pull request merged**
