### PR TITLE
feat(sdk.v2): Allow set pipeline_root via @dsl.pipeline decorator. Make pipeline_root optional.

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
- Setting `pipeline_root`/`output_directory` via `@dsl.pipeline` decorator was added in v1 but not used in v2. Make it available in v2.
- Rename `output_directory` to `pipeline_root` in `@dsl.pipeline` decorator, so that it's consistent with `pipeline_root` argument in `Compiler.compiler()` method (also consistent with TFX if that matters).
- The `pipeline_root` in `Compiler.compile()` was previously a required argument, change it to optional as it no longer makes sense to enforce it when user can also set it via `@dsl.pipeline` decorator. Similarly, make it optional for compiler cli.

BREAKING CHANGE:
- Renaming `output_directory` to `pipeline_root` in `@dsl.pipeline` decorator. The background for naming it `output_directory` was to [avoid possible confusion with pipeline root spec](https://github.com/kubeflow/pipelines/pull/4927#discussion_r546946026). However, on a second thought, the pipeline root spec (IR) is non-user-facing implementation details, whereas using `output_directory` in one place and `pipeline_root` in other places is probably more confusing. 
- Changing `pipeline_root` to an optional argument in `Compiler.compile()` requires swapping its position with `output_path` (the path to compiler output, i.e., pipeline job json). This could break existing v2 users if they call the `compile()` method with positional arguments. No breakage if they use keyword arguments though.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by chensun** [comment]
@numerology @neuromage , can you please review the "BREAKING CHANGES" section in the description.

/hold

**Comment by neuromage** [comment]
/lgtm

The breaking changes seem reasonable.

**Pull request merged**
