### PR TITLE
fix(components): Refactor Kubeflow E2E mnist example

### PR DESCRIPTION
**Pull request by andreyvelich**
**Description of your changes:**
Fixes: https://github.com/kubeflow/pipelines/issues/5306.
Blocked by: https://github.com/kubeflow/pipelines/pull/5287, https://github.com/kubeflow/pipelines/pull/5676
I refactored E2E MNIST Kubeflow example. I named it `kubeflow-e2e-mnist` to be more precise and I added OWNERS file.
Please let me know if I need to add someone else in the OWNERS.

For Katib, TFJob and KFServing I am using the upstream launchers to run the KFP tasks.
This example uses namespaced Pipeline to run it from the Kubeflow Notebook and we should merge: https://github.com/kubeflow/pipelines/pull/5287 to update the KFP SDK.

Please take a look.

/assign @Bobgy @zijianjoy @Tomcli @chinhuang007
/cc @gaocegege @johnugeorge @elikatsis 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by Bobgy** [comment]
Thank you for these efforts!
/cc @zijianjoy 
This sounds like a good example to verify kubeflow e2e! May be we can point distributions to test this.

**Comment by Bobgy** [comment]
I'll report back when there's progress on the KFP PR

**Comment by zijianjoy** [comment]
> Thank you for these efforts!
> /cc @zijianjoy
> This sounds like a good example to verify kubeflow e2e! May be we can point distributions to test this.

Thank you Yuan! Added an item to use this E2E example to validate Kubeflow deployment in https://github.com/kubeflow/pipelines/projects/12

**Comment by zijianjoy** [comment]
Hello @andreyvelich , I have validated the E2E mnist example using this PR, but I encountered this issue but couldn't explain why, would you like to help on debugging? https://github.com/kubeflow/gcp-blueprints/issues/271

**Comment by andreyvelich** [comment]
Hi @Bobgy @zijianjoy, I was able to run this example in Multi-User mode using the latest KFP SDK version [1.6.5](https://pypi.org/project/kfp/1.6.5/).
As I can see, this version includes this SDK change: https://github.com/kubeflow/pipelines/pull/5676.

If you are fine with this example, I think we can finally merge it.

cc @elikatsis @johnugeorge

**Comment by zijianjoy** [comment]
Thank you @andreyvelich for the change! 

I redeployed a cluster to validate the E2E workflow, I encountered the following issue in the first step:

mnist_firststep

How to look closer for the log to debug further?

**Comment by andreyvelich** [comment]
Thank you for the testing @zijianjoy.
Which version of GKE cluster are you using ?
If your GKE Nodes are using `Container-Optimized OS with Containerd` image type, do you have the problem mentioned here: https://github.com/kubeflow/gcp-blueprints/issues/271#issuecomment-846138743?

**Comment by zijianjoy** [comment]
/lgtm
/approve

Debugged with Andrey offline, I am able to run the E2E example:

1. We shouldn't restrict resource quota in user profile, which is why I failed the pipeline in https://github.com/kubeflow/pipelines/pull/5433#issuecomment-884673380.
2. We are able to ping the prediction endpoint with `http://{}-predictor-default.{}.svc.cluster.local/v1/models/{}:predict`, but not `mnist-e2e.namespace1.svc.cluster.local`, which is supposed to be the right way to call prediction service.

Approving this PR, thank you so much Andrey again for helping to refresh the E2E workflow example!

**Pull request merged**
