### PR TITLE
404 page

### LINKED ISSUE #55: Frontend should give 404s for non-existing pages/routes.
http://localhost:9090/pipelinez

### PR DESCRIPTION
**Pull request by yebrahim**
Fixes #55.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/135)

### CODE REVIEW

**Comment by yebrahim** [comment]
Ping.

**Comment by qimingj** [comment]
@rileyjbauer can you review it?

**Comment by Ark-kun** [comment]
Is this a real 404? (Does it give the 404 HTTP code?)

**Comment by yebrahim** [comment]
Pipelines UI is singe page app, which means all the routing is done on the client, so the server sends the HTML/JS/CSS bundle just once (or multiple times when we have code splitting), returning 200 status, and never serving such requests again.

But what's the value of having a 404 return code here? We don't really care about search engine crawling, SEO, or any of that, we're not a public website either

**Comment by Ark-kun** [comment]
When I visit a non-existing url like http://localhost:8080/pipelines/ I'd like to see a proper error instead of a blank page with some scripts.

**Comment by yebrahim** [comment]
That requires a change to Ambassador, it's not something the Pipelines frontend can handle. A request to /pipelines won't even reach our webserver.

**Comment by Ark-kun** [comment]
> That requires a change to Ambassador, it's not something the Pipelines frontend can handle. A request to /pipelines won't even reach our webserver.

Understood. Then how does this fix https://github.com/kubeflow/pipelines/issues/55 ?

**Comment by yebrahim** [comment]
I misread your issue. This fixes all frontend-managed pages. For example if the Pipelines UI is at http://localhost:8080/pipeline then this handles going to http://localhost/pipeline/#/jobz instead of http://localhost/pipeline/#/jobs.

Outside this change, that issue shouldn't be on the Pipelines repo, it should be on kubeflow/kubeflow, that's where the Ambassador config is managed.

**Pull request merged**
