### PR TITLE
Add sdk test coverage.

### PR DESCRIPTION
**Pull request by numerology**
Add sdk test coverage collection and report to coveralls.io.

Patched #898

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1858)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Can you provide more information as for why `--omit */site-packages/*` is the correct way to handle the paths?
I'm concerned that this just excludes certain traces from consideration.
I'd like to understand why different traces produce different paths.

P.S. It would be great to make source viewing work. Right now when I click on https://coveralls.io/builds/25178194/source?filename=kfp/components/_components.py I get 
```
SOURCE NOT AVAILABLE
The file "kfp/components/_components.py" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.```

**Comment by numerology** [comment]
> Can you provide more information as for why `--omit */site-packages/*` is the correct way to handle the paths?
> I'm concerned that this just excludes certain traces from consideration.
> I'd like to understand why different traces produce different paths.
> 
> P.S. It would be great to make source viewing work. Right now when I click on https://coveralls.io/builds/25178194/source?filename=kfp/components/_components.py I get
> 
> ```
> SOURCE NOT AVAILABLE
> The file "kfp/components/_components.py" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.```
> ```

Yes I got it too. Do you think it's okay to solve the problem in a following PR? I suspect that it's because we didn't set 'src' for coveralls correctly.

**Comment by gaoning777** [comment]
https://github.com/kubeflow/pipelines/pull/898 also adds the coverage. Which one do we want to merge?

**Comment by numerology** [comment]
> #898 also adds the coverage. Which one do we want to merge?

@gaoning777 Let's merge that one. Ark-kun also makes coverage display works IIRC.

**Pull request closed without merging**
