### PR TITLE
fix(sdk): fix --no-deps flag usage

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title 
convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
`test-run-all-gcpc-modules` is independent of these changes. Fixing separately.

FYI @chensun

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks for the quick fix!

**Pull request merged**
