### PR TITLE
[WIP] chore(test): remove pinning cluster version

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
Part of https://github.com/kubeflow/pipelines/issues/10779

**Comment by gmfrasca** [comment]
Hey @chensun - looking at the CI logs here, it appears the GKE cluster was successfully created and the failure is coming from the integration workflow test itself.  I'm not terribly familiar with the GKE platform but IMO that means this PR is working as expected, and the CI failure is unrelated.  Since this is blocking/causing issues with CI on other PRs, perhaps we can retest to see if it's an intermittent problem?

**Comment by chensun** [comment]
> Hey @chensun - looking at the CI logs here, it appears the GKE cluster was successfully created and the failure is coming from the integration workflow test itself. I'm not terribly familiar with the GKE platform but IMO that means this PR is working as expected, and the CI failure is unrelated. Since the issue this PR fixes is blocking/causing problems with CI on other PRs, perhaps we can retest to see if it's an intermittent problem?

After the cluster was created, the test would time out in ~1 hr due to the Argo docker-in-docker issue that's mentioned in the comment, the fix needs to be migrating away from using Argo DinD to build test images.

I've made `kubeflow-pipeline-e2e-test` optional in https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2266, it should not block other PRs.

**Pull request closed without merging**
