### PR TITLE
SDK - Moved the @python_component decorator test to dsl tests

### PR DESCRIPTION
**Pull request by Ark-kun**
Removing stray dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3324)

### CODE REVIEW

**Comment by numerology** [comment]
If the goal is to deprecate `@python_component`, shall we add a deprecation warning there?

**Comment by Ark-kun** [comment]
> If the goal is to deprecate `@python_component`, shall we add a deprecation warning there?

The main goal was to remove dependency between `test_python_op.py` and `kfp.dsl`.

But since I do not see any usage of `@python_component` I've added a deprecation warning.

**Pull request merged**
