### PR TITLE
Fixes test flakiness caused by "unsupported operand type(s) for -=: 'Retry' and 'int'"

### PR DESCRIPTION
**Pull request by Bobgy**
I want to first test if this fix actually help.
part of https://github.com/kubeflow/pipelines/issues/2556
The fix come from https://stackoverflow.com/a/37531821

/kind bug

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2563)

### CODE REVIEW

**Comment by numerology** [comment]
Thanks @Bobgy ! This might need some time to run, though...

**Comment by Bobgy** [comment]
@numerology np, I will retry a few time today to verify.

**Comment by Ark-kun** [comment]
Thanks for fixing the issue!

**Comment by Bobgy** [comment]
First try succeeded
/retest

**Comment by Bobgy** [comment]
Second try succeeded
/test kubeflow-pipeline-e2e-test
/test kubeflow-pipeline-sample-test

**Comment by Bobgy** [comment]
Third try succeeded
/test kubeflow-pipeline-e2e-test
/test kubeflow-pipeline-sample-test

**Comment by Bobgy** [comment]
Fourth try succeeded
/test kubeflow-pipeline-e2e-test
/test kubeflow-pipeline-sample-test

**Comment by Bobgy** [comment]
Fourth try succeeded
/test kubeflow-pipeline-e2e-test
/test kubeflow-pipeline-sample-test

**Comment by Bobgy** [comment]
Sixth try failed with
```
Step #0: go: error loading module requirements
Step #0: The command '/bin/sh -c GO111MODULE=on go build -o /bin/persistence_agent backend/src/agent/persistence/*.go' returned a non-zero code: 1
```
Not related to this fix, but it shouldn't happen. Because image building should be cached. It seems inverse-proxy-agent is wrongly queried even though it is not built.

/test kubeflow-pipeline-e2e-test
/test kubeflow-pipeline-sample-test

**Comment by Bobgy** [comment]
Seventh try succeeded.
I think we can merge and later take an eye on if this error shows up again.

/approve

**Pull request merged**
