### PR TITLE
feat(deployment): Kustomize manifest for Azure deployments

### PR DESCRIPTION
**Pull request by jotaylo**
**Description of your changes:**
Kustomize manifest for KFP deployment using Azure Database for MySQL and MinIO gateway to Azure Blobstore

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by jotaylo** [comment]
@googlebot I signed it!

**Comment by Bobgy** [comment]
@Ark-kun let's the continue the discussion here.

We actually accepted AWS manifests from people working for AWS.
https://github.com/kubeflow/pipelines/pull/4350

The previous AWS manifests we rejected were maintained by community.

Do you have any concerns with this?

**Comment by Bobgy** [comment]
@jotaylo I want to confirm responsibilities for putting the manifests in kfp repo:
* Before each release, we'll ask your team to verify your manifests still work for Azure
* For user issues reported specific to Azure, we'd expect response from your team members
* In the long term, you should either maintain your own test infra that continuously ensure it's working so we can reduce some of the manual efforts before release

Do you think that's reasonable?
/cc @dtzar @eedorenko @sudivate

**Comment by eedorenko** [comment]
> Do you think that's reasonable?
Sounds good to me.

/approve

**Comment by Ark-kun** [comment]
> We actually accepted AWS manifests from people working for AWS.
> #4350
> 
> The previous AWS manifests we rejected were maintained by community.
> 
> Do you have any concerns with this?

I do not have any concerns. I welcome all contributors. I just wanted our response to be consistent. Glad to see it is consistent.

**Comment by Bobgy** [comment]
Sorry for the delay, I was on vacation.

**Pull request merged**
