### PR TITLE
feat(cache): ability to specify extra parameters for DB connection

### PR DESCRIPTION
**Pull request by Subreptivus**
Ability to specify extra parameters for DB connection.

For example: `/bin/cache_server --db_driver=$(DBCONFIG_DRIVER) --db_host=$(DBCONFIG_HOST_NAME) --db_port=$(DBCONFIG_PORT) --db_name=$(DBCONFIG_DB_NAME) --db_user=$(DBCONFIG_USER) --db_password=$(DBCONFIG_PASSWORD) --db_extra_params={\"tls\": \"preferred\"} --namespace_to_watch=$(NAMESPACE_TO_WATCH)`

### CODE REVIEW

**Comment by Ark-kun** [comment]
Thank you for your contribution.
/ok-to-test

**Comment by Ark-kun** [comment]
Hello.
Could you please fix the conflict?

**Comment by Subreptivus** [comment]
Already merged the same code from another user: #5599

**Pull request closed without merging**
