### PR TITLE
feat(components): Restructure the components directory

### PR DESCRIPTION
**Pull request by IronPan**
**Description of your changes:**
Move most the components to the contrib/ directory, except the aws/azure/ibm/google-cloud/kubeflow components.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by SinaChavoshi — COMMENTED** [review]
In principle I agree with the restructure / clean up. However this is a fairly large change that affects many contributed components. This move will erase the history for all affected components, and could break users who are not linking to head. I believe we should raise this in the community meeting first if that has not already been done.

**Comment by neuromage** [comment]
/lgtm

Ideally, users should not be linking to the main branch so their components are always pinned to a specific version for reproducibility.

**Comment by Ark-kun** [comment]
Hello, @IronPan. Thank you for your proposal.

Can you please outline all the ways this change improves the critical user journeys?

What are the reported user issues, this change is solving?

This PR is marked as a feature, so it would be great to understand this feature, its pros and cons.

Could you prepare a public design document RFC for your idea and present it on one of the next community meetings as well as the Pipelines team design review? I think it's worth to discussing this topic and get formal approval from all the key stakeholders.

**Comment by neuromage** [comment]
> Could you prepare a public design document RFC for your idea and present it on one of the next community meetings as well as the Pipelines team design review? I think it's worth to discussing this topic and get formal approval from all the key stakeholders.

@Ark-kun That's not necessary. I've already discussed this change with @IronPan and approved it. The goal is to clean up the components directory and have clear ownership and boundaries between supported components and community contributions.

/lgtm

**Comment by Ark-kun** [comment]
>That's not necessary. I've already discussed this change with @IronPan and approved it. 

@neuromage Having one team member approve something is a good first step, but the Pipelines community seems to be bigger than that. Can you please provide the user testimonies that clearly demonstrate that the community and customers approve the significant changes that you want to make?
The last community meeting was yesterday and the next meeting will be on August 4. You can book a slot for the proposal discussion.

P.S. Do we have any user studies that conclusively back the hypothesis that the community and the paying customers are delighted when global changes are made without asking for their feedback?

/cc @Bobgy 
/cc @james-jwu 
/cc @paveldournov

**Pull request closed without merging**
