### PR TITLE
add working dir to ContainerOps

### PR DESCRIPTION
**Pull request by hamedhsn**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1879)

### CODE REVIEW

**Comment by Ark-kun** [comment]
AFAIK, you can already set that property using `container_op.container.working_dir`.

**Comment by hongye-sun** [comment]
@hamedhsn, I think Alexey is right. You should use `container_op.container.working_dir` to specify working_dir. We are not planning to expose all container setting to top level.

**Comment by hamedhsn** [comment]
sure. it is enough then.
closing this, thanks

**Pull request closed without merging**
