### PR TITLE
SDK - Components - Use relative imports for tests

### PR DESCRIPTION
**Pull request by Ark-kun**
This makes tests easier to run in local dev scenarios.

Fixes https://github.com/kubeflow/pipelines/issues/3786

### CODE REVIEW

**Comment by numerology** [comment]
@Ark-kun Do you mind providing an example where this is superior to absolute import?

Because in general this is not recommended by http://google.github.io/styleguide/pyguide.html#22-imports

**Comment by Ark-kun** [comment]
> @Ark-kun Do you mind providing an example where this is superior to absolute import?
> 
> Because in general this is not recommended by http://google.github.io/styleguide/pyguide.html#22-imports

I understand. However the relative layout has been traditionally used in KFP.
One reason is that it helps you be sure where all code comes from. With relative imports, code files in the working copy link to each other. If you change one of the files, the change is always reflected. With absolute imports, the code being imported can be affected by your installed packages and also your current directory. I had multiple cases when I had weird issues that just should not be happening. I change the code, but the tests still have weird errors. Turns out the tests were using the code of the installed package of an older version. Couple of time, the problems did not go away even when I uninstalled the package (beware of different virtual environments BTW), because it turned out I had it installed both as a system and --user package (and at different versions...).

I usually have ~6 working copies with different branches, so making sure the tests in each working copy use the code from the same working copy helps the development and debugging. Otherwise I need to remember which exact version is installed (which is also often different for different python versions).

Thanks.

**Comment by Bobgy** [comment]
/lgtm
I'd generally prefer absolute import too, but I understand python package import really has some uncertainty that's hard to troubleshoot. I wonder if we can consider fully isolated python environments for each project (virtualenvs that don't inherit system default packages?), is it possible?

If it's hard to do so, I don't think this PR needs to be blocked, because it only updates imports from tests which sounds reasonable to use relative imports.

**Comment by Ark-kun** [comment]
Another advantage of relative imports is that it makes the library and test code independent from the surrounding package. The code can be placed in different packages or directories and still work without any changes. This improves the portability of the library.

**Comment by numerology** [comment]
Regarding the name collision, I think if one installed a package twice (locally and into python site-packages) it's highly likely something wrong will occur. IMHO I don't think it's a great justification to prefer relative import, at the cost of readability and manageability, especially when the project grows bigger.

I believe if we can follow absolute importing strictly across the project, instead of mixing two styles everywhere, situation won't be that bad.

**Comment by Ark-kun** [comment]
> Regarding the name collision, I think if one installed a package twice (locally and into python site-packages) it's highly likely something wrong will occur.

The most common use case is not as complicated. (I should not have mentioned that exotic double install scenario).

A common situation is: You have some version of KFP installed. You have a local GIT working copy. You fix a bug in the library and write a test that verifies the bug fix. You run the test, but it fails. The test fails, because it imports the installed package, not the code in your GIT working copy.

**Comment by numerology** [comment]
> You run the test, but it fails. The test fails, because it imports the installed package, not the code in your GIT working copy.

Right, but I think it can be solved by `pip install -e .`, right? And IMO it's pretty straightforward b/c the error log will show it's actually shouting from python/lib/site-packages

**Comment by Ark-kun** [comment]
> Right, but I think it can be solved by `pip install -e .`, right?

That's true. This is what I have used before. But it does not work that well when you have multiple working copies. When you switch to a different windows you also need to remember to `pip install -e .`.

**Comment by Ark-kun** [comment]
But the most important aspect which for me outweighs the others is the portability aspect.

>Another advantage of relative imports is that it makes the library and test code independent from the surrounding package. The code can be placed in different packages or directories and still work without any changes. This improves the portability of the library.

The component library package is already independent from the KFP package and does not have any references to KFP.

Now the component library tests are independent too.

Portability allows growing the component ecosystem support beyond KFP. Imagine using the same components with KFP, TFX, CMLE, Airflow, Argo, Tekton, etc.

The CMLE Training package probably cannot depend on the full KFP. But it can depend on the KFP's component library.

**Comment by numerology** [comment]
I think we shall not mix the portability of the component ecosystem with the portability with the source code (and the associated development experience).

I am under the impression that when talking about the portability of KFP component eco-system, the shiny point is that the yaml spec is portable and can be executed without assuming excessive pre-baked dependencies. This is great.

However here, I don't think whether to use relative imports or not impacts the portability of KFP component ecosystem -- the compiled component yaml spec are always the same. It does not matter as long as component authors are not required to publish the source file alongside the component yaml, which I don't believe is something we want to do.

It seems to me that using relative import only benefits the case where:

1. one wishes to maintain multiple working copies of the component repo (let's say we isolate it out from KFP, which I believe is doable); and
2. one does not want to switch between virtual envs and do 'pip install' multiple times.

**Pull request merged**
