### PR TITLE
chore: Remove pip requirements from docker files

### PR DESCRIPTION
**Pull request by DavidSpek**
As discussed in https://github.com/kubeflow/pipelines/pull/5056#issuecomment-770355729, this PR removes the python dependencies that are within docker files to separate `requirements.txt` files so that those dependencies can also be analyzed by the Renovate bot. There are some Dockerfiles in `ibm-components` that I did not edit as they pipe the install command to `tail` for some reason and I did not want to break them. 

This PR will need some testing if the images still build with the CI, along with a review as I made all the changes by hand. 
/cc @Bobgy

### CODE REVIEW

**Comment by DavidSpek** [comment]
@Bobgy Should I rework this from `pip install`/`pip3 install` to `python3 -m pip install` and remove the `requirements.txt` files after installation everywhere?

**Comment by Bobgy** [comment]
Thank you for the contribution!

Sorry for the late reply, this is a little challenging to review, because many of those components are not maintained by first party.

If tests pass, I think it might be okay to merge this PR.

What do you think @numerology @chensun @Ark-kun ?

You know more about python dependency management than I do.

**Comment by DavidSpek** [comment]
I did notice that I was inconsistent in using pip or pip3, so I think this should be addressed regardless.

**Comment by Bobgy** [comment]
I'd suggest scoping down to just KFP server  images in the first PR, all of them are tested by presubmit so we can easily verify and merge

**Comment by DavidSpek** [comment]
I was just busy testing to build some images and the arena one seems to have an unrelated error, while the aws athena dockerfile is giving invalid sytanx for pip with anything I try (also seems to be using python2). Do you know off the top of your head what folders all contain first party dockerfiles?

**Comment by DavidSpek** [comment]
Just checked, and the original aws athena image is giving the same error. @PatrickXYS maybe something to look into.

**Comment by DavidSpek** [comment]
I'm going through all the images and actually testing building them so some third party images can stay in the PR and have more optimized dockerfiles.

**Comment by DavidSpek** [comment]
@Bobgy should be good after these tests pass, as I built all the images in the PR manually. I added `--no-cache-dir` to `backend/Dockerfile` and change `pip3 install -r requirements.txt` to `python3 -m pip install -r requirements.txt --no-cache-dir` in `backend/Dockerfile.visualization` to be consistent and reduce the image size slight;y.

**Comment by Bobgy** [comment]
That's awesome!
/lgtm

**Comment by Bobgy** [comment]
/assign @chensun @numerology 
any suggestions?

**Comment by numerology** [comment]
/lgtm

Thanks! @DavidSpek This is super helpful.

For my education, when are we going to pin the version of a dependency vs. not specifying its version constraint at all?

**Comment by DavidSpek** [comment]
@numerology I created the requirements files based on the original dockerfiles. Renovate should handle pinning all the dependency versions with a PR as far as I know.

**Comment by DavidSpek** [comment]
I will push the changes from https://github.com/kubeflow/pipelines/pull/4479/files to this PR tomorrow morning.

**Comment by DavidSpek** [comment]
Rebase did something weird. Looking into it now.

**Comment by DavidSpek** [comment]
@numerology The conflict and rebase issue I had have been solved and all the tests have passed.

**Comment by numerology** [comment]
/lgtm
/approve

Thanks!

**Comment by DavidSpek** [comment]
@Bobgy It looks like you still need to approve this as well.

**Comment by Bobgy** [comment]
/approve
Thank you!
Let's go with this!

**Pull request merged**
