### PR TITLE
remove duplicate volumes

### PR DESCRIPTION
**Pull request by gaoning777**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/558)

### CODE REVIEW

**Comment by Ark-kun** [comment]
This is not a fully correct solution.

Fully correct solution would be to dedup based on the volume itself, not the name. Then, if we have name conflicts, we should rename the volume+volumeMount (we have to do that when processing a task (ContainerOp), because later we won't know which volume is used by which volumeMount).

One solution to this is to have a method like `task.add_mounted_volume(volume, volume_mount)` which will automatically set the volume name to volume structure hash. That way different volumes will get different names and same volumes will get same names.

**Comment by gaoning777** [comment]
Maybe addvolume should be pipeline level thing because it gets converted to workflow level volumes in argo yaml.

**Comment by Ark-kun** [comment]
> Maybe addvolume should be pipeline level thing because it gets converted to workflow level volumes in argo yaml.

It's complicated because in Kubernetes volumes are specified at the Pod level. Argo has many properties that can be set both at workflow and at template levels. Maybe some day `volumes` will also be available in template. https://github.com/argoproj/argo/issues/1094

**Comment by gaoning777** [comment]
There is no pod level volumes, is there. AFAIK, there is pod level volume mount.

**Comment by Ark-kun** [comment]
> There is no pod level volumes, is there. AFAIK, there is pod level volume mount.

volumes are Pod-level
volumeMounts are Container-level

**Comment by gaoning777** [comment]
Make sense. Added a todo to add the support later.

**Comment by Ark-kun** [comment]
/lgtm
Issue: https://github.com/kubeflow/pipelines/issues/494

**Pull request merged**
