### PR TITLE
fix(backend): allow multiple values per key/op in filter. Fixes #4975

### LINKED ISSUE #4975: Can't apply multiple filters on the same key for a given op
### What steps did you take:

In a filter with more than one predicate using the same op **and** key, all but one of the predicates will be ignored. This is mostly relevant for the `NOT_EQUALS` and `IS_SUBSTRING` ops, although there might be unusual situations where someone wants multiple such predicates with other ops. At present, Making a request with such a filter does not raise any errors or warnings despite this surprising behavior.

An example of such a filter, serialized to JSON, is the following:

{ "predicates": [{
      "op": "IS_SUBSTRING",
      "key": "name",
      "stringValue": "a"
    }, {
      "op": "IS_SUBSTRING",
      "key": "name",
      "stringValue": "b"
    }]
}

### What happened:

Only results with name containing "b" were returned.

### What did you expect to happen:

All results containing both "a" and "b" should be returned.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

I did not deploy it myself, but am using a full deployment in the cloud.

KFP version: 

KFP SDK version: Build [743746b](https://github.com/kubeflow/pipelines/tree/743746b96e6efc502c33e1e529f2fe89ce09481c)

### Anything else you would like to add:

This issue seems to stem from the [definition](https://github.com/kubeflow/pipelines/blob/c51c96a973f8b94d0f993b0b292d58008fe05607/backend/src/apiserver/filter/filter.go#L33-L46) of filter. I think I can fix this myself, if the KFP team thinks it's worth doing.

If so, I would start by changing the types of [`Filter.neq`](https://github.com/kubeflow/pipelines/blob/c51c96a973f8b94d0f993b0b292d58008fe05607/backend/src/apiserver/filter/filter.go#L37) and `Filter.substring` from `map[string]interface{}` to `[]map[string]interface{}`. Let me know if you'd rather I make this change for *all* fields of `Filter`.

/kind bug
/area backend

### PR DESCRIPTION
**Pull request by bencwallace**
**Description of your changes:**

I detailed the issue a few days ago [here](https://github.com/kubeflow/pipelines/issues/4975). Ended up taking a look and saw that it was a relatively small fix.

The main change is that the fields of the Filter struct now map strings (keys) to *slices* of structs (values), rather than to a single struct.

Also added a couple of unit tests for the new functionality, but would be happy to add more if deemed necessary. All tests passed and expected functionality seems to work on a local deployment.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by bencwallace** [comment]
@Bobgy or @capri-xiyue Just wanted to check if someone's seen this. Let me know if I can make the underlying issue more clear :)

**Comment by Bobgy** [comment]
Thank you for this great contribution!

Looks good to me

/LGTM
/cc @capri-xiyue 
Do you want to review?

**Comment by bencwallace** [comment]
Looks like there was some problem creating the test cluster for some of the tests? Guessing this is a fluke.
/retest

**Comment by bencwallace** [comment]
Thanks @Bobgy and @capri-xiyue for taking a look! I'm unclear about whether there's anything else I should do. The lgtm label has been applied but looks like the PR is still not approved...

**Comment by capri-xiyue** [comment]
@Bobgy  Can you help approve this PR? It looks like I don't have the permission of approval.

**Pull request merged**
