### PR TITLE
fix(sdk): Fix serialization of ExecutorInput.

### PR DESCRIPTION
**Pull request by neuromage**
The special-casing resulted in component.yaml not being able to load
correctly. Now, both `{executorInput}` and `{executorInput: null}` work.
The latter is what is generated when saving components that have this
placeholder.

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 
- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

### CODE REVIEW

**Comment by amygdala** [comment]
Is it possible that there would still be a similar issue for v1 compilation? I'm seeing an error that suggests that might be the case (using 1.5.0rc2). A snippet from the pipeline .yaml looks like this:
```
spec:
  entrypoint: ucaip-model-train-mb
  templates:
  - name: create-training-pipeline-custom-job
    container:
      args: [--executor_input, '{{$}}', --function_to_execute, create_training_pipeline_custom_job,
  ...
```
Can provide more detail.

**Comment by amygdala** [comment]
Is it possible that there would still be a similar issue for v1 compilation? I'm seeing an error that suggests that might be the case (using 1.5.0rc2 KFP, running on a 1.5.0rc2 cluster installation). 
The error is:
```
Traceback (most recent call last):
  File "/tmp/tmp.AJ2iW9wxNL", line 656, in <module>
    executor_main()
  File "/tmp/tmp.AJ2iW9wxNL", line 646, in executor_main
    executor_input = json.loads(args.executor_input)
  File "/opt/conda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

However, the snippet from the yaml looks like this, which seems correct IIUC..
```
spec:
  entrypoint: ucaip-model-train-mb
  templates:
  - name: create-training-pipeline-custom-job
    container:
      args: [--executor_input, '{{$}}', --function_to_execute, create_training_pipeline_custom_job,
        --project-output-path, '{{inputs.parameters.project}}', --display-name-output-path,
        '{{inputs.parameters.training_display_name}}', --model-display-name-output-path,
        '{{inputs.parameters.model_display_name}}', --train-container-type-output-path,
        '{{inputs.parameters.train_container_type}}', --executor-image-uri-output-path,
        '{{inputs.parameters.executor_image_uri}}', --package-uri-output-path, '{{inputs.parameters.package_uri}}',
        --python-module-output-path, '{{inputs.parameters.python_module}}', --container-image-uri-output-path,
        '{{inputs.parameters.container_image_uri}}', --base-output-directory-prefix-output-path,
        '{{inputs.parameters.base_output_directory_prefix}}', --prediction-image-uri-output-path,
        '{{inputs.parameters.prediction_image_uri}}', --accelerator-type-output-path,
        '{{inputs.parameters.accelerator_type}}', --accelerator-count-output-path,
        '{{inputs.parameters.accelerator_count}}', --machine-type-output-path, '{{inputs.parameters.train_machine_type}}',
        --location-output-path, '{{inputs.parameters.location}}', --trainer-args-output-path,
        '{{inputs.parameters.trainer_args}}', --model-res-output-path, /tmp/outputs/model_res/data,
        --model-dispname, /tmp/outputs/model_dispname/data, --model-uri, /tmp/outputs/model_uri/data]
  ...
```
(Can provide a repro if need be).

**Comment by neuromage** [comment]
Hi @amygdala this won't work in v1 at all yet. There is a pending PR to make it work in v1-compatible mode though, will send it out soon.

**Comment by remoyson** [comment]
Hi @neuromage and @amygdala,
I have the same issue with executor_input parsing in v1. Is there any update about 'pending PR to make it work in v1-compatible mode'?

Thanks in advance!

**Pull request merged**
