### PR TITLE
apiserver glog uses -alsologtostderr

### PR DESCRIPTION
**Pull request by ywskycn**
To make "kubectl logs" work for apiserver, instead of sshing into the apiserver pod.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/859)

### CODE REVIEW

**Comment by ywskycn** [comment]
It looks like the e2e-test is unrelated. @IronPan anyway to re-trigger the test?

**Comment by IronPan** [comment]
`/test kubeflow-pipeline-e2e-test` will retrigger the test

**Pull request merged**
