### PR TITLE
merge build image to test suit

### PR DESCRIPTION
**Pull request by IronPan**
Due to https://github.com/kubernetes/test-infra/issues/11197
we need to move build image step to individual test suit. 

Steps:
- Add image build to test suit (this PR)
- clean up - delete presubmit-test.sh in pipelien repo. (this PR)
- Split test suits to two pipelines https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/kubeflow-presubmits.yaml#L202. remove [build image](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/kubeflow-presubmits.yaml#L211) step

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/799)

### CODE REVIEW

**Comment by IronPan** [comment]
cc @krzyzacy

**Comment by krzyzacy** [comment]
Do you want to split up the unified job into multiple jobs then?

**Comment by IronPan** [comment]
@krzyzacy yup that's the plan. please check pr description see if i miss anything.

**Comment by krzyzacy** [comment]
maybe close/reopen the PR to get a clearer state?

**Comment by krzyzacy** [comment]
test-infra PR is not merged yet

**Pull request merged**
