### PR TITLE
updating components and samples owners file

### PR DESCRIPTION
**Pull request by animeshsingh**
have reviewed ~30 prs, and done around 20 commits. pretty confident of sharing responsibility and handling samples and components

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1264)

### CODE REVIEW

**Comment by animeshsingh** [comment]
@Ark-kun any chance to remove this label, else i can close and resubmit this.

**Comment by Ark-kun** [comment]
Just remove qimingj from the files.

**Comment by animeshsingh** [comment]
Thanks @Ark-kun . Done

**Comment by vicaire** [comment]
@animeshsingh, I assigned the PR to the folks who are coming up with the criteria to gain approver permissions on the wider project. Thanks for your patience!

**Comment by jlewi** [comment]
@animeshsingh growing the set of approvers is great.  Can we take advantage of the growing number of reviewers/approvers to create finer grained OWNERs files?

See
https://www.kubeflow.org/docs/about/contributing/#maintaining-owners-files

Particularly for components and samples, would it make sense to aim to have each sub group have a clear set of owners?

I'd really like to leave it to the primary authors of the individual components and samples to decide who the set of approvers should be.

As an example, it looks like all the Arena code was submitted by @cheyang so I'd defer to @cheyang about who the approvers for Arena should be. 

Which are the components and samples which are lacking their own OWNERs files? For which of these can we identify a clear set of OWNERs?

**Comment by animeshsingh** [comment]
Thanks @jlewi - it would definitely make sense. I can follow up with folks to make sure they identify the maintainers for them, and add that. We have done the same for for own, so it would make sense to identify the maintainers for that. In most cases though it would be a single person behind those samples. 

The files in this PR are mostly for reviewing and approving any new components coming in, or if some change in pipeline architecture which can affect every components/samples, which need to be absorbed.

**Comment by jlewi** [comment]
Closing this PR as stale.

**Pull request closed without merging**
