### PR TITLE
fix(backend): set correct permissions for local directory

### PR DESCRIPTION
**Pull request by larrytin**
same problem as https://github.com/kubeflow/pipelines/issues/7213

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
is this related to https://github.com/kubeflow/pipelines/pull/6530 and https://github.com/kubeflow/pipelines/issues/5673 ?

**Comment by larrytin** [comment]
> 

yes, this pull request is enough for me to use a non-root image

**Comment by juliusvonkohout** [comment]
@zijianjoy  this is important for the 2.0 release then, because otherwise it would be a regression.

**Comment by rimolive** [comment]
What is required to merge this PR? I tested the changes in a restricted k8s environment (OpenShift) and these changes look good. With that, we and kfp-tekton team don't need to create SecurityContextContraint objects if this PR is merged.

**Comment by rimolive** [comment]
> @rimolive You need to join the KFP meeting to push this PR.

Thank you, Julius! I've been attending the meetings for a while. I will propose this PR to be reviewed next meeting.

**Comment by chensun** [comment]
Same change has merged as https://github.com/kubeflow/pipelines/pull/9946

**Pull request closed without merging**
