### PR TITLE
SDK - DSL - Deprecated ArtifactLocation

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2326)

### CODE REVIEW

**Comment by eterna2** [comment]
Yup. I am ok with it. Have swapped to the config map artifactory settings already.

**Comment by Ark-kun** [comment]
> Yup. I am ok with it. Have swapped to the config map artifactory settings already.

Great. Thank you.
I'll deprecate the `PipelineConf.set_artifact_location` too then.

BTW, Argo 2.4.0 has been released with my `ArtifactRepositoryRef` feature https://github.com/argoproj/argo/pull/1350, but it's not exposed in Pipelines yet and I'll wait until I hear enough feature requests for it.

**Comment by eterna2** [comment]
Nice. 

Originally, I needed this because I need to support different teams with diff use cases, and need some way to isolate the logs and artifacts between the teams.

Eventually, we went with deploying multiple light-weight pipelines for individual teams in their own namespaces to keep things simple.

Mostly because there are no rbac support and it is hard to manage many different experiments for different teams. Even for now, I feel we need some basic rbac and some way to better organize the experiments and runs.

**Comment by ca-scribner** [comment]
Sorry I couldn't find all the discussion around this.  

Is this deprecation because per-task redirection of the artifact location is discouraged, or because it was implemented elsewhere?  I just came across this and it would suit a current need I have, so wondering if the functionality was transplanted elsewhere.  I see mention about using workflow-controller-configmap, which I don't have experience with, but it seemed like that was controlling a higher level than per-task locations?

**Comment by nlarusstone** [comment]
I also would like to see if there's a long-term solution here. It's not clear to me what the suggested new behavior would be

**Pull request merged**
