### PR TITLE
fix: Modified the swagger json files according to the modified proto files.

### PR DESCRIPTION
**Pull request by amadhusu**
**Description of your changes:**
Continuation of the modifications made in the PR [10581](https://github.com/kubeflow/pipelines/pull/10581)
This will help resolve issue #10451 . This will help us generate the new API docs with the correction.

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by amadhusu** [comment]
@Tomcli @chensun can I get your reviews here so I can generate the new API docs via the tool?

**Review by Tomcli — APPROVED** [review]
/lgtm

**Pull request merged**
