### PR TITLE
test: Fixed the Travis TFX tests since TFX now requires Bazel. Fixes #4221

### LINKED ISSUE #4221: [Testing] travis tests failing "ImportError: cannot import name 'pipeline_pb2'"
https://travis-ci.com/github/kubeflow/pipelines/jobs/361545078#L3696
/kind bug
/area sdk
/area testing

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/kubeflow/pipelines/issues/4221

### CODE REVIEW

**Comment by Bobgy** [comment]
By the way, how long do you expect we can retire Travis?

**Comment by Ark-kun** [comment]
> By the way, how long do you expect we can retire Travis?

I think we can already retire it. All prow tests should be already submitted and working.

**Comment by Bobgy** [comment]
> > By the way, how long do you expect we can retire Travis?
> 
> I think we can already retire it. All prow tests should be already submitted and working.

That would be great!
Would you mind creating another PR that let those presubmit tests show up in github statuses?

**Comment by Ark-kun** [comment]
> Would you mind creating another kubernetes/test-infra config PR that let those presubmit tests show up in github statuses?

Done. https://github.com/kubernetes/test-infra/pull/18348

**Pull request merged**
