### PR TITLE
SDK/CLI: Implement kfp pipeline group

### PR DESCRIPTION
**Pull request by elikatsis**
* kfp pipeline upload
* kfp pipeline get
* kfp pipeline list
* Use logging [Set logging level to INFO]
* Catch exceptions raised in command calls and log them as errors
* Add comment for TODO kfp pipeline delete

Signed-off-by: Ilias Katsakioris <elikatsis@arrikto.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2340)

### CODE REVIEW

**Comment by Ark-kun** [comment]
> * Add comment for TODO kfp pipeline delete

Are you sure your `kfp-server-api` package is up to date? There was a swagger bug causing those errors and I fixed it by generating the package using a newer version of Swagger Codegen.

**Comment by elikatsis** [comment]
@Ark-kun 
>Are you sure your kfp-server-api package is up to date? There was a swagger bug causing those errors and I fixed it by generating the package using a newer version of Swagger Codegen.

I'm using `kfp-server-api==0.1.18.3`.
The availalbe versions are:
```
... (from versions: 0.1.18.1, 0.1.18.2, 0.1.18.3, 0.1.26)
```
I'm also seeing these:
1. https://github.com/kubeflow/pipelines/blob/e9b96de317989a9673ef88d88fb9dab9dac3005f/sdk/python/setup.py#L35
2. https://github.com/kubeflow/pipelines/blob/e9b96de317989a9673ef88d88fb9dab9dac3005f/sdk/python/setup.py#L35

So, I guess I'm using the latest accepted version.
Should I use `0.1.26` and fix the requirements [in a separate PR]? Then the requirements should be `==0.1.26`, right?

**Comment by elikatsis** [comment]
Hmm you probably mean kubeflow/pipelines#2418.
I'll hold this until that PR gets merged, and I'll add `delete` command as well.

/hold

**Comment by Ark-kun** [comment]
> Hmm you probably mean #2418.

No that PR is unrelated. Most likely the fix I mentioned was in v0.1.18.3.
The problem was that when the API response is empty, Swagger would generate an error.

/hold cancel

**Comment by Ark-kun** [comment]
Pipeline delete might be deprecated. @jingzhang36 may have details.

**Pull request merged**
