### PR TITLE
test(sdk): install `kfp-pipeline-spec` from source in `kfp` sdk tests

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Installs `kfp-pipeline-spec` from source in KFP SDK tests.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — APPROVED** [review]
/lgtm
/approve

**Comment by connor-mccarthy** [comment]
`kubeflow-pipelines-sdk-execution-tests` failures are independent of these changes and tracked separately. Manually merging.

**Pull request merged**
