### PR TITLE
[WIP] Allow input and output interceptors

### PR DESCRIPTION
**Pull request by gabrielvcbessa**
### TODO 
- [ ] Discuss the approach 
- [ ] See if it would make more sense to have this feature on the `ContainerOp` itself
- [ ] Implement tests
- [ ] Extend to `func_to_component_file` and `func_to_component_text`

### Background Context
We needed to save into a storage all inputs and outputs of every pipeline step, in order to fully understand what happened during the run and be able to pass huge datasets forward. 

This was being done for every `ContainerOp` (inside the container itself), but we needed to implement it in every step that was created using `python_op`. 

We would modify the data, save in some storage, pass the uri for the next step, load there, modify, save, pass the uri forward and so on.

### What this PR is about
Since the `python_op` already handles serialization and deserialization, would make sense to take advantage of this and implement interceptors that could persist the output data and load it for the next step. As an example, we could have as following:

```python
def load_from_s3(argument):
    ...
    if is_s3_uri(argument):
        ...
        return s3_file.get()['Body'].read().decode('utf-8').strip()
    return argument


def save_to_s3_and_return_uri(output, output_path):
    ...
    prefix = f'kfp/runs/{{workflow.uid}}/{{pod.name}}/{file_name}'
    ...
    return f's3://some-bucket/{prefix}'


op = func_to_container_op(
    sample_fn,
    argument_interceptor=load_from_s3,
    output_interceptor=save_to_s3_and_return_uri)
```

This way the user would not need to worry about it in every new op, and it would be handled internally by the pipeline. Of course, persisting objects is one of the many possible use cases.

We currently have implemented only the concept, in order to be able to discuss what would be the best approach.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2267)

### CODE REVIEW

**Comment by gabrielvcbessa** [comment]
@googlebot I signed it!

**Comment by Ark-kun** [comment]
Hi, Gabriel.

Thank you for an interesting PR.

I know that data passing is a big pain point. I've recently implemented a way to allow the component author torely on the system for that instead of implementing data passing in every component. That's  now preferable way to pass data. See the end of the Data passing tutorial: https://github.com/kubeflow/pipelines/blob/c7f7593d08510940ed2a81f522e8c3eba8930be0/samples/tutorials/Data%20passing%20in%20python%20components.ipynb Do you think that it will satisfy your needs?

I'll take a deeper look into your PR and add more comments.

**Comment by gabrielvcbessa** [comment]
Hi Ark, 

Just took a look at your notebook, I wasn't aware of `InputPath` and `OutputTextFile`, they will be very handy. How big can be the files written on a give `OutputPath`? 

In order to give some context, we are already using kfp to develop ML-Pipelines, but now most of the team working on it are MLEs, and we are trying to find out how we can improve the DSL so it can be used by the whole company (Nubank).

I thought about using something similar with what is done in the notebook, but, the way I see, there is one main problem:

- There is no way of creating something like `upload_to_s3(*args: Any)`. The op would always be restricted to the number and types of parameters specified on the container op. This is not generic enough, thus the user would probably need to implement some consumers and producers.

For me, an ideal solution would allow me to create this kind of decorators:
```python
from kfp.components import func_to_container_op

def func_to_container_op_with_gcp_interceptors(fn, **kwargs):
    return func_to_container_op(fn, argument_interceptor=load_from_gcp, output_interceptor=save_to_gcp, **kwargs)
```

Having this kind of feature I could make a decorator that would work for every container and enforce where each output of each pod should be persisted. Going more in details: 
1. `argument_interceptor`: Will receive the serialized argument value. This value could be generated in many ways: PipelineParams, could be generated by one  output_interceptor and so on. It can return the same value or modify it. 
2. `output_interceptor`:  Receive the serialized output generated by the ContainerOp. It can return the same value or modify it. 

This way we would be taking advantage of the `converters` existent on the `_data_passing` and the user would not need to worry about it (considering that we will know how to convert the desired type).

In the example below `URI`s represent some path to a remote storage and the `ContainerOp` will just multiply the input by 10.

example

You can see that the container does not need to be aware of the interceptors, and I think this is a good thing.

The code that I wrote was not meant to be the final solution, I just wanted to bring up the discussion so we can think in the best approach.

**Comment by Ark-kun** [comment]
>How big can be the files written on a give OutputPath?

They're only limited by container disk sizes.Currently, the data is taken from the container (`docker cp` or `kubectl cp` or just taken from a volume). The data is then uploaded to any S3-compatible storage. (As specified in ConfigMap).

> * There is no way of creating something like `upload_to_s3(*args: Any)`. The op would always be restricted to the number and types of parameters specified on the container op. This is not generic enough, thus the user would probably need to implement some consumers and producers.

Can you elaborate on this? Yes, the number of inputs and outputs is currently static, but I do not see this as too big of a problem. If the user wants to upload two outputs to S3, they can do that individually. The types are not limiting since type-less inputs accept any data (same with `InputPath()` (not type)).

>Having this kind of feature I could make a decorator that would work for every container and enforce where each output of each pod should be persisted.

Usually I'm more in favor of pipelines being portable and platform-agnostic, where all platform-specific details are added before submission or even at execution time. For example, the S3 storage configuration is no longer part of the pipeline.

```python
def my_pipeline():
    ...

# add/apply some pipeline/op transofrms
# submit pipeline
```

>This way we would be taking advantage of the converters existent on the _data_passing and the user would not need to worry about it (considering that we will know how to convert the desired type).

I think we could extend the converters and my generic types proposal to achieve something like this in generic way. Although there would be some practical complications.
It might be straightforward to "deserialize" object with `type: {S3Path: {GZipped: CSV}}`, but serializing it would be harder as the order of converters will be reversed. I'm also not fully settled on the design of the generic types yet. `type: {S3Path: {GZipped: CSV}}` looks nice, but it can turn out to be too limiting in future.
Maybe `type: {S3Path: {innerType: {GZipped: {innerType: CSV}}}`.

**Pull request closed without merging**
