### PR TITLE
fix(sdk): fix v1 output deserialization

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Fixes v1 component YAML output deserialization logic.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title 
convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
/hold

Merge after https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1747

**Review by chensun — COMMENTED** [review]
/lgtm
/approve

**Comment by connor-mccarthy** [comment]
Error is unrelated to this PR.

Will be fixed by https://github.com/kubeflow/pipelines/pull/8273

Will rebase this PR after merging fix.

cc @chensun

**Comment by connor-mccarthy** [comment]
Test failure unrelated to this PR. Merging to unblock https://github.com/kubeflow/pipelines/pull/8262.

**Pull request merged**
