### PR TITLE
chore(manifests): Add commonLabels to cache kustomizations

### PR DESCRIPTION
**Pull request by yanniszark**
**Description of your changes:**

Add commonLabels to cache kustomizations. This is helpful for consumers who want to quickly get all objects related to the cache components, in order to remove them.

This change does not break backwards compatibility and follows the best practice of labelling all components of an app. @Bobgy what do you think?

### CODE REVIEW

**Comment by Bobgy** [comment]
> This change does not break backwards compatibility and follows the best practice of labelling all components of an app.

@yanniszark I believe this is not true, we've seen many times that, changing `commonLabels` would result in changes in labelselector, so it breaks upgradability.

I'm OK with changing cache folder to be not included by installs folder, so that people can compose it optionally. We can still include it in `envs` folders by default.

**Comment by yanniszark** [comment]
> @yanniszark I believe this is not true, we've seen many times that, changing commonLabels would result in changes in labelselector, so it breaks upgradability.

Thanks for the comment. You are right in general, but in this case I already accounted for that. I should have made that more explicit.The labels I added to `commonLabels` are what each Deployment selector had:
- `app: cache-deployer` for cache deployer: https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml#L9-L11
- `app: cache-server` for cache: https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/cache/cache-deployment.yaml#L12-L15

So I think this fulfills this requirement:

> so that labelselector is not changed for deployments

Finally, I'm including the old and new yaml for cache and cache-deployer, so you can examine it thoroughly if you want.
[new_deployer.yaml.log](https://github.com/kubeflow/pipelines/files/6181605/new_deployer.yaml.log)
[old_deployer.yaml.log](https://github.com/kubeflow/pipelines/files/6181607/old_deployer.yaml.log)
[old_cache.yaml.log](https://github.com/kubeflow/pipelines/files/6181606/old_cache.yaml.log)
[new_cache.yaml.log](https://github.com/kubeflow/pipelines/files/6181608/new_cache.yaml.log)

**Comment by Bobgy** [comment]
My mistake, you are totally right on this!
Thank you for the considerations!
/lgtm
/approve

**Comment by yanniszark** [comment]
Rebased on top of latest master...

**Comment by Ark-kun** [comment]
Thank you for improving the manifests. The team will take a look.

> quickly get all objects related to the cache components, in order to remove them.

Can you describe (or better link to) the issue that you have with the caching component? We consider the caching to be an important part of the end-to-end user experience and want to make it work for everyone.

**Comment by Bobgy** [comment]
/lgtm

Besides our intention to improve caching, this PR does no harm if there are people who do not want it. So I'll proceed with it.
@Ark-kun please let me know if you have concerns

**Pull request merged**
