### PR TITLE
fix(backend): Fixed workflow cannot be retried with node xxx in Omitted

### LINKED ISSUE #5537: [bug] Failed to retry run (Can not trigger retry from UI when the failed step has dependent steps)
### What steps did you take

This issue happened after we upgraded to Kubeflow Pipeliines `1.5.0`

Minimum example to reproduce:

```python
import kfp


@kfp.components.create_component_from_func
def fail_func():
    raise ValueError("failure")


@kfp.components.create_component_from_func
def dummy_func():
    print("hello")


@kfp.dsl.pipeline(name="my-pipeline")
def pipeline():
    task_1 = fail_func()
    task_2 = dummy_func().after(task_1)


if __name__ == "__main__":
    client = kfp.Client()
    client.create_run_from_pipeline_func(
        pipeline,
        arguments={},
        experiment_name="a-kfp-test",
        run_name="Test manual retry",
    )
```

### What happened:

After the `Fail func` fails,  if click `Retry` on UI the following error message would show up:

>"error":"Retry run failed.: InternalServerError: Workflow cannot be retried with node xxx in Omitted phase: workflow cannot be retried","code":13,...

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 
Kubeflow Pipelines Standalone on EKS, also reproduced on Minikube.

*  KFP version: 
`1.5.0`

*  KFP SDK version: 
kfp                           1.4.0
kfp-pipeline-spec             0.1.7
kfp-server-api                1.5.0

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by guanhuichen**
phase Fixes #5537

**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by guanhuichen** [comment]
@googlebot I fixed it.

**Comment by Bobgy** [comment]
/lgtm
/approve

Looks great! Thank you for the well requested fix!

**Comment by yanp** [comment]
Thank you for the fix!

@Bobgy May I ask when will this fix be released? Sorry to bug you but we have been blocked by this issue. Thanks!

**Comment by caleb-artifact** [comment]
Any idea when this fix will land in the 1.6.x branch?

**Pull request merged**
