### PR TITLE
Modifications done by the execution of the release script.

### PR DESCRIPTION
**Pull request by vicaire**
Using commit ID: 6ad2601ec7d04e842c212c50d5c78e548e12ddea
https://gubernator.k8s.io/pr/kubeflow/pipelines/739
https://gubernator.k8s.io/pr/kubeflow/pipelines/739

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/777)

### CODE REVIEW

**Comment by paveldournov** [comment]
Thanks Pascal!

**Comment by vicaire** [comment]
Looks like the issue is that the cluster deletion takes too long. Otherwise the e2e tests are succeeding. 

I am going to merge this PR to unblock the release. Asked @IronPan to double check and got approval.

**Pull request merged**
