### PR TITLE
docs(backend)update docs of deploying apiserver

### PR DESCRIPTION
**Pull request by capri-xiyue**
**Description of your changes:**
update docs of deploying apiserver with the image you own build

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by capri-xiyue** [comment]
cc @james-jwu

**Comment by numerology** [comment]
/assign @Bobgy 
/lgtm

Thanks!

**Comment by Bobgy** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
