### PR TITLE
Backend - Annotate Workflow with the run name

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2902)

### CODE REVIEW

**Comment by IronPan** [comment]
Is there any reason metadata writer needs to know the run name instead of run id which uniquely identifies the run?

**Comment by Ark-kun** [comment]
> Is there any reason metadata writer needs to know the run name instead of run id which uniquely identifies the run?

This simplifies information flow to be one-way:

SDK -> Backend -> Argo -> Kubernetes -> Metadata Writer -> MLMD

This way the Metadata Writer does not need to talk back to the Backend.

Alternatively, Backend could pre-create the MLMD Context for the run and stamp the workflow with Context ID and Run ID.

**Pull request merged**
