### PR TITLE
fix(frontend): fixes link to Vertex AI workbench in GettingStarted page.

### PR DESCRIPTION
**Pull request by jiyongjung0**
Cloud AI Platform Notebook was migrated to Vertex AI workbench and the URL has changed.

**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by zijianjoy** [comment]
/lgtm
/approve 

Thank you Jiyong for keeping documentaiton up-to-date!

**Comment by zijianjoy** [comment]
For the test failure:

Run `npm run test` and update snapshot based on instruction.

**Comment by jiyongjung0** [comment]
/retest

I tried to run `npm run test` but couldn't install dependent packages. I just manually updated relevant data. Please create a separate PR if this approach is not right.

**Comment by zijianjoy** [comment]
/lgtm
/approve

You probably need to install package using `npm ci`.

But it is all good now as you fixed it, thank you!

**Pull request merged**
