### PR TITLE
SDK - Improve errors when ContainerOp.output is unavailable

### PR DESCRIPTION
**Pull request by Ark-kun**
ContainerOp.output is only available when there is only one output.
Right now, when there are multiple outputs it just holds `None` instead of the a task output reference.
In this case however it's indistinguishable from just passing None argument.
This PR gives a quick fix to make accessing the nonexistent `.output` a compile-time error.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1578)

### CODE REVIEW

**Comment by gaoning777** [comment]
Please fix the test errors.

**Comment by Ark-kun** [comment]
> Please fix the test errors.

I've fixed the errors.

**Comment by Ark-kun** [comment]
All the tests pass.

**Pull request merged**
