### PR TITLE
Tests - reintegrate build-image stage back into test suites

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/461)

### CODE REVIEW

**Comment by IronPan** [comment]
could you do this for e2e-test-v2 and sample-test-v2 instead?

**Comment by IronPan** [comment]
v1 will be deprecated soon

**Comment by IronPan** [comment]
is this pr still applicable?

**Comment by Ark-kun** [comment]
The v2 tests are already building the images.

**Pull request closed without merging**
