### PR TITLE
Revert "Tests - Testing master+branch instead of just branch"

### PR DESCRIPTION
**Pull request by IronPan**
This would make test non deterministic and time sensitive. If there is any change in between test steps that are non backward compatible, the test would fail.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/199)

### CODE REVIEW

**Comment by IronPan** [comment]
Fix https://github.com/kubeflow/pipelines/issues/196

**Comment by Ark-kun** [comment]
There are two problems here:

1. If you revert this, then the tests codes would almost always be "non deterministic and time sensitive" since the root test code (test/presubmit_tests.sh and test/*.yaml) are always taken from a different commit than the rest of the test code. Please try to understand the mechanics of what's happening.
2. If we revert this, we do not really test what happens if the PR is merged into master. 

Imagine the following scenario: our PR adds some code that relies on another module or file. Meanwhile, this module/file was renamed in master. The tests that only consider the PR head commit would succeed and allow merging the broken code.

This issue is the exact reason all CI systems including Prow act the way they do. They always check what would happen is you merge the PR in master, because that's what is important. Unfortunately, we circumvent this behavior by doing `git clone` many times and also by splitting the test into build-images and the rest and using mutable global state (gcr image repo) for communication.

This wasn't important previously, when we could only check-in the code that was merged with the master HEAD (after the tests pass). The check-in system in the new repo does not enforce this rule, so out tests need to handle this.

**Comment by Ark-kun** [comment]
JFYI, to revert a commit you can just create fork a branch from master and run `git revert b190e729d28b3d4941f100a3161a61a4734f4fc1`. This would create a single revert commit.

**Comment by Ark-kun** [comment]
Closing this PR, since it looks like we'll go move in other direction.

**Pull request closed without merging**
