### PR TITLE
[Windows] PowerShell script added to start proxies for front-end UI

### PR DESCRIPTION
**Pull request by avdaredevil**
## About
This PR adds a cross-platform PowerShell script that can deploy proxies for Mac / Linux / Windows environments.

Image |
--- |
image |

_**Note:** I don't have a properly deployed cluster currently, but it's identical to the Linux counterpart found [here](https://github.com/kubeflow/pipelines/blob/master/frontend/start-proxy-standalone-and-server.sh)_

### Meta
/area pipelines
/area front-end
/priority p1
/assign @avdaredevil
/cc @kwasi @Bobgy

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2835)

### CODE REVIEW

**Comment by Bobgy** [comment]
Hi @avdaredevil, I later realized the script could be vastly simplified by port-forwarding services directly: https://github.com/kubeflow/pipelines/pull/2836.

Can you adjust your script too?

**Comment by Bobgy** [comment]
Some discussion:
Is powershell in linux well supported? https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7
Can we take other approaches like writing node scripts for this?
In windows, can we use mingw to run these?

**Comment by avdaredevil** [comment]
Hi @Bobgy, thanks for the insights:
- Is powershell in linux well supported? [https://docs...](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7)
  - Not all parts of powershell, as in the .NET Core which is not used in this script (since .NET core is a really fundamental part of windows. However this should change with PwShell v7 coming out this year). But for this PR, this is a non-issue
- Can we take other approaches like writing node scripts for this?
  - Definitely, and in fact this would be the preferred way! (this in conjuction with using [`cross-env`](https://www.npmjs.com/package/cross-env) in package.json)
- In windows, can we use mingw to run these?
  - Yes, but this is not a good solution, as it requires non-standard installations of Linux build tools to run really trivial scripts. (which do not auto-update, or get patches)

**Comment by Bobgy** [comment]
sounds like node scripts will be the best option going forward. I will try writing more of it.

**Pull request merged**
