### PR TITLE
chore(sample/test): Rename `data_passing` test to `legacy_data_passing`

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
We should make it clear that the data passing stories demonstrated in this file are allowed in the legacy mode, yet it doesn't mean that they should be the recommended user journeys going forward. 

As I commented in https://github.com/kubeflow/pipelines/pull/6008, which should have stayed open for review, we're evaluating if we want to allow some or all of the data passing stories in v2 for backward compatibility. But still, these data passing stories are not considered as "conformance tests" for KFP. 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
/lgtm

+1 for building consistent naming to clarify where each sample is supposed to run.
The previously proposed sample folder naming and structure https://github.com/kubeflow/pipelines/issues/5686 does not strictly say that a sample that only runs on v1 needs to have the `legacy` prefix.
Can you also update the guidelines in the issue?

I wonder if `_v1` suffix/prefix can have a clearer messaging than `legacy`, because in community meetings we are still saying v2 compatible is experimental. Anyway, I don't think these matter a lot, because samples/test folder is meant for testing only. The core samples are user facing.

**Comment by Ark-kun** [comment]
>I wonder if _v1 suffix/prefix can have a clearer messaging than legacy
>In community meetings we are still saying v2 compatible is experimental.

+1

**Comment by chensun** [comment]
> I wonder if _v1 suffix/prefix can have a clearer messaging than legacy, because in community meetings we are still saying v2 compatible is experimental.

Chatted offline, "legacy" is applied on the data passing stories but not all v1 features. 
We will support all the listed data passing options in v2 as well for maximum backward compatibility. However, we do not recommend all of the options for newly written components and pipelines because some of them could lead to unexpected and unpredictable runtime failures. 

> Anyway, I don't think these matter a lot, because samples/test folder is meant for testing only. The core samples are user facing.

I'm not sure if users may see it in the same way. We probably shouldn't have a double standard for the test samples. Having the name "legacy" could alert users this may not be the pattern they want to follow.

**Pull request merged**
