### PR TITLE
chore(sdk): Refactored command-line resolving

### PR DESCRIPTION
**Pull request by Ark-kun**
Moved the execution engine specific code to the component bridge.

### CODE REVIEW

**Comment by neuromage** [comment]
What's the goal of this change?

**Comment by Ark-kun** [comment]
> What's the goal of this change?

This is a refactoring PR which mainly moves the code around.

With the v2 compiler activity I've noticed that the resolve_command_line function becomes a bottleneck for the implementation of new v2 placeholders and semantics. This is especially true now that we're having two v2 compilation modes that resolve the placeholders differently.

This PR accomplishes the following two goals:

1) Make it possible to change the resolution rules for new placeholders without modifying the `resolve_command_line` code. 
2) Open up resolve_command_line by adding custom_resolver
3) Keep the pieces of v2-related placeholder code close to each other.
4) Moving the platform-specific code to the appropriate architecture diagram layer.

Since this is a small internal refactoring, it does not break any tests or API.

Thank you.

**Comment by chensun** [comment]
/lgtm

Thanks!

**Pull request merged**
