### PR TITLE
SDK - Removed the ArtifactLocation feature

### PR DESCRIPTION
**Pull request by Ark-kun**
The feature was deprecated in v0.1.34 https://github.com/kubeflow/pipelines/pull/2326

### CODE REVIEW

**Comment by Ark-kun** [comment]
@eterna2 As far as I remember, you've stopped using this feature, so it's OK to remove: https://github.com/kubeflow/pipelines/pull/2326#issuecomment-539742318

**Comment by numerology** [comment]
/lgtm

but I guess we shall wait for @eterna2 to confirm?

**Comment by Ark-kun** [comment]
> but I guess we shall wait for @eterna2 to confirm?

I'll wait a bit more.
But when I was deprecating this feature in the beginning of October, he was no longer using it.

**Comment by eterna2** [comment]
Yeah. I am not using it any more. Being using configmap to set the artifact location.

**Comment by Ark-kun** [comment]
> Yeah. I am not using it any more. Being using configmap to set the artifact location.

Thank you for confirmation.
/approve

**Comment by Ark-kun** [comment]
@numerology Can you re-LGTM please?

**Pull request merged**
