### PR TITLE
Updating s3 path in metadata writer

### PR DESCRIPTION
**Pull request by gautamkmr**
Even though artifact path is s3 but it still starts with minio.

### CODE REVIEW

**Comment by Ark-kun** [comment]
I think this change needs to be coordinated with the UX.
Generally, what we want here is to encode schema, endpoint and object key into a single URL.
External S3 URLs need to be handled differently form the in-cluster Minio URIs.

**Comment by gautamkmr** [comment]
@Ark-kun do u have any pointer on how you wanted it ? I was under impression that line has full path (which I am guessing include schema as well) of object except the beginning which should have been `S3` than `minio`. Happy to incorporate UX changes as well.

**Comment by Jeffwan** [comment]
@Ark-kun @gautamkmr I will file a PR to address this issue. We need some other way to infer the storage.

**Comment by Ark-kun** [comment]
> @Ark-kun do u have any pointer on how you wanted it ? I was under impression that line has full path (which I am guessing include schema as well) of object except the beginning which should have been `S3` than `minio`. Happy to incorporate UX changes as well.

bucket+key combination does not provide enough information to access an s3 object. The server needs to know the endpoint (e.g. `s3.eu-west-1.amazonaws.com`). We will have several kinds of endpoints - in-cluster Minio, GCS, AWS and Azure.

**Comment by gautamkmr** [comment]
Closing in favor of Jiaxin's PR

**Pull request closed without merging**
