### PR TITLE
add retry tests

### PR DESCRIPTION
**Pull request by gaoning777**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2141)

### CODE REVIEW

**Comment by numerology** [comment]
/lgtm

Thanks for the fix!

**Comment by gaoning777** [comment]
> /lgtm
> 
> Thanks for the fix!

Sure.

**Comment by gaoning777** [comment]
fixing https://github.com/kubeflow/pipelines/issues/1813

**Pull request merged**
