### PR TITLE
Fix README formatting.

### PR DESCRIPTION
**Pull request by neuromage**

### CODE REVIEW

**Comment by neuromage** [comment]
I did. The README looks the same. There is markdown autofmt (google-based style), but I don't see anything different in what shows up other than those changes? What am I missing?

**Comment by neuromage** [comment]
@IronPan PTAL, thanks!

**Comment by Ark-kun** [comment]
> There are more changes such as
> could you double check?

There might have been a base branch issue. But there does not seem to be any problem now.

**Pull request merged**
