### PR TITLE
Release b8afd0418f55362112d1fbe077fdd7da2737c500

### PR DESCRIPTION
**Pull request by kevinbache**
Also contains some upgrades to release.sh

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1799)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Are you sure that this PR has been produced by the release.sh script? There are some aspects that are notably different. Also this PR is notably bigger than the usual release PRs.

Let's check whether something went wrong.

**Comment by kevinbache** [comment]
it was produced on a mac which added a few newlines.  also the tests are passing now that our service accounts have been cleared out again.

**Comment by IronPan** [comment]
could you remove the formatting change from this PR?

**Comment by kevinbache** [comment]
@IronPan do you mean the newlines?

**Pull request closed without merging**
