### PR TITLE
Expose step id and step name

### PR DESCRIPTION
**Pull request by cheyang**
Need expose step id and step name when running pipelines.

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1191)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Can you please explain the purpose of this change? Why do you need to pass step ID and name?
I see that you're passing workflow ID and name which is not the same as task/pod id/name.
I also see that you're using Argo placeholders in the code. I'd like to limit their usage since this will prevent us from switching orchestrators if we decide to do so.

**Comment by cheyang** [comment]
Yes, the requirement is from our customer. They want to persistent the logs and some outputs to distributed storage so they need the unique name of the step.

**Comment by animeshsingh** [comment]
Hi @cheyang - why do they want to persist at step level? Argo has a setting where you can configure logs to be stored on S3 for archival for a pipeline run. Also then what will be needed is UI change to display the logs from the S3 if its stored there. cc @vicaire

**Comment by cheyang** [comment]
> Hi @cheyang - why do they want to persist at step level? Argo has a setting where you can configure logs to be stored on S3 for archival for a pipeline run. Also then what will be needed is UI change to display the logs from the S3 if its stored there. cc @vicaire

Thanks for response.

In fact, the purpose is to persistent the logs and some outputs(for example, the result of feature extraction) in specific format in the distributed storage so it can be easily  used to trace the process 
 of experiment after a long time of the run  (even the step container is cleaned up).  A sample format is  {experiment_name}/{RUN_ID}/{STEP_ID}, so the user can easily build the relationship between each step of run and the result of the step.


And for on-prem user and the user in China, S3 is impossible to use.

**Comment by Ark-kun** [comment]
@cheyang Is it possible to move these to the pipeline level? The higher it is - the easier it would be to change later.
The pipeline step may receive a URI or a unique ID (in contrast with explicitly receiving "step name" and "step id"). See https://github.com/kubeflow/pipelines/blob/b29266351ed3c639356c4fa578950a71baa54662/samples/kubeflow-tf/kubeflow-training-classification.py#L44

**Comment by cheyang** [comment]
@Ark-kun our users will build a lot of pipelines, so it is a duplicate work to set `output_template = str(output) + '/{{workflow.uid}}/{{pod.name}}/data` for them and expose more details to them. I think the concept `step` is in Kubeflow.  It's fine for the user to understand. But `workflow` and `pod` is implementation layer concept, I prefer to make them transparent to the pipeline authors.

I think the benefits of doing this in abstraction layer(arena op) are only changes in one place if we are not using Argo any more.  The end user should be not aware of this change, they just update the SDK. 

WDYT?

**Comment by vicaire** [comment]
@Ark-kun, do you have additional comments on this one?

**Comment by vicaire** [comment]
@Ark-kun, any further comments on this one?

**Comment by Ark-kun** [comment]
> @Ark-kun, do you have additional comments on this one?

I'm handling this PR and I'm also chatting with @cheyang on Hangouts.

**Comment by Ark-kun** [comment]
@cheyang 
> A sample format is {experiment_name}/{RUN_ID}/{STEP_ID}

Are you sure your code is doing what you want? I do not see it to be using step/pod ID. It only uses `workflow.uid` which is the same for all steps. Did you mean `pod.name`?

**Comment by Ark-kun** [comment]
I see you've fixed the pod.name issue

/lgtm
/approve

**Comment by vicaire** [comment]
@animeshsingh, I saw your comment only after entering mine. I agree on the idea of using Argo to backup the logs to an object store. (exposing step ID and step name might be useful regardless to, for instance, call the future ML Metadata service and store metadata about an artifact, including which pipeline and which pipeline step computed it).

**Comment by cheyang** [comment]
> I see you've fixed the pod.name issue
> 
> /lgtm
> /approve

Thank you!

**Pull request merged**
