### PR TITLE
chore(sdk): Add Alpha feature notice for local client

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
* Also exposes `pipeline_root` from `run_pipeline_func_on_cluster`. Fixes: https://github.com/kubeflow/pipelines/issues/6435

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
Thanks!
/lgtm

**Comment by etsyamitra** [comment]
@chensun could you please point me to how to get this change? is there a kfp client version could use for alpha or anywhere could keep a lookout for when it will be available.

**Comment by chensun** [comment]
> @chensun could you please point me to how to get this change? is there a kfp client version could use for alpha or anywhere could keep a lookout for when it will be available.

Hi @etsyamitra, this change was released in KFP SDK 1.8.0. 
You can update your SDK to the latest version via `pip3 install --upgrade kfp` to get this change.

**Comment by etsyamitra** [comment]
Thank you @chensun, do you think there will be value in being able to support multiple mounts in local runner as well?
This would bring this closer to docker and more flexible, curious about your thoughts and then can create a request on it.

**Pull request merged**
