### PR TITLE
chore(deployment): gcp mkp - default pipeline root to gcs when configured

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Changes:
* default pipeline root to gcs when configured
* update config snapshot for emissary executor

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
/assign @zijianjoy @capri-xiyue 
can you help me LGTM?

**Comment by Bobgy** [comment]
tests are passing now

**Comment by zijianjoy** [comment]
/lgtm 

Thank you Yuan for the change!

**Pull request merged**
