### PR TITLE
Add CMLE deploy comment missing parameters

### PR DESCRIPTION
**Pull request by hongye-sun**
python-version and model are missed in the args list.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2048)

### CODE REVIEW

**Comment by gaoning777** [comment]
it is weird that postsubmit test shows up. Could you push an empty commit?

**Comment by Ark-kun** [comment]
It shows, because the postsubmit test configuration and the fact that this branch is created in the main repo instead of the fork.
I've investigated this couple of weeks ago and created issues in the relevant repos: https://github.com/kubernetes/test-infra/issues/14125
I've submitted a fix PR for that: https://github.com/kubernetes/test-infra/pull/14293

**Comment by Ark-kun** [comment]
> /retest

@hongye-sun Please check https://github.com/kubeflow/pipelines/pull/2048#issuecomment-530624396

**Comment by hongye-sun** [comment]
This one is blocked by postsubmit. Created another PR https://github.com/kubeflow/pipelines/pull/2296 from a fork.

**Pull request closed without merging**
