### PR TITLE
fix(sdk): SDK - Avoiding deprecated ContainerOp methods

### PR DESCRIPTION
**Pull request by Ark-kun**
Switched from `task.set_X` to `task.container.set_X`

**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Gentle ping.

**Comment by Bobgy** [comment]
/lgtm

Can you help me understand the difference between .container. and without it?

Will users know they should do this?

**Comment by Ark-kun** [comment]
> Can you help me understand the difference between .container. and without it?
> 
> Will users know they should do this?

Initially `ContainerOp` had attributes that resembled a subset of Kubernetes `Container` attributes.
However there were several issues:
1) Many Kubernetes `Container` attributes were not supported. Adding attributes one by one was not scaleable.
2) Some of our users wanted to have sidecar containers and init containers. In that case, there are more than 1 container.
This lead to the idea of just reusing the Kubernetes `Container` object. All attributes will be supported and to update the attributes to the latest version we can just upgrade the Kubernetes client. The compilation also becomes easier since Kubernetes Container object can be just serialized to dict.

One of our external contributors has lead the effort. https://github.com/kubeflow/pipelines/pull/879 (Mar 28, 2019)

That PR added several features including introducing `ContainerOp.container` and deprecating the container-related attributes on the `ContainerOp` itself. Here is the test for deprecations: 
 https://github.com/kubeflow/pipelines/pull/879/files#diff-aa33976e60c18db4fb4c7224b2dc0939R55

Recently I've noticed those deprecation warnings in the tests and decided to fix those tests/samples:
https://travis-ci.com/github/kubeflow/pipelines/jobs/356686816#L754
```
/home/travis/build/kubeflow/pipelines/sdk/python/kfp/dsl/_container_op.py:44: PendingDeprecationWarning: `dsl.ContainerOp.set_image_pull_policy` will be removed in future releases. Use `dsl.ContainerOp.container.set_image_pull_policy` instead.
  (op_name, container_name), PendingDeprecationWarning)
ok
/home/travis/build/kubeflow/pipelines/sdk/python/kfp/dsl/_container_op.py:44: PendingDeprecationWarning: `dsl.ContainerOp.add_volume_mount` will be removed in future releases. Use `dsl.ContainerOp.container.add_volume_mount` instead.
  (op_name, container_name), PendingDeprecationWarning)
/home/travis/build/kubeflow/pipelines/sdk/python/kfp/dsl/_container_op.py:44: PendingDeprecationWarning: `dsl.ContainerOp.add_env_variable` will be removed in future releases. Use `dsl.ContainerOp.container.add_env_variable` instead.
  (op_name, container_name), PendingDeprecationWarning)
ok
```

**Comment by Ark-kun** [comment]
I'm not sure whether I should call this fix or chore. The only "fix" here is the prevention of warning when using `kfp.gcp.use_tpu`. SO, maybe this is a chore. @Bobgy WDYT?

**Comment by Bobgy** [comment]
Thanks! Well explained.

Yes, I think fix is suitable. Warnings are also user-facing and could be annoying.

**Comment by Bobgy** [comment]
Do you want to approve by yourself?
or should I approve next time.

this is ready to go I think

**Pull request merged**
