### PR TITLE
fix(backend): get pipeline by name is broken due to version typo, Fixes #9940

### LINKED ISSUE #9940: [bug] Always 404 on kfp sdk
I was using kfp==2.0.0b12 and everything was working great. But as soon as i got into 2.0.1 I am always getting 404 when trying to use methods from client, like this:

`kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Express', 'content-security-policy': "default-src 'none'", 'x-content-type-options': 'nosniff', 'content-type': 'text/html; charset=utf-8', 'content-length': '170', 'date': 'Mon, 28 Aug 2023 23:52:33 GMT', 'x-envoy-upstream-service-time': '2', 'server': 'istio-envoy'})
HTTP response body: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /pipeline/apis/v2beta1/pipelines</pre>
</body>
</html>`

I am now using kfp==2.0.1 kfp-pipeline-spec==0.2.2 kfp-server-api==2.0.1 and I am creating the client this way:

`session = requests.Session()
    response = session.get(HOST)

    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
    }

    data = {"login": USERNAME, "password": PASSWORD}
    session.post(response.url, headers=headers, data=data)
    return session.cookies.get_dict()["authservice_session"]
client = Client(host=f"{HOST}/pipeline",
                    cookies=f"authservice_session={session_cookie}",
                    namespace=NAMESPACE)
return client
`

It used to work great, but now using kfp sdk 2.0.1 if I try something like list_pipelines() I am always getting the error.

What am I doing wrong here?

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by cybernagle**
function getPipelineByName have a version typo:
V2beta1 -> v2beta1

thanks for @Jimmyshao 's help to find out this issue. 
**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — APPROVED** [review]
/lgtm

**Comment by chensun** [comment]
@cybernagle Can you please sign the CLA following the the instruction, also split the SDK change out as a separate PR? Thanks!

**Comment by cybernagle** [comment]
> @cybernagle Can you please sign the CLA following the the instruction, also split the SDK change out as a separate PR? Thanks!

No problem ,will do so.

**Comment by cybernagle** [comment]
@chensun  please feel free to comment if you need me to change anything else. thanks a lot. :)

**Review by chensun — APPROVED** [review]
/lgtm

Thanks, @cybernagle !

**Pull request merged**
