### PR TITLE
fix(sdk): google client: set ai platform endpoint by region

### PR DESCRIPTION
**Pull request by toshitanian**
**Description of your changes:**

When I attempted to create a scheduled job as below according to the [Vertex AI document](https://cloud.google.com/vertex-ai/docs/pipelines/run-pipeline), I succeed to deploy to Cloud Scheduler, Cloud functions but the scheduler job failed to kick the pipeline run.
**Please note that the region is `asia-east1`**

```python
    project_name = "my-gcp-project"
    region = "asia-east1" # Taiwan
    api_client = AIPlatformClient(project_id=project_name, region=region)
    job_spec_path = "kubeflow_pipeline.json"
    pipeline_root = "gs://my-bucket/pipeline_root_vertexai/experiments"

      schedule = "*/5 * * * *"
        api_client.create_schedule_from_job_spec(
            job_spec_path=job_spec_path,
            pipeline_root=pipeline_root,
            parameter_values={},
            schedule=schedule,
            time_zone='Asia/Tokyo',
        )
```

I looked into the logs of cloud functions and found the log line below. So it seems that it requested to us-central1 endpoint at `_CAIPP_DEFAULT_ENDPOINT`, so I fixed the hard-coded endpoint in the file I fixed in this pull request.

```
"description": "The provided location ID doesn't match the endpoint. The valid location ID is `us-central1`.""
```

I tried again after applied this change, error message changed. It still has another issue for me, but the request seems to be accepted and the issue related to the region seems to be fixed.

```
"message": "You do not have permission to act as service_account:00000000000-compute@developer.gserviceaccount.com. (or it may not exist).",
```

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by toshitanian** [comment]
@ji-yaqi Hi, how this looks like? we are planning to use this SDK. So i’m really appreciate if you could take a look!
Thanks you

**Comment by ji-yaqi** [comment]
/lgtm
/approve

Thanks!

**Comment by toshitanian** [comment]
@ji-yaqi Resolved the conflict 🙏

**Review by ji-yaqi — APPROVED** [review]

**Comment by toshitanian** [comment]
Thanks!

**Pull request merged**
