### PR TITLE
chore(release): upgrade mlmd to 0.25.1

### PR DESCRIPTION
**Pull request by rui5i**
This PR upgrades mlmd version to 0.25.1.

#4565

### CODE REVIEW

**Comment by numerology** [comment]
nit:

You can try to use `git reset --hard upstream/master` to forcefully sync the master in your fork to be exactly the same as the mainstream. That way the commit history of the PR would be less noisy.

**Comment by numerology** [comment]
> nit:
> 
> You can try to use `git reset --hard upstream/master` to forcefully sync the master in your fork to be exactly the same as the mainstream. That way the commit history of the PR would be less noisy.

.... but do not do that in this PR, which will clean it up. Hopefully I made it clear!

**Comment by Bobgy** [comment]
and a tip, if you want to keep commit history clean in this PR, you can
```
git rebase -i upstream/master
```

it tries to patch your changes in the PR on top of upstream/master, but when you push to your branch, you'll have to force it because commit history has changed.
```
git push origin HEAD --force
```

Anyway, this is a choice. I no longer do this, because I don't think it's worth it keeping commit history clean for a small PR, it'll be more useful for bigger PRs.

**Comment by Bobgy** [comment]
Thanks @rui5i for fixing the process and updating the docs!
/lgtm
/approve

**Pull request merged**
