### PR TITLE
chore: Azure owners

### PR DESCRIPTION
**Pull request by eedorenko**
Added owners to Azure kustomization

### CODE REVIEW

**Comment by Bobgy** [comment]
Do you plan to contribute the manifests? I'd suggest send that PR with this OWNERs file

**Comment by jotaylo** [comment]
@Bobgy ack, included the OWNERs file with manifest PR #4567

**Comment by Ark-kun** [comment]
> Do you plan to contribute the manifests? I'd suggest send that PR with this OWNERs file

AFAIK, for AWS we keep the deployment manifests in a separate repo...

**Pull request closed without merging**
