### PR TITLE
refactor(deployment): separate metadata-writer and metadata-grpc folders

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Separate metadata-writer and metadata-grpc folders, so that we can reuse metadata-writer easier in Kubeflow 1.1 manifest by referring to the `kustomize/base/metadata/metadata-writer` folder directly.

/cc @Ark-kun 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [x] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by rmgogogo** [comment]
+1 to this PR. I plan to deprecate metadata-writer and cache-server someday after we support native MLMD. So does persistence-agent.

/lgtm
/approve

**Comment by Ark-kun** [comment]
I wonder maybe the Metadata Writer belongs more to the backend, not the metadata directory.
The Metadata-gRPC is an external project like Argo, Minio, Envoy, etc, but the Metadata Writer is part of KFP.

**Comment by Bobgy** [comment]
@Ark-kun good point! will adjust

**Pull request merged**
