### PR TITLE
[WIP] Support ppcle64 in pipelines/frontend

### PR DESCRIPTION
**Pull request by QxiaoQ**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2234)

### CODE REVIEW

**Comment by QxiaoQ** [comment]
@jinchihe

**Comment by Ark-kun** [comment]
What are the changes here?

**Comment by rmgogogo** [comment]
Any background introduction?
Please be noticed we don't have plan to support ppcle64 and won't test it for future changes.
In such case, better put this file to other repo and refer this repo.

Would like to know more first.

Maybe the file can be put to https://github.com/kubeflow/pipelines/tree/master/contrib/ppcle64.

**Comment by Bobgy** [comment]
/close
resolved by https://github.com/kubeflow/pipelines/pull/3113
because we no longer use backstop js, so no dependency on phantomjs now

**Pull request closed without merging**
