### PR TITLE
Added the backend Go module cache to .gitignote

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2190)

### CODE REVIEW

**Comment by neuromage** [comment]
Does `go build` create this directory?

**Comment by Ark-kun** [comment]
> Does `go build` create this directory?

I think it's somehow related to some new Go modules utilities.
Something like gomod used by the VS Code started downloading thousands of files there.

**Pull request merged**
