### PR TITLE
feat(components/google-cloud): Add user agent to the CustomJob request header

### PR DESCRIPTION
**Pull request by IronPan**
**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by sasha-gitg — COMMENTED** [review]
/lgtm

**Review by SinaChavoshi — APPROVED** [review]
/lgtm

**Review by SinaChavoshi — APPROVED** [review]
Thank you for the PR
/lgtm

**Pull request merged**
