### PR TITLE
chore: Add Question issue template

### LINKED ISSUE #4688: [Community] GitHub issue templates for feature request and question
We've set up a github bug template to
* inform people which information they should fill in
* automatically mark the issue as `kind/bug`

It's been working very well and saving efforts for github issue triage.
I think we should follow the same pattern for feature request and questions now.

### PR DESCRIPTION
**Pull request by rimolive**
**Description of your changes:**
Fixes #4688

Add a template for users to ask questions

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
/hold 

We were considering enabling [GitHub Discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions) for questions and general discussions.
Any comments/thoughts?

**Comment by HumairAK** [comment]
I don't think GH issues should be for q/a. 

Wouldn't having an issue template for a question only give the impression that we welcome q/a style gh issues? 

I agree with sending such questions to GH discussions. Don't know too much about gh discussions, but it seems like for this we would want a category form: https://docs.github.com/en/discussions/managing-discussions-for-your-community/creating-discussion-category-forms  instead of an issue template

**Comment by rimolive** [comment]
cc @Tomcli 

Looking for your thoughts too

**Comment by Tomcli** [comment]
In the new projects we created, we use GitHub discussions because it works like a forum where you can upvote the important discussion. This also help reduce the number of issues we have.

Before GitHub discussions, the only way users can ask question is through issues and slack, so you still see some old GitHub repo is doing that way. I agree we should use GitHub discussions instead as many community such as KServe, Argo already using it.

**Comment by gregsheremeta** [comment]
not personally familiar with Discussions, but it seems like it will do the trick.

is it easy to enable?

**Comment by StefanoFioravanzo** [comment]
I love the idea of moving Q/A and generic discussion to GH Discussions. That will help in reducing the number of issues and keep them higher quality

**Comment by StefanoFioravanzo** [comment]
If we go with GH discussions, let's see if we can direct users to that when they try opening a new issue. See how they do it in JAX https://github.com/google/jax/issues/new/choose

**Comment by rimolive** [comment]
@chensun Can you enable the discussions tab? I'll change the issues template to guide the community to that tab when enabled, following @StefanoFioravanzo suggestion.

**Comment by chensun** [comment]
> @chensun Can you enable the discussions tab? 

Done.

**Review by chensun — APPROVED** [review]
/lgtm

@rimolive I will leave it to you to unhold and merge.

**Pull request merged**
