### PR TITLE
chore: stop releasing gcp components

### PR DESCRIPTION
**Pull request by IronPan**
**Description of your changes:**
stop releasing gcp components for a transition to use google-cloud/

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
@IronPan You need to remove GCP components from release script too.

Check https://github.com/kubeflow/pipelines/blob/1752d372b43967cd3ed8d085b602c3981f6767ef/components/release-in-place.sh#L32
https://github.com/kubeflow/pipelines/blob/1752d372b43967cd3ed8d085b602c3981f6767ef/components/release.sh#L33

**Comment by IronPan** [comment]
Done. removed the entry from release script too

**Review by SinaChavoshi — APPROVED** [review]
/lgtm

**Pull request merged**
