### PR TITLE
fix(mkp): Added service account description to prevent validation errors

### PR DESCRIPTION
**Pull request by Ark-kun**
See https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/schema.md#type-service_account

Fixes https://buganizer.corp.google.com/issues/177083468

### CODE REVIEW

**Comment by Bobgy** [comment]
/lgtm

but
/hold
I think it's worth asking @joeliedtke to take a quick look

**Comment by joeliedtke** [comment]
@Ark-kun, Where would users see that description? Is this service account used only for deploying KFP? (And not for running pipelines.)

**Comment by Ark-kun** [comment]
> @Ark-kun, Where would users see that description? Is this service account used only for deploying KFP? (And not for running pipelines.)

I'm not sure where this could be visible. Maybe it can be seen during the installation. I was just asked to add description, since it's a required field.

**Comment by Ark-kun** [comment]
Unholding to unblock the marketplace release
/unhold

**Pull request merged**
