### PR TITLE
test: fix version conflict for functional tests

### PR DESCRIPTION
**Pull request by tmvfb**
**Description of your changes:**
Functional tests are still broken (and seem to annoy not only me) despite the fix https://github.com/kubeflow/pipelines/pull/10817. Apologies for creating multiple pull requests, looked to me that the previous PR worked.

What's causing problems now is the outdated requirements.txt file (see [here](https://github.com/kubeflow/pipelines/tree/master/test/kfp-functional-test)). I deleted the old file and created a new one by running  `pip-compile requirements.in` on python3.12 (supported by kfp>=2.5.0). 

This PR fixes version conflict issue. Unfortunately, I'm not able to run complete test on my fork, since that requires google cloud configuration. So further problems related to gcloud authentication might possibly be encountered.
 
image
  
**Note:** Should I use kfp version 2.0.5 in `requirements.in` instead of the current one? Seems that test cluster should be using that version (https://github.com/kubeflow/testing/blob/master/test-infra/kfp/Makefile). 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by tmvfb** [comment]
Also prow tests [have been failing](https://testgrid.k8s.io/googleoss-kubeflow-pipelines#kubeflow-pipelines-periodic-functional-test) since PR https://github.com/kubeflow/pipelines/pull/10817 was merged.   
Happens because `sudo` is not available on `python3.7-slim` image used for the prow tests. Not sure how to best fix that.

**Comment by HumairAK** [comment]
Question, maybe it would make sense to have these tests run on the PR, at least for when the workflow that changes this tests (or the tests themselves) are updated, so we can verify if these fixes have the intended affect or not?

**Comment by tmvfb** [comment]
> Question, maybe it would make sense to have these tests run on the PR, at least for when the workflow that changes this tests (or the tests themselves) are updated, so we can verify if these fixes have the intended affect or not?

Being able to run this in the context of kubeflow/pipelines environment before merging would surely make things easier!

**Review by chensun — APPROVED** [review]

**Review by chensun — APPROVED** [review]
/lgtm

**Pull request merged**
