### PR TITLE
fix(components/google-cloud): Fix typo in 'optional'

### PR DESCRIPTION
**Pull request by markwinter**
**Description of your changes:**
Fix the typo in `optional`

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by markwinter** [comment]
@IronPan 

Could you take a look at this test failure? Looks like a bit of a weird one and it's related to the google-cloud component tests

**Comment by markwinter** [comment]
This was fixed in https://github.com/kubeflow/pipelines/pull/7074

**Pull request closed without merging**
