### PR TITLE
fix(sdk/component): ml_engine deploy version is incorrect type. Fixes #4291

### LINKED ISSUE #4291: kfp component ml_engine deploy version param is incorrectly typed
### What steps did you take:

I tried to specify the `version` param to the gcp ml_engine deploy component via:

```
 mlengine_deploy_op = comp.load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/1.0.0/components/gcp/ml_engine/deploy/component.yaml')

. . .

 upload_task = mlengine_deploy_op(
    model_id=model_id,
    project_id=project_id,
    python_version=python_version,
    runtime_version=runtime_version,
    version_id=version_id,
    model_uri=model_uri,
    model={
        'onlinePredictionLogging': True,
        'onlinePredictionConsoleLogging': True,
    },
    version={
        'packageUris': package_uris,
        'predictionClass': prediction_class,
    },
)
```

### What happened:

Received a type error that str object (version) does not support assignment
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ml/kfp_component/launcher/__main__.py", line 34, in <module>
    main()
  File "/ml/kfp_component/launcher/__main__.py", line 31, in main
    launch(args.file_or_module, args.args)
  File "kfp_component/launcher/launcher.py", line 45, in launch
    return fire.Fire(module, command=args, name=module.__name__)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "kfp_component/google/ml_engine/_deploy.py", line 68, in deploy
    wait_interval)
  File "kfp_component/google/ml_engine/_create_version.py", line 55, in create_version
    version['deploymentUri'] = deployemnt_uri
TypeError: 'str' object does not support item assignment
```

### What did you expect to happen:

I expected to be able to pass additional version parameters as a dictionary as described in https://cloud.google.com/ml-engine/reference/rest/v1/projects.models.versions and https://github.com/kubeflow/pipelines/blob/master/components/gcp/ml_engine/deploy/component.yaml#L64:L69

However, this type is being declared as a str when it should be a dict: https://github.com/kubeflow/pipelines/blob/master/components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_create_version.py#L47

This is ultimately based on the assumption that fire is using the docstring to do type hinting.

### Environment:
How did you deploy Kubeflow Pipelines (KFP)?
Deployed via AI-Platform Pipelines

KFP version:
```
Build commit: 9c16e12
``` 

KFP SDK version: 
```
kfp                      0.5.1
kfp-server-api           0.5.0
```

/kind bug
/area sdk

### PR DESCRIPTION
**Pull request by jphines**
**Description of your changes:**

* Update the docstring of `kfp_component/google/ml_engine/_create_version.py` to specify `dict` instead of `str`.
* Update examples of the ml_engine deploy component to use `{}` instead of `''` to demostrate correct type.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [x] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by jphines** [comment]
@googlebot I signed it!

**Comment by Bobgy** [comment]
Thanks for the fix!
/lgtm
/approve

**Comment by Bobgy** [comment]
/retest

@Ark-kun in case you want to review

**Pull request merged**
