### PR TITLE
chore(sdk.v2): Error out on invalid pipeline name

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
Raise an error if pipeline.name doesn't conform to [a-z0-9][a-z0-9-]{0,127}.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by neuromage** [comment]
Nice, thanks!
/lgtm
/approve

**Comment by numerology** [comment]
Looks like there is a transitive dependency issue. Let me take a stab.

**Pull request merged**
