### PR TITLE
Fixing grammatical errors and references

### PR DESCRIPTION
**Pull request by animeshsingh**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/835)

### CODE REVIEW

**Comment by animeshsingh** [comment]
Thanks @hongye-sun.  Can this be merged?

**Comment by hongye-sun** [comment]
I think you already have the approval permission. Could you try to approve by yourself?

**Comment by hongye-sun** [comment]
I can also approve but just want to verify that the OWNERS file under the ibm-samples directory is working. Let me know if you still need my approval. Thanks.

**Comment by animeshsingh** [comment]
So @hongye-sun when add the label to approve, seems it still needs an additional approver. So that means the OWNERS file isn`t working? 

"This pull-request has been approved by: _[animeshsingh](https://github.com/kubeflow/pipelines/pull/835#issuecomment-466147251)_
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **hongye-sun**"

**Comment by animeshsingh** [comment]
@vicaire is the OWNERS file in here not working? Or an OWNER cannot get his own PR in once reviewed by a reviewer?

**Comment by hongye-sun** [comment]
@animeshsingh, sorry for the delay, I missed your last message. I don't quite understand why the OWNER file doesn't work here. Usually, I can approve my own PR if it's LGTMed by others.

**Comment by animeshsingh** [comment]
Thanks @hongye-sun. Who can we discuss this with? Also would love to get in the OWNERS file for 'samples' repo, even if i will just exercise it on ibm-samples?

**Comment by hongye-sun** [comment]
@vicaire and @IronPan , do you have any insight on this?

**Comment by vicaire** [comment]
Hi @animeshsingh,

I think you just need someone else to LGTM your PR. It could be someone from your team or one of us. The comments above from k8-ci-robot list what was missing at each iteration. It may be the same for /approve. You might have to add an approver from your team to the OWNER file. 

(Note: please make sure not to check-in any binaries)

About granting "approve" on the whole "sample" directory, could you suggest instead how we could reorganize the code so that you are not blocked?

**Comment by animeshsingh** [comment]
@vicaire LGTM was already added by @hongye-sun - still this does not get in... so the thing missing someone else saying /approve as well?

**Comment by vicaire** [comment]
@animeshsingh. That's my guess: when you approved, the robot answered that you cannot LGTM your own PR (maybe it should have said that you cannot "approve" your own PR).  

Note that we are using the Kubernetes bot. Looking at the code could help figure out the exact behavior. 
https://github.com/oracle/kubernetes-test-infra/blob/master/commands.md

I would suggest to have a second approver. If it does not work, we can investigate further.

**Pull request merged**
