### PR TITLE
Release component image version d3c4add0a95e930c70a330466d0923827784eb9a

### PR DESCRIPTION
**Pull request by IronPan**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/655)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Were there any notable changes?

**Comment by gaoning777** [comment]
Note that we do not have tests covering the components, yet since the current sample tests test old component images.

**Comment by IronPan** [comment]
the sample tests are green. https://gubernator.k8s.io/pr/kubeflow/pipelines/655

**Pull request merged**
