### PR TITLE
Component releasing for 0.1.17

### PR DESCRIPTION
**Pull request by gaoning777**
release new components and remove the resnet image release in the release script

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1171)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Can you also try replacing the component branch in samples from master to `439d90cf194cade07b2a6ede3f7a493b08b537e9` ?

**Comment by gaoning777** [comment]
> Can you also try replacing the component branch in samples from master to `439d90cf194cade07b2a6ede3f7a493b08b537e9` ?

Which files exactly? you mean which components in the sample directory?

**Comment by Ark-kun** [comment]
I meant https://github.com/kubeflow/pipelines/blob/d24dba5aae73af286e798be1364fe3569f1cd992/samples/kubeflow-tf/kubeflow-training-classification.py#L21
and https://github.com/kubeflow/pipelines/blob/d24dba5aae73af286e798be1364fe3569f1cd992/samples/xgboost-spark/xgboost-training-cm.py#L22

I should probably extend the `release.sh` script to do that automatically.

**Comment by Ark-kun** [comment]
Note that the SHA you use when loading components is different than the image SHA. (It's actually the SHA of your commit where you change the image tags.)

**Comment by gaoning777** [comment]
Then it requires two commit, then?

**Comment by Ark-kun** [comment]
> Then it requires two commit, then?

Yes. But they can be submitted in one PR.
I'll be changing the release.sh script to do that automatically in future.

**Comment by gaoning777** [comment]
that is not a good a idea to reference a yaml that exists in other forks

**Comment by IronPan** [comment]
Here are the recommended steps:
1. Update the images tag in component folder to latest version that tests pass, using release script and run against component/ dir.
2. Merge the PR in step 1 and wait for test pass
3. Update the image tag in sample folders to merge SHA in step 2, using release script and run against sample/ dir.
4. Merge the PR in step 3.

Later when we deprecate the intermediate YAML the regular process will resume.

**Comment by gaoning777** [comment]
SGTM

**Comment by Ark-kun** [comment]
> 1. Update the images tag in component folder to latest version that tests pass, using release script and run against component/ dir.
> 3. Update the image tag in sample folders to merge SHA in step 2, using release script and run against sample/ dir.

@IronPan 
There is no problem in updating **all images** in both components directory and samples directory at the same time. The release script is doing the right thing.

**Pull request merged**
