### PR TITLE
Use string literals for reference resource relation and for reference resource type in frontend

### PR DESCRIPTION
**Pull request by jingzhang36**
Use string literals for reference resource relationship and for reference resource type in frontend.
For bug https://github.com/kubeflow/pipelines/issues/2430

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2453)

### CODE REVIEW

**Comment by jingzhang36** [comment]
@Bobgy and @IronPan for frontend changes.
@Ark-kun for sdk changes.

**Comment by Bobgy** [comment]
Side note:
For <any> cast in typescript enums, I found there's a PR fixing it for swagger: https://github.com/swagger-api/swagger-codegen/pull/7914, but no one is working on it.
Author mentioned the PR is merged in a fork of swagger-codegen: https://github.com/OpenAPITools/openapi-generator/pull/145

openapi-generator is compatible with swagger-codegen 2.4.0, so it may be an option too. I feel there could be a lot of efforts figuring out what we want to choose from. Just noting these discoveries first.

**Comment by Bobgy** [comment]
Oops, I reformatted frontend/src/apis
Which part of it is auto generated code?

**Comment by Bobgy** [comment]
Thanks for the fix!
/approve
/lgtm

**Pull request merged**
