### PR TITLE
add missing licenses for viz server

### PR DESCRIPTION
**Pull request by hongye-sun**

### CODE REVIEW

**Comment by numerology** [comment]
/lgtm
Feel free to manually approve at this moment.

Thanks!

**Comment by numerology** [comment]
Thanks! @hongye-sun 
```
Error: google-cloud-dlp package's license is missing.
```

**Comment by hongye-sun** [comment]
@numerology 

The package is added at https://github.com/kubeflow/pipelines/pull/3529/files#diff-0120184420a070818e6301d061832ca6R41

Not sure why it still fails.

**Comment by hongye-sun** [comment]
Found the cause, I need to run the download script to put the license to the local folder.

**Pull request merged**
