### PR TITLE
2682: Support a custom kube config location in K8sJobHelper

### PR DESCRIPTION
**Pull request by pahask8**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2683)

### CODE REVIEW

**Comment by pahask8** [comment]
@Ark-kun please take a look.

**Comment by pahask8** [comment]
@Ark-kun , @gaoning777 , could you please take a look? Thank you

**Comment by pahask8** [comment]
Hi @Ark-kun, is master broken? Tests failed:

`build-basic-e2e-tests-image:	ERROR: google-auth 1.8.1 has requirement setuptools>=40.3.0, but you'll have setuptools 33.1.1 which is incompatible`

Thank you

**Comment by pahask8** [comment]
Hi @Ark-kun, my pull request is still failing with e2e tests even when I've rebased with the master:

`ERROR: google-auth 1.9.0 has requirement setuptools>=40.3.0, but you'll have setuptools 33.1.1 which is incompatible.`. Looks like it is not related to my changes, could you please suggest?

Thank you

**Comment by Ark-kun** [comment]
> Looks like it is not related to my changes, could you please suggest?

The actual error is:
```
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	List of buckets:
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	Traceback (most recent call last):
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "<string>", line 6, in <module>
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/local/lib/python2.7/dist-packages/google/api_core/page_iterator.py", line 212, in _items_iter
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    for page in self._page_iter(increment=False):
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/local/lib/python2.7/dist-packages/google/api_core/page_iterator.py", line 243, in _page_iter
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    page = self._next_page()
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/local/lib/python2.7/dist-packages/google/api_core/page_iterator.py", line 369, in _next_page
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    response = self._get_next_page_response()
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/local/lib/python2.7/dist-packages/google/api_core/page_iterator.py", line 419, in _get_next_page_response
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    method=self._HTTP_METHOD, path=self.path, query_params=params
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 417, in api_request
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    timeout=timeout,
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 275, in _make_request
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    method, url, headers, data, target_object, timeout=timeout
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 313, in _do_request
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    url=url, method=method, headers=headers, data=data, timeout=timeout
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 277, in request
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    self.credentials.before_request(auth_request, method, url, request_headers)
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/local/lib/python2.7/dist-packages/google/auth/credentials.py", line 124, in before_request
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    self.refresh(request)
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/local/lib/python2.7/dist-packages/google/auth/compute_engine/credentials.py", line 102, in refresh
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    six.raise_from(new_exc, caught_exc)
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	  File "/usr/lib/python2.7/dist-packages/six.py", line 737, in raise_from
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	    raise value
run-sample-tests-loop(4:secret):	using-google-cloud-apis-with-auth:	google.auth.exceptions.RefreshError: ('Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 500 Response:\nGKE Metadata Server encountered an error: Could not recursively fetch uri\n', <google.auth.transport.requests._Response object at 0x7f32e3834650>)
run-sample-tests-loop(4:secret):	access-gcs-using-auth-token:	gs://ml-pipeline-playground/shakespeare1.txt
run-sample-tests-loop(4:secret):	access-gcs-using-auth-token:	Auth token is located at /secret/gcp-credentials/user-gcp-sa.json
```

**Comment by pahask8** [comment]
Thank you, looks like it passed now.

**Pull request merged**
