### PR TITLE
chore(components/google-cloud): Refer to Vertex AI instead of AI Platform (Unified)

### PR DESCRIPTION
**Pull request by dakl**
**Description of your changes:**

* Update readme to refer to Vertex AI instead of AIP Unified

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
/assign @sasha-gitg @SinaChavoshi

FYI, you might want to update the OWNERS file to remove people who do not need to review coming PRs.
Each PR will be assigned to two reviewers in the list randomly.

**Review by SinaChavoshi — APPROVED** [review]
Thank you for the PR.

**Comment by dakl** [comment]
@SinaChavoshi thanks for approval. Looks like I need a `/ok-to-test` to be able to rerun the failed test. Not really sure what to do about it though. Is master broken? I don't see how my changes should cause CI to fail like this. Maybe I should merge master and then retest?

**Pull request merged**
