### PR TITLE
2014: support a docker context in kfp compiler

### PR DESCRIPTION
**Pull request by pahask8**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2015)

### CODE REVIEW

**Comment by pahask8** [comment]
@Ark-kun, could you please take a look? Thank you

**Comment by Ark-kun** [comment]
Maybe this class can serve you better?
```python
from kfp.compiler._container_builder import ContainerBuilder
ContainerBuilder().build(local_dir=...)
```

We'll probably move it to `kfp.containers.KanikoImageBuilder` in future.

**Comment by pahask8** [comment]
> Maybe this class can serve you better?
> 
> ```python
> from kfp.compiler._container_builder import ContainerBuilder
> ContainerBuilder().build(local_dir=...)
> ```
> 
> We'll probably move it to `kfp.containers.KanikoImageBuilder` in future.

Thank you for update. Yes, this will work but it will be accessing to the protected member of the module. Why we can't merge this improvement? This will add a really helpful feature because there are a few cases where you really need a Dockerfile without any context.

Thank you

**Comment by Ark-kun** [comment]
> This will add a really helpful feature because there are a few cases where you really need a Dockerfile without any context.

Can you also take a look at the new public container-building API:
`kfp.containers.build_image_from_working_dir`:
https://github.com/kubeflow/pipelines/blob/44a08a5275092e0cbb4f9550c06915976bb353ed/sdk/python/kfp/containers/_build_image_api.py#L72

It supports Docker context directory that can optionally contain `Dockerfile` or `requirements.txt`. (Note that by default only *.py files from the context are grabbed).

**Comment by pahask8** [comment]
Thank you, closing the pull request.

**Comment by Ark-kun** [comment]
> Thank you, closing the pull request.

Sorry about the duplication of work.

When you've submitted your PR, the PR adding this functionality was already pending (https://github.com/kubeflow/pipelines/pull/1970) and we were in the middle of effort to reduce the number of different container-building APIs (https://github.com/kubeflow/pipelines/pull/2276 https://github.com/kubeflow/pipelines/pull/2277 https://github.com/kubeflow/pipelines/pull/2266). The API you wanted to extend was subject to deprecation (https://github.com/kubeflow/pipelines/pull/2276). This is why I was hesitant to add new features to it, given that the new API supports them explicitly.

Thank you.

**Pull request closed without merging**
