### PR TITLE
Frontend - Metadata - Use custom properties in addition to plain properties

### PR DESCRIPTION
**Pull request by Ark-kun**
Adapting to the recent TFX changes https://github.com/kubeflow/pipelines/issues/2562#issuecomment-572818936

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2854)

### CODE REVIEW

**Comment by Bobgy** [comment]
Just want to double check, does the new UI work with current tfx sample?

**Comment by Bobgy** [comment]
Nevermind, I saw that you have always tried to use the old value first.
/hold cancel

**Comment by Ark-kun** [comment]
This is currently a backwards compatible change.
The old properties are still used (I've corrected the title), so the UX will still work with the current TFX sample.
Without this change, the UX will stop working for the TFX sample once the TFX SDK updates.
/hold cancel

**Pull request merged**
