### PR TITLE
refactor(components): AWS SageMaker - Black format all files

### PR DESCRIPTION
**Pull request by RedbackThomson**
**Description of your changes:**
I ran the `black` formatter on our entire codebase to align all of our Python scripts with a standard format. Also added a step that ensures that the current PR has formatted the code base properly.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by surajkota** [comment]
good change, needs more time to review. Few comments:

1. Can we use the config from here so that all files are in sync - https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/tests/integration_tests/.flake8

2. Is it possible to include aws-samples also in the PR and automated test?

**Comment by RedbackThomson** [comment]
>  Can we use the config from here so that all files are in sync - https://github.com/kubeflow/pipelines/blob/master/components/aws/sagemaker/tests/integration_tests/.flake8

Flake8 is a more lenient form of style checker and it doesn't come with an automatic formatter - so the developer would have to format it based on the errors in provides. Black is easier because you can run `black .` on the root directory and it will propogate through all files.

**Comment by RedbackThomson** [comment]
Closing - to be included as part of a larger refactor.

**Pull request closed without merging**
