### PR TITLE
chore(components): clean up deprecated GCP components

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**

Follow up on the deprecation notices from README in subfolders (listed below), delete the deprecated component files and references to them.
- https://github.com/kubeflow/pipelines/blob/43cdbbe118b5b8508aa9b52684cd49d217f33204/components/gcp/automl/README.md
- https://github.com/kubeflow/pipelines/blob/43cdbbe118b5b8508aa9b52684cd49d217f33204/components/gcp/bigquery/README.md
- https://github.com/kubeflow/pipelines/blob/43cdbbe118b5b8508aa9b52684cd49d217f33204/components/gcp/dataflow/README.md
- https://github.com/kubeflow/pipelines/blob/43cdbbe118b5b8508aa9b52684cd49d217f33204/components/gcp/dataproc/README.md
- https://github.com/kubeflow/pipelines/blob/43cdbbe118b5b8508aa9b52684cd49d217f33204/components/gcp/ml_engine/README.md

For reviewers, easiest way to review this PR is review by commits:
- first commit deleted the `components/gcp` folder
- second commits deleted related script and updated any reference to the deleted files from master branch.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
> @chensun: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> kubeflow-pipelines-integration-v2	[36e0f2e](https://github.com/kubeflow/pipelines/commit/36e0f2e51acffb4e740f91a356c240442f7bb405)	[link](https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/8685/kubeflow-pipelines-integration-v2/1615504506932432896)	true	`/test kubeflow-pipelines-integration-v2`

This test runs on a long running cluster with KFP 2.0.0-alpha.6 deployed, so the API not defined error is expected. Once we have a beta release and update the test cluster, the issue should be gone.

**Comment by chensun** [comment]
test failure should be resolved by https://github.com/kubeflow/pipelines/pull/8841

**Comment by gkcalat** [comment]
/lgtm
/approve

Thank you, @chensun!

**Pull request merged**
