### PR TITLE
feat(sdk): Make kaniko_executor_image a parameter for ContainerBuilder

### PR DESCRIPTION
**Pull request by casassg**
**Description of your changes:**

ContainerBuilder has kaniko executor image path hard set to the open GCR kaniko-project repository.

However, for users running Kubernetes with closed GCR repositories (aka only certain GCR repositories are allowlisted), this makes the default ContainerBuilder not possible to use. By parametrizing, we can allow users to overwrite the fields if needed.

At Twitter, we had to manually overwrite this field to replace it with an GCR path with the image re-uploaded on an allowlisted internal repository.

However this overwrite is using private APIs of this class. Instead of doing that, we would prefer to parametrize ContainerBuilder so that we don't have to rely on private APIs.

### CODE REVIEW

**Comment by casassg** [comment]
@chensun not sure how to see why the test failed. If I try to go to the pipeline url, it gives me a 403 error.

**Comment by casassg** [comment]
@chensun any idea on wether this can be included on the 1.7 release?

**Comment by chensun** [comment]
> @chensun any idea on wether this can be included on the 1.7 release?

Yes, we'll include this in the next SDK release.

**Pull request merged**
