### PR TITLE
switch default tag to strongly typed version number

### PR DESCRIPTION
**Pull request by IronPan**
Having strongly versioned image tag would help identifying issue more efficiently. We should consider avoid latest tag even though it's just default value.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/234)

### CODE REVIEW

**Comment by Ark-kun** [comment]
@IronPan Can this PR wait for #232 or do you need it to be merged ASAP?

**Comment by IronPan** [comment]
No worry. This is not urgent.

**Pull request merged**
