### PR TITLE
fix(release): Add v1 and v2 proto generation. Closes #8818

### LINKED ISSUE #8818: chore(backend): Update release script due to proto generation changes in V2
We need to update one of the release scripts due to the changes in API generator script:

- Add `API_VERSION` variable
- Add proto compilation for v1 and v2

---

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by gkcalat**
**Description of your changes:**

- Export `API_VERSION`
- Repeat API generation for `v1beta1` and `v2beta1`

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by gkcalat** [comment]
Closes #8818

**Review by chensun — APPROVED** [review]
/lgtm

**Comment by chensun** [comment]
Test issue is being fixed by https://github.com/kubeflow/pipelines/pull/8821

**Pull request merged**
