### PR TITLE
Trims whitespace from pipeline params on creation of new run

### LINKED ISSUE #162: Pipeline input cleansing
It might make sense to cleanse the pipeline input. 
For example, if there is a parameter that requires a GCS path, with a negligible SPACE before the GCS path(e.g. " gs://pipeline/input-bucket") would lead to the pipeline failure. This type of bugs are hard to detect.

### PR DESCRIPTION
**Pull request by rileyjbauer**
Fixes #162

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1605)

### CODE REVIEW

**Comment by gaoning777** [comment]
@sinachavoshi What do you think of trimming the spaces in the pipeline input?

**Comment by gaoning777** [comment]
verified with sina offline. It's reasonable to trim the spaces/tabs in the input params during the run creation.
/lgtm

**Comment by Ark-kun** [comment]
/lgtm
Note that in future we might start getting requests to add the ability to turn this off.
There are some legitimate cases to want control over whitespace. The simplest is when the user wants to specify column separator character (usually space or tab).

**Pull request merged**
