### PR TITLE
SDK - Stop adding empty descriptions and inputs

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1969)

### CODE REVIEW

**Comment by numerology** [comment]
It lgtm to remove empty description. May I ask is it still allow to specify description=''?

**Comment by Ark-kun** [comment]
Yes, the actual schema does not change.

**Comment by Ark-kun** [comment]
@gaoning777 Can you please take another look?

**Pull request merged**
