### PR TITLE
Fix the broken sample path in API

### PR DESCRIPTION
**Pull request by IronPan**
Related change https://github.com/kubeflow/pipelines/commit/b476a848d9894acc6212a88fcecd8df06e0d3cf6

/hold
Need investigate why test doesn't catch it. 

/assign @numerology @gaoning777

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1805)

### CODE REVIEW

**Comment by numerology** [comment]
Sorry I'm not aware of this part of test.
May I ask where the related backend test lives? Thanks!

**Comment by IronPan** [comment]
@numerology All presubmit tests should fail because API server should in theory fail to start.

**Comment by IronPan** [comment]
With further investigation, it appears these lines didn't fully delete the pipeline's artifact/metadata GCE PD 
https://github.com/kubeflow/pipelines/blob/701b90de7c61bcd0d9ea0b87c53c09d41faa2605/test/deploy-pipeline.sh#L55

The PD backing metadata store is name with `${KFAPP}-storage-metadata-store`
When reinstall the pipeline, the PD got reused and the metadata got recovered. 

The API server decides to load sample or not based on the `HaveSamplesLoaded` flag in the DB
https://github.com/kubeflow/pipelines/blob/701b90de7c61bcd0d9ea0b87c53c09d41faa2605/backend/src/apiserver/main.go#L145
Because the DB's PD is reused, the flag is still true after reinstall, thus it skipped to load the samples.

**Comment by gaoning777** [comment]
> With further investigation, it appears these lines didn't fully delete the pipeline's artifact/metadata GCE PD
> https://github.com/kubeflow/pipelines/blob/701b90de7c61bcd0d9ea0b87c53c09d41faa2605/test/deploy-pipeline.sh#L55
> 
> The PD backing metadata store is name with `${KFAPP}-storage-metadata-store`
> When reinstall the pipeline, the PD got reused and the metadata got recovered.
> 
> The API server decides if needs to load samples based on the `HaveSamplesLoaded` flag in the DB
> https://github.com/kubeflow/pipelines/blob/701b90de7c61bcd0d9ea0b87c53c09d41faa2605/backend/src/apiserver/main.go#L145
> 
> 
> Because the DB's PD is reused, the flag is still true after reinstall, thus it skipped to load the samples.

Thanks for the investigation. This is really important for the test to catch the errors.

**Pull request merged**
