### PR TITLE
SDK - Moved _dsl_bridge to dsl

### PR DESCRIPTION
**Pull request by Ark-kun**
This is a pure refactoring change.
The components library should not have any dependencies on the DSL library.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3267)

### CODE REVIEW

**Comment by Ark-kun** [comment]
/approve
@numerology Can you please take a look?

**Comment by numerology** [comment]
There is a silent bump causing dependencies issues in the sample test dockerfile. Fixing in https://github.com/kubeflow/pipelines/pull/3119

**Pull request merged**
