### PR TITLE
add ai_platform test

### PR DESCRIPTION
**Pull request by gaoning777**
Add AI_platform sample test
debug the model delete permission issue.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2327)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Is this similar to https://github.com/kubeflow/pipelines/pull/2236?

**Comment by numerology** [comment]
> Is this similar to #2236?

I think @gaoning777 is investigating how to delete models and versions in the notebook, which is blocked by some permission issue.
In #2236 the plan is just run the pipeline and use some separate logic to GC the model and version generated during execution.

**Comment by gaoning777** [comment]
Looks like the service accounts are working fine. @numerology

**Comment by gaoning777** [comment]
Looks like the service accounts are working fine. @numerology

**Comment by numerology** [comment]
/lgtm

Thanks @gaoning777  !

**Comment by gaoning777** [comment]
fixing https://github.com/kubeflow/pipelines/issues/1813

**Pull request merged**
