### PR TITLE
Fixed workflow parameters support for withItems task feature

### PR DESCRIPTION
**Pull request by meiblorn**
**Problem:** 

When I am trying to use pipeline parameters inside `withItems` section, kubeflow SDK leaves it as is, what later becomes a reason of throwing an exception:
```python
    if '{{pipelineparam' in yaml_text:
      raise RuntimeError(
          'Internal compiler error: Found unresolved PipelineParam. '
          'Please create a new issue at https://github.com/kubeflow/pipelines/issues '
          'attaching the pipeline code and the pipeline package.' )
```

**Solution:**
This fix solves issue by passing an args array deeper in code. I understand, fix is not brilliant ... but it works for me.

It parses all the unresolved `pipelineparam` items in `withItems` section and converts them to `workflow.parameter.%name_placeholder%` string.

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2691)

### CODE REVIEW

**Comment by meiblorn** [comment]
@googlebot I signed it!

**Comment by Ark-kun** [comment]
Does this fix work when you use task's output in `withItems`?

**Pull request closed without merging**
