### PR TITLE
Minor fix on samples/tfx-oss/README.md

### PR DESCRIPTION
**Pull request by ucdmkt**
- TFX whl doesn't seem to install TensorFlow
- Remove `!` at the beginning (copy'n'pasted from notebook?)
- There is no longer taxi_pipelien_kubeflow_large.py in https://github.com/tensorflow/tfx/tree/master/examples/chicago_taxi_pipeline

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/969)

### CODE REVIEW

**Comment by neuromage** [comment]
/hold

Hmm, looks like these changes aren't based on master. I think some of this has already  been fixed. Requiring TF 1.12 is a change worth making though. Can you sync and try again? Thanks.

**Comment by Ark-kun** [comment]
BTW, does TFX on Kubeflow requires TF to be installed? Sure, the components use it, but is it needed on the client machine?

**Comment by ucdmkt** [comment]
Without TF installed on client machine, graph compilation failed in my environment.

**Comment by Ark-kun** [comment]
> Without TF installed on client machine, graph compilation failed in my environment.

You should probably also create an issue in https://github.com/tensorflow/tfx .

**Comment by neuromage** [comment]
> > Without TF installed on client machine, graph compilation failed in my environment.
> 
> You should probably also create an issue in https://github.com/tensorflow/tfx .

I don't think that's needed. This seems to be about instructions for running it with KFP, which belong here.

**Comment by vicaire** [comment]
@ucdmkt, is this PR still needed? Can we close?

**Comment by ucdmkt** [comment]
@vicaire I think it is still relevant for the first two bullet points?

**Comment by Ark-kun** [comment]
> I don't think that's needed. This seems to be about instructions for running it with KFP, which belong here.

I do not see any usage of raw TF in the TFX Kubeflow sample:
https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow.py

Is it the case that TFX requires TF, but does not install it when installed using the wheel?

**Comment by ucdmkt** [comment]
> Is it the case that TFX requires TF, but does not install it when installed using the wheel?

Indeed. TFX whl doesn't come with TF. And, [TFX documentation](https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/workshop.md#step-1-setup-your-environment) instructs users to separately pip install TensorFlow.


(also; updated path to example code according to latest tensorflow/tfx)

```
$ python tfx/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow.py
Traceback (most recent call last):
  File "tfx/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow.py", line 21, in <module>
    from tfx.components.evaluator.component import Evaluator
  File "/usr/local/google/home/muchida/miniconda3/envs/tfx-kfp-2/lib/python3.5/site-packages/tfx/components/evaluator/component.py", line 23, in <module>
    from tfx.components.base import base_driver
  File "/usr/local/google/home/muchida/miniconda3/envs/tfx-kfp-2/lib/python3.5/site-packages/tfx/components/base/base_driver.py", line 20, in <module>
    import tensorflow as tf
ImportError: No module named 'tensorflow'
```

**Comment by neuromage** [comment]
@vicaire @IronPan @Ark-kun can one of you please approve? Thanks.

**Comment by Ark-kun** [comment]
> Indeed. TFX whl doesn't come with TF. And, [TFX documentation](https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/workshop.md#step-1-setup-your-environment) instructs users to separately pip install TensorFlow.

I see. That's rather inconvenient.

**Comment by Ark-kun** [comment]
> @vicaire @IronPan @Ark-kun can one of you please approve? Thanks.

Sure
/approve

**Pull request merged**
