### PR TITLE
Update WORKSPACE and BUILD files incoporating recent changes

### LINKED ISSUE #638: Building backend using Bazel fails on mac
Latest master, installed bazel throw homebrew:
```
$ bazel build //backend/...
INFO: Invocation ID: 1f680dcf-8507-4bfc-b2f3-41bfa0d7c68f
DEBUG: /private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/external/bazel_skylib/lib.bzl:30:1: WARNING: lib.bzl is deprecated and will go away in the future, please directly load the bzl file(s) of the module(s) needed as it is more efficient.
INFO: Analysed 176 targets (0 packages loaded, 0 targets configured).
INFO: Found 176 targets...
ERROR: /Users/me/dev/pipelines/backend/src/apiserver/storage/BUILD.bazel:42:1: GoCompile backend/src/apiserver/storage/darwin_amd64_stripped/go_default_test%/github.com/kubeflow/pipelines/backend/src/apiserver/storage.a failed (Exit 1) compile failed: error execu
ting command bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/darwin_amd64_stripped/compile -sdk external/go_sdk -installsuffix darwin_amd64 -src backend/src/apiserver/storage/db.go -src ... (remaining 92 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
GoCompile: error running compiler: exit status 2
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/14/execroot/__main__/backend/src/apiserver/storage/db_fake.go:40:4: undefined: model.DBStatus
INFO: Elapsed time: 3.409s, Critical Path: 2.53s
INFO: 13 processes: 13 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

I then re-generated the BUILD files using gazelle then tried to build again, but got this:
```
$ bazel build //backend/...
INFO: Invocation ID: 7482fdf4-e759-4d82-856e-0506efd47832
DEBUG: /private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/external/bazel_skylib/lib.bzl:30:1: WARNING: lib.bzl is deprecated and will go away in the future, please directly load the bzl file(s) of the module(s) needed as it is more efficient.
INFO: Analysed 176 targets (152 packages loaded, 1632 targets configured).
INFO: Found 176 targets...
ERROR: /Users/me/dev/pipelines/backend/src/common/client/api_server/BUILD.bazel:3:1: GoCompile backend/src/common/client/api_server/darwin_amd64_stripped/go_default_library%/github.com/kubeflow/pipelines/backend/src/common/client/api_server.a failed (Exit 1) comp
ile failed: error executing command bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/darwin_amd64_stripped/compile -sdk external/go_sdk -installsuffix darwin_amd64 -src ... (remaining 84 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
GoCompile: error running compiler: exit status 2
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:35:28: cannot use runtime (type *"github.com/go-openapi/runtime/client".Runtime) as type "github.com/
kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientTransport in argument to experiment_client.New:
        *"github.com/go-openapi/runtime/client".Runtime does not implement "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientTransport (wrong type for Submit method)
                have Submit(*"github.com/go-openapi/runtime".ClientOperation) (interface {}, error)
                want Submit(*"github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientOperation) (interface {}, error)
/private/var/tmp/_bazel_yelsayed/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:35:28: cannot use "github.com/go-openapi/strfmt".Default (type "github.com/go-openapi/strfmt".Registry) as type "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/strfmt".Registry in argument to experiment_client.New:
        "github.com/go-openapi/strfmt".Registry does not implement "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/strfmt".Registry (wrong type for Add method)
                have Add(string, "github.com/go-openapi/strfmt".Format, "github.com/go-openapi/strfmt".Validator) bool
                want Add(string, "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/strfmt".Format, "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/strfmt".Validator) bool
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:51:65: cannot use parameters (type *"github.com/kubeflow/pipelines/backend/api/go_http_client/experiment_client/experiment_service".CreateExperimentParams) as type *"github.com/kubeflow/pipelines/backend/api/vendor/github.com/kubeflow/pipelines/backend/api/go_http_client/experiment_client/experiment_service".CreateExperimentParams in argument to c.apiClient.ExperimentService.CreateExperiment
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:51:65: cannot use PassThroughAuth (type "github.com/go-openapi/runtime".ClientAuthInfoWriter) as type "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientAuthInfoWriter in argument to c.apiClient.ExperimentService.CreateExperiment:
        "github.com/go-openapi/runtime".ClientAuthInfoWriter does not implement "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientAuthInfoWriter (wrong type for AuthenticateRequest method)
                have AuthenticateRequest("github.com/go-openapi/runtime".ClientRequest, "github.com/go-openapi/strfmt".Registry) error
                want AuthenticateRequest("github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientRequest, "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/strfmt".Registry) error
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:64:17: cannot use response.Payload (type *"github.com/kubeflow/pipelines/backend/api/vendor/github.com/kubeflow/pipelines/backend/api/go_http_client/experiment_model".APIExperiment) as type *"github.com/kubeflow/pipelines/backend/api/go_http_client/experiment_model".APIExperiment in return argument
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:75:62: cannot use parameters (type *"github.com/kubeflow/pipelines/backend/api/go_http_client/experiment_client/experiment_service".GetExperimentParams) as type *"github.com/kubeflow/pipelines/backend/api/vendor/github.com/kubeflow/pipelines/backend/api/go_http_client/experiment_client/experiment_service".GetExperimentParams in argument to c.apiClient.ExperimentService.GetExperiment
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:75:62: cannot use PassThroughAuth (type "github.com/go-openapi/runtime".ClientAuthInfoWriter) as type "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientAuthInfoWriter in argument to c.apiClient.ExperimentService.GetExperiment:
        "github.com/go-openapi/runtime".ClientAuthInfoWriter does not implement "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientAuthInfoWriter (wrong type for AuthenticateRequest method)
                have AuthenticateRequest("github.com/go-openapi/runtime".ClientRequest, "github.com/go-openapi/strfmt".Registry) error
                want AuthenticateRequest("github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientRequest, "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/strfmt".Registry) error
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:88:17: cannot use response.Payload (type *"github.com/kubeflow/pipelines/backend/api/vendor/github.com/kubeflow/pipelines/backend/api/go_http_client/experiment_model".APIExperiment) as type *"github.com/kubeflow/pipelines/backend/api/go_http_client/experiment_model".APIExperiment in return argument
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:99:63: cannot use parameters (type *"github.com/kubeflow/pipelines/backend/api/go_http_client/experiment_client/experiment_service".ListExperimentParams) as type *"github.com/kubeflow/pipelines/backend/api/vendor/github.com/kubeflow/pipelines/backend/api/go_http_client/experiment_client/experiment_service".ListExperimentParams in argument to c.apiClient.ExperimentService.ListExperiment
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:99:63: cannot use PassThroughAuth (type "github.com/go-openapi/runtime".ClientAuthInfoWriter) as type "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientAuthInfoWriter in argument to c.apiClient.ExperimentService.ListExperiment:
        "github.com/go-openapi/runtime".ClientAuthInfoWriter does not implement "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientAuthInfoWriter (wrong type for AuthenticateRequest method)
                have AuthenticateRequest("github.com/go-openapi/runtime".ClientRequest, "github.com/go-openapi/strfmt".Registry) error
                want AuthenticateRequest("github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/runtime".ClientRequest, "github.com/kubeflow/pipelines/backend/api/vendor/github.com/go-openapi/strfmt".Registry) error
/private/var/tmp/_bazel_me/3f151afcbbadf3f1c35b4c73adfaf525/sandbox/darwin-sandbox/25/execroot/__main__/backend/src/common/client/api_server/experiment_client.go:99:63: too many errors
INFO: Elapsed time: 4.154s, Critical Path: 1.85s
INFO: 26 processes: 26 darwin-sandbox.
```

@neuromage any ideas? Haven't tried building on linux, so this might be mac only.
/area back-end

### PR DESCRIPTION
**Pull request by neuromage**
In particular, fix it for the change in #449 which introduced more dependencies from using the  controller-runtime Kubernetes library. That change was submitted in parallel with the PR that moved everything to Bazel and so wasn't included.

Along the way, fix conflicts in imports that was using
controller-runtime library. We can import it either through
github.com/kubernetes-sigs or sigs.k8s.io/controller-runtime, but
shouldn't be using both imports, which was causing conflicts at build
time.

Fixes #638

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/639)

### CODE REVIEW

**Comment by neuromage** [comment]
We should probably also make Bazel build and test everything as part of Travis. I'll look into doing that.

**Comment by IronPan** [comment]
@neuromage Does Prow tests need to be updated too?
https://github.com/kubeflow/pipelines/blob/master/test/api-integration-test/run_test.sh#L67

**Comment by neuromage** [comment]
> @neuromage Does Prow tests need to be updated too?
Not necessary. #640 will add it as part of Travis. We still want `go test` to continue working anyway for now.

**Pull request merged**
