### PR TITLE
chore: release KFP SDK and v2 launcher 1.7.0

### PR DESCRIPTION
**Pull request by ji-yaqi**

### CODE REVIEW

**Comment by chensun** [comment]
kubeflow-pipelines-samples-v2 failed because kfp 1.7.0 isn't available yet, which is expected.
```
ERROR: Could not find a version that satisfies the requirement kfp==1.7.0 (from versions: 0.1.11, 0.1.16, 0.1.19, 0.1.23, 0.1.23.1, 0.1.24, 0.1.25, 0.1.26, 0.1.27, 0.1.29, 0.1.30, 0.1.31, 0.1.31.1, 0.1.31.2, 0.1.32, 0.1.32.1, 0.1.32.2, 0.1.33, 0.1.34, 0.1.35, 0.1.36, 0.1.37, 0.1.38, 0.1.39, 0.1.40, 0.2.0, 0.2.1, 0.2.2, 0.2.2.1, 0.2.4, 0.2.4.1, 0.2.5, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 1.0.0rc4, 1.0.0rc5, 1.0.0, 1.0.1rc1, 1.0.1, 1.0.3rc1, 1.0.3, 1.0.4, 1.1.0a1, 1.1.0, 1.1.1b1, 1.1.1rc0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.4.0rc1, 1.4.0, 1.4.1rc0, 1.4.1rc1, 1.6.0rc0, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6)
ERROR: No matching distribution found for kfp==1.7.0
```

I think we can force merge this PR, then think about how to address this going forward. 

Maybe it means we need to change our release process to be:
1. Make a PR like this one, expect the test to fail.
2. Build KFP SDK and publish the package.
3. Rerun test and merge the PR.

/cc @ji-yaqi @neuromage

**Comment by neuromage** [comment]
> kubeflow-pipelines-samples-v2 failed because kfp 1.7.0 isn't available yet, which is expected.
> 

That's strange. The sample tests are supposed to install KFP from the pull request directly, not from PyPi. Can you ping me the link to the failed pipeline please?

**Comment by neuromage** [comment]
Ah, nvm, looks like the failing pipelines did not set up its components correctly. @ji-yaqi @chensun I can send a fix for this now.

**Pull request merged**
