### PR TITLE
Show version tag in UI

### PR DESCRIPTION
**Pull request by Bobgy**
Fixes https://github.com/kubeflow/pipelines/issues/3000

Implementation details can refer from: https://github.com/kubeflow/pipelines/issues/3000#issuecomment-583935207

/area frontend
/area backend

/assign @jingzhang36 

Screenshot (feels like we are releasing 1.0 for real now, lol):
Screen Shot 2020-05-12 at 4 40 15 PM

### CODE REVIEW

**Comment by Bobgy** [comment]
/hold
I need to test this e2e.

**Comment by Bobgy** [comment]
Verified this works well. I got UI showing the tag name I passed from dockerfile.

**Comment by Bobgy** [comment]
/approve
on frontend changes

**Comment by jingzhang36** [comment]
/lgtm
/approve
A qq: if we have different versions for FE and BE. E.g., frontend is 0.5.0 and backend is 0.4.0. Which one UI will show?

**Comment by Bobgy** [comment]
> /lgtm
> /approve
> A qq: if we have different versions for FE and BE. E.g., frontend is 0.5.0 and backend is 0.4.0. Which one UI will show?

Backend will be shown. If backend is not available, frontend version will be shown.

**Comment by Bobgy** [comment]
/unhold
travis test passed

**Pull request merged**
