### PR TITLE
[Testing] Use google/cloud-sdk:279.0.0 to resolve workload identity flakiness

### PR DESCRIPTION
**Pull request by Bobgy**
Same rationale as https://github.com/kubeflow/pipelines/pull/3018,
but this PR tries if the new version is stable

Discussion about which versions are good: b/146669263
It also mentions client version is also related, so I will try upgrading google/cloud-sdk version soon

UPDATE 2020.2.10: client version is the most important, after updating to google/cloud-sdk/279.0.0 (latest one), flakiness disappears.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3019)

### CODE REVIEW

**Comment by Bobgy** [comment]
1.15.8 alone doesn't fix the issue, will need to try also use new google/cloud-sdk version

**Comment by Bobgy** [comment]
As mentioned in b/148920399, we also need to update clients to latest.

**Comment by Bobgy** [comment]
/retest
It failed in cloud build, not our problem

**Comment by Bobgy** [comment]
/hold
This doesn't seem good, error messages look a little weird

**Comment by Bobgy** [comment]
1.15.8 doesn't seem compatible with kfp, it triggers some stable integration test failures.
However, it seems upgrading gcloud version is the best fix. Everything seems stable, except secret sample is failing due to `pip` not found. After investigation, it seems google python2 support has stopped. google/cloud-sdk image no longer contains `pip`. I updated the sample to use python3 instead. Let's see if that makes tests pass.

**Comment by Bobgy** [comment]
xgboost timed out, we should increase time limit

**Comment by Bobgy** [comment]
/test kubeflow-pipeline-e2e-test
/test kubeflow-pipeline-sample-test
Now all tests are passing, retry for the first time.

**Comment by Bobgy** [comment]
/test kubeflow-pipeline-e2e-test
/test kubeflow-pipeline-sample-test
Great, passed again. Retry the second time

**Comment by Bobgy** [comment]
Cleaned up unrelated changes

**Comment by numerology** [comment]
Thanks @Bobgy !
Let me give a third shot:)

**Comment by numerology** [comment]
Took a look and it seems like Travis is complaining about the version of six. Perhaps we need to pin it in .travis.yaml to get it fixed.

Specifically, test on py35 passed because it got six==1.12.0 while other failed with six==1.11.0

**Comment by Bobgy** [comment]
@numerology Thank you! Let me try that

**Comment by numerology** [comment]
FYI the fix is pending here https://github.com/kubeflow/pipelines/pull/3035

**Comment by Bobgy** [comment]
@numerology separated travis test failure to a separate PR: https://github.com/kubeflow/pipelines/pull/3039

**Comment by Bobgy** [comment]
/hold cancel
I'll self approve because this seems stable now.

**Pull request merged**
