### PR TITLE
add an optional name for dsl.Condition (kubeflow#3210)

### PR DESCRIPTION
**Pull request by xiaohanhuang**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3212)

### CODE REVIEW

**Comment by xiaohanhuang** [comment]
Don't know why the CLA didn't work, all my information are correct now.

**Comment by numerology** [comment]
Thanks! @xiaohanhuang  do you mind adding some tests for this?

**Comment by xiaohanhuang** [comment]
> Thanks! @xiaohanhuang do you mind adding some tests for this?
Added tests

**Pull request merged**
