### PR TITLE
Pin sample doc links during backend image build

### PR DESCRIPTION
**Pull request by Bobgy**
Part of https://github.com/kubeflow/pipelines/issues/2721#issuecomment-565287314

/assign @numerology 
/cc @Ark-kun

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2880)

### CODE REVIEW

**Comment by numerology** [comment]
Thanks @Bobgy !

**Comment by Bobgy** [comment]
Thanks for review, also
/assign @jingzhang36 
for backend review

**Pull request merged**
