### PR TITLE
test(v2): presubmit unit tests of v2

### LINKED ISSUE #5685: [Launcher] presubmit unit tests
https://github.com/kubeflow/pipelines/tree/master/v2

this should run:
* go mod tidy
* go test ./... (including tests that use an one-off MLMD local server)

### PR DESCRIPTION
**Pull request by capri-xiyue**
**Description of your changes:**
fixed #5685 
presubmit unit tests of v2
**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by capri-xiyue** [comment]
@Bobgy Looks like I need to add this presubmit tests into some prow config. Do you know where the prow config is?

**Comment by capri-xiyue** [comment]
> @Bobgy Looks like I need to add this presubmit tests into some prow config. Do you know where the prow config is?

https://github.com/GoogleCloudPlatform/oss-test-infra/pull/890 added

**Comment by Bobgy** [comment]
Thank you!
Shall we call this presubmit-go-v2 test to be more specific?

**Comment by capri-xiyue** [comment]
> Thank you!
> Shall we call this presubmit-go-v2 test to be more specific?

How about `presubmit-go-v2-component-test`?

**Comment by Bobgy** [comment]
> > Thank you!
> > Shall we call this presubmit-go-v2 test to be more specific?
> 
> How about `presubmit-go-v2-task-handler-test`?

We'll keep building KFP v2 go code in this folder, so it won't be `task-handler` specific by then.

**Comment by capri-xiyue** [comment]
> > > Thank you!
> > > Shall we call this presubmit-go-v2 test to be more specific?
> > 
> > 
> > How about `presubmit-go-v2-task-handler-test`?
> 
> We'll keep building KFP v2 go code in this folder, so it won't be `task-handler` specific by then.
How about presubmit-go-v2-backend-test?

**Comment by Bobgy** [comment]
Thank you!

Note, adding a test should start with `test` PR type

**Pull request merged**
