### PR TITLE
MetadataStore:Update metadata grpc server image to use version 0.22.1

### PR DESCRIPTION
**Pull request by dushyanthsc**
Change to upgrade Metadata store to use Metadata grpc server image version 0.22.1

### CODE REVIEW

**Comment by Ark-kun** [comment]
/hold
Need to check whether all the places were updated.

**Comment by Ark-kun** [comment]
Can you please merge the following old PR with the MLMD update instructions and check whether this PR follows them? https://github.com/kubeflow/pipelines/pull/3658

I think this PR might be missing updates to the MLMD client in Frontend and Metadata Writer.

/cc @Bobgy

**Comment by dushyanthsc** [comment]
@Ark-kun Is there are dependency on the image version and not the metadata service?

**Comment by Ark-kun** [comment]
> @Ark-kun Is there are dependency on the image version and not the metadata service?

Can you please help me understand the question?
The reason we have to keep versions in sync: The last time the MLMD server version was updated, we later learned that the MLMD team has introduced a breaking change that started silently returning empty results for artifact queries from older clients. This caused some silent issues in the metadata logging.
The MLMD team has pledged to prevent such silent breaking changes from happening, but we might still want to keep the versions in sync.

WDYT?

**Comment by neuromage** [comment]
@dushyanthsc I think you just need to additionally update the metadata writer dependencies like so: 
https://github.com/kubeflow/pipelines/pull/3657/files

@Ark-kun consider merging your PR, or wait for this to go in and merge, to get the comments in as well.

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/blob/c0124cb74797c2eaa5dfed54ee0a694d52a281ef/test/upgrade-tests.sh#L115
you need add metadata db upgrade tool here

**Comment by Bobgy** [comment]
Update kubeflow/frontend: https://github.com/kubeflow/frontend#generated-protocol-buffers

**Comment by dushyanthsc** [comment]
> > @Ark-kun Is there are dependency on the image version and not the metadata service?
> 
> Can you please help me understand the question?
> The reason we have to keep versions in sync: The last time the MLMD server version was updated, we later learned that the MLMD team has introduced a breaking change that started silently returning empty results for artifact queries from older clients. This caused some silent issues in the metadata logging.
> The MLMD team has pledged to prevent such silent breaking changes from happening, but we might still want to keep the versions in sync.
> 
> WDYT?

@Ark-kun my read from your statement was that metadata-writer had a dependency on the image tag, which got me confused. Metadata-write has a dependency on the released python package.

w.r.t to MLMD team making changes that affect metadata-writer, I feel the right way to do this is an integration e2e test(as my comment in your initial metadata-write PR) run as part of the pre-submit.

**Comment by Ark-kun** [comment]
> @Ark-kun consider merging your PR, or wait for this to go in and merge, to get the comments in as well.

I'd like to, but that PR needs special approval since it adds a comment to a file in the root directory.

Speaking of which, can you please approve my PR adding me to the approvers? The set of people maintaining OSS KFP has changed and we need to update accordingly. https://github.com/kubeflow/pipelines/pull/2254

**Comment by Ark-kun** [comment]
> w.r.t to MLMD team making changes that affect metadata-writer, I feel the right way to do this is an integration e2e test(as my comment in your initial metadata-write PR) run as part of the pre-submit.

I agree. I have an issue logged for that.
The e2e tests would also prevent us from forgetting to upgrade the client version. We should still try to use a single MLMD version across the product. WDYT?

**Comment by Bobgy** [comment]
/hold
We'd also need to have this in the same PR: https://github.com/kubeflow/pipelines/pull/3982#issuecomment-644508517

**Comment by dushyanthsc** [comment]
> > w.r.t to MLMD team making changes that affect metadata-writer, I feel the right way to do this is an integration e2e test(as my comment in your initial metadata-write PR) run as part of the pre-submit.
> 
> I agree. I have an issue logged for that.
> The e2e tests would also prevent us from forgetting to upgrade the client version. We should still try to use a single MLMD version across the product. WDYT?

I would prefer this as well. But the update to image is a customer requirement at this time, but we do not have a point release from MLMD. I would prefer us to go ahead with the image change and follow-up with the metadata-write and ui change, as long as there are no issues with the image update. WDYT?

@Bobgy

**Comment by Ark-kun** [comment]
>we do not have a point release from MLMD
I'm not sure I understand this statement.

> @Ark-kun & @Bobgy
> I would prefer this as well. But the update to image is a customer requirement at this time, but we do not have a point release from MLMD. I would prefer us to go ahead with the image change and follow-up with the metadata-write and ui change, as long as there are no issues with the image update. WDYT?

OK. I never meant to hold you PR for any prolonged time. I thought it would be very easy for you to update the additional places in the same PR, but if you want to do this in a separate PR, then it's OK. Let's just make sure both PRs go in before the 1.0 release. Also both PRs will probably need to be cherry-picked.
WDYT?

**Comment by Bobgy** [comment]
SGTM
/unhold
Created an issue in KFP 1.0 project to track this, to make sure we don't forget about it:  https://github.com/kubeflow/pipelines/issues/4013

**Comment by Ark-kun** [comment]
> Change to upgrade Metadata store to use Metadata grpc server image version 0.22.1

Are you sure this image actually exists?
```
$ docker pull gcr.io/tfx-oss-public/ml_metadata_store_server:0.22.1
Error response from daemon: manifest for gcr.io/tfx-oss-public/ml_metadata_store_server:0.22.1 not found: manifest unknown: Failed to fetch "0.22.1" from request "/v2/tfx-oss-public/ml_metadata_store_server/manifests/0.22.1".
```

**Comment by dushyanthsc** [comment]
> > Change to upgrade Metadata store to use Metadata grpc server image version 0.22.1
> 
> Are you sure this image actually exists?
> 
> ```
> $ docker pull gcr.io/tfx-oss-public/ml_metadata_store_server:0.22.1
> Error response from daemon: manifest for gcr.io/tfx-oss-public/ml_metadata_store_server:0.22.1 not found: manifest unknown: Failed to fetch "0.22.1" from request "/v2/tfx-oss-public/ml_metadata_store_server/manifests/0.22.1".
> ```

Yes, I see the image - https://pantheon.corp.google.com/gcr/images/tfx-oss-public/GLOBAL/ml_metadata_store_server@sha256:b2bd69a85580afbc5b680688bd6ccfa124a78dbbbf13fd3939ba3d9b277faf2b/details?tab=info&project=tfx-oss-public&organizationId=433637338589

**Comment by numerology** [comment]
> > > Change to upgrade Metadata store to use Metadata grpc server image version 0.22.1
> > 
> > 
> > Are you sure this image actually exists?
> > ```
> > $ docker pull gcr.io/tfx-oss-public/ml_metadata_store_server:0.22.1
> > Error response from daemon: manifest for gcr.io/tfx-oss-public/ml_metadata_store_server:0.22.1 not found: manifest unknown: Failed to fetch "0.22.1" from request "/v2/tfx-oss-public/ml_metadata_store_server/manifests/0.22.1".
> > ```
> 
> Yes, I see the image - https://pantheon.corp.google.com/gcr/images/tfx-oss-public/GLOBAL/ml_metadata_store_server@sha256:b2bd69a85580afbc5b680688bd6ccfa124a78dbbbf13fd3939ba3d9b277faf2b/details?tab=info&project=tfx-oss-public&organizationId=433637338589

I just recovered this. It seems like 0.22.1 was incorrectly purged yesterday afternoon. We shall make sure the tags for all the images we have right now keep intact from now on.

**Pull request merged**
