### PR TITLE
[Test/Sample test] Fix model version in AI platform sample

### LINKED ISSUE #2399: [Sample test] AI platform sample test does not generate/reclaim model and version properly
This is because in the deploy phase the version_id was not specified properly. Working on a fix.

### PR DESCRIPTION
**Pull request by numerology**
Fixes #2399

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2400)

### CODE REVIEW

**Comment by gaoning777** [comment]
thanks for the fix.

**Comment by numerology** [comment]
/retest
Seems like GCP is having a bad day.

**Pull request merged**
