### PR TITLE
feat(frontend): caching may now be disabled when starting pipeline runs

### PR DESCRIPTION
**Pull request by TobiasGoerke**
As discussed in #8104 and the subsequent community meeting on 17. August, Kubeflow requires a way to manage its artifacts and cache. 

We've agreed on proceeding and implementing suitable mechanisms step by step.

This first feature adds a switch that lets users disable or enable caching for new pipelines.

2022-08-22 13_54_50-Kubeflow Central Dashboard

Implementation notes:
* I've included a mechanism to restore previous cache staleness values. I.e., when cloning runs and enabling/disabling caching, the initial values may always be restored. 
* The API/SDK doesn't support disabling caching when running referenced pipelines (e.g. see [Python SDK](https://www.google.com/url?q=https://github.com/kubeflow/pipelines/blob/3b1bd08ce0188605cff90e3f14563d55436aac96/sdk/python/kfp/client/client.py%23L985&sa=D&source=docs&ust=1661177270824488&usg=AOvVaw3cGw1fBUWUAzMTKuepoz_j)). Thus, the workflow yaml needs to be fetched with another request when disabling the cache in this case.

### CODE REVIEW

**Comment by TobiasGoerke** [comment]
Does this correspond to your ideas, @chensun and @zijianjoy?

**Comment by TobiasGoerke** [comment]
As discussed with @zijianjoy (see [google docs comments](https://docs.google.com/document/d/1WdPjTgoDj5AdPNYVzqYwVIWKsWjPPphYD3Ck4DFxSLA)), disabling the cache for new runs / jobs is now implemented in the backend. The UI hasn't changed and still features a switch for controlling the cache.

Frontend and backend changes are implemented for both V1 and V2. 

Feel free to review and test them.

Note: There's a new field `disable_cache` in the Run and Job protos. I've decided against declaring the new field in the `CreateRunRequest` or `CreateJobRequest` as this would break backwards compatibility (the body is currently flattened and run/job sent as the top-level object instead of the request object itself).

TODO: reviewing the `v2_template.go`. I'm unsure where how to set the `cachingOptions` here. Also, when `EnableCache` is set to false, the field is removed entirely and the default value `true` is inferred automatically.

**Comment by juliusvonkohout** [comment]
@TobiasGoerke can you rebase to master and fix the merge conflict?

Please try my new cache server at mtr.devops.telekom.de/ai/cache-server:latest with the environment variables MAXIMUM_CACHE_STALENESS=P0DT0H3M30S DEFAULT_CACHE_STALENESS=P0DT0H1M31S

**Comment by TobiasGoerke** [comment]
> @TobiasGoerke can you rebase to master and fix the merge conflict?
> 
> Please try my new cache server at mtr.devops.telekom.de/ai/cache-server:latest with the environment variables MAXIMUM_CACHE_STALENESS=P0DT0H3M30S DEFAULT_CACHE_STALENESS=P0DT0H1M31S

I've tested your changes and they work well for me. The cache is invalidated after a couple of minutes. 

To reproduce and install this PR locally, I've pushed the ml-pipeline images to dockerhub. 
Simply add the following to your top-level kustomization:

```yaml
images:
  - name: gcr.io/ml-pipeline/cache-server
    newName: mtr.devops.telekom.de/ai/cache-server
    newTag: latest
  - name: gcr.io/ml-pipeline/frontend
    newName: tobiasgoerke/ml-pipeline-frontend
  - name: gcr.io/ml-pipeline/api-server
    newName: tobiasgoerke/ml-pipeline-api-server

patchesStrategicMerge:
- |
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cache-server
    namespace: kubeflow
  spec:
    template:
      spec:
        containers:
        - name: server
          env:
          - name: MAXIMUM_CACHE_STALENESS
            value: P0DT0H3M30S
          - name: DEFAULT_CACHE_STALENESS
            value: P0DT0H1M31S
```

**Note**: some tests are failing. These are the same currently failing upstream.

**Comment by juliusvonkohout** [comment]
APi changes are to be discussed with @Linchin

**Comment by juliusvonkohout** [comment]
As discussed in todays KFP meeting I will break off the cacheserver stuff into another very small PR such that @chensun can review and merge it independently.

**Pull request closed without merging**
