### PR TITLE
Release cb7342c5c19bfbc2f4f253e7ada9f9ff909594d1

### PR DESCRIPTION
**Pull request by gaoning777**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2795)

### CODE REVIEW

**Comment by numerology** [comment]
Seems like the fix in #2779 is not valid. Let me take a look

**Comment by numerology** [comment]
@gaoning777  I took a look and it seems like gcr.io/ml-pipeline/ml-pipeline-gcp:a8fcec5f702fc2528c87ed6fd698b9cfca8b509e does not contain the change in #2779 . Can you confirm?

**Comment by gaoning777** [comment]
I tried to pull the master, merge, and push. Let's see how it goes.

**Comment by gaoning777** [comment]
/hold 
There are bugs in the gcp components.

**Comment by numerology** [comment]
Memo:

There are two issues about the invocation style of Python fire right now.
1. it should be `ui_metadata_path` instead of `ui-metadata-path`; and
2. `ui_metadata_path` needs to be the first in the argument list.

Will put together a fix shortly.

**Comment by gaoning777** [comment]
Thanks Jiaxiao for the investigation.

**Pull request closed without merging**
