### PR TITLE
refactor(sdk): Refactored ResourceOp deletion

### PR DESCRIPTION
**Pull request by Ark-kun**
Part of the efforts to make the DSL orchestrator-agnostic. https://github.com/kubeflow/pipelines/issues/4083

### CODE REVIEW

**Comment by elikatsis** [comment]
@Ark-kun,
KFP is highly tied to Argo and there are PRs that tie it even more (static & runtime workflow parsing, durations, i/o display, `argo lint`, caching, etc.).

So what's the end goal? Argo independence makes sense but I'm confused since your proposal in [this issue](https://github.com/kubeflow/pipelines/issues/3820) is in the opposite direction.

Is there a roadmap for this?
Is there a discussion somewhere so that we have shared context?
What are alternative execution engines that we are targeting?

If we have access to this information, we'd be happy to use some other feature to manage resources.
I could help with this, since I wrote this code and as you've said [here](https://github.com/kubeflow/pipelines/issues/2320#issuecomment-633718857):
>[these] are community contributions and may have bugs. It's pretty hard for our team to provide support for it.

If you don't mind, I'll hold this PR
/hold

**Comment by Ark-kun** [comment]
@elikatsis 
We're trying to balance between making KFP feature-rich and locking in our customers to a particular orchestrator. Although there are gaps, we're trying to have an abstraction layer that allows changing the implementation.

ResourceOp is an Argo-specific feature, but it's pretty easy to just implement it as a container. In fact Argo itself just uses a container with launcher that executes kubectl. Controlling the code will allow us to add more features for manipulating Kubernetes resources.

Switching ResourceOp to just be a ContainerOp factory will significantly simplify the compiler.

It will also allow VolumeOp etc proper components (neither ContainerOp or ResourceOp are currently components). This will allow including them in portable graph components.

I'd like to make this move to reduce Argo exposure and improve portability. The portability increase should be advantageous for you as well.

WDYT?

**Comment by Ark-kun** [comment]
@elikatsis Friendly ping.

**Comment by elikatsis** [comment]
@Ark-kun 

Sure, it sounds good. Could you provide some answers to my previous questions?
>Is there a roadmap for this?
Is there a discussion somewhere so that we have shared context?
What are alternative execution engines that we are targeting?

[Also mentioned in my previous comment, but rephrasing]
What about the UI being totally Argo dependent?

**Comment by Ark-kun** [comment]
> @Ark-kun
> 
> Sure, it sounds good. Could you provide some answers to my previous questions?
> 
> > Is there a roadmap for this?
> > Is there a discussion somewhere so that we have shared context?
> > What are alternative execution engines that we are targeting?
> 
> [Also mentioned in my previous comment, but rephrasing]
> What about the UI being totally Argo dependent?

There is some community work on using KFP with Tekton. There are PRs to add KFP support to TFX SDK.
There are also requests to add support for running locally.
No concrete plans for now. Just cleanup and refactoring.

There is a bit of discussion here: https://github.com/kubeflow/pipelines/issues/4083

**Comment by Bobgy** [comment]
And there will be upcoming efforts to make UI portable too.

**Comment by Ark-kun** [comment]
Friendly ping.

**Comment by elikatsis** [comment]
@Ark-kun sorry forgot to remove hold when I wrote the previous comment

/hold cancel

**Pull request merged**
