### PR TITLE
fix: fix google cloud components tests discovery

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Fixes tests by:
* Adding `__init__.py` recursively to test directories.
* Renaming `types/` directory to `artifact_types/`

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this 
repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
cc/chongyouquan

**Review by Arhell — COMMENTED** [review]
/lgtm

**Pull request closed without merging**
