### PR TITLE
feat(sdk): SDK - Components - Added annotations to InputSpec and OutputSpec

### PR DESCRIPTION
**Pull request by Ark-kun**
This allows the component authors to add custom annotation to particular component inputs or outputs.
For example, they can use the annotations to specify the data schema for structured data.
It's might also be a place to set other per-input information.

### CODE REVIEW

**Comment by Bobgy** [comment]
similar question, why we are having both?

**Comment by Ark-kun** [comment]
> similar question, why we are having annotations?

This allows the component authors to add custom annotation to particular component inputs or outputs.
For example, they can use the annotations to specify the data schema for structured data.
It's might also be a place to set other per-input information.

**Pull request merged**
