### PR TITLE
add RAG pipeline example

### PR DESCRIPTION
**Pull request by sefgsefg**
Accidentally deleted repo to reissue PR

### CODE REVIEW

**Comment by hbelmiro** [comment]
@sefgsefg what does this PR do?
If it's a mistake, can you please close it?

**Comment by sefgsefg** [comment]
I originally posted a PR, but I accidentally deleted the repo, so I posted a new PR.
This PR is an example about kubeflow pipeline run RAG code

**Comment by hbelmiro** [comment]
> I originally posted a PR, but I accidentally deleted the repo, so I posted a new PR.

@sefgsefg I'm not following. Is this PR still valid? Otherwise, you can click the "Close PR" button below.

**Comment by sefgsefg** [comment]
It's valid

**Comment by hbelmiro** [comment]
It doesn't seem valid. Look at the "Files changed" tab here in this page.

**Review by hbelmiro — CHANGES_REQUESTED** [review]
@sefgsefg there's an issue with your commit. Can you do it again or send a new PR?
image

**Review by sefgsefg — COMMENTED** [review]
changed

**Pull request closed without merging**
