### PR TITLE
Allow adding pipeline with name and description.

### PR DESCRIPTION
**Pull request by neuromage**
Add back the ability to add a pipeline with just the name and description (i.e., not just using the new PipelineMeta construct). This ensures backward compatibility with TFX pipelines SDK.

This fix should obviate the need to pin KFP version as was previously done in  https://github.com/tensorflow/tfx/pull/30.

/assign @gaoning777

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1139)

### CODE REVIEW

**Comment by neuromage** [comment]
Can you approve as well @gaoning777 ? I don't have permissions to approve. Thanks.

**Comment by neuromage** [comment]
/test kubeflow-pipeline-e2e-test
--

**Comment by neuromage** [comment]
> The `dsl.Pipeline` is a private compiler context which I'm moving to the dsl-compiler in a next PR. We should not use it to pass pipeline attributes.
This is already a public-facing function, and this is to fix a breakage in the TFX pipeline construction. Please don't break API compatibility. You are free to deprecate APIs, but not remove them.

**Comment by Ark-kun** [comment]
Talked offline:

* `Pipeliene` is a private DSL--compiler implementation context class
* There was a design error made that exposed this class to public
* Since we did not consider this API to be public, @gaoning777 has modifier some of its methods in a way that broke the backwards compatibility of an undocumented function.
* TFX integration got broken since it has taken a dependency on this API

We need to properly hide this private class, but now we might need to do it gradually without breaking backwards compatibility.

**Comment by Ark-kun** [comment]
I've fixed the merge conflict.
/lgtm

**Pull request merged**
