### PR TITLE
SDK - Components - Added the ComponentSpec.save method

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2264)

### CODE REVIEW

**Comment by numerology** [comment]
I think it would be better if a unittest is added.

**Comment by Ark-kun** [comment]
> I think it would be better if a unittest is added.

I think this code path is tested by the following unit tests:

https://github.com/kubeflow/pipelines/blob/be4f5851ed02c3be780c6f1f97c7cd1de2c342ba/sdk/python/tests/components/test_python_op.py#L166
https://github.com/kubeflow/pipelines/blob/be4f5851ed02c3be780c6f1f97c7cd1de2c342ba/sdk/python/tests/components/test_python_op.py#L175
https://github.com/kubeflow/pipelines/blob/be4f5851ed02c3be780c6f1f97c7cd1de2c342ba/sdk/python/tests/components/test_python_op.py#L730

This PR just extracts/moves the code.

**Pull request merged**
