### PR TITLE
[UIServer] Add DISABLE_GKE_METADATA env flag to skip metadata retrieval.

### PR DESCRIPTION
**Pull request by Bobgy**
/area frontend
/kind feature

Resolves https://github.com/kubeflow/pipelines/issues/3070

Changes:
1. Added a flag DISABLE_GKE_METADATA that people can put on `ml-pipeline-ui` deployment to turn off gke metadata api.
2. Related tests.
3. Updated build steps
4. Always use `npm ci`, part of https://github.com/kubeflow/pipelines/issues/2452

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3118)

### CODE REVIEW

**Comment by lzuwei** [comment]
Hi all can we get this merged soon, it's blocking our deployment on aws because it cannot access GKE metadata.

**Comment by Bobgy** [comment]
@lzuwei Sure, going to merge now
/approve

**Pull request merged**
