### PR TITLE
[Sample tests] Upgrade GCP sdk to 272 in sample test

### PR DESCRIPTION
**Pull request by numerology**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2786)

### CODE REVIEW

**Comment by numerology** [comment]
/assign @Bobgy 
The tests are passing.
However the `container_build` sample test took very long to finish. Let me re-run it a couple of times to see if it's normal.

**Comment by Bobgy** [comment]
If packages interferes with each other, shall we consider using conda or virtual env to separate our python installation?

**Comment by numerology** [comment]
> If packages interferes with each other, shall we consider using conda or virtual env to separate our python installation?

Sounds good.

Before we proceed, may I know what's the initial motivation of upgrading SDK? It seems to me that it's still pretty flaky

**Comment by Bobgy** [comment]
Thanks, let me explain.
Initial motivation is
* test real environment, it is recommended to use latest gcloud
* workload identity was very flaky with gcloud 21x, so I upgraded all to 272, except this one
* I would prefer all gcloud images are using the same version and we can freely change them.

**Comment by Bobgy** [comment]
I can first investigate observed flakiness here.
but I think it would still be helpful if we use conda, it means we can freely upgrade or downgrade without breaking test code

**Comment by Bobgy** [comment]
I took a look at the error log, secret sample fails with connectivity issue. I think it's not related to this PR. It's because of workload identity's own issues.

**Comment by Bobgy** [comment]
Starting to verify flakiness change after efforts to reduce flakiness in https://github.com/kubeflow/pipelines/pull/2777
/test kubeflow-pipeline-sample-test

**Comment by Bobgy** [comment]
This supercedes https://github.com/kubeflow/pipelines/pull/2744

**Comment by Bobgy** [comment]
@numerology
It seems flakiness problem is resolved. Shall we merge this version? You can install virtual env/conda in separate PR at the time you see fit (maybe next time when we need to upgrade gcloud version).

Try test last time: /test kubeflow-pipeline-sample-test

**Pull request merged**
