### PR TITLE
[WIP] Updated Argo to v2.4.1

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2419)

### CODE REVIEW

**Comment by Bobgy** [comment]
@Ark-kun I think you need to use my scripts here: https://github.com/kubeflow/pipelines/pull/2393 to regenerate license.txt with this new version of argo and manually maintain repo-MPL.txt.

Also, the tag name `v2.3.0-license-compliance` was only meant to differentiate with existing `gcr.io/ml-pipeline/argoexec:v2.3.0`. Since we never tagged `gcr.io/ml-pipeline/argoexec:v2.4.1` before, I recommend switching back to just use the same tag as argo images.

**Comment by Ark-kun** [comment]
> @Ark-kun do you mind sharing more context why we need to bump the version in the description? are we relying on workflow template now？

We're not relying on it. But Argo controller failed to start because WorkflowTemplate was missing/denied somewhere.
We can probably add it to fewer places, but it needs to be investigated.

**Comment by Ark-kun** [comment]
Here is the error I was getting:
`github.com/argoproj/argo/workflow/controller/controller.go:157: Failed to list *v1alpha1.WorkflowTemplate: workflowtemplates.argoproj.io is forbidden: User "system:serviceaccount:kubeflow:argo" cannot list resource "workflowtemplates" in API group "argoproj.io" in the namespace "kubeflow"`

**Comment by Jeffwan** [comment]
@Ark-kun Seems most of the users are looking for 2.5.0 and above. Is there a chance we bump to that version or latest Argo directly?

**Comment by Ark-kun** [comment]
I've already upgraded Argo to v2.7.5

**Pull request closed without merging**
