### PR TITLE
feat(sdk): add kfp registry functions to CLI

### LINKED ISSUE #9853: [feature: sdk] Add CLI commands for `kfp.registry` functions
### Feature Area

/area sdk

### What feature would you like to see?

Add CLI commands for KFP registry functions

### What is the use case or pain point?

Uploading a compiled pipeline (for example) as part of CI/CD requires the user to write their own Python script to run

### Is there a workaround currently?

Write standalone Python scripts using the `kfp.registry` functions

---

Love this idea? Give it a 👍.

### PR DESCRIPTION
**Pull request by ghost**
**Description of your changes:**

Add CLI commands for `kfp.registry` functions

Fixes #9853 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by browningjp-datatonic** [comment]
Couldn't see unit tests for other CLI commands, but I have tested the commands manually from my local machine

**Comment by connor-mccarthy** [comment]
FYI, `test-upgrade-kfp-sdk` is a known failure that we're in the process of resolving. `kubeflow-pipelines-sdk-execution-tests` is a known failure and set to `optional` for that reason. Please ignore.

**Comment by browningjp-datatonic** [comment]
The `isort` pre-commit hook was messing with the order of the imports - maybe an inconsistency between pre-commit checks and CI checks? (or my local setup is messed up)

**Comment by browningjp-datatonic** [comment]
@connor-mccarthy anything else needed for this?

**Comment by connor-mccarthy** [comment]
Given the newness of this pattern (the CLI is currently a wrapper around the `Client`, not the `RegistryClient`) and the costs to the KFP SDK team to maintain this code, I think we should wait to see if more support accumulates on #9853. I recommend using the `RegistryClient` directly for now, if possible.

For a CI script, you should be able to invoke the `RegistryClient` for simple tasks using `python -c`. Apologies for the inconvenience.

**Pull request closed without merging**
