### PR TITLE
SDK/Components - More meaningful error when trying to convert graph component to ContainerOp

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/710)

### CODE REVIEW

**Comment by gaoning777** [comment]
Since there is not going to be a graph component now, why add the if-statement here? Maybe we should add graph component related codes when it is part of the component yaml.

**Comment by Ark-kun** [comment]
> Since there is not going to be a graph component now

As was decided during the graph component meeting scope, there will be graph components.
But you are unblocked, because may may implement the features you want in the old compiler instead of waiting for the new one.

>why add the if-statement here?

To improve the experience of people using the existing compiler that does not support the nested pipelines.

>Maybe we should add graph component related codes when it is part of the component yaml.

I'm not sure it's good idea. I was asked by Bradley to make my PRs as small as possible.
Delaying the code additions and then dumping them all at once will make it hard to review. It also makes things hard to review and develop, because later commits rely on previous fixes and changes.
I'd prefer not to do 1000-line code reviews.
For this to happen there needs to be a steady stream of small PRs coming through review.

**Pull request merged**
