### PR TITLE
Base64 encode the pickled code

### LINKED ISSUE #1453: Cloudpickle fails to deserialize a function
Deserializing a python function during runtime fails in case the function has a default parameter, which uses an argo variable.

Here is a simple example:
```
def _test_func(
    path: str,
    local_path: str,
    remote_artifact_name: str,
    minio_bucket: str = 'mlpipeline',
    minio_key: str = 'runs/{{workflow.uid}}/{{pod.name}}',
    minio_ext: str = '.tgz',
):
    remote_path = f'minio://{minio_bucket}/{minio_key}/{remote_artifact_name}{minio_ext}'
    print(remote_path)
```

This can be executed fine when compiled with 0.1.19 (latest version in PyPI), but fails with the latest master (which uses cloudpickle). The error message is one of the following:
- in case only `{{workflow.uid}}` is used:
```
Traceback (most recent call last):
  File "<string>", line 9, in <module>
AttributeError: 'dict' object has no attribute 'append'
```
- in case `{{pod.name}}` is used:
```
Traceback (most recent call last):
  File "<string>", line 9, in <module>
_pickle.UnpicklingError: invalid load key, '5'.
```

Using a default value without brackets resolves the issue.

### PR DESCRIPTION
**Pull request by kvalev**
Due to its nature, Argo will replace any strings it encounters that are enclosed in double curly braces, which will make the code non-executable. To workaround this, the code is encoded in the Argo yaml template and decoded on the fly, before the execution.

Fixes #1453

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1476)

### CODE REVIEW

**Comment by Ark-kun** [comment]
We only really need to replace double opening braces `{{`

**Comment by Ark-kun** [comment]
\lgtm

**Comment by Ark-kun** [comment]
> Due to its nature, Argo will replace any strings it encounters that are enclosed in double curly braces, which will make the code non-executable. To workaround this, the code is encoded in the Argo yaml template and decoded on the fly, before the execution.
> 
> Fixes #1453

Please note that this won't fully "fix" your old workflow. The code will stop crashing, but the placeholders won't be substituted.

The best way to use them is 

```
unique_task_id_template = '{{workflow.uid}}_{{pod.name}}' #We should probably move that to DSL to hide the actual template strings.

some_op(output_path = prefix + '/' + unique_task_id_template + '/data')
```

**Comment by kvalev** [comment]
Actually it does fix it (in a way). The DSL compiler explicitly declares all arguments in the `container.args` section in the generated argo template, so the default function values are ignored anyway. And argo seems to correctly substitute those values, so in the end it works out.

Another solution that I had in mind was modifying the method metadata by removing the default values before serializing the function, but it seems that the metadata is immutable, so it was not easily doable (if at all).

And the reason for even passing such details as the expected minio path is that I want to visualize some data using the output viewers. I was hoping that I can just define the local file as `source` in `mlpipeline-ui-metadata.json` and the file will be automatically stored in the configured storage and the local path in the metadata file will be replaced on the fly with the remote one. However that does no seem to be the case, so the only way to currently achieve something similar is to declare the local file as output artifact (so that it is archived by argo) and then write the expected minio location in the `mlpipeline-ui-metadata.json` file, so that the file contents can be visualized afterwards.

**Pull request merged**
