### PR TITLE
chore(sdk): clean up v2 CLI

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Cleans up V2 CLI source code before introducing substantive 
changes.

**Checklist:**
- [x] The title for your pull request (PR) should follow our 
title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
I left some nitpick comments in https://github.com/kubeflow/pipelines/pull/7559, looks like I should have add them here instead. Anyway, I think you would be able to apply any changes here. :)

**Comment by connor-mccarthy** [comment]
Thanks for your review, @chensun. I addressed your comments with additional changes and responded in #7559.

**Comment by chensun** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
