### PR TITLE
chore(test): revert api changes to deprecated client

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
sdk execution test failures are tracked by https://github.com/kubeflow/pipelines/issues/8845 and https://github.com/kubeflow/pipelines/issues/8846

**Comment by chensun** [comment]
All tests except the `kubeflow-pipelines-sdk-execution-tests`, which is explained in https://github.com/kubeflow/pipelines/pull/8841#issuecomment-1428685174, are passing now. 
This can be merged to unlock `kubeflow-pipelines-integration-v2`. 

/cc @gkcalat @Linchin

**Comment by gkcalat** [comment]
/lgtm
/approve

Thank you, @chensun!

**Pull request merged**
