### PR TITLE
feat(sdk): Accept newer `typing-extensions` versions

### LINKED ISSUE #7631: SDK: Accept newer `typing-extensions` versions
### Feature Area

The SDK currently requires [`typing-extensions>=3.7.4,<4`](https://github.com/kubeflow/pipelines/blob/2.0.0-alpha.1/sdk/python/requirements.in#L45).

### What feature would you like to see?

I would like the SDK to accept higher versions - `>=4` specifically.

### What is the use case or pain point?

I would like to use the SDK on Cloud Composer (a.k.a Google-managed Apache Airflow). However, I can't install the SDK because Cloud Composer is using `looker-sdk 22.4.0` which requires `typing-extensions>=4.1.1`

### Is there a workaround currently?

There are some workarounds but I think it's no problem that the SDK accepts newer `typing-extensions` versions.

### PR DESCRIPTION
**Pull request by mai-nakagawa**
Fixes #7631.

I think it's no problem that the SDK accepts newer `typing-extensions` versions because:
- `typing-extensions 4.0.0` has some backwards-incompatible changes, however, these changes affect only Python 3.5 and older. See [Removed in version 4.0.0 of typing-extensions](https://github.com/python/typing/blob/master/typing_extensions/CHANGELOG.md#removed-in-version-400) for more in detail.
- `typing-extensions 4.2.0` drops support Python 3.6 as per [Release 4.2.0 of typing-extensions](https://github.com/python/typing/blob/master/typing_extensions/CHANGELOG.md#release-420-april-17-2022), however, it does not affect as the SDK drop support for python 3.6 by #7303 
- It used to be `typing-extensions>=3.7.4,<5` but changed to `typing-extensions>=3.7.4,<4` by #7303. But I assume it didn't have to. I presume the change was made because there is a following statement in [`typing-extensions PyPI`](https://pypi.org/project/typing-extensions/):

> Starting with version 4.0.0, `typing_extensions` uses [Semantic Versioning](https://semver.org/). The major version is incremented for all backwards-incompatible changes. Therefore, it’s safe to depend on `typing_extensions` like this: `typing_extensions >=x.y, <(x+1)`

### CODE REVIEW

**Comment by jgoodman8** [comment]
It would be great to have this feature. We are currently blocked by this due to a compatibility issue. So, it would be awesome if everyone could have a pre-release with this change. Thank you @mai-nakagawa!

**Comment by connor-mccarthy** [comment]
@mai-nakagawa, could you please add a bullet in our [release notes](https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md#bug-fixes-and-other-changes-1) indicating that we're changing the version?

After that, I think we should be good to merge and it will be included in our alpha.2 release. (cc: @jgoodman8)

**Comment by mai-nakagawa** [comment]
@connor-mccarthy Thanks for your review! Added a description to the release notes by https://github.com/kubeflow/pipelines/pull/7632/commits/0faf033debfd9dd3ebf508a4a89f2ff60e166180.

**Comment by connor-mccarthy** [comment]
/lgtm
/approve

Thanks @mai-nakagawa!

**Comment by jiyongjung0** [comment]
Thank you for the PR! I'm working on a project called `tfx` and we were struggling with conflicting dependencies of `typing-extensions`. We would be able to resolve the conflict if this change is released.

**Comment by connor-mccarthy** [comment]
Awesome, @jiyongjung0! Really glad to hear that this is unblocking lots of different projects.

**Comment by jiyongjung0** [comment]
Hi, @connor-mccarthy Is there a plan to release a new python package for kfp 1.x? It seems like the package wasn't released for two months and this PR wasn't included in any releases.

**Comment by connor-mccarthy** [comment]
> Hi, @connor-mccarthy Is there a plan to release a new python package for kfp 1.x? It seems like the package wasn't released for two months and this PR wasn't included in any releases.

Hi, @jiyongjung0. Looks like these changes were only applied to v2, but you're working with v1. I have a PR #7786 to mirror these changes in v1 and we can release once that is merged.

**Pull request merged**
