### PR TITLE
SDK/DSL: Enable the deletion of a resource via ResourceOp method

### LINKED ISSUE #1779: VolumeOp doesn't support GC after workflow deletion
The PVC created from VolumeOp is not automatically recycled after workflow is deleted.

I wonder if owner reference can work with PVC when it is set with workflow's reference. If it works, we can provide an option in volumeop to set it when creating the PVC.

If it doesn't work, we should provide a way to either use Argo's volume API or support a delete PVC op in exit handler.

### PR DESCRIPTION
**Pull request by elikatsis**
Related to #1779.

This PR enables performing the `delete` action on a resource that's highly connected to the workflow (e.g., a PVC created using a `VolumeOp`).

The approach of #3194 is aligned to this one, but is a subset of it. I decided to submit this PR to have a generic `delete()` method that would work out of the box with any `ResourceOp` (or subclass).

cc @PatrickXYS

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3213)

### CODE REVIEW

**Comment by PatrickXYS** [comment]
Your approach is generic, but I have some questions from users' side: 
1. How can we make sure that our users who use `ResourceOp` want to have to separate `ResourceOp.delete()`? And of course `VolumeOp` want this method, but we need to gather more information about other people who use `ResourceOp`. Probably ping more people take a look and confirm the idea. @Ark-kun @IronPan @Jeffwan @gaoning777 @hongye-sun 

2. It's a little bit confusing with having a passing parameter as `action` and a separate `.delete()` method, if we have to do it this way, we need to be very careful about writing documentation for our users.

3. I suggest you mention your change in `ResourceOp.__init__()` function's comment, and tell our users use `.delete()` if they want to utilize delete operation.  

Overall, it looks great and if we confirm users want to have a separate `.delete()` let's do it this way.

cc @elikatsis

**Comment by elikatsis** [comment]
> Your approach is generic, but I have some questions from users' side:
> 
> 1. How can we make sure that our users who use `ResourceOp` want to have to separate `ResourceOp.delete()`? And of course `VolumeOp` want this method, but we need to gather more information about other people who use `ResourceOp`. Probably ping more people take a look and confirm the idea. @Ark-kun @IronPan @Jeffwan @gaoning777 @hongye-sun

`VolumeOp` is a subclass of `ResourceOp`. [`VolumeOp` extends `ResourceOp`. These two phrases have the same meaning].
So a `VolumeOp` inherits every `ResourceOp` property, attribute, method, etc., e.g., the method `delete()`.
The class `VolumeOp` may decide to override a method if the parent class implementation isn't sufficient. For example, if the `ResourceOp` method `delete()` isn't sufficient for a `VolumeOp`, then it can have its own.
In this case, I think there is no need to override it. It seems to me that the tests I've added prove that it's ok, but, of course, if and when you actually use it you may find something that's not functioning properly and we will figure out how to solve it.

> 2. It's a little bit confusing with having a passing parameter as `action` and a separate `.delete()` method, if we have to do it this way, we need to be very careful about writing documentation for our users.
> 3. I suggest you mention your change in `ResourceOp.__init__()` function's comment, and tell our users use `.delete()` if they want to utilize delete operation.
>
> Overall, it looks great and if we confirm users want to have a separate `.delete()` let's do it this way.

`ResourceOp`s [and `VolumeOps`, `VolumeSnapshotOp`s] are entities that enable the manipulation of resources. Such manipulation may mean `create`, `patch`, `apply`, `delete`, etc., and that's what the argument `action` is for.
The `delete()` method is a **new** pipeline step, that deletes a resource **already manipulated** in a previous pipeline step.
So creating a `ResourceOp` with `action="delete"` is different from running `.delete()` on an already defined `ResourceOp`.

Did I get your arguments correct?

**Comment by PatrickXYS** [comment]
@elikatsis Thank you for explanation!

**Comment by kim-sardine** [comment]
I really need this one. it would be great if I can delete pvc in `ExitHandler`

**Comment by PatrickXYS** [comment]
@kim-sardine It's also the feature that we want. @elikatsis Seems like one of the CI test failed? If you're tied up, perhaps I could help with it.

**Comment by elikatsis** [comment]
@PatrickXYS I don't understand what the error is.

I tried running retest command but the bot didn't listen to me :cry:
I tried it again in case it was stuck, but no luck

**Comment by PatrickXYS** [comment]
@elikatsis  It's weird. Seems like this PR is detached from Prow system. I'm not sure if there's any workaround we could move forward. But submitting another PR should work. 

Perhaps mention our discussion in the new PR would help others gather context.

**Pull request merged**
