### PR TITLE
chore: restore KFP SDK version to 1.6.2, decouple SDK release from KFP main release.

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
It was accidentally overwritten by https://github.com/kubeflow/pipelines/commit/1c66f93f5149a8d5ed7f33895d3ebc01e662d837

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
@Bobgy we should update the release script to decouple SDK version update.

**Comment by Bobgy** [comment]
@chensun ohh, sorry I missed that.

Can you update in this PR?
Just remove this line
https://github.com/kubeflow/pipelines/blob/fba546e0f4f8ef041ea537f5514a20ea455e08d0/test/release/bump-version-in-place.sh#L45

**Comment by chensun** [comment]
> @chensun ohh, sorry I missed that.
> 
> Can you update in this PR?
> Just remove this line
> https://github.com/kubeflow/pipelines/blob/fba546e0f4f8ef041ea537f5514a20ea455e08d0/test/release/bump-version-in-place.sh#L45

Thanks for the pointer. Done.

**Comment by Bobgy** [comment]
/lgtm
/approve

Thank you!

**Pull request merged**
