### PR TITLE
Improved the "IBM - Create kubernetes secret" component

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixed the following issues:
* Checking that every command finishes successfully (non-zero return code)
* Fixed the path for the secret_name output (the program was producing variable paths different from the path in component.yaml)

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1027)

### CODE REVIEW

**Comment by Ark-kun** [comment]
> Thanks @Ark-kun. The idea here was to create a secret, and assign to kubernetes Apiserver, by using _kubectl create secret_ command, rather than passing that as an input param for next component.

I understand that. I just noticed that the created secret can have inferred name which is deduced from the URL. Also having any output makes it easier to chain dependent tasks.

I can remove that output if you think it's not useful.

Are there any issues with other changes?

**Comment by animeshsingh** [comment]
Thanks @Ark-kun - rest of the changes look good. I would say storing secrets in outfile file will still be a security hazerd, so best to remove that part.

**Comment by Ark-kun** [comment]
> I would say storing secrets in output file will still be a security hazard, so best to remove that part.

Just want to clarify: we're not storing/passing the actual secret. Just the secret **name**. Does this alleviate the concern?

**Comment by mpoqq** [comment]
Hi @Ark-kun, is it possible to update the docker image on [docker hub ](https://hub.docker.com/r/aipipeline/wml-config)? Due to your changes the [component.yaml](https://github.com/kubeflow/pipelines/blob/master/components/ibm-components/commons/config/component.yaml) pulls an old image and therefore this error  `config.py: error: unrecognized arguments: --output-secret-name-file /outputs/secret_name/data` occurs.

**Comment by animeshsingh** [comment]
we will take care of oy @mpoqq

**Comment by mpoqq** [comment]
Thanks @animeshsingh, I think [Watson Sample](https://github.com/kubeflow/pipelines/blob/master/samples/ibm-samples/watson/watson_train_serve_pipeline.py) is also outdated.

**Comment by animeshsingh** [comment]
@mpoqq the sample was updated recently, its dependent on the secret component and docker image though. key thing is even if the docker image doesn't go all the way, its able to create the secrets, so rest of the steps can continue. But we are going to update the image today. If you found any issue while running samples, please let us know

**Pull request merged**
