### PR TITLE
fix(backend): add brackets if metadata service host is ipv6.  Fixes (#5161)

### PR DESCRIPTION
**Pull request by vsk2015**
Fixes https://github.com/kubeflow/pipelines/issues/5161

### CODE REVIEW

**Comment by vsk2015** [comment]
@googlebot I signed it!

**Comment by vsk2015** [comment]
@googlebot I fixed it.

**Comment by Ark-kun** [comment]
/ok-to-test
This seems to be an issue in ml_metadata. It should handle the IPv6 hosts correctly. Have you reported it?

Can you show us where `isIPv6` is defined?

**Comment by vsk2015** [comment]
https://github.com/kubeflow/pipelines/blob/5ffa2be1b9243773d5459b22406a3f2cd5e7881c/backend/metadata_writer/src/metadata_helpers.py#L421

**Comment by Bobgy** [comment]
/LGTM
/Approve

@Ark-kun do you have any concerns?
/Hold

**Comment by Ark-kun** [comment]
/hold cancel

Please remove IPv6 detection in the Metadata Writer once ML Metadata fixes the bug on their side. https://github.com/google/ml-metadata/issues/107

**Pull request merged**
