### PR TITLE
fix(sdk): fix nested placeholders and block illegal IfPresent form in Concat

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
This PR:

- Adds a check to prevent `then` or `else_` arguments to `IfPresentPlaceholder` from 
being lists if the `IfPresentPlaceholder` is within a `ConcatPlaceholder`.
- Fixes a bug in handling of `then` and `else_` when either is a string element (instead of 
a list of elements)

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more 
about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
Note that the `kubeflow-pipelines-component-yaml` failures are attributed to two Google Cloud Pipeline Components components which will never be loaded by users directly (only via the `google_cloud_pipeline_components` library). Since the current versions of `google_cloud_pipeline_components` is incompatible with `kfp==2.x.x`, this is not an error users will ever experience. Therefore, it is safe to ignore these two YAML failures and merge.

**Comment by chensun** [comment]
> Note that the `kubeflow-pipelines-component-yaml` failures are attributed to two Google Cloud Pipeline Components components which will never be loaded by users directly (only via the `google_cloud_pipeline_components` library). Since the current versions of `google_cloud_pipeline_components` is incompatible with `kfp==2.x.x`, this is not an error users will ever experience. Therefore, it is safe to ignore these two YAML failures and merge.

What is the plan for these two incompatible components? Are they going to be updated when GCPC migrate to support kfp 2.*?
We should exclude them from the test with some TODO comments. Otherwise, once this PR is merged, the same presubmit test will fail for all subsequent PRs.

**Comment by connor-mccarthy** [comment]
> What is the plan for these two incompatible components? Are they going to be updated when GCPC migrate to support kfp 2.*?

Yes. It will be impossible to author these incompatible components via KFP 2.*, so GCPC authors will be pushed in the correct direction.

> We should exclude them from the test with some TODO comments. Otherwise, once this PR is merged, the same presubmit test will fail for all subsequent PRs.

Will follow up with this change.

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks!

**Comment by Ark-kun** [comment]
Using if placeholder inside concat might look weird, but the lest-surprise way of handling it seems to be pretty simple - concatenate the then/else list items with the rest of the concat items.
Are there any backend issues handling this?

**Pull request merged**
