### PR TITLE
feat(sdk): Add `enable_job` method to client

### PR DESCRIPTION
**Pull request by droctothorpe**
**Description of your changes:**
This PR implements an `enable_job` method in the KFP SDK. The capability is already present in the generated http client so providing support for it in the SDK is trivial.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — COMMENTED** [review]
@droctothorpe Thanks for the PR. 

Can you please add an entry in the release note for this change? https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md

/lgtm

**Comment by droctothorpe** [comment]
Thanks for the review, @chensun! I updated [RELEASE.md](https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md). Standing by for any additional notes / input.

**Comment by droctothorpe** [comment]
Hm. No idea why the test is failing. Is this related to the code changes in the PR or some out of band problem?

**Comment by droctothorpe** [comment]
Checking in on the status of this, @chensun. Please let me know if there's anything else that I need to do.

**Comment by chensun** [comment]
> Hm. No idea why the test is failing. Is this related to the code changes in the PR or some out of band problem?

The sample test failure is unrelated to this change, I'm debugging that right now. Will ignore the failure if that's the only failed test here.

/test all

**Comment by droctothorpe** [comment]
Woohoo! Thanks, @chensun! 🙏

**Pull request merged**
