### PR TITLE
SDK - Removing unneeded uses of dsl.Pipeline

### PR DESCRIPTION
**Pull request by Ark-kun**
`dsl.Pipeline` is a private compiler context object that should not be used outside the compiler (and compiler tests).
This PR removes most of the unnecessary uses of `dsl.Pipeline`.
Please turn on "Hide whitespace changes" in diff settings when looking at the diff.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1229)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Ping
/cc @gaoning777

**Comment by gaoning777** [comment]
Sorry for the delay. I'll take a look today.

**Pull request merged**
