### PR TITLE
docs[manifests]: fix and standardize pns comments

### PR DESCRIPTION
**Pull request by droctothorpe**
**Description of your changes:**
This PR just removes an inaccurate comment about docker in one of the manifests and standardizes the comments across two otherwise identical kustomize patches.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by droctothorpe** [comment]
Following up on this.

**Comment by connor-mccarthy** [comment]
/unassign @connor-mccarthy

@zijianjoy is better suited to handle this PR :)

**Pull request merged**
