### PR TITLE
feat(swf): Add a [[RunUUID]] macro

### PR DESCRIPTION
**Pull request by StefanoFioravanzo**
Part of https://github.com/kubeflow/pipelines/issues/4700

**Context**

Scheduled Workflows support macros in pipeline parameters. Existing macros are documented here: https://github.com/kubeflow/pipelines/blob/34d23aa924720ead13fe67ebca5c1ab9926585ee/backend/src/crd/samples/scheduledworkflow/parameterized.yaml

**What**

This PR adds a new macro `[[RunUUID]]` which gets replaced with the KFP Run UUID.

**Why**

User code, running inside a pipeline step, might access some external system (i.e. a database) to write data or perform some operation. In these scenarios the pipeline can leave an auditable trace using the Run UUID in the external system, so that someone looking at it later on can go back to the original KFP run.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by capri-xiyue** [comment]
The use case of tracing makes sense to me. But I'm not sure whether using RunUUID here will break other use cases or cause some side effects. Maybe it will be better to add some trace identifier in scheduleworkflow to support trace. @Bobgy Any ideas?

**Comment by StefanoFioravanzo** [comment]
@capri-xiyue when you say 
> But I'm not sure whether using RunUUID here for tracing will break other use cases or cause some side effects
do you something specific in mind?

**Comment by capri-xiyue** [comment]
> @capri-xiyue when you say
> 
> > But I'm not sure whether using RunUUID here for tracing will break other use cases or cause some side effects
> 
> do you something specific in mind?

Currently no. I'm quite new to KFP. Therefore I'm not sure whether it will break other use cases. Need to ask someone else for confirmation.

**Comment by StefanoFioravanzo** [comment]
Using the KFP Run UUID for logging or creating an auditable trace is just an example, I see what you say about using a different tracing ID, but this PR is not about that rather than implementing a KFP-native way to expose the Run ID to Pipeline runs.

Currently one can access the Run ID from inside a run using a DSL placeholder: see https://github.com/kubeflow/pipelines/issues/4700 and: https://github.com/kubeflow/pipelines/blob/ca09c7a026e0dccc2a5f4e232d3ee304b42e4e65/sdk/python/kfp/dsl/__init__.py#L28-L29

These placeholders were introduced in https://github.com/kubeflow/pipelines/pull/1683.

This makes retrieving the Run ID an Argo-specific feature, since it relies on reading `{{workflow.uid}}`.  
This PR, instead, introduces a macro that can be used regardless of the workflow orchestrator (Argo, Tekton, ...) and is in line with the other macros mechanism.

And, given @Bobgy 's comment here https://github.com/kubeflow/pipelines/issues/4700#issuecomment-727305972 I think in general this should the way to go to expose other information, even in one-off runs.

**Comment by capri-xiyue** [comment]
> #4700 (comment)

I thought adding a [[RunUUID]] macro allows user to specify the RunUUID , how can this macro helps exposing the Run ID to Pipeline runs? Do you mean this user can specify the RunUUID so that the RunUUID can be exposed to users? I don't think it is a ideal way to expose RunUUID to users.

**Comment by StefanoFioravanzo** [comment]
@capri-xiyue The macro acts as a placeholder, which gets substituted by the KFP API Server (actually, the Scheduled Workflow controller) whenever a new run is triggered. It's the same mechanism that we currently use in KFP to substitute the time-related macros I mentioned above (current time, scheduled time, etc..).

You can see here 
https://github.com/kubeflow/pipelines/pull/4995/files#diff-3c9cc0d4bd2beb53306be4fd8d7471ebe5453932ffdc813fadb8c54785aa692cR190
that I am passing the run UID that would have been created **anyway**. All the user needs to specify is `[[RunUUID]]` as a pipeline parameter, then the controller will fill this value with the real Run UUID. I think it's a very simple and clear way to expose this information to users, without being dependent on the workflow engine (e.g. Argo).

**Comment by capri-xiyue** [comment]
> All the user needs to specify is `[[RunUUID]]` as a pipeline parameter, then the controller will fill this value with the real Run UUID. I think it's a very simple and clear way to expose this information to users, without being dependent on the workflow engine (e.g. Argo).
I'm quite new to the codebase. Just wanna confirm the meaning of `All the user needs to specify is `[[RunUUID]]` as a pipeline parameter`, does that mean user need to specify RunUUID with a real value but what user specified will be override by the UUID created by the scheduled Workflow controller?

**Comment by Bobgy** [comment]
Sorry coming late, my major concern is that the macro is not specific to scheduled workflow. If we decide to add it, it should be usable in one off workflows.

**Comment by StefanoFioravanzo** [comment]
> Sorry coming late, my major concern is that the macro is not specific to scheduled workflow. If we decide to add it, it should be usable in one off workflows too.

@Bobgy as a matter of fact, I have the code ready already to provide support for this macro to one-off runs. I was planning to open that PR as soon as we merge this one. I should have mentioned it from the start 😄

**Comment by Bobgy** [comment]
That's great, so the only remaining concern is whether `[[xxxx]]` syntax is the right macro syntax we'd like to pursue in the long term. I think maybe we should start using the same syntax as what we standardized in KFP IR: https://github.com/kubeflow/pipelines/blob/7ed110e9845237115591d04d82085d957e343795/api/v2alpha1/pipeline_spec.proto#L595-L613

**Comment by StefanoFioravanzo** [comment]
@Bobgy I will take a deeper look at the KFP IR, how would that work? Would the API Server still be responsible for replacing these `{{..}}` placeholders? Is there already a backed version/branch that supports this IR? Can you link to it?

Anyway, given this, I think we could move on with this and then talk more about the IR syntax here https://github.com/kubeflow/pipelines/issues/4700

**Comment by Bobgy** [comment]
> @Bobgy I will take a deeper look at the KFP IR, how would that work? Would the API Server still be responsible for replacing these `{{..}}` placeholders? Is there already a backed version/branch that supports this IR? Can you link to it?

That's a long and different story, I've been drafting some design doc and implementing POCs for the new KFP IR, we'll share that publically soon.

> Anyway, given this, I think we could move on with this and then talk more about the IR syntax here #4700

I changed my mind, I think we can proceed with `[[]]` syntax at least for now. It will probably take some time for anything related to IR, and considering we have many other placeholders already in the `[[]]` syntax, we can figure out a migrate path later in a batch.
/cc @capri-xiyue 
what do you think?

We could mitigate the migration problem by suggesting users to not hard-code the raw text value of `[[RunUUID]]`, but rather use a string constant from the dsl like
https://github.com/kubeflow/pipelines/blob/32ce8d8f90bfc8f89a2a3c347ad906f99ba776a8/sdk/python/kfp/dsl/__init__.py#L28-L29

Unfortunately, the best naming for it should be `RUN_ID_PLACEHOLDER`, but it was already used by argo workflow run ID. Do you have any suggestions?

**Comment by capri-xiyue** [comment]
I agree that  we can proceed with [[]] syntax at least for now and migrate it later.

**Comment by StefanoFioravanzo** [comment]
> We could mitigate the migration problem by suggesting users to not hard-code the raw text value of [[RunUUID]], but rather use a string constant from the dsl like

That would be an option, but for consistency we should do the same for all of the existing macros as well. I am not against it, maybe let's discuss in a separate issue if/when we find the need for it.

Shall we move on and merge this in the meanwhile?

**Comment by Bobgy** [comment]
/lgtm
/approve
Makes sense.
Considering these are not documented, it's fine getting this in first

**Comment by Bobgy** [comment]
Hi @StefanoFioravanzo, I made a mistake when reviewing this PR. Run ID was already exposed as kfp.dsl.RUN_ID_PLACEHOLDER. See https://github.com/kubeflow/pipelines/pull/5385#issuecomment-810017791

**Comment by Bobgy** [comment]
Hmm, after digging through a bit more of the history. We also have https://github.com/kubeflow/pipelines/pull/3709 trying to remove the auto replacement of {{workflow.uid}}. Shall we update `kfp.dsl.RUN_ID_PLACEHOLDER` to be `[[RunUUID]]` instead? This seems to be a change that breaks SDK backward compatibility with old KFP servers.

**Comment by StefanoFioravanzo** [comment]
Hey @Bobgy I think that the "correct" way forward would be to merge #3709 and update `kfp.dsl.RUN_ID_PLACEHOLDER` to be `[[RunUUID]]`, so that we stop replace the Argo label and we a KFP native way to reference KFP Run IDs.

Also cc @elikatsis since he created #3709

**Comment by Bobgy** [comment]
Thanks @StefanoFioravanzo, I agree with that. To reduce backward compatibility concerns, I'd suggest the folloowing rollout plan:

1. Now KFP api server supports both `[[RunUUID]]` and `{{workflow.uid}}` as KFP run ID placeholder.
1. After a certain period (3months?), change `kfp.dsl.RUN_ID_PLACEHOLDER` to `[[RunUUID]]`. (Wait 3 months, because there are people who upgrade their SDK a lot more than their KFP cluster.)
1. After another certain period (3month?), merge #3709. (Again, the wait period is to allow old SDK users to keep using new KFP api server without problem.)

**Comment by StefanoFioravanzo** [comment]
@Bobgy we were writing at the same time but you were faster! :)

I wanted to propose something similar. But I would consider the following points:

> Now KFP api server supports both [[RunUUID]] and {{workflow.uid}} as KFP run ID placeholder.

Indeed, and I think this is actually good. This is why:

- We cannot just update `kfp.dsl.RUN_ID_PLACEHOLDER` to be `[[RunUUID]]` because the current placeholder is an Argo macro, which will be replaced **anywhere** in the workflow, while the `[[RunUUID]]` works just for pipeline parameters.
- We should keep support for `[[RunUUID]]` in one-off runs because it is a consistent mechanism to retrieve the Run UUID in pipeline parameters. People use this in SWFs and they expect it to work in one-off runs as well (We've seen this with our customers)
- The KFP Python SDK placeholder can be used as well, it's more generic and it does overlap a little bit with `[[RunUUID]]`, but this doesn't mean we need to support just one or the other. They are two different mechanisms that happen to overlap in this particular case (run id as pipeline parameter). I do still think that merging #3709 would make things more clean, but it's an orthogonal discussion.

Maybe, as a longer term plan:

It's the KFP API server who replaces the argo string with the run id throughout the workflow. That's how we can get the run id using that string. We can make the API server also replace all macro (`[[ * ]]`) occurrences throughout the workflow the exact same way. Then we can phase out the argo string.

**Comment by Bobgy** [comment]
Very good point, the two placeholders have subtle behavior differences.

Do you want to create a separate issue about it? This doesn't seem like a good place to keep complex discussions.

**Comment by StefanoFioravanzo** [comment]
@Bobgy I am coming back to this now. Yes I will create the issue, sorry for the delay

**Pull request merged**
