### PR TITLE
fix(backend): Avoid multiple PutParentContexts on the same primary key.

### PR DESCRIPTION
**Pull request by zijianjoy**
**Description of your changes:**
Related: #9586 

MLMD will complain for primary key (parent context id + child context id) conflict if PutParentContexts() is called multiple times. The fix is to check this relationship exists before calling PutParentContexts(). If this relationship already exists, we should not return error. 

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Linchin** [comment]
Thank you @zijianjoy for fixing this issue!
/ltgm
/approve

**Comment by chensun** [comment]
/hold 

Test failures aside, can we hold this change until GA? Consider a code freeze period with exception for bug fixing for GA.

@zijianjoy @Linchin

**Comment by zijianjoy** [comment]
Hello @chensun , refer to https://github.com/kubeflow/pipelines/issues/9586#issuecomment-1584838329, this is an existing issue on KFPv2.

**Comment by chensun** [comment]
> Hello @chensun , refer to [#9586 (comment)](https://github.com/kubeflow/pipelines/issues/9586#issuecomment-1584838329), this is an existing issue on KFPv2. I believe this is a bug fixing case for GA scope.

I see. As long as you fix the test failure then. Thanks!

**Pull request merged**
