### PR TITLE
chore: Resolve comments in #4392

### PR DESCRIPTION
**Pull request by numerology**
**Description of your changes:**
Resolving comments in https://github.com/kubeflow/pipelines/pull/4932

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by Ark-kun** [comment]
Thank you for the fixes.
/lgtm

**Comment by numerology** [comment]
/close

Looks like this PR is actually override by other PRs and after resolving conflicts it's empty now.

**Pull request closed without merging**
