### PR TITLE
fix: Update GettingStarted.tsx

### PR DESCRIPTION
**Pull request by rcrowe-google**
Updating link text and URL for TFX template launch.

**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by zijianjoy** [comment]
Thank you @rcrowe-google , can you change `Cloud Vertex AI Workbench` to `Vertex AI Workbench`? Thank you!

**Comment by rcrowe-google** [comment]
> Thank you @rcrowe-google , can you change `Cloud Vertex AI Workbench` to `Vertex AI Workbench`? Thank you!

Yes, done.

**Comment by zijianjoy** [comment]
Thank you for your contribution and update! The fix has been merged with https://github.com/kubeflow/pipelines/pull/7227. You can safely close this PR now.

**Pull request closed without merging**
