### PR TITLE
feat(sdk): support optional artifact inputs

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Supports optional artifact inputs, toward feature parity with KFP SDK v1.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title 
convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — COMMENTED** [review]
/lgtm

**Comment by connor-mccarthy** [comment]
`kubeflow-pipelines-sdk-execution-tests` failures are due to the BE's PipelineSpec validation on the current deployment on which we test. This is fixed in BE HEAD with https://github.com/kubeflow/pipelines/pull/8614 and https://github.com/kubeflow/pipelines/pull/8614.

Manually merging to temporarily bypass this.

**Pull request merged**
