### PR TITLE
fix(samples): Remove broken xgboost sample

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Part of https://github.com/kubeflow/pipelines/issues/5089

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by numerology** [comment]
Thanks @Bobgy !

I think front end test might need change as well because we implemented some test against the landing page.

**Comment by Ark-kun** [comment]
Are you sure we need to remove the snapshots?
There is a pending PR to replace the sample and removing the snapshots make it harder to fix. https://github.com/kubeflow/pipelines/pull/5090

**Comment by Bobgy** [comment]
@Ark-kun I believe we want to hurry on a KFP release without being blocked on fixing/preparing a new XGBoost sample. I can help you add the new XGBoost sample back when your sample is ready.

**Comment by Ark-kun** [comment]
Sure. The marketplace release is really old, so let's focus on that.
P.S. We already have several XGBoost samples available in our repo - working and ready.

**Pull request merged**
