### PR TITLE
Bump minio-go dependency to v6.0.53

### PR DESCRIPTION
**Pull request by Jeffwan**
Resolve part of https://github.com/kubeflow/pipelines/issues/3398

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>

1. The way to import minio sdk has been changed. latest version has go modules support. module path has been changed to `github.com/minio/minio-go/v6`.  Check here for more details https://github.com/minio/minio-go

2. I update WORKSPACE. The problem is it's `minio/minio-go/v6` now and doesn't match github path. I get error like below

```
ERROR: /go/src/github.com/kubeflow/pipelines/backend/src/apiserver/BUILD.bazel:3:1: no such package '@com_github_minio_minio_go//': failed to fetch com_github_minio_minio_go: 2020/04/19 03:58:18 not a root of a repository: github.com/minio/minio-go/v6
 and referenced by '//backend/src/apiserver:go_default_library'
ERROR: Analysis of target '//backend/src/apiserver:apiserver' failed; build aborted: no such package '@com_github_minio_minio_go//': failed to fetch com_github_minio_minio_go: 2020/04/19 03:58:18 not a root of a repository: github.com/minio/minio-go/v6
```

After some search, I add `remote` and `vcs` to fix this issue following instruction here. https://github.com/bazelbuild/rules_go/issues/1953

But `bazel run
//:gazelle -- update-repos --from_file=go.mod` will remove that, is that a problem?

3. I search `https://github.com/minio/minio-go` and notice https://github.com/kubeflow/pipelines/tree/master/third_party/minio has some reference? When I upgrade versions, Do I need to upgrade license as well?

### CODE REVIEW

**Comment by Jeffwan** [comment]
@neuromage @jingzhang36  Can some one give some guidance on the upgrade?

**Comment by Jeffwan** [comment]
@Ark-kun @Bobgy Can someone give guidance on how to upgrade dependency?

**Comment by Bobgy** [comment]
@Jeffwan Yes, for thirdparty images, you need to follow process in https://github.com/kubeflow/pipelines/tree/master/third_party.

I don't have much knowledge in upgrading go dependencies.
/cc @jingzhang36

**Comment by karlschriek** [comment]
Can this be reopened? For a lot of AWS users It is really important to have IRSA capabilities in Pipelines and that requires a newer version of minio-go

**Comment by Bobgy** [comment]
@karlschriek feel free to do so, I believe @Jeffwan no longer works for AWS, so welcome anyone who wants this to pick it up.

**Comment by karlschriek** [comment]
@Bobgy do you have an ETA on when KFP 2.0 will be released? There are several place upstream in the Minio client where IRSA support additionally needs to be built in. Depending on when you plan to release KFP 2.0 it might be less effort to just make sure IRSA works there.

**Comment by Bobgy** [comment]
@karlschriek moving artifact API to backend is not at high priority, so if you want this feature quickly. I think there is still value to upgrade these clients now

**Pull request closed without merging**
