### PR TITLE
SDK - Compiler - Fix bugs in the data passing rewriter

### PR DESCRIPTION
**Pull request by deepio-oc**
fix for #2295 

`argument_placeholder_parts` seems to have been copied/pasted from the code above. `parts` seems to be the more suitable here.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2297)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Thank you a lot @deepio-oc .
Can you please sign the CLA? I'd really like to merge and release this fix today or tomorrow.

**Comment by deepio-oc** [comment]
> Thank you a lot @deepio-oc .
> Can you please sign the CLA? I'd really like to merge and release this fix today or tomorrow.

My organization (One Convergence) has already signed CLA.

**Comment by Ark-kun** [comment]
> My organization (One Convergence) has already signed CLA.

Are you using the correct e-mail in your commits?
Can you try checking the links the CLA bot has posted: https://github.com/kubeflow/pipelines/pull/2297#issuecomment-538076322

**Comment by Ark-kun** [comment]
> > Thank you a lot @deepio-oc .
> > Can you please sign the CLA? I'd really like to merge and release this fix today or tomorrow.
> 
> My organization (One Convergence) has already signed CLA. I would like them to be credited for the fix.

We list all contributions with their respective contributors in our [Changelog](https://github.com/kubeflow/pipelines/blob/master/CHANGELOG.md).

**Pull request merged**
