### PR TITLE
fix(sdk): Fix opsgroups dependency resolution

### PR DESCRIPTION
**Pull request by sabiroid**
**Description of your changes:**
There is a bug in the `Compiler` class when it resolves dependencies for `Op`s and `OpsGroup`s. The nature of this bug is the following: when a dependency is an `OpsGroup`, compiler fails with an uncaught exception because it tries to access the wrong variable. This diff fixes this bug by changing the variable to access.

[This gist](https://gist.github.com/sabiroid/08bb7d8e5a413f7d465bbb119df5449c) surfaces the bug and proves the fix:
* With the fix execution of [example.py](https://gist.github.com/sabiroid/08bb7d8e5a413f7d465bbb119df5449c#file-example-py) succeeds and produces a [correct yaml file](https://gist.github.com/sabiroid/08bb7d8e5a413f7d465bbb119df5449c#file-example-py-yaml).
* Without the fix the execution results in the [AttributeError exception](https://gist.github.com/sabiroid/08bb7d8e5a413f7d465bbb119df5449c#file-exception-txt).

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention.
- [x] Do you want this pull request (PR) cherry-picked into the current release branch? *- Yes, please! Can I please have `cherrypick-approved` label added to the pull request when it gets accepted? Thanks!*
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.

### CODE REVIEW

**Comment by sabiroid** [comment]
@googlebot I signed it!

**Comment by sabiroid** [comment]
So, some tests seem to have failed, but I am pretty sure my change is not the reason. Are there any action items for me as for now?

**Comment by Ark-kun** [comment]
@sabiroid Thank you for this fix for the DSL compiler.
Can you comment on which scenarios are broken before the fix? I just wonder why this hasn't been triggered before.

P.S. Maybe you can add a small compiler test to the test suite.
/lgtm

**Pull request merged**
