### PR TITLE
Automated the component image release script

### PR DESCRIPTION
**Pull request by Ark-kun**
The script now clones clean repo, makes the changes and commits them.
Then it optionally pushes the changes to a new release branch and even opens the web-browser with a pull request page ready.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1172)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Gentle ping. @gaoning777 @hongye-sun 

How can I help you review this PR? Is there any particular problem?

**Comment by hongye-sun** [comment]
/lgtm

thanks for the change.

**Comment by Ark-kun** [comment]
> thanks for the change.

Thanks.
https://github.com/kubeflow/pipelines/pull/1283 will make it even better

**Pull request merged**
