### PR TITLE
fix(frontend): Introduce ALLOWED_ARTIFACT_DOMAIN_REGEX flag to prevent accessing undesired domains. Remove user input string from server response.

### PR DESCRIPTION
**Pull request by zijianjoy**
**Description of your changes:**

1. Remove user query parameter string from server response.
2. Introduce ALLOWED_ARTIFACT_DOMAIN_REGEX to allow configuration of allowed domains querying.
3. By default, ALLOWED_ARTIFACT_DOMAIN_REGEX is match all. Default configuration is meant to be demo purpose and not for production.
4. Users can provide ALLOWED_ARTIFACT_DOMAIN_REGEX environment variable to restrict object storage endpoint querying domains.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thank you @zijianjoy for the fix. Would you document this configuration somewhere?

**Comment by zijianjoy** [comment]
> /lgtm /approve
> 
> Thank you @zijianjoy for the fix. Would you document this configuration somewhere?

That is a good point, I created a PR for the documentation: https://github.com/kubeflow/website/pull/3577. I think it will be great to start educating users about how to administrate their KFP instances.

**Pull request merged**
