### PR TITLE
fix(sdk): use kfp.dsl.types to replace kfp.components.types Fixes #10282

### LINKED ISSUE #10282: [sdk] no module named `kfp.components.types' error when a deprecated package is used.
### Environment

*  KFP version: 2.0.4, as well as on top of master

*  KFP SDK version: sdk-v2.4.0, the latest sdk version as well as on top of master branch

### Steps to reproduce

build pipeline with a deprecated package encounter error.

```
  File "/usr/local/lib/python3.11/dist-packages/kfp/deprecated/dsl/_component_bridge.py", line 29, in <module>
    from kfp.deprecated.dsl import component_spec as dsl_component_spec
  File "/usr/local/lib/python3.11/dist-packages/kfp/deprecated/dsl/component_spec.py", line 21, in <module>
    from kfp.deprecated.dsl import type_utils
  File "/usr/local/lib/python3.11/dist-packages/kfp/deprecated/dsl/type_utils.py", line 19, in <module>
    from kfp.components.types import type_utils
ModuleNotFoundError: No module named 'kfp.components.types'
```
the module `kfp.components.types` is moved to `kfp.dsl.types` during #9710.
 
### Expected result

build without error

### Materials and Reference

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by hsinhoyeh**
Fixes: #10282

**Description of your changes:**

replacing `kfp.components.types` with `kfp.dsl.types` as the package is relocated.

**Checklist:**
- [ x ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by hsinhoyeh** [comment]
> Hi, @hsinhoyeh. Thank you for proposing the change. However, deprecated is currently not part of the KFP 2.x.x public API. It's used only for testing the KFP backend.

@connor-mccarthy Thanks for the reply. That make sense to me totally. But I am wondering if the deprecated api is still there (in the part of the sdk), should we at least guarantee it is functional working? right now the deprecated API is not working except for some doc string points in the wrong direction :(

**Comment by connor-mccarthy** [comment]
I see what you're saying, though I think the break is representative of the reason we don't plan to guarantee the code's functionality; we don't plan to backward compatible support this code with each change to the rest of SDK. The [reference docs](https://kubeflow-pipelines.readthedocs.io/) cover what is considered to be a part of the public API.

**Comment by connor-mccarthy** [comment]
Reopening. While we don't endorse use of deprecated in the general case, we can check in this PR to unblock you and fix the tests.

/ok-to-test

**Comment by connor-mccarthy** [comment]
Test failures are independent of these changes. Manually merging.

/lgtm
/approve

**Comment by connor-mccarthy** [comment]
Thank you!

**Pull request merged**
