### PR TITLE
Refactor BaseOp to context manager pattern

### PR DESCRIPTION
**Pull request by hongye-sun**
Changes:
* Rename BaseOp to KfpExecutionContext
* Implement KfpExecutionContext with context manager pattern which is more flexible than inheritance pattern.
* Add context ID support to generate stable ID across retries.
* Ignore errors in local runs

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/762)

### CODE REVIEW

**Comment by hongye-sun** [comment]
@vicaire This PR is mostly same as the BaseOp PR, but I decided to go with context manager pattern to make it easier for user to write operation in a single function. Could you take a some time to take another look of it? Thanks.

**Comment by Ark-kun** [comment]
@hongye-sun Are all those 23 commits part of this PR changes? Can you rebase it on top of master so that the real changes are clearer to see?

**Pull request merged**
