### PR TITLE
chore(backend): bump argo-workflows to latest.

### LINKED ISSUE #6916: [feature] Upgrade argo-workflows to 3.2.x
### Feature Area

/area backend

### What feature would you like to see?

Upgrade argo-workflows to 3.2.x.

### What is the use case or pain point?

argo-workflows 3.2 includes some useful features, including conditional retries.

### Is there a workaround currently?

Without conditional retries, we can either retry too often (retryPolicy: Always) and waste resources or not retry often enough (retryPolicy: OnError).

cc @zijianjoy, since I see you upgraded argo-workflows recently.
cc @jli and @joshlipschultz, who are also interested in the feature

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

### PR DESCRIPTION
**Pull request by jmcarp**
**Description of your changes:**

Try to upgrade argo-workflows based on previous PRs. Resolves #6916.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by zijianjoy** [comment]
Can you also update https://github.com/kubeflow/pipelines/tree/master/manifests as well? Examples: https://github.com/kubeflow/pipelines/commit/a89183fd002573e753bbcb24d972b3ebd13e2396#diff-75d17c1c8ea73190533f46fa0bfb393085b8f96b0587c51622e8f9388fd23477

**Comment by zijianjoy** [comment]
You will need to update `.cloudbuild.yaml` and `.release.cloudbuild.yaml` as well: https://github.com/kubeflow/pipelines/commit/a89183fd002573e753bbcb24d972b3ebd13e2396#diff-51ad04b116a62f170e26dd77721528424f95fbc1df7adcd2a325bdaa100dac08

**Comment by zijianjoy** [comment]
@jmcarp Would you mind granting me edit permission to your branch? https://github.com/jmcarp/pipelines/tree/jmcarp/argo-workflows-v3.2 So I can push images based on your change.

**Comment by jmcarp** [comment]
Do you not have access to my fork? Maintainers should be allowed to push:

Screen Shot 2021-11-19 at 7 32 55 PM

And I invited you to my fork:

Screen Shot 2021-11-19 at 7 33 08 PM

**Comment by jmcarp** [comment]
@zijianjoy let me know if I need to do anything else you give you access to my branch.

**Comment by zijianjoy** [comment]
/retest-required

I have pushed the license compliance images.

**Comment by zijianjoy** [comment]
Question: Why do we need to upgrade golang version for presubmit in this PR?

**Comment by zijianjoy** [comment]
Creating PR to supplement your argo workflow change: https://github.com/jmcarp/pipelines/pull/1. 

I was not able to directly push to your branch since the name has changed to `jmcarp/argo-workflows-v3.2` (I guess having slash `/` in the branch name is a bit tricky to push commits to this remote branch)

**Comment by zijianjoy** [comment]
/lgtm
/approve

Thank you for your PR!

**Comment by jmcarp** [comment]
Hi @Bobgy, would it be possible to get this into the 1.8 release?

**Pull request merged**
