### PR TITLE
fix(cli): update client to allow equal signs('=') in parameters. Fixes #5577

### LINKED ISSUE #5577: [sdk] `kfp run submit` fails when paramerer values contain '=' with "dictionary update sequence element"
### Environment

*  KFP version: 

*  KFP SDK version: 1.4.0, 1.5.0

*  All dependencies version: n/a

### Steps to reproduce

* Compile test pipeline below (run py script)

```py
import kfp as kfp

@kfp.components.func_to_container_op
def print_func(param: str):
    print(str(param))
    return

@kfp.dsl.pipeline(name='pipeline')
def pipeline(param: str):
    print_func(param)
    return

if __name__ == '__main__':
    kfp.compiler.Compiler().compile(pipeline, __file__ + ".zip")
```

* Upload to KF
* Grab the `pipeline-id` to use it in the command line sdk
* Using the command line SDK, run the following:

```sh
$ kfp run submit --pipeline-id <pipeline-id> --experiment-name 'Test = parsing' param=12345   # Succeeds
$ kfp run submit --pipeline-id <pipeline-id> --experiment-name 'Test = parsing' param=some_name=4567    # Fails
dictionary update sequence element #0 has length 3; 2 is required
```

Running the parameter directly from the KFP UI with value `some_name=4567` works fine and prints `some_name=4567`.

#### Problem Explanation
The pipeline expects an input parameter named `param` to run and it prints the value of that param. The SDK will parse pipeline parameters on the `=` sign [here](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/cli/run.py#L79). The value contains an `=` sign, so we are trying to update the `dict()` with `('param', 'some_name', '4567')` when the goal is to update it with `('param', 'some_name=4567')`.

#### Problem Significance
The equality sign `=` is typically used to partition datasets in distributed storage (S3, HDFS, etc) leading to paths like
```
hdfs://path/to/table/year_partition=2020/month_partition=01/other_partition=other_value/file1.parquet
hdfs://path/to/table/year_partition=2020/month_partition=02/other_partition=other_value/file1.parquet
...
```
Due to the problem discussed above, we cannot use the CLI SDK to provide parameters that contain the `=` sign. However, we _can_ use the KFP UI and pass such paramters, leading to inconsistent behavior.

### Expected result

Running
```sh
$ kfp run submit --pipeline-id <pipeline-id> --experiment-name 'Test = parsing' param=some_name=4567 
```
should succeed just like running the pipeline via the KFP UI with the value `some_name=4567` for the run parameter **param**.

#### Suggested Solution
[This line](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/cli/run.py#L79) should be
```py
    arg_dict = dict(arg.split('=', maxsplit=1) for arg in args)
```

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by NikeNano**
**Description of your changes:**
Update to allow equal signs in parameters fixes: https://github.com/kubeflow/pipelines/issues/5577

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by NikeNano** [comment]
The error in `kubeflow-pipelines-tfx-python36` seems to be related to: https://github.com/kubeflow/pipelines/pull/5639/files @chensun.

**Comment by chensun** [comment]
> The error in `kubeflow-pipelines-tfx-python36` seems to be related to: https://github.com/kubeflow/pipelines/pull/5639/files @chensun.

Yes, the issue is from TFX side, we'd ask them to revert this revert: https://github.com/tensorflow/tfx/commit/f8c1dea2095197ceda60e1c4d67c4c90fc17ed44

We can ignore the test for now.

**Pull request merged**
