### PR TITLE
[WIP] Add imagepullsecret notebook sample

### PR DESCRIPTION
**Pull request by numerology**
Add a notebook sample to demonstrate the usage of imagepullsecret.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1727)

### CODE REVIEW

**Comment by numerology** [comment]
Should be ready to merge. @gaoning777

**Comment by gaoning777** [comment]
Would you mind moving this sample to samples/core, similar to the other samples, please?

**Comment by numerology** [comment]
> Would you mind moving this sample to samples/core, similar to the other samples, please?

Sure.

**Comment by numerology** [comment]
Looks good to the bots @gaoning777

**Comment by numerology** [comment]
Per offline discussion, this PR is redundant.

**Comment by gaoning777** [comment]
It is still worth moving the existing one from the unit test folder to the samples folder. WDYT?

**Comment by numerology** [comment]
@gaoning777 Sure, but no wonder it'll be in another PR.

**Pull request closed without merging**
