### PR TITLE
fix(backend) Replace LEFT with INNER JOIN when Archive Experiment

### PR DESCRIPTION
**Pull request by difince**
**Description of your changes:**
Replace LEFT with INNER JOIN when Archive Experiment
Follow-up PR on https://github.com/kubeflow/pipelines/pull/9680
See [comment](https://github.com/kubeflow/pipelines/pull/9680#issuecomment-1633771148) 

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by gkcalat — COMMENTED** [review]
Thank you @difince!

Could you please add a [TODO note](https://github.com/kubeflow/pipelines/pull/9680#issuecomment-1634613690) in the ArchiveExperiment method that got changed in the previous PR?

**Comment by difince** [comment]
@gkcalat

**Review by gkcalat — COMMENTED** [review]
Thank you @difince!

/retest

**Comment by gkcalat** [comment]
> /retest

Trying to resolve the issue in #9743. This one should be merged after we fix the tests. Thanks for your patience!

**Pull request merged**
