### PR TITLE
SDK - Fixes and improvements to schedule_pipeline

### PR DESCRIPTION
**Pull request by omarzouk**
Bugfix for cron, added start_date_time, end_date_time and support for pipeline version

### CODE REVIEW

**Comment by omarzouk** [comment]
@googlebot I signed it!

**Comment by faweis** [comment]
Note: I've done something similar in #2978. It also implements the possibility to schedule a job with a periodic trigger.

**Comment by omarzouk** [comment]
Thanks @faweis ! I didn't see your PR. Now that I look at it, I believe yours is more in line with the rest of the SDK structure than this function. The motivation for me doing this was that I wanted something working I could use with my CI to unblock myself and since I made the fixes I thought to contribute them back here. I really don't mind if the maintainers choose to go with either/both PRs as long as the SDK has a working version and it is released as soon as possible.

**Comment by yaronha** [comment]
@omarzouk this PR also seems to fix my issue #3523

**Comment by omarzouk** [comment]
@yaronha I couldn't get the pipeline to actually run setting a startdate, even if the cron schedule is set on the experiment correctly

**Comment by numerology** [comment]
/ok-to-test

@omarzouk Sorry it seems like you'll need to resolve the conflicts.

**Comment by omarzouk** [comment]
I think this pull request is no longer needed since https://github.com/kubeflow/pipelines/pull/2978 has already been merged

**Pull request closed without merging**
