### PR TITLE
chore: Update kustomize/manifests OWNERS

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
Hi @zijianjoy,
/Approve

**Comment by zijianjoy** [comment]
Thank you Yuan! Would you like to still sit on the approver list? It is best practice to avoid one-point failure by having more than one approver.

**Comment by Bobgy** [comment]
@zijianjoy no worries, owners have inheritance, I am still an owner for this folder, because I am a root owner

**Comment by zijianjoy** [comment]
/lgtm
/approve

Thank you Yuan for confirming! LGTMed.

**Pull request merged**
