### PR TITLE
remove tfx-taxi sample in favor of the tfx oss sample

### PR DESCRIPTION
**Pull request by gaoning777**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2160)

### CODE REVIEW

**Comment by gaoning777** [comment]
fixing https://github.com/kubeflow/pipelines/issues/1903

**Comment by numerology** [comment]
Also, two files in the website need change
https://github.com/kubeflow/website/blob/05d3d9233205ad926b0baa3f5e1f6a5bfc5c0689/content/docs/pipelines/sdk/build-component.md
and
https://github.com/kubeflow/website/blob/cf7b9f3a87c30cdd3aaf2089bbe9cbbb5220d774/content/docs/pipelines/sdk/output-viewer.md

**Comment by gaoning777** [comment]
> Also, two files in the website need change
> https://github.com/kubeflow/website/blob/05d3d9233205ad926b0baa3f5e1f6a5bfc5c0689/content/docs/pipelines/sdk/build-component.md
> and
> https://github.com/kubeflow/website/blob/cf7b9f3a87c30cdd3aaf2089bbe9cbbb5220d774/content/docs/pipelines/sdk/output-viewer.md

Thanks for pointing that out. I'm in fact in the middle of sending that PR.

**Comment by cvenets** [comment]
Hello @gaoning777, can you please explain the reason for this PR?

Why are we removing this example? We are heavily relying on this example to showcase the e2e Taxi Cab pipeline running on-prem, and produce tutorials.

cc: @jinchihe @jessiezcc @jlewi

**Pull request merged**
