### PR TITLE
SDK - Bumping the upper version of Kubernetes package

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/kubeflow/pipelines/issues/2771

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2780)

### CODE REVIEW

**Comment by Ark-kun** [comment]
The upper version was pinned in #1159
@gaoning777 Do you remember what the breaking change was?

**Comment by gaoning777** [comment]
It was a while back and I couldn't remember. 
If all tests are passing, bumping the version seems good to me.

**Comment by Ark-kun** [comment]
Looks like everything is working. @gaoning777 Can you please LGTM?
/approve

**Pull request merged**
