### PR TITLE
Pipelines now can be suspended using the DSL and resumed using KFP API

### LINKED ISSUE #3101: Feature request - Suuport Argo suspense and resume on KFP
Hey,
Sometimes we have pipelines that need to be suspend for some time in order to do human interactions such DB writes / using 3rd party apps and so on..

Argo supports suspense of a workflow and resuming it and I thought it's a good feature to have a SuspendOp in the dsl that suspense the workflow and a resume API endpoint that resumes the pipeline when it reaches a suspend Op.

- [x] DSL - Add SuspendOp to KFP python packge's DSL
- [x] Backend -Add to KFP backend API endpoint for pipeline resume
- [x] Frontend - Add to KFP frontend a resume button if needed
- [x] Frontend - for a suspend component in the DAG, show it as suspended and not as running

I'm willing to help writing the feature if I get some guidance on where should I do it.
Thanks, 
Amit

### PR DESCRIPTION
**Pull request by amitripshtos**
Fixes #3101 

This PR contains the following changes:

- Added SuspendOp to the python DSL in order to have a suspense step (including setting a specific duration)
- Added "ResumeRun" API in KFP backend to support resuming a suspended pipeline
- Updated the UI to show suspended steps in the Graph (showing the right icon/color/text) and added Resume button in RunDetails to allow manually resume a suspended pipeline.
- Tests has been added in the DSL and the Backend API
- Pipeline with suspended step has been added to the frontend API mock server

Thanks to @NikeNano for the help!

How it looks:
Screen Shot 2020-03-02 at 0 52 27

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3202)

### CODE REVIEW

**Comment by NikeNano** [comment]
@amitripshtos we need to update and check the tests a lot it seams like :) I will ok at it tomorrow.

**Comment by Bobgy** [comment]
Hi @amitripshtos! Thank you the for the contribution!
This sounds like a really useful feature.

My quick suggestion: can you separate this PR to different areas? One PR for UI, one for backend+db and one for SDK. That makes different area owners easier to review.

**Comment by amitripshtos** [comment]
I will do that now, thanks!

**Pull request closed without merging**
