### PR TITLE
Use GCP external Stackdriver links

### PR DESCRIPTION
**Pull request by derekhh**
**Background**

#1310 added links to show Stackdriver logs. However, the links seem to be some Google-internal links. 

**Changes**

In this PR, I updated the links to using `console.cloud.google.com`.

**Test Plan**

- [x] Verified manually that by changing the prefix from `pantheon.corp.google.com` to `console.cloud.google.com` and keep the rest of the URL the same, we can correctly fetch the logs from Stackdriver k8s logs.

- [ ] I was not able to fetch the logs from Legacy Stackdriver logging though but I don't think that's an issue of this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1552)

### CODE REVIEW

**Comment by rileyjbauer** [comment]
Hello! Thank you for this PR!

Looks good to me, but you'll need to update the snapshot tests before this can be submitted.

**Comment by derekhh** [comment]
Thanks @rileyjbauer :)

**Comment by rileyjbauer** [comment]
Thank you @derekhh !

**Pull request merged**
