### PR TITLE
Correct input height

### PR DESCRIPTION
**Pull request by rileyjbauer**
This styling is not applied via the MUI themes because doing so breaks multiline input.

Before:
image

After:
image

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1294)

### CODE REVIEW

**Comment by ajayalfred** [comment]
Looks good. While you're doing this, can you change the style of input text to 
image
image

**Comment by rileyjbauer** [comment]
@ajayalfred the font change should only be for the text in the input fields?

**Comment by ajayalfred** [comment]
Yes that's correct. Just for the text in the input field.

**Comment by rileyjbauer** [comment]
Alright, then this should be all set!

**Comment by rileyjbauer** [comment]
/test kubeflow-pipeline-sample-test
--

**Comment by Bobgy** [comment]
@rileyjbauer is this still something we want?

**Comment by Bobgy** [comment]
/close
because no longer activity in this and there are too many conflicts

I'll look into this later

**Pull request closed without merging**
