### PR TITLE
chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

### PR DESCRIPTION
**Pull request by Juneezee**
**Description of your changes:**

The package `github.com/ghodss/yaml` is no longer actively maintained. See discussion in https://github.com/ghodss/yaml/issues/75 and https://github.com/ghodss/yaml/issues/80. [`sigs.k8s.io/yaml`](https://github.com/kubernetes-sigs/yaml) is a permanent fork of `github.com/ghodss/yaml`. It is actively maintained by Kubernetes SIG, and also widely used in K8s projects.

The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Linchin** [comment]
Hi @Juneezee, there is still something wrong with the integration test. Could you please fix this too? Thank you.

**Comment by Juneezee** [comment]
Hi @Linchin. Correct me if I'm wrong, but I've looked at the logs and I don't think the failure is caused by this PR.

**Comment by Juneezee** [comment]
@Linchin  The error comes from `deepmerge-ts@5.0.0` which was released 4 days ago (https://github.com/RebeccaStevens/deepmerge-ts/releases/tag/v5.0.0) and dropped support for Node 14.

```
[36mintegration-test-sdwcd-2311914601: npm WARN notsup Unsupported engine for deepmerge-ts@5.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.2","npm":"6.14.17"})[0m
[36mintegration-test-sdwcd-2311914601: npm WARN notsup Not compatible with your version of node/npm: deepmerge-ts@5.0.0[0m

[36mintegration-test-sdwcd-2311914601: > pipelines-frontend-integration-test@0.0.1 test /src[0m
[36mintegration-test-sdwcd-2311914601: > wdio wdio.conf.js[0m
[36mintegration-test-sdwcd-2311914601: [0m
[36mintegration-test-sdwcd-2311914601: (node:182) UnhandledPromiseRejectionWarning: TypeError: Object.hasOwn is not a function[0m
[36mintegration-test-sdwcd-2311914601:     at file:///src/node_modules/deepmerge-ts/dist/node/index.mjs:240:51[0m
[36mintegration-test-sdwcd-2311914601:     at Array.filter (<anonymous>)[0m
[36mintegration-test-sdwcd-2311914601:     at getUtils (file:///src/node_modules/deepmerge-ts/dist/node/index.mjs:240:18)[0m
[36mintegration-test-sdwcd-2311914601:     at deepmergeCustom (file:///src/node_modules/deepmerge-ts/dist/node/index.mjs:220:19)[0m
[36mintegration-test-sdwcd-2311914601:     at file:///src/node_modules/webdriver/build/utils.js:10:19[0m
[36mintegration-test-sdwcd-2311914601:     at <anonymous> (<anonymous>)[0m
```

`Object.hasOwn` is only available after V8 v9.3 [^1]. That means only Node.js 16 and above supports it [^2]

[^1]: https://v8.dev/features/object-has-own
[^2]: https://nodejs.org/en/download/releases

**Comment by Linchin** [comment]
> Hi @Linchin. Correct me if I'm wrong, but I've looked at the logs and I don't think the failure is caused by this PR.

I think you are right. @chensun created a PR today to fix this issue.

**Review by chensun — COMMENTED** [review]
/lgtm

**Pull request merged**
