### PR TITLE
test: Migrate KFP SDK YAPF test to a GHA Workflow

### PR DESCRIPTION
**Pull request by DharmitD**
**Description of your changes:**
Resolves https://github.com/kubeflow/pipelines/issues/10925

Converts the KFP SDK YAPF test to a GH Action Workflow.

Here's a working GH Action run on my fork: https://github.com/DharmitD/data-science-pipelines-argo/actions/runs/9672832818

PR to remove the KFP SDK YAPF test from prow config: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2310

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by DharmitD** [comment]
cc: @hbelmiro @rimolive @chensun @zijianjoy @james-jwu

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Comment by DharmitD** [comment]
@chensun could you please take a look? 
Here's the PR to remove the KFP SDK YAPF test from prow config: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2310
thank you!

**Pull request merged**
