### PR TITLE
fix(manifests): fix error when kpt pkg get manifests. Part of #5368

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
A workaround of https://github.com/kubeflow/pipelines/issues/5368.
We should not update upstream manifests, so this is only a workaround.
/assign @zijianjoy 

Taking the chance, I'm also adding presubmit tests for kustomize manifests.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by zijianjoy** [comment]
Thank you Yuan! It looks good to me with one comment.

**Comment by Bobgy** [comment]
@zijianjoy Thank you, did I miss anything? I am not seeing a comment

**Comment by Bobgy** [comment]
/approve
Test passed : )

**Comment by Bobgy** [comment]
Self LGTMed because it's already reviewed and now a conditional presubmit test depends on the change.

**Comment by edi-bice-by** [comment]
I ran into this from kubeflow/gcp-blueprints doing a pull_upstream with kubeflow manifests @ 1.3.1 and all versions of pipelines >= 1.5.0

**Review by zijianjoy — COMMENTED** [review]
Sorry for missing this comment!

**Pull request merged**
