### PR TITLE
'core' folder included to parameters related On-Premise cluster

### PR DESCRIPTION
**Pull request by olegchorny**
Update is required because this sample was migrated to the samples/core folder

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1751)

### CODE REVIEW

**Comment by numerology** [comment]
Good catch. THX!

**Comment by numerology** [comment]
Otherwise /lgtm

**Comment by olegchorny** [comment]
@numerology hi, new name of the folder again and we'd need another PR for that :)
/mnt/pipelines/samples/core/tfx**_cab_classification**/taxi-cab-classification/

**Comment by numerology** [comment]
> @numerology hi, new name of the folder again and we'd need another PR for that :)
> /mnt/pipelines/samples/core/tfx**_cab_classification**/taxi-cab-classification/

Hi @olegchorny can you sync your fork and do that in this PR? Thanks.

**Comment by numerology** [comment]
LGTM after resolving conflicts.

**Comment by numerology** [comment]
@olegchorny  Gentle ping.

**Comment by numerology** [comment]
@olegchorny Could you try pull the master branch and merge to solve the conflicts? Thanks.

**Comment by numerology** [comment]
Thanks!

**Pull request merged**
