### PR TITLE
add presto pipeline component

### PR DESCRIPTION
**Pull request by mertkavi**
A Kubeflow Presto Pipeline component to submit a query to Presto.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3261)

### CODE REVIEW

**Comment by mertkavi** [comment]
@googlebot I signed it! and we'll verify it.

**Comment by Ark-kun** [comment]
It seems that this component does not have any outputs.
Usually, components have outputs so that the data they produce can be used.

**Comment by mertkavi** [comment]
@Ark-kun Presto queries write a file by nature. For example, `create table programs with (format = 'parquet') ...` query create a table and write Parquet files to Object Storage. That's why this component has not output.

**Comment by Ark-kun** [comment]
> @Ark-kun Presto queries write a file by nature. For example, `create table programs with (format = 'parquet') ...` query create a table and write Parquet files to Object Storage. That's why this component has not output.

Even if the component creates something in an external system, it's useful to have outputs. You can output table name, object id or URI. Then a downstream component can use that to run another query or read the data.

**Comment by mertkavi** [comment]
Thank you for comment @Ark-kun I added the output.

**Comment by Ark-kun** [comment]
Are there going to be other presto-related components in the future? If so, it might be better to move the code to, say, `components/presto/query/`. Usually the path schema is `company_name[/group_name]/component_name/`.

**Comment by mertkavi** [comment]
> Are there going to be other presto-related components in the future? If so, it might be better to move the code to, say, `components/presto/query/`. Usually the path schema is `company_name[/group_name]/component_name/`.

It makes sense. I moved it.

**Pull request merged**
