### PR TITLE
feat(sdk): SDK - Components - Replaced Kubernetes options with generic launcher options

### PR DESCRIPTION
**Pull request by Ark-kun**
This reduces the schema size and makes the task launcher options more flexible.

### CODE REVIEW

**Comment by Bobgy** [comment]
Is this a breaking change?

**Comment by Ark-kun** [comment]
> Is this a breaking change?

Formally, yes. But this option has never been used since it was never supported.
It was possible to add something there, but there was no effect.

I want to remove this unused option before the release so that we do not need to support it.

**Comment by Bobgy** [comment]
@googlebot rescan

**Comment by Bobgy** [comment]
OK, I overlooked this. It should be cherry picked ASAP.
Thanks!
/lgtm
/approve

**Comment by Bobgy** [comment]
/hold
on second thought, I'd prefer not adding launcher options in such a hurry before release.

Can we just remove kubernetes options in one PR?

**Comment by Ark-kun** [comment]
> I'd prefer not adding launcher options in such a hurry

That's just a generic dictionary.

>Can we just remove kubernetes options in one PR?

I think something needs to replace it.

We're basically replacing Kubernetes-specific `kubernetesOptions` with generic `launcherOptions` that can hold the same information.

**Comment by Ark-kun** [comment]
@numerology What do you think?

**Comment by numerology** [comment]
One question I have is what can be in the `launcherOptions` other than `k8sOptions`?

Otherwise as long as this field is not being interpreted right now I think it's fine.

**Comment by Ark-kun** [comment]
> One question I have is what can be in the `launcherOptions` other than `k8sOptions`?

Not sure. Maybe some Argo-specific or Tekton-specific settings. E.g. parallelism, retry behavior, etc.

In general this might provide a forward-compatible place for launcher options.

>as long as this field is not being interpreted right now I think it's fine.

Yes, it's not interpreted yet. (Also isEnabled - maybe I should reduce it as well)

**Comment by Bobgy** [comment]
> > One question I have is what can be in the `launcherOptions` other than `k8sOptions`?
> 
> Not sure. Maybe some Argo-specific or Tekton-specific settings. E.g. parallelism, retry behavior, etc.
> 
> In general this might provide a forward-compatible place for launcher options.
> 
> > as long as this field is not being interpreted right now I think it's fine.
> 
> Yes, it's not interpreted yet. (Also isEnabled - maybe I should reduce it as well)

kubernetesOptions wasn't implemented at all.
We are seeing new requirements now (not being kubernetes specific), so that we need to remove it.


I think we want to promise component spec is stable afterwards. Therefore, I prefer not adding new options until we have a plan to support them.

**Comment by Ark-kun** [comment]
> I think we want to promise component spec is stable afterwards.

That's why I want to add it now before 1.0 is released.

I want to replace/add it for forward compatibility. I want to finish implementing the support for kubernetes options. If we do not have launcherOptions in 1.0, then the later pipelines (e.g. v1.1) using that feature would not load in 1.0 SDK. I want to prevent that by adding the launcherOptions field in 1.0. Same with the annotations.

I'd like to prevent any incompatibilities between the 1.* versions.

**Comment by Bobgy** [comment]
Moving to post 1.0

**Comment by Ark-kun** [comment]
Had an offline discussion with @Bobgy and @rmgogogo 

We've discussed the following three otpions:

### Option 1:
Implement the renaming after 1.0
Cons:
* Technically a breaking change

### Option 2:
Rename in one PR before 1.0: https://github.com/kubeflow/pipelines/pull/4156/

### Option 3:
Perform the renaming in two PRs:
*Remove kubernetesOptions in 1.0 https://github.com/kubeflow/pipelines/pull/4230/
*Add launcherOptions in 1.1

Cons:
*Between the two PRs, the feature “specify Kubernetes options on TaskSpec” is missing


Yuan and Renmin preferred to follow the option 3 where we remove kubernetesOptions now and add `launcherOptions` later when there is a proper implementation.
The removal of `kubernetesOptions` is implemented in https://github.com/kubeflow/pipelines/pull/4230/

**Pull request closed without merging**
