### PR TITLE
incremented app version

### PR DESCRIPTION
**Pull request by kevinbache**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1107)

### CODE REVIEW

**Comment by kevinbache** [comment]
I signed it!

**Comment by gaoning777** [comment]
we probably need to update the release script to auto update the version.
Or else, we need to manually update the version during the release.

**Comment by gaoning777** [comment]
Added an issue: https://github.com/kubeflow/pipelines/issues/1190

**Pull request merged**
