### PR TITLE
Delete namespaced-install.yaml

### PR DESCRIPTION
**Pull request by IronPan**
This file is no longer needed as we store the materialized version in GCS
/assign @Bobgy

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2603)

### CODE REVIEW

**Comment by Bobgy** [comment]
Thanks!

/lgtm
/approve

**Comment by numerology** [comment]
@IronPan Quick Q: is publishing the materialized version to GCS part of the oncall process?

**Comment by Bobgy** [comment]
> @IronPan Quick Q: is publishing the materialized version to GCS part of the oncall process?

It is part of release.cloudbuild.yaml, no manual action needed

**Pull request merged**
