### PR TITLE
Tutorials/Kubeflow TFX pipeline with lightweight python CMLE deployer component

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/145)

### CODE REVIEW

**Comment by gaoning777** [comment]
Could we close this since we have a good example of cmle deployer and lightweight notebook samples?

**Comment by Ark-kun** [comment]
> Could we close this since we have a good example of cmle deployer and lightweight notebook samples?

The idea was to show how to do non-trivial real work using the Lightweight components.

**Comment by gaoning777** [comment]
Are you planning to merge this one? If so, let me know and I'll review

**Pull request closed without merging**
