### PR TITLE
Add numerology to SDK owner

### PR DESCRIPTION
**Pull request by numerology**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3006)

### CODE REVIEW

**Comment by Ark-kun** [comment]
It's fun how I had the same thought to add you to to the SDK owners just an hour ago (sorry, got busy with some bugs) =)

/lgtm
/approve

**Comment by numerology** [comment]
> It's fun how I had the same thought to add you to to the SDK owners just an hour ago (sorry, got busy with some bugs) =)
> 
> /lgtm
> /approve

Lol thanks! @Ark-kun

**Pull request merged**
