### PR TITLE
test: skip archiving experiments because of perf problem

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Mitigates https://github.com/kubeflow/pipelines/issues/6815#issuecomment-955938098

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
Merging quickly to verify whether it successfully mitigates the problem.

**Comment by chaodaiG** [comment]
for testing purpose, expecting a command from prow GitHub app
/woof

**Pull request merged**
