### PR TITLE
fix(cache): Cache executions with no outputs. Fixes #3507

### LINKED ISSUE #3507: Execution Cache does not cache executions that have no outputs
This is probably caused by Argo not putting outputs annotation on the pod.
I'm not sure why it does not exist since there should be an artifact with the console logs.

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/kubeflow/pipelines/issues/3507

### CODE REVIEW

**Comment by Bobgy** [comment]
@Ark-kun QQ: when an execution doesn't have any outputs, it must be doing some side effects to external systems, right (otherwise, it's useless)? Then, in order to make it cacheable, we need user to guarantee this component is idempotent considering its side-effects.

e.g. we have the echo component, if they are cached, they no longer echo to log. We are losing that side-effect we want.

Can we make the assumption for users and make it cached by default?

**Comment by Ark-kun** [comment]
> when an execution doesn't have any outputs, it must be doing some side effects to external systems, right (otherwise, it's useless)?

Interesting thought.

I think there still might be some components that just write something to the log or, check the condition and fail if it's not met (e.g. component that validates config/model/data correctness).

>Then, in order to make it cacheable, we need user to guarantee this component is idempotent considering its side-effects.
>Can we make the assumption for users and make it cached by default?

I think it's pretty surprising when caching is controlled by the number of inputs. This was definitely not intended and this will actually fix itself when Argo fixes the following bug https://github.com/argoproj/argo/issues/3069.

The users already have a way to disable caching per-task and we tell them to do so for non-pure components.

>e.g. we have the echo component, if they are cached, they no longer echo to log. We are losing that side-effect we want.

I consider this a separate issue. I think that the UX should show the archived logs (from the artifact) when the container logs are not available. I remember Eterna2 merged a PR for that https://github.com/kubeflow/pipelines/pull/2081, but it looks like the feature is disabled by default. I think we should enable it now that we have caching.

**Comment by Bobgy** [comment]
@Ark-kun Totally agree there are valid cases caching is preferred and valid. I'm more asking if we should make that the default behavior. **Actually**, I should be asking this before we roll out cache feature by default.

From my past experience, the systems I used usually default to no optimization and let users opt-in if they are sure their workload can be optimized safely (also specify cache-keys it should rely on).
e.g.
* https://reactjs.org/docs/react-api.html#reactpurecomponent
* https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
* https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects

I think the benefit is that:
e.g. consider an organization adopted KFP before caching feature was available
Many users built pipelines in KFP and not all of them can work well with the new caching feature. Additionally, the only way to know if something works or not with caching is to actually try it.

Then, how does this organization roll out KFP caching feature? I don't find a good way, they can only enable it and keep forward-fixing found issues.

What if caching is enabled by letting pipeline authors opt-in? They can each test out their own pipeline first before using it. The organization can enable caching right away.

Additionally, I think a pipeline may only have a few steps that are especially computational heavy, it will be enough if the author just enables caching for those.

What do you think?

**Comment by Bobgy** [comment]
/lgtm
just some discussions around the field, not blocking this pR

**Comment by Bobgy** [comment]
@Ark-kun do you want to merge this?

**Pull request merged**
