### PR TITLE
SDK - Components - Added the create_component_from_tfx_component function

### PR DESCRIPTION
**Pull request by Ark-kun**
The function creates a component from a TFX component, so that it can be used in a KFP pipeline.

Example:

```python
from tfx.components import CsvExampleGen
csv_example_gen_op = create_component_from_tfx_component(CsvExampleGen)
```

This will allow us to remove the generated TFX component files.

### CODE REVIEW

**Comment by Bobgy** [comment]
/cc @numerology 
because I don't think I have enough knowledge about these

**Comment by Ark-kun** [comment]
@numerology 
The big part of the code (the `_run_executor` function) is the same code you have reviewed in https://github.com/kubeflow/pipelines/pull/3684 , so it should be OK.

**Comment by Ark-kun** [comment]
> /hold

Can you please explain why did you decide to block my efforts to delete the TFX components?

What is you motivation for blocking my work?

**Comment by numerology** [comment]
@Ark-kun 

> block my efforts to delete the TFX components

It's confusing because I cannot see why this is related to the efforts of deleting the TFX wrapper components, as you said:
> The big part of the code (the _run_executor function) is the same code you have reviewed in #3684 , so it should be OK.

To me it looks like another incarnation of those components, which, I don't think is the intended approach discussed in the internal thread. (Can you please reply to that thread btw?)

Thanks

**Comment by neuromage** [comment]
> > /hold
> 
> Can you please elaborate on the reasons for putting this PR on hold. I wanted to move forward towards deleting the TFX component python files?

Hi Alexey, I had elaborated on the reasons in the internal bug for this. Shall we continue our discussion there?

**Comment by rmgogogo** [comment]
hi Alexey,

It's an interesting PR. Thanks first.

Here quickly check your design.

So may I say it essentially didn't load/run Driver and Publisher, but just load the core logic part of an Executor? Aka input is a folder or file which contains the required data (e.x. a model or a folder contains CSVs), output is a folder which target to contain a model file or TFRecord files etc.

Is it the idea?

---

How about the run-env? Considering many TFX components are on Beam while KFP naturally is not a distributed system, so may I say it essentially is using local-beam to run it? Aka single process but may multiple thread, right?

**Comment by Ark-kun** [comment]
@rmgogogo Sorry, I somehow missed your comment.

> So may I say it essentially didn't load/run Driver and Publisher, but just load the core logic part of an Executor? Aka input is a folder or file which contains the required data (e.x. a model or a folder contains CSVs), output is a folder which target to contain a model file or TFRecord files etc.
> 
> Is it the idea?

I think this is correct. The driver and publisher are not executed - only the executor and the component code (there is some code in the component classes themselves). You can see the components [here](https://github.com/kubeflow/pipelines/blob/master/components/deprecated/tfx/Trainer/component.py) and also [README](https://github.com/kubeflow/pipelines/blob/master/components/deprecated/tfx/README.md).
The input and output paths are just passed to the executor as URIs. Each input and output is a separate directory/file.
These components also support parallelized runners like Dataflow.

**Comment by rimolive** [comment]
Is this PR still relevant? It's opened for more than a year and has merge conflicts.

**Comment by Ark-kun** [comment]
@rimolive The answer to that question is complex and depends on many things.
Is TFX still relevant? It was a big deal at some point. But is it now? Do KFP users still want to use TFX components in KFP?
Which organizations own the KFP SDK now? Who has real veto power over the functionality/PRs?
Is there alignment between the users' goals and the goals of people with veto power over PRs?

This PR is about KFP component functionality.
Does KFP SDK in it's 2.0 form even support components as envisioned in the KFP design docs?

The merge conflict seems to be pretty trivial.
The bigger problem is that this PR is a nice addition to a since then demolished building.

**Comment by rimolive** [comment]
@Ark-kun We discussed in our last Pipelines WG meeting and we agreed that tfx did not get much traction from community. If you feel the same, we can close this PR.

However, I'm open to help with reviews/approvals if it's possible to fix the merge conflicts quickly. We have many issues and PRs opened and we plan to triage them to prioritize the most desired features/bug fixes and close the ones the community are not interested.

**Pull request closed without merging**
