### PR TITLE
SDK - Moved the _container_builder from kfp.compiler to kfp.containers

### PR DESCRIPTION
**Pull request by Ark-kun**
This only moves the files. The imports remain the same for now.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2192)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Fixed the merge conflicts.

**Comment by numerology** [comment]
/lgtm

But it seems like the CLA is problematic, might because merged with commits from other people?

**Comment by Ark-kun** [comment]
@googlebot I fixed it.

**Comment by Ark-kun** [comment]
> But it seems like the CLA is problematic, might because merged with commits from other people?

Looks like the bot just got stuck for some reason.

**Pull request merged**
