### PR TITLE
chore(sdk): remove cleanup param in local init

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
#localexecution

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks!

**Comment by connor-mccarthy** [comment]
`kubeflow-pipelines-sdk-execution-tests` failures are independent of these changes and tracked separately. Manually merging.

**Pull request merged**
