### PR TITLE
Update Dataflow component _client.py to use projects.locations.templates API endpoint

### PR DESCRIPTION
**Pull request by NikeNano**
Fix for https://github.com/kubeflow/pipelines/issues/3801. Updated client to use the in order to support more regions the component should switch to the projects.locations.templates API endpoint instead of the projects.templates endpoint it uses currently.

This is based upon the suggestion from @DennisVis

The project.locations.templates API is described [here](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.templates/launch).

### CODE REVIEW

**Comment by NikeNano** [comment]
How is this normally verified @hongye-sun? I have not verified this on Kubeflow yet and will try it out tomorrow, thus added hold. Don't have access to the cluster from this computer.

**Comment by NikeNano** [comment]
friendly ping @hongye-sun

**Comment by Ark-kun** [comment]
Thank you for this improvement.

**Comment by Bobgy** [comment]
FYI, cherry picking to 1.0 branch

**Pull request merged**
