### PR TITLE
feat(sdk): support compiling platform specific features

### PR DESCRIPTION
**Pull request by connor-mccarthy**
**Description of your changes:**
Supports the `PipelineTask.platform_config` property for setting platform-specific features.

Future PRs will update the client and the documentation.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull 
request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by connor-mccarthy** [comment]
/hold on release of `kfp-pipeline-spec` package

This is the cause of test failures, which pass locally and will be resolved when we release the new `kfp-pipeline-spec` and bump the version required in the KFP SDK. I'd like this PR to undergo review before we release the next `kfp-pipeline-spec`.

cc @chensun

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks!

**Review by chensun — APPROVED** [review]
/lgtm

**Pull request merged**
