### PR TITLE
feat(manifests): Add liveness Probe for cloud sql proxy. Fix #4973

### LINKED ISSUE #4973: "driver: bad connection" when using Managed storage via Google Cloud Marketplace deployment
### What steps did you take:
- Using GCP default VPC network settings
- Created multi-regional EU Google Cloud Storage bucket
- Create mySQL (v5.7) instance in europe-west1-d with only root user and no password (default settings: Public IP - I also tried enabling the private IP but that also did not resolve the issue)
- Configured AI Platform Pipelines (Google's KFP managed service) using Managed Storage
(params: storage bucket name: bucket name (without gs://), sql connection name: connection name copied from the mySQL UI, database prefix: 'db-test-sven', database username & password left empty to default to root user without password.

### What happened:
Deployment hangs on 'ml-pipeline' component that reports `driver: bad connection` as critical and a continuous stream of errors : `[mysql] 2021/01/11 10:52:23 packets.go:36: unexpected EOF`

Also the 'metadata-grpc-deployment' fails to start with following errors:
```
2021-01-11 10:52:07.160738: F ml_metadata/metadata_store/metadata_store_server_main.cc:220] Non-OK-status: status status: Internal: mysql_real_connect failed: errno: 2002, error: Can't connect to MySQL server on 'mysql' (115)MetadataStore cannot be created with the given connection config.
```

```
2021-01-11 10:52:08.781095: F ml_metadata/metadata_store/metadata_store_server_main.cc:220] Non-OK-status: status status: Internal: mysql_real_connect failed: errno: 2013, error: Lost connection to MySQL server at 'handshake: reading inital communication packet', system error: 11MetadataStore cannot be created with the given connection config.
```

It appears the mySQL connection cannot be instantiated, any help on how to resolve this?

### What did you expect to happen:
Deployment to successfully finish.

How did you deploy Kubeflow Pipelines (KFP)?
Google Cloud Marketplace

KFP version: 1.0.4

/kind bug

### PR DESCRIPTION
**Pull request by zijianjoy**
**Description of your changes:**

When the cloud sql connection has error, currently it doesn't fail, which caused difficulty for debugging issue like `ml-pipeline` being unavailable. When adding the liveness probe, this cloud sql proxy pod will fail, and allow user to discover the issue and look at logs.
Fix #4973

cloudsqlproxy

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
Hi @zijianjoy, this change looks great!

Can you also update GCP marketplace manifests in https://github.com/kubeflow/pipelines/blob/ce5c100e8e34daae1af7c6f0e97fe7fdcd5addbb/manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml#L25-L73? and try to figure out why mkp test is failing?

**Comment by zijianjoy** [comment]
> Hi @zijianjoy, this change looks great!
> 
> Can you also update GCP marketplace manifests in
> 
> ? and try to figure out why mkp test is failing?


Thank you for the tip! I have added to the GCP mktplace manifests too. The test failure seems to be unavailability of go-yaml endpoint.

**Comment by zijianjoy** [comment]
@Bobgy I don't know why rsync is missing from the cloud build environment, which is the error in 

https://console.cloud.google.com/cloud-build/builds/3b402000-8041-4ced-92be-4baabe885f8d?project=363997316495

**Comment by Bobgy** [comment]
rsync issue is being fixed in https://github.com/kubeflow/pipelines/pull/6921

**Comment by Bobgy** [comment]
/lgtm
You can approve when tests pass.

**Comment by zijianjoy** [comment]
@Bobgy Thank you so much for your guidance!

**Pull request merged**
