### PR TITLE
[google-cloud-components sdk] casting on remote runner

### PR DESCRIPTION
**Pull request by sasha-gitg**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Review by SinaChavoshi — APPROVED** [review]
/lgtm

**Comment by SinaChavoshi** [comment]
Nice work!

**Comment by Bobgy** [comment]
Hi @sasha-gitg and @SinaChavoshi ,
Thank you for the great work on components!
I want to remind you that PR titles are auto collected in CHANGELOG, it'll help users understand what have changed if you follow the convention: https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention

The most important thing is to decide which PRs do not need to be user visible, you use chore type to hide them.

**Comment by Bobgy** [comment]
For example, I might name this PR as 
```
feat(components): GCP - cast on remote runner
```

**Pull request merged**
