### PR TITLE
feat(samples/contrib/modular_exponentiation_quantum_circuit)

### PR DESCRIPTION
**Pull request by Rhm-B-WT**
Create an example of modular exponentiation quantum circuit in kubflow pipeline

### CODE REVIEW

**Comment by Rhm-B-WT** [comment]
I've tested the code on kubeflow and it worked. The AttributeError said "module 'kfp_server_api' has no attribute 'ApiGetHealthzResponse'". The environment I used is python 3.11.7. How can I fix it?

**Comment by hbelmiro** [comment]
> I've tested the code on kubeflow and it worked. The AttributeError said "module 'kfp_server_api' has no attribute 'ApiGetHealthzResponse'". The environment I used is python 3.11.7. How can I fix it?

@Rhm-B-WT  I'm migrating the kubeflow-pipelines-samples-v2 tests to GitHub Actions and facing this issue too. When I complete this migration the problem should be fixed.

It would be nice to have a test for this new sample you're adding. However, since the existing tests are not working, we need to wait for the migration to GitHub Actions.

Can we put this PR on hold in the meantime?

/hold

**Review by hbelmiro — CHANGES_REQUESTED** [review]
@Rhm-B-WT [now that we have tests for samples](https://github.com/kubeflow/pipelines/pull/11048), can you please add a test for this?

**Review by hbelmiro — CHANGES_REQUESTED** [review]
@Rhm-B-WT you don't need to create any scripts to run the test. You just need to add your test to https://github.com/kubeflow/pipelines/blob/ba006bddcb83e34bc68c3db15b09fbb0bc317f6c/samples/v2/sample_test.py#L46

**Pull request closed without merging**
