### PR TITLE
[UI] Wrap parameter/urls on overflow

### PR DESCRIPTION
**Pull request by Bobgy**
Fixes https://github.com/kubeflow/pipelines/issues/2897

Instead of showing a hovering tip, I think it's a better UX if parameters and urls just show up as a whole. From my knowledge, these usages shouldn't include super-long strings that clutter the page too much.

If a parameter is too long, it should be a file instead. URLs have length limit intrinsically.

Demos:
When there are enough space:
Screen Shot 2020-05-12 at 10 02 12 PM
When there isn't enough space:
Screen Shot 2020-05-12 at 10 02 23 PM

### CODE REVIEW

**Comment by Bobgy** [comment]
/assign @jingzhang36 
/cc @eterna2 @Ark-kun 

@Ark-kun do you think arguments could be long enough that showing them entirely will cause a problem to the UX?
@eterna2 For review, because I'm also changing how it shows for artifact url/preview.

**Comment by eterna2** [comment]
Lgtm. 

Do we want to also make the preview box a standard size so that it is consistent?

Just noticed that the preview box grows depending on the input (see screenshot 1)

**Comment by Bobgy** [comment]
> Lgtm.
> 
> Do we want to also make the preview box a standard size so that it is consistent?
> 
> Just noticed that the preview box grows depending on the input (see screenshot 1)

@eterna2 Thanks for the suggestions! Sounds reasonable to me. I'll try to do that now.

FYI, I noticed another problem with the preview (when switching between steps, preview may show content for other steps for a short period of time).

**Comment by Bobgy** [comment]
Updated:
Screen Shot 2020-05-13 at 7 31 57 AM

**Pull request merged**
