### PR TITLE
feat: allow the default-editor to edit argo workflows and fix bug #6649

### PR DESCRIPTION
**Pull request by juliusvonkohout**
**Description of your changes:**

@elikatsis  @zijianjoy 
This also fixes  bug https://github.com/kubeflow/pipelines/issues/6649

@Bobgy Currently the jupyterlab user has no way to cleanup his workspace

With this change e.g. 
```
kubectl -n $NAMESPACE delete workflows -l 'workflows.argoproj.io/completed=true' # for argo
```
works

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by zijianjoy** [comment]
/approve

It looks a legit permission change to me. Thank you for the change.

**Comment by juliusvonkohout** [comment]
@Bobgy  @zijianjoy  please lgtm again, I had to rebase to master to fix the cicd pipeline

**Pull request merged**
