### PR TITLE
apiserver: Remove TFX output artifact recording to metadatastore

### PR DESCRIPTION
**Pull request by dushyanthsc**
Removing metadatastore output artifact logging.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1904)

### CODE REVIEW

**Comment by IronPan** [comment]
please fix the travis tests

**Comment by IronPan** [comment]
@dushyanthsc could you add yourself as the kubeflow member?

**Comment by spiffxp** [comment]
FYI: tide is spamming `failed merging [1904]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "Travis CI - Pull Request" is failing.]`

**Comment by stevekuznetsov** [comment]
/hold

So that check is using New Travis, which uses some new-and-shiny GitHub API to report the results. We don't support that API and thereby do not support Travis unless it's using the legacy framework.

**Comment by cjwagner** [comment]
Ref https://github.com/kubeflow/pipelines/issues/930

**Comment by neuromage** [comment]
/hold cancel

Let's use #930 to figure out why we're spamming tide. No need to block this PR since the tests have passed now.

**Pull request merged**
