### PR TITLE
feat(sdk): Preserve parameter arguments and input names

### PR DESCRIPTION
**Pull request by Ark-kun**
ContainerOp has no concept of inputs, so it loses any information about them such as input names and in some cases even the passed argument values (which are just injected into the command line).
This commit fixes that issue by preserving the paramater arguments map and ultimately storing it in an Argo template annotation.

Fixes https://github.com/kubeflow/pipelines/issues/4556

### CODE REVIEW

**Comment by Bobgy** [comment]
/retest
/lgtm
/approve
Thanks @Ark-kun for the quick fix!

It will be great if we can verify the change via an integration test.

**Comment by Bobgy** [comment]
/hold
actually we should wait for @neuromage @numerology @chensun to review

**Comment by Ark-kun** [comment]
@numerology Can you please take a look?

**Comment by Ark-kun** [comment]
> It will be great if we can verify the change via an integration test.

This probably relates to the Backend PR, right? https://github.com/kubeflow/pipelines/pull/4564
This SDK-side PR has unit tests.

**Comment by Bobgy** [comment]
> This probably relates to the Backend PR, right? #4564

Exactly

**Comment by Ark-kun** [comment]
> /hold
> actually we should wait for @neuromage @numerology @chensun to review

Got /lgtm from @chensun
/hold cancel

**Comment by Bobgy** [comment]
I'm getting some test failures after cherry picking this PR, it seems it has previous dependencies not cherry picked.
I'll skip it for 1.0.4.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4652/kubeflow-pipelines-sdk-python36/1319168221034582016

**Pull request merged**
