### PR TITLE
feat(sdk)!: move v2 to main namespace

### PR DESCRIPTION
**Pull request by ji-yaqi**
**Description of your changes:**

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by connor-mccarthy — CHANGES_REQUESTED** [review]
Hi Yaqi, I have a few questions after my first pass:

1. I noticed a few outstanding v2 SDK references that may or may not be an issue (I'm unsure). Can you let me know what you think?
- [One example](https://github.com/ji-yaqi/pipelines/blob/00b7fb70682a5d3a661439753674a3bc802875ac/sdk/python/kfp/deprecated/dsl/__init__.py#L28)
- [.dockerignore](https://github.com/ji-yaqi/pipelines/blob/00b7fb70682a5d3a661439753674a3bc802875ac/.dockerignore#L6) --> should this just be `build` instead of `v2/build`? Or maybe we can just append `build` to the list?
- Do we want to update the imports/namespace references in the [components/ directory](https://github.com/ji-yaqi/pipelines/tree/merge_v2/components)? ([Example](https://github.com/ji-yaqi/pipelines/blob/00b7fb70682a5d3a661439753674a3bc802875ac/components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/__init__.py#L19))
- Do we want to update the v2 imports (and namespace) in the [pipelines/frontend/mock-backend/data/v2/pipeline/](https://github.com/ji-yaqi/pipelines/tree/master/frontend/mock-backend/data/v2/pipeline) directory ([example](https://github.com/ji-yaqi/pipelines/blob/master/frontend/mock-backend/data/v2/pipeline/pipeline_with_loops_and_conditions.json))?

2. Can you explain why we want to keep the [v2/](https://github.com/ji-yaqi/pipelines/tree/merge_v2/sdk/python/kfp/v2) directory with only an empty `__init__.py` file? Is it possible to remove this? Tests pass when this is removed.

**Comment by ji-yaqi** [comment]
> Hi Yaqi, I have a few questions after my first pass:
> 
> 1. I noticed a few outstanding v2 SDK references that may or may not be an issue (I'm unsure). Can you let me know what you think?
> 
> * [One example](https://github.com/ji-yaqi/pipelines/blob/00b7fb70682a5d3a661439753674a3bc802875ac/sdk/python/kfp/deprecated/dsl/__init__.py#L28)
> * [.dockerignore](https://github.com/ji-yaqi/pipelines/blob/00b7fb70682a5d3a661439753674a3bc802875ac/.dockerignore#L6) --> should this just be `build` instead of `v2/build`? Or maybe we can just append `build` to the list?
> * Do we want to update the imports/namespace references in the [components/ directory](https://github.com/ji-yaqi/pipelines/tree/merge_v2/components)? ([Example](https://github.com/ji-yaqi/pipelines/blob/00b7fb70682a5d3a661439753674a3bc802875ac/components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/__init__.py#L19))
> * Do we want to update the v2 imports (and namespace) in the [pipelines/frontend/mock-backend/data/v2/pipeline/](https://github.com/ji-yaqi/pipelines/tree/master/frontend/mock-backend/data/v2/pipeline) directory ([example](https://github.com/ji-yaqi/pipelines/blob/master/frontend/mock-backend/data/v2/pipeline/pipeline_with_loops_and_conditions.json))?
> 
> 2. Can you explain why we want to keep the [v2/](https://github.com/ji-yaqi/pipelines/tree/merge_v2/sdk/python/kfp/v2) directory with only an empty `__init__.py` file? Is it possible to remove this? Tests pass when this is removed.

Thanks for the review!
1. Edited the first one, for `dockerignore`, it refers to the backend folders. 
2. For empty init, we will provide possible redirects in next PR, for current users to migrate. Thanks for pointing it out!

**Comment by chensun** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
