### PR TITLE
chore(components): Added missing annotations to my components

### PR DESCRIPTION
**Pull request by Ark-kun**
Many components already have these annotations, but some components miss them.
The annotation makes it easier for the users to contact the component author for support.

### CODE REVIEW

**Comment by NikeNano** [comment]
> The annotation makes it easier for the users to contact the component author for support.

Isn't it enough to look at github and commit history if a user want to reach the specific author and otherwise things are expected to be solved through the community rather than the author? 

Super impressive amount of components created @Ark-kun!

**Comment by chensun** [comment]
> > The annotation makes it easier for the users to contact the component author for support.
> 
> Isn't it enough to look at github and commit history if a user want to reach the specific author and otherwise things are expected to be solved through the community rather than the author?
> 
> Super impressive amount of components created @Ark-kun!

Echo what @NikeNano said on both parts. 

First of all, thanks for all your contributions, @Ark-kun.

Second, I wonder if this is really a "correct" use of annotations. IIUC, annotations will be load into memory at (compiler) runtime, and it will be passed along to the backend (only in v1 for now). Why would the author info ever need to be loaded and passed along if it doesn't affect runtime behavior?

I personally think Git commit history should be enough and probably better in scenarios there are more than one contributors to a component -- probably don't want to maintain, in the annotations section, a list of authors including creator, updaters, and the revision history, etc, while all such info would be available in commit history already.

That said, if you think Git commit history isn't enough? Shouldn't we put the author info in some header comments? That feels to be a better place for information not useful at runtime.

**Comment by Ark-kun** [comment]
Thank you for your comment. I see that I should have described rationale for this better.
This is not really about the credit.
There are two main reasons why I'm making this change: getting support and component indexing/versioning/search.

### 1. Getting support
Suppose the user wants to get support for one of their components.
Suppose a user has a pipeline that starts like this. 
```
CsvExampleGen_op    = load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/8c545b62/components/tfx/ExampleGen/CsvExampleGen/component.yaml')
StatisticsGen_op    = load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/8c545b62/components/tfx/StatisticsGen/component.yaml')
SchemaGen_op        = load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/8c545b62/components/tfx/SchemaGen/component.yaml')
```
You've proposed to use the git history.

So, how do we get the git history for the `https://raw.githubusercontent.com/kubeflow/pipelines/8c545b62/components/tfx/ExampleGen/CsvExampleGen/component.yaml` URL? This is not trivial.

A tech savvy user can try to deduce that they need to go to the Kubeflow Pipelines repo and then go to the components/tfx/ExampleGen/CsvExampleGen/ folder. But that folder just does not exist. Dead end.
https://github.com/kubeflow/pipelines/blob/master/components/tfx/ExampleGen/CsvExampleGen/component.yaml returns 404.

So, the user goes and files an issue with the TFX team instead and the TFX team very vocally complains to me that I should support my components myself.

### 2. Indexing

There is a need to search and index components. I've seen that there are many copies of components on GitHub. Some are repo clones, but some are source copies (so GIT history does not work). Anyways, if you search for components on GitHub you'll find lots of duplicates.

I see 2200+ [hits](https://github.com/search?q=filename%3Acomponent.yaml+inputValue). I see that the top repos are not the official ones.
image

When you see several components it's not easy to understand whether they're are different versions or different components having same name. I'm working on a way to deduplicate the components and help users find the canonical versions of the components. This becomes even more important when components are stored in different repositories. Currently most components are in Kubeflow Pipelines repo, but I'm not sure this model is sustainable. So, properly annotating the component origins becomes important. Annotating the author is an important first step. The next step would be to annotate the canonical repo for a component. I've decided to do this in two separate steps so make each change smaller.

This also helps me build curated lists of components - when searching I want to specify author:"Alexey Volkov" and get a set of components that I know would work well together. Compiling such lists one by one is really tedious and not maintainable (e.g. when making this PR it was pretty hard to identify all components that I've built). With this PR, making additional changes becomes much easier. So, it's also a way to group components across different directories.

>Second, I wonder if this is really a "correct" use of annotations. IIUC, annotations will be load into memory at (compiler) runtime, and it will be passed along to the backend (only in v1 for now). Why would the author info ever need to be loaded and passed along if it doesn't affect runtime behavior?

I understand the issue you're raising.
I consider this to be a correct use of annotations. As in Kubernetes, Annotations are intended to attach additional information to a component that does **not** affect runtime behavior. But the v1 compiler breaks this somewhat by copying the component annotations to the workflow. Perhaps we should not be doing that, but I have not seen any users complaining. There might have been some users that actually wanted that, so that their kubernetes tools can get the component annotations from the pods. We're not copying the component annotations in v2, so I'm not sure this is a problem, but I'm fine with removing that in v1.

In some sense we're actually cleaning up the data sent to the backend. Without annotations, some users put the author information in the code itself, which is less than optimal: Putting the author in the annotation helps decrease the size of the code sent for execution.
https://github.com/kubeflow/pipelines/blob/4d75ec98b228f81f56ef8dc102a933ec837685c9/components/ml_metrics/Calculate_classification_metrics/from_CSV/component.py#L21

### Summary:

* Having author information in component files is helpful for users who want to get support
* The `annotations` section is the correct place for such information. (But maybe the compiler should not copy it to Kubernetes)
* Having such information in the machine-readable annotations section is important for component indexing, filtering and searching

**Comment by chensun** [comment]
Thanks for the detailed explanation, @Ark-kun!

> In some sense we're actually cleaning up the data sent to the backend. Without annotations, some users put the author information in the code itself, which is less than optimal: Putting the author in the annotation helps decrease the size of the code sent for execution.

I still kinda prefer code comments to annotations for the author info. Seems more common to strip away code comments to help reduce code size for execution?

All that being said, I agree we can merge this for consistence -- as you mentioned that half of your components are already annotated this way. Thanks again!

/lgtm
/approve

**Comment by Ark-kun** [comment]
>I still kinda prefer code comments to annotations for the author info. Seems more common to strip away code comments to help reduce code size for execution?

One problem with the Python code comments is that they are lost when generating the `component.yaml` files (which are the ones the users load). This PR adds the code to propagate the annotations from `component.py` to `component.yaml`.

**Pull request merged**
