### PR TITLE
remove the magic which update codes only when building a docker image…

### PR DESCRIPTION
**Pull request by rmgogogo**
remove the magic which update codes only when building a docker image with a commit callback

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3188)

### CODE REVIEW

**Comment by rmgogogo** [comment]
in the future we may bring similar logic in release script and submit codes (just like the part we update component commit sha)

**Comment by Bobgy** [comment]
> in the future we may bring similar logic in release script and submit codes (just like the part we update component commit sha)

Can you put your ideas on https://github.com/kubeflow/pipelines/issues/2721#issuecomment-565287314?
We have discussed about this and all prefer not complicating release step.

**Pull request merged**
