### PR TITLE
AWS sagemaker : Added license files and updated Dockerfile to use AmazonLinux

### PR DESCRIPTION
**Pull request by akartsky**
Added license file

and updated the Dockerfile to use AmazonLinux

### CODE REVIEW

**Comment by Jeffwan** [comment]
@akartsky Can you sign CLA first?

**Comment by mameshini** [comment]
/lgtm

Some e2e tests are failing for this PR @Jeffwan

**Comment by Jeffwan** [comment]
@mameshini 

```
WARNING: Your Pod address range (`--cluster-ipv4-cidr`) can accommodate at most 1008 node(s). 
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=Master version "1.14.10-gke.17" is unsupported.
```
Seems GCP's testing infra resources hit limit. I reported to #buildcop channel

**Comment by akartsky** [comment]
Added few more license files 
please re-review it

**Pull request merged**
