### PR TITLE
fix(Backend + SDK): Add missing optional field to SecretAsVolume and …

### LINKED ISSUE #10548: [sdk]  Missing optional parameter to  v2 `use_config_map_as_volume` and `use_secret_as_volume`
In kfp v1 the config map or secret can be marked as optional when used as a volume source, as shown in the example below.

This capability is missing in the recent added `use_config_map_as_volume` and `use_secret_as_volume` v2 sdk functions. (https://github.com/kubeflow/pipelines/pull/10400, https://github.com/kubeflow/pipelines/pull/10483)

```bash
vol = k8s_client.V1Volume(
        name='dummy',
        config_map=k8s_client.V1ConfigMapVolumeSource(name='name', optional=True),
    )
    component.add_pvolumes({mountPoint: vol})


vol = k8s_client.V1Volume(
        name='dummy',
        secret=k8s_client.V1SecretVolumeSource(secret_name='name', optional=False),
    )
    component.add_pvolumes({mountPoint: vol})

```

What is the use case or pain point?

Making the secret or config map an optional resource allows the KFP component to function without failing even if those resources are not present.

### PR DESCRIPTION
**Pull request by revit13**
…ConfigMapAsVolume. Fixes #10548.

Description of your changes:
Part of https://github.com/kubeflow/pipelines/issues/9714, https://github.com/kubeflow/pipelines/pull/10400, https://github.com/kubeflow/pipelines/pull/10483 and https://github.com/kubeflow/pipelines/pull/10549

This PR supports the addition of missing optional fields to SecretAsVolume and ConfigMapAsVolume introduced in https://github.com/kubeflow/pipelines/pull/10549. The fields were added to avoid failure when the secret or config map used as volume source are missing.

To be rebased and update go.mod after #10548.

Checklist:

- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by Tomcli — COMMENTED** [review]
/lgtm
/assign @chensun

**Review by Tomcli — APPROVED** [review]
/lgtm
@chensun could you review this PR? Thanks.

**Review by chensun — APPROVED** [review]
/lgtm

**Review by Tomcli — COMMENTED** [review]
/lgtm

**Pull request merged**
