### PR TITLE
Updated the image in TFMA component

### PR DESCRIPTION
**Pull request by Ark-kun**
Incorporates the fix in #1094.

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1106)

### CODE REVIEW

**Comment by gaoning777** [comment]
Could you elaborate this change in the image?

**Comment by Ark-kun** [comment]
> Could you elaborate this change in the image?

It's the bug fix we released on Friday: #1094

**Comment by gaoning777** [comment]
Why not update all the component image tags such that it looks more consistent

**Comment by Ark-kun** [comment]
> Why not update all the component image tags such that it looks more consistent

I'm not sure it's a good idea to update all component images and component definitions every time someone make a change to a single component.

**Comment by gaoning777** [comment]
Agreed that we need not build new component images but since we are releasing the components all at one time using the release script, why not keep the image tag consistent? 
BTW, is it blocking the release? I saw 0.1.16 is released.

**Comment by Ark-kun** [comment]
> Since we are releasing the components all at one time using the release script, why not keep the image tag consistent?

I did not want any more big somewhat untested changes right before NEXT. The reality is that the images being released are not passing through testing (we release the images that are build by CloudBuild and do not go through testing). So, I was trying not to make any unnecessary sweeping changes.
During the next release we can run the release script again and update all images to the same SHA.

> BTW, is it blocking the release? I saw 0.1.16 is released.
It's not blocking the release. The 0.1.16 release is using the rolled-back TFMA image (v.0.1.14).

**Comment by Ark-kun** [comment]
The image was updated the next week using the normal release process.

**Pull request closed without merging**
