### PR TITLE
Support multi-user artifacts with MinIO

### PR DESCRIPTION
**Pull request by maganaluis**
**Description of your changes:**

This PR adds support to multi-user artifacts with MinIO for KFP V1. 

This solves issue https://github.com/kubeflow/pipelines/issues/4649

The scope of this PR is to:

- Add support for multi-user artifacts with MinIO. This does not include pipelines definitions (tar/yaml)
- Ensure the functionality is backwards compatible. 
- Compatibility with the latest supported version of Argo in KFP 2.9+

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by maganaluis** [comment]
@arllanos Could you add an example.

**Comment by arllanos** [comment]
> @arllanos Could you add an example.

For multiuser, for each namespace the following needs to be set:

1. a bucket, where the bucket name is the name of the user namespace.

2. a default configMap with name `artifact-repositories`.
Note: the configMap expects secret `mlpipeline-minio-artifact` to exist in the namespace. This secret is typically created by the [pipeline profile controller](https://github.com/kubeflow/manifests/blob/3eab165b37283f7965786dd0e906db577a6767af/apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/sync.py)

```bash
export NS=<namespace>

cat <<EOF | kubectl apply -n $NS -f -
apiVersion: v1
data:
  mlpipeline-repository: |
    s3:
      bucket: $NS
      keyPrefix: artifacts
      endpoint: minio-service.kubeflow:9000
      insecure: true
      accessKeySecret:
        name: mlpipeline-minio-artifact
        key: accesskey
      secretKeySecret:
        name: mlpipeline-minio-artifact
        key: secretkey
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: mlpipeline-repository
  name: artifact-repositories
EOF
```

**Comment by Bobgy** [comment]
/cc @capri-xiyue 
has been designing artifact repository config for KFP v2 compatible mode.

I suggest we think about the two designs together and come up with a design that works for both KFP v1 and KFP v2 compatible.

**Comment by Bobgy** [comment]
Hi @maganaluis @arllanos, sorry that I feel reluctant to accept this PR, because it would introduce argo coupled interface to KFP API surface. There are already a lot of active work to build KFP v2 compatible and KFP v2. Both now focus on the pipeline_root concept, which can be configured easily (and also per namespace / per pipeline). With the new direction, it seems to me that merging this PR will only introduce more maintenance cost and confusion than help.

I'd like to hear your feedback about this.

**Comment by maganaluis** [comment]
@Bobgy Makes sense, we will start taking a look at KFPv2, so we can start paving a migration route for us. We can maintain this code internally until then.

**Comment by Bobgy** [comment]
Thank you for your understanding and we keep welcoming future contributions!

**Comment by Bobgy** [comment]
As agreed above, closing this PR

**Pull request closed without merging**
