### PR TITLE
components: Added dataset_manipulation - split_data_into_folds component

### PR DESCRIPTION
**Pull request by Ark-kun**
The component splits the data table into the specified number of folds.

### CODE REVIEW

**Comment by eterna2** [comment]
lgtm. 

But just thinking if we can make it more generic, as the current implementation limits it to max 5 folds (which is a reasonable number).

Can we break this into 2 components?

1. splitter - outputs a list of index slices (for each fold) and optionally the original df
2. use-fold - output a df based on the specific index slice and the corresponding df

Then this can theoretically support any number of folds.

probably inefficient for now, but if the execution on same-pod feature is up, then this will be less of a concern.

**Comment by Ark-kun** [comment]
> Can we break this into 2 components?
> 
> 1. splitter - outputs a list of index slices (for each fold) and optionally the original df
> 2. use-fold - output a df based on the specific index slice and the corresponding df
> 
> Then this can theoretically support any number of folds.

Interesting idea. I'll consider it (probably as an addition, not replacement to this component).
It's also possible to output a directory of datasets, a partitioned dataset or even add a bitmap column that can be used for filtering.

**Pull request merged**
