### PR TITLE
reenable basic sample tests, serially after frontend integ tests(triggering 5 times, successful always)

### PR DESCRIPTION
**Pull request by gaoning777**
will trigger multiple rerun and make sure there is no issue with frontend integ tests.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/298)

### CODE REVIEW

**Comment by gaoning777** [comment]
It works continuously when I manually triggered it at least four times.

**Comment by yebrahim** [comment]
Did something change between this and the original code before revert? Why is this not flaky?

**Comment by gaoning777** [comment]
I've commented in https://github.com/kubeflow/pipelines/issues/272 that the reasons for the flakiness comes from the cluster creation quota and accidentally being shutdown manually.

**Comment by yebrahim** [comment]
I see. Interesting coincidence with how tests got flaky only when this change was checked in, but if you've tested it a few times here then I'm fine with trying it out again.
/lgtm

**Comment by gaoning777** [comment]
The one failed in the 8-runs is that one of the commit force push one commit that overrides the previous one. And, the tests failed when git checkout.

**Comment by gaoning777** [comment]
And, BTW, in this PR, I run the tests concurrently with the frontend integration tests.

**Pull request merged**
