### PR TITLE
chore(backend): update v2 images for beta release

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
Fixes #8815

**Comment by gkcalat** [comment]
Thank you, @chensun 

/lgtm
/approve

**Pull request merged**
