### PR TITLE
Marked all scripts as executable

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1177)

### CODE REVIEW

**Comment by Ark-kun** [comment]
> is it necessary to change mode of the test script?

Script should be executable, right? Otherwise there is an error when you try to run them `./script.sh`.
Sure, right now we use `source` to "run" the scripts, but that's pretty hacky.

**Comment by gaoning777** [comment]
JFYI, source a script is different from directly running the script.
Source will run the script in the same bash where all the environment variables are retained.

**Comment by Ark-kun** [comment]
Thanks for the info.

**Pull request merged**
