### PR TITLE
SDK - Components - Hiding signature attribute from CloudPickle

### PR DESCRIPTION
**Pull request by Ark-kun**
The high-level user issue this solves is that some converted Airflow operators fail to work due to unpickling errors.
Cloudpickle has some issues with pickling type annotations in python versions < 3.7, so they disabled it. https://github.com/cloudpipe/cloudpickle/issues/196
`create component_from_airflow_op` spoofs the function signature by setting the `func.__signature__` attribute. cloudpickle then tries to pickle that attribute which leads to failures during unpickling.
To prevent this we remove the `.__signature__` attribute before pickling.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/2045)

### CODE REVIEW

**Comment by Ark-kun** [comment]
@numerology Can you please take a look?

**Comment by numerology** [comment]
I guess we might want to create a issue to track this hacking work-around. Once cloudpickle solves their problem we can switch to a more elegant way. WDYT?

**Comment by Ark-kun** [comment]
> Once cloudpickle solves their problem we can switch to a more elegant way.

They tried several times and ultimately failed to handle it for python <3.7. So they disabled this for python <3.7. But it looks like they only disabled it for the actual function signature and not the normal attributes.

>Once cloudpickle solves their problem we can switch to a more elegant way. WDYT?

I'll think of a way to solve this. But generally it's just a way to make `_func_to_component_spec` see some extra information, but hide it from cloudpickle (we do not want to serialize that extra information).

**Pull request merged**
